{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='composition', url='', help='"A Composition specifies how a composite resource should be composed."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Composition', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'apiextensions.crossplane.io/v1',
    kind: 'Composition',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"CompositionSpec specifies desired state of a composition."'),
  spec: {
    '#compositeTypeRef':: d.obj(help='"CompositeTypeRef specifies the type of composite resource that this composition is compatible with."'),
    compositeTypeRef: {
      '#withApiVersion':: d.fn(help='"APIVersion of the type."', args=[d.arg(name='apiVersion', type=d.T.string)]),
      withApiVersion(apiVersion): { spec+: { compositeTypeRef+: { apiVersion: apiVersion } } },
      '#withKind':: d.fn(help='"Kind of the type."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { compositeTypeRef+: { kind: kind } } },
    },
    '#environment':: d.obj(help='"Environment configures the environment in which resources are rendered. THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice."'),
    environment: {
      '#environmentConfigs':: d.obj(help='"EnvironmentConfigs selects a list of `EnvironmentConfig`s. The resolved resources are stored in the composite resource at `spec.environmentConfigRefs` and is only updated if it is null. \\n The list of references is used to compute an in-memory environment at compose time. The data of all object is merged in the order they are listed, meaning the values of EnvironmentConfigs with a larger index take priority over ones with smaller indices. \\n The computed environment can be accessed in a composition using `FromEnvironmentFieldPath` and `CombineFromEnvironment` patches."'),
      environmentConfigs: {
        '#ref':: d.obj(help='"Ref is a named reference to a single EnvironmentConfig. Either Ref or Selector is required."'),
        ref: {
          '#withName':: d.fn(help='"The name of the object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { ref+: { name: name } },
        },
        '#selector':: d.obj(help='"Selector selects one EnvironmentConfig via labels."'),
        selector: {
          '#matchLabels':: d.obj(help='"MatchLabels ensures an object with matching labels is selected."'),
          matchLabels: {
            '#withKey':: d.fn(help='"Key of the label to match."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withType':: d.fn(help='"Type specifies where the value for a label comes from."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
            '#withValue':: d.fn(help='"Value specifies a literal label value."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
            '#withValueFromFieldPath':: d.fn(help='"ValueFromFieldPath specifies the field path to look for the label value."', args=[d.arg(name='valueFromFieldPath', type=d.T.string)]),
            withValueFromFieldPath(valueFromFieldPath): { valueFromFieldPath: valueFromFieldPath },
          },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.array)]),
          withMatchLabels(matchLabels): { selector+: { matchLabels: if std.isArray(v=matchLabels) then matchLabels else [matchLabels] } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.array)]),
          withMatchLabelsMixin(matchLabels): { selector+: { matchLabels+: if std.isArray(v=matchLabels) then matchLabels else [matchLabels] } },
        },
        '#withType':: d.fn(help='"Type specifies the way the EnvironmentConfig is selected. Default is `Reference`"', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#patches':: d.obj(help="\"Patches is a list of environment patches that are executed before a composition's resources are composed.\""),
      patches: {
        '#combine':: d.obj(help='"Combine is the patch configuration for a CombineFromComposite or CombineToComposite patch."'),
        combine: {
          '#string':: d.obj(help='"String declares that input variables should be combined into a single string, using the relevant settings for formatting purposes."'),
          string: {
            '#withFmt':: d.fn(help='"Format the input using a Go format string. See https://golang.org/pkg/fmt/ for details."', args=[d.arg(name='fmt', type=d.T.string)]),
            withFmt(fmt): { combine+: { string+: { fmt: fmt } } },
          },
          '#variables':: d.obj(help='"Variables are the list of variables whose values will be retrieved and combined."'),
          variables: {
            '#withFromFieldPath':: d.fn(help='"FromFieldPath is the path of the field on the source whose value is to be used as input."', args=[d.arg(name='fromFieldPath', type=d.T.string)]),
            withFromFieldPath(fromFieldPath): { fromFieldPath: fromFieldPath },
          },
          '#withStrategy':: d.fn(help='"Strategy defines the strategy to use to combine the input variable values. Currently only string is supported."', args=[d.arg(name='strategy', type=d.T.string)]),
          withStrategy(strategy): { combine+: { strategy: strategy } },
          '#withVariables':: d.fn(help='"Variables are the list of variables whose values will be retrieved and combined."', args=[d.arg(name='variables', type=d.T.array)]),
          withVariables(variables): { combine+: { variables: if std.isArray(v=variables) then variables else [variables] } },
          '#withVariablesMixin':: d.fn(help='"Variables are the list of variables whose values will be retrieved and combined."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='variables', type=d.T.array)]),
          withVariablesMixin(variables): { combine+: { variables+: if std.isArray(v=variables) then variables else [variables] } },
        },
        '#policy':: d.obj(help='"Policy configures the specifics of patching behaviour."'),
        policy: {
          '#mergeOptions':: d.obj(help='"MergeOptions Specifies merge options on a field path"'),
          mergeOptions: {
            '#withAppendSlice':: d.fn(help='"Specifies that already existing elements in a merged slice should be preserved"', args=[d.arg(name='appendSlice', type=d.T.boolean)]),
            withAppendSlice(appendSlice): { policy+: { mergeOptions+: { appendSlice: appendSlice } } },
            '#withKeepMapValues':: d.fn(help='"Specifies that already existing values in a merged map should be preserved"', args=[d.arg(name='keepMapValues', type=d.T.boolean)]),
            withKeepMapValues(keepMapValues): { policy+: { mergeOptions+: { keepMapValues: keepMapValues } } },
          },
          '#withFromFieldPath':: d.fn(help="\"FromFieldPath specifies how to patch from a field path. The default is 'Optional', which means the patch will be a no-op if the specified fromFieldPath does not exist. Use 'Required' if the patch should fail if the specified path does not exist.\"", args=[d.arg(name='fromFieldPath', type=d.T.string)]),
          withFromFieldPath(fromFieldPath): { policy+: { fromFieldPath: fromFieldPath } },
        },
        '#transforms':: d.obj(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."'),
        transforms: {
          '#convert':: d.obj(help='"Convert is used to cast the input into the given output type."'),
          convert: {
            '#withFormat':: d.fn(help='"The expected input format. \\n * `quantity` - parses the input as a K8s [`resource.Quantity`](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#Quantity). Only used during `string -> float64` conversions. \\n If this property is null, the default conversion is applied."', args=[d.arg(name='format', type=d.T.string)]),
            withFormat(format): { convert+: { format: format } },
            '#withToType':: d.fn(help='"ToType is the type of the output of this transform."', args=[d.arg(name='toType', type=d.T.string)]),
            withToType(toType): { convert+: { toType: toType } },
          },
          '#match':: d.obj(help='"Match is a more complex version of Map that matches a list of patterns."'),
          match: {
            '#patterns':: d.obj(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."'),
            patterns: {
              '#withLiteral':: d.fn(help='"Literal exactly matches the input string (case sensitive). Is required if `type` is `literal`."', args=[d.arg(name='literal', type=d.T.string)]),
              withLiteral(literal): { literal: literal },
              '#withRegexp':: d.fn(help='"Regexp to match against the input string. Is required if `type` is `regexp`."', args=[d.arg(name='regexp', type=d.T.string)]),
              withRegexp(regexp): { regexp: regexp },
              '#withResult':: d.fn(help='"The value that is used as result of the transform if the pattern matches."', args=[d.arg(name='result', type=d.T.any)]),
              withResult(result): { result: result },
              '#withType':: d.fn(help='"Type specifies how the pattern matches the input. \\n * `literal` - the pattern value has to exactly match (case sensitive) the input string. This is the default. \\n * `regexp` - the pattern treated as a regular expression against which the input string is tested. Crossplane will throw an error if the key is not a valid regexp."', args=[d.arg(name='type', type=d.T.string)]),
              withType(type): { type: type },
            },
            '#withFallbackValue':: d.fn(help='"The fallback value that should be returned by the transform if now pattern matches."', args=[d.arg(name='fallbackValue', type=d.T.any)]),
            withFallbackValue(fallbackValue): { match+: { fallbackValue: fallbackValue } },
            '#withPatterns':: d.fn(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."', args=[d.arg(name='patterns', type=d.T.array)]),
            withPatterns(patterns): { match+: { patterns: if std.isArray(v=patterns) then patterns else [patterns] } },
            '#withPatternsMixin':: d.fn(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='patterns', type=d.T.array)]),
            withPatternsMixin(patterns): { match+: { patterns+: if std.isArray(v=patterns) then patterns else [patterns] } },
          },
          '#math':: d.obj(help='"Math is used to transform the input via mathematical operations such as multiplication."'),
          math: {
            '#withMultiply':: d.fn(help='"Multiply the value."', args=[d.arg(name='multiply', type=d.T.integer)]),
            withMultiply(multiply): { math+: { multiply: multiply } },
          },
          '#string':: d.obj(help='"String is used to transform the input into a string or a different kind of string. Note that the input does not necessarily need to be a string."'),
          string: {
            '#regexp':: d.obj(help='"Extract a match from the input using a regular expression."'),
            regexp: {
              '#withGroup':: d.fn(help='"Group number to match. 0 (the default) matches the entire expression."', args=[d.arg(name='group', type=d.T.integer)]),
              withGroup(group): { string+: { regexp+: { group: group } } },
              '#withMatch':: d.fn(help='"Match string. May optionally include submatches, aka capture groups. See https://pkg.go.dev/regexp/ for details."', args=[d.arg(name='match', type=d.T.string)]),
              withMatch(match): { string+: { regexp+: { match: match } } },
            },
            '#withConvert':: d.fn(help='"Optional conversion method to be specified. `ToUpper` and `ToLower` change the letter case of the input string. `ToBase64` and `FromBase64` perform a base64 conversion based on the input string. `ToJson` converts any input value into its raw JSON representation. `ToSha1`, `ToSha256` and `ToSha512` generate a hash value based on the input converted to JSON."', args=[d.arg(name='convert', type=d.T.string)]),
            withConvert(convert): { string+: { convert: convert } },
            '#withFmt':: d.fn(help='"Format the input using a Go format string. See https://golang.org/pkg/fmt/ for details."', args=[d.arg(name='fmt', type=d.T.string)]),
            withFmt(fmt): { string+: { fmt: fmt } },
            '#withTrim':: d.fn(help='"Trim the prefix or suffix from the input"', args=[d.arg(name='trim', type=d.T.string)]),
            withTrim(trim): { string+: { trim: trim } },
            '#withType':: d.fn(help='"Type of the string transform to be run."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { string+: { type: type } },
          },
          '#withMap':: d.fn(help='"Map uses the input as a key in the given map and returns the value."', args=[d.arg(name='map', type=d.T.object)]),
          withMap(map): { map: map },
          '#withMapMixin':: d.fn(help='"Map uses the input as a key in the given map and returns the value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='map', type=d.T.object)]),
          withMapMixin(map): { map+: map },
          '#withType':: d.fn(help='"Type of the transform to be run."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#withFromFieldPath':: d.fn(help='"FromFieldPath is the path of the field on the resource whose value is to be used as input. Required when type is FromCompositeFieldPath or ToCompositeFieldPath."', args=[d.arg(name='fromFieldPath', type=d.T.string)]),
        withFromFieldPath(fromFieldPath): { fromFieldPath: fromFieldPath },
        '#withToFieldPath':: d.fn(help="\"ToFieldPath is the path of the field on the resource whose value will be changed with the result of transforms. Leave empty if you'd like to propagate to the same path as fromFieldPath.\"", args=[d.arg(name='toFieldPath', type=d.T.string)]),
        withToFieldPath(toFieldPath): { toFieldPath: toFieldPath },
        '#withTransforms':: d.fn(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."', args=[d.arg(name='transforms', type=d.T.array)]),
        withTransforms(transforms): { transforms: if std.isArray(v=transforms) then transforms else [transforms] },
        '#withTransformsMixin':: d.fn(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='transforms', type=d.T.array)]),
        withTransformsMixin(transforms): { transforms+: if std.isArray(v=transforms) then transforms else [transforms] },
        '#withType':: d.fn(help="\"Type sets the patching behaviour to be used. Each patch type may require its' own fields to be set on the Patch object.\"", args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#withEnvironmentConfigs':: d.fn(help='"EnvironmentConfigs selects a list of `EnvironmentConfig`s. The resolved resources are stored in the composite resource at `spec.environmentConfigRefs` and is only updated if it is null. \\n The list of references is used to compute an in-memory environment at compose time. The data of all object is merged in the order they are listed, meaning the values of EnvironmentConfigs with a larger index take priority over ones with smaller indices. \\n The computed environment can be accessed in a composition using `FromEnvironmentFieldPath` and `CombineFromEnvironment` patches."', args=[d.arg(name='environmentConfigs', type=d.T.array)]),
      withEnvironmentConfigs(environmentConfigs): { spec+: { environment+: { environmentConfigs: if std.isArray(v=environmentConfigs) then environmentConfigs else [environmentConfigs] } } },
      '#withEnvironmentConfigsMixin':: d.fn(help='"EnvironmentConfigs selects a list of `EnvironmentConfig`s. The resolved resources are stored in the composite resource at `spec.environmentConfigRefs` and is only updated if it is null. \\n The list of references is used to compute an in-memory environment at compose time. The data of all object is merged in the order they are listed, meaning the values of EnvironmentConfigs with a larger index take priority over ones with smaller indices. \\n The computed environment can be accessed in a composition using `FromEnvironmentFieldPath` and `CombineFromEnvironment` patches."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='environmentConfigs', type=d.T.array)]),
      withEnvironmentConfigsMixin(environmentConfigs): { spec+: { environment+: { environmentConfigs+: if std.isArray(v=environmentConfigs) then environmentConfigs else [environmentConfigs] } } },
      '#withPatches':: d.fn(help="\"Patches is a list of environment patches that are executed before a composition's resources are composed.\"", args=[d.arg(name='patches', type=d.T.array)]),
      withPatches(patches): { spec+: { environment+: { patches: if std.isArray(v=patches) then patches else [patches] } } },
      '#withPatchesMixin':: d.fn(help="\"Patches is a list of environment patches that are executed before a composition's resources are composed.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='patches', type=d.T.array)]),
      withPatchesMixin(patches): { spec+: { environment+: { patches+: if std.isArray(v=patches) then patches else [patches] } } },
    },
    '#functions':: d.obj(help='"Functions is list of Composition Functions that will be used when a composite resource referring to this composition is created. At least one of resources and functions must be specified. If both are specified the resources will be rendered first, then passed to the functions for further processing. \\n THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice."'),
    functions: {
      '#container':: d.obj(help='"Container configuration of this function."'),
      container: {
        '#network':: d.obj(help='"Network configuration for the Composition Function."'),
        network: {
          '#withPolicy':: d.fn(help="\"Policy specifies the network policy under which the Composition Function will run. Defaults to 'Isolated' - i.e. no network access. Specify 'Runner' to allow the function the same network access as its runner.\"", args=[d.arg(name='policy', type=d.T.string)]),
          withPolicy(policy): { container+: { network+: { policy: policy } } },
        },
        '#resources':: d.obj(help='"Resources that may be used by the Composition Function."'),
        resources: {
          '#limits':: d.obj(help='"Limits specify the maximum compute resources that may be used by the Composition Function."'),
          limits: {
            '#withCpu':: d.fn(help='"CPU, in cores. (500m = .5 cores)"', args=[d.arg(name='cpu', type=d.T.any)]),
            withCpu(cpu): { container+: { resources+: { limits+: { cpu: cpu } } } },
            '#withMemory':: d.fn(help='"Memory, in bytes. (500Gi = 500GiB = 500 * 1024 * 1024 * 1024)"', args=[d.arg(name='memory', type=d.T.any)]),
            withMemory(memory): { container+: { resources+: { limits+: { memory: memory } } } },
          },
        },
        '#runner':: d.obj(help='"Runner configuration for the Composition Function."'),
        runner: {
          '#withEndpoint':: d.fn(help='"Endpoint specifies how and where Crossplane should reach the runner it uses to invoke containerized Composition Functions."', args=[d.arg(name='endpoint', type=d.T.string)]),
          withEndpoint(endpoint): { container+: { runner+: { endpoint: endpoint } } },
        },
        '#withImage':: d.fn(help='"Image specifies the OCI image in which the function is packaged. The image should include an entrypoint that reads a FunctionIO from stdin and emits it, optionally mutated, to stdout."', args=[d.arg(name='image', type=d.T.string)]),
        withImage(image): { container+: { image: image } },
        '#withImagePullPolicy':: d.fn(help='"ImagePullPolicy defines the pull policy for the function image."', args=[d.arg(name='imagePullPolicy', type=d.T.string)]),
        withImagePullPolicy(imagePullPolicy): { container+: { imagePullPolicy: imagePullPolicy } },
        '#withTimeout':: d.fn(help='"Timeout after which the Composition Function will be killed."', args=[d.arg(name='timeout', type=d.T.string)]),
        withTimeout(timeout): { container+: { timeout: timeout } },
      },
      '#withConfig':: d.fn(help="\"Config is an optional, arbitrary Kubernetes resource (i.e. a resource with an apiVersion and kind) that will be passed to the Composition Function as the 'config' block of its FunctionIO.\"", args=[d.arg(name='config', type=d.T.object)]),
      withConfig(config): { config: config },
      '#withConfigMixin':: d.fn(help="\"Config is an optional, arbitrary Kubernetes resource (i.e. a resource with an apiVersion and kind) that will be passed to the Composition Function as the 'config' block of its FunctionIO.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='config', type=d.T.object)]),
      withConfigMixin(config): { config+: config },
      '#withName':: d.fn(help='"Name of this function. Must be unique within its Composition."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withType':: d.fn(help='"Type of this function."', args=[d.arg(name='type', type=d.T.string)]),
      withType(type): { type: type },
    },
    '#patchSets':: d.obj(help='"PatchSets define a named set of patches that may be included by any resource in this Composition. PatchSets cannot themselves refer to other PatchSets."'),
    patchSets: {
      '#patches':: d.obj(help='"Patches will be applied as an overlay to the base resource."'),
      patches: {
        '#combine':: d.obj(help='"Combine is the patch configuration for a CombineFromComposite, CombineFromEnvironment, CombineToComposite or CombineToEnvironment patch."'),
        combine: {
          '#string':: d.obj(help='"String declares that input variables should be combined into a single string, using the relevant settings for formatting purposes."'),
          string: {
            '#withFmt':: d.fn(help='"Format the input using a Go format string. See https://golang.org/pkg/fmt/ for details."', args=[d.arg(name='fmt', type=d.T.string)]),
            withFmt(fmt): { combine+: { string+: { fmt: fmt } } },
          },
          '#variables':: d.obj(help='"Variables are the list of variables whose values will be retrieved and combined."'),
          variables: {
            '#withFromFieldPath':: d.fn(help='"FromFieldPath is the path of the field on the source whose value is to be used as input."', args=[d.arg(name='fromFieldPath', type=d.T.string)]),
            withFromFieldPath(fromFieldPath): { fromFieldPath: fromFieldPath },
          },
          '#withStrategy':: d.fn(help='"Strategy defines the strategy to use to combine the input variable values. Currently only string is supported."', args=[d.arg(name='strategy', type=d.T.string)]),
          withStrategy(strategy): { combine+: { strategy: strategy } },
          '#withVariables':: d.fn(help='"Variables are the list of variables whose values will be retrieved and combined."', args=[d.arg(name='variables', type=d.T.array)]),
          withVariables(variables): { combine+: { variables: if std.isArray(v=variables) then variables else [variables] } },
          '#withVariablesMixin':: d.fn(help='"Variables are the list of variables whose values will be retrieved and combined."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='variables', type=d.T.array)]),
          withVariablesMixin(variables): { combine+: { variables+: if std.isArray(v=variables) then variables else [variables] } },
        },
        '#policy':: d.obj(help='"Policy configures the specifics of patching behaviour."'),
        policy: {
          '#mergeOptions':: d.obj(help='"MergeOptions Specifies merge options on a field path"'),
          mergeOptions: {
            '#withAppendSlice':: d.fn(help='"Specifies that already existing elements in a merged slice should be preserved"', args=[d.arg(name='appendSlice', type=d.T.boolean)]),
            withAppendSlice(appendSlice): { policy+: { mergeOptions+: { appendSlice: appendSlice } } },
            '#withKeepMapValues':: d.fn(help='"Specifies that already existing values in a merged map should be preserved"', args=[d.arg(name='keepMapValues', type=d.T.boolean)]),
            withKeepMapValues(keepMapValues): { policy+: { mergeOptions+: { keepMapValues: keepMapValues } } },
          },
          '#withFromFieldPath':: d.fn(help="\"FromFieldPath specifies how to patch from a field path. The default is 'Optional', which means the patch will be a no-op if the specified fromFieldPath does not exist. Use 'Required' if the patch should fail if the specified path does not exist.\"", args=[d.arg(name='fromFieldPath', type=d.T.string)]),
          withFromFieldPath(fromFieldPath): { policy+: { fromFieldPath: fromFieldPath } },
        },
        '#transforms':: d.obj(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."'),
        transforms: {
          '#convert':: d.obj(help='"Convert is used to cast the input into the given output type."'),
          convert: {
            '#withFormat':: d.fn(help='"The expected input format. \\n * `quantity` - parses the input as a K8s [`resource.Quantity`](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#Quantity). Only used during `string -> float64` conversions. \\n If this property is null, the default conversion is applied."', args=[d.arg(name='format', type=d.T.string)]),
            withFormat(format): { convert+: { format: format } },
            '#withToType':: d.fn(help='"ToType is the type of the output of this transform."', args=[d.arg(name='toType', type=d.T.string)]),
            withToType(toType): { convert+: { toType: toType } },
          },
          '#match':: d.obj(help='"Match is a more complex version of Map that matches a list of patterns."'),
          match: {
            '#patterns':: d.obj(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."'),
            patterns: {
              '#withLiteral':: d.fn(help='"Literal exactly matches the input string (case sensitive). Is required if `type` is `literal`."', args=[d.arg(name='literal', type=d.T.string)]),
              withLiteral(literal): { literal: literal },
              '#withRegexp':: d.fn(help='"Regexp to match against the input string. Is required if `type` is `regexp`."', args=[d.arg(name='regexp', type=d.T.string)]),
              withRegexp(regexp): { regexp: regexp },
              '#withResult':: d.fn(help='"The value that is used as result of the transform if the pattern matches."', args=[d.arg(name='result', type=d.T.any)]),
              withResult(result): { result: result },
              '#withType':: d.fn(help='"Type specifies how the pattern matches the input. \\n * `literal` - the pattern value has to exactly match (case sensitive) the input string. This is the default. \\n * `regexp` - the pattern treated as a regular expression against which the input string is tested. Crossplane will throw an error if the key is not a valid regexp."', args=[d.arg(name='type', type=d.T.string)]),
              withType(type): { type: type },
            },
            '#withFallbackValue':: d.fn(help='"The fallback value that should be returned by the transform if now pattern matches."', args=[d.arg(name='fallbackValue', type=d.T.any)]),
            withFallbackValue(fallbackValue): { match+: { fallbackValue: fallbackValue } },
            '#withPatterns':: d.fn(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."', args=[d.arg(name='patterns', type=d.T.array)]),
            withPatterns(patterns): { match+: { patterns: if std.isArray(v=patterns) then patterns else [patterns] } },
            '#withPatternsMixin':: d.fn(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='patterns', type=d.T.array)]),
            withPatternsMixin(patterns): { match+: { patterns+: if std.isArray(v=patterns) then patterns else [patterns] } },
          },
          '#math':: d.obj(help='"Math is used to transform the input via mathematical operations such as multiplication."'),
          math: {
            '#withMultiply':: d.fn(help='"Multiply the value."', args=[d.arg(name='multiply', type=d.T.integer)]),
            withMultiply(multiply): { math+: { multiply: multiply } },
          },
          '#string':: d.obj(help='"String is used to transform the input into a string or a different kind of string. Note that the input does not necessarily need to be a string."'),
          string: {
            '#regexp':: d.obj(help='"Extract a match from the input using a regular expression."'),
            regexp: {
              '#withGroup':: d.fn(help='"Group number to match. 0 (the default) matches the entire expression."', args=[d.arg(name='group', type=d.T.integer)]),
              withGroup(group): { string+: { regexp+: { group: group } } },
              '#withMatch':: d.fn(help='"Match string. May optionally include submatches, aka capture groups. See https://pkg.go.dev/regexp/ for details."', args=[d.arg(name='match', type=d.T.string)]),
              withMatch(match): { string+: { regexp+: { match: match } } },
            },
            '#withConvert':: d.fn(help='"Optional conversion method to be specified. `ToUpper` and `ToLower` change the letter case of the input string. `ToBase64` and `FromBase64` perform a base64 conversion based on the input string. `ToJson` converts any input value into its raw JSON representation. `ToSha1`, `ToSha256` and `ToSha512` generate a hash value based on the input converted to JSON."', args=[d.arg(name='convert', type=d.T.string)]),
            withConvert(convert): { string+: { convert: convert } },
            '#withFmt':: d.fn(help='"Format the input using a Go format string. See https://golang.org/pkg/fmt/ for details."', args=[d.arg(name='fmt', type=d.T.string)]),
            withFmt(fmt): { string+: { fmt: fmt } },
            '#withTrim':: d.fn(help='"Trim the prefix or suffix from the input"', args=[d.arg(name='trim', type=d.T.string)]),
            withTrim(trim): { string+: { trim: trim } },
            '#withType':: d.fn(help='"Type of the string transform to be run."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { string+: { type: type } },
          },
          '#withMap':: d.fn(help='"Map uses the input as a key in the given map and returns the value."', args=[d.arg(name='map', type=d.T.object)]),
          withMap(map): { map: map },
          '#withMapMixin':: d.fn(help='"Map uses the input as a key in the given map and returns the value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='map', type=d.T.object)]),
          withMapMixin(map): { map+: map },
          '#withType':: d.fn(help='"Type of the transform to be run."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#withFromFieldPath':: d.fn(help='"FromFieldPath is the path of the field on the resource whose value is to be used as input. Required when type is FromCompositeFieldPath, FromEnvironmentFieldPath, ToCompositeFieldPath, ToEnvironmentFieldPath."', args=[d.arg(name='fromFieldPath', type=d.T.string)]),
        withFromFieldPath(fromFieldPath): { fromFieldPath: fromFieldPath },
        '#withPatchSetName':: d.fn(help='"PatchSetName to include patches from. Required when type is PatchSet."', args=[d.arg(name='patchSetName', type=d.T.string)]),
        withPatchSetName(patchSetName): { patchSetName: patchSetName },
        '#withToFieldPath':: d.fn(help="\"ToFieldPath is the path of the field on the resource whose value will be changed with the result of transforms. Leave empty if you'd like to propagate to the same path as fromFieldPath.\"", args=[d.arg(name='toFieldPath', type=d.T.string)]),
        withToFieldPath(toFieldPath): { toFieldPath: toFieldPath },
        '#withTransforms':: d.fn(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."', args=[d.arg(name='transforms', type=d.T.array)]),
        withTransforms(transforms): { transforms: if std.isArray(v=transforms) then transforms else [transforms] },
        '#withTransformsMixin':: d.fn(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='transforms', type=d.T.array)]),
        withTransformsMixin(transforms): { transforms+: if std.isArray(v=transforms) then transforms else [transforms] },
        '#withType':: d.fn(help="\"Type sets the patching behaviour to be used. Each patch type may require its' own fields to be set on the Patch object.\"", args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#withName':: d.fn(help='"Name of this PatchSet."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withPatches':: d.fn(help='"Patches will be applied as an overlay to the base resource."', args=[d.arg(name='patches', type=d.T.array)]),
      withPatches(patches): { patches: if std.isArray(v=patches) then patches else [patches] },
      '#withPatchesMixin':: d.fn(help='"Patches will be applied as an overlay to the base resource."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='patches', type=d.T.array)]),
      withPatchesMixin(patches): { patches+: if std.isArray(v=patches) then patches else [patches] },
    },
    '#publishConnectionDetailsWithStoreConfigRef':: d.obj(help='"PublishConnectionDetailsWithStoreConfig specifies the secret store config with which the connection details of composite resources dynamically provisioned using this composition will be published. \\n THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice."'),
    publishConnectionDetailsWithStoreConfigRef: {
      '#withName':: d.fn(help='"Name of the referenced StoreConfig."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsWithStoreConfigRef+: { name: name } } },
    },
    '#resources':: d.obj(help='"Resources is a list of resource templates that will be used when a composite resource referring to this composition is created. At least one of resources and functions must be specififed. If both are specified the resources will be rendered first, then passed to the functions for further processing."'),
    resources: {
      '#connectionDetails':: d.obj(help='"ConnectionDetails lists the propagation secret keys from this target resource to the composition instance connection secret."'),
      connectionDetails: {
        '#withFromConnectionSecretKey':: d.fn(help="\"FromConnectionSecretKey is the key that will be used to fetch the value from the composed resource's connection secret.\"", args=[d.arg(name='fromConnectionSecretKey', type=d.T.string)]),
        withFromConnectionSecretKey(fromConnectionSecretKey): { fromConnectionSecretKey: fromConnectionSecretKey },
        '#withFromFieldPath':: d.fn(help='"FromFieldPath is the path of the field on the composed resource whose value to be used as input. Name must be specified if the type is FromFieldPath."', args=[d.arg(name='fromFieldPath', type=d.T.string)]),
        withFromFieldPath(fromFieldPath): { fromFieldPath: fromFieldPath },
        '#withName':: d.fn(help="\"Name of the connection secret key that will be propagated to the connection secret of the composition instance. Leave empty if you'd like to use the same key name.\"", args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withType':: d.fn(help='"Type sets the connection detail fetching behaviour to be used. Each connection detail type may require its own fields to be set on the ConnectionDetail object. If the type is omitted Crossplane will attempt to infer it based on which other fields were specified. If multiple fields are specified the order of precedence is: 1. FromValue 2. FromConnectionSecretKey 3. FromFieldPath"', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
        '#withValue':: d.fn(help='"Value that will be propagated to the connection secret of the composite resource. May be set to inject a fixed, non-sensitive connection secret value, for example a well-known port."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { value: value },
      },
      '#patches':: d.obj(help='"Patches will be applied as overlay to the base resource."'),
      patches: {
        '#combine':: d.obj(help='"Combine is the patch configuration for a CombineFromComposite, CombineFromEnvironment, CombineToComposite or CombineToEnvironment patch."'),
        combine: {
          '#string':: d.obj(help='"String declares that input variables should be combined into a single string, using the relevant settings for formatting purposes."'),
          string: {
            '#withFmt':: d.fn(help='"Format the input using a Go format string. See https://golang.org/pkg/fmt/ for details."', args=[d.arg(name='fmt', type=d.T.string)]),
            withFmt(fmt): { combine+: { string+: { fmt: fmt } } },
          },
          '#variables':: d.obj(help='"Variables are the list of variables whose values will be retrieved and combined."'),
          variables: {
            '#withFromFieldPath':: d.fn(help='"FromFieldPath is the path of the field on the source whose value is to be used as input."', args=[d.arg(name='fromFieldPath', type=d.T.string)]),
            withFromFieldPath(fromFieldPath): { fromFieldPath: fromFieldPath },
          },
          '#withStrategy':: d.fn(help='"Strategy defines the strategy to use to combine the input variable values. Currently only string is supported."', args=[d.arg(name='strategy', type=d.T.string)]),
          withStrategy(strategy): { combine+: { strategy: strategy } },
          '#withVariables':: d.fn(help='"Variables are the list of variables whose values will be retrieved and combined."', args=[d.arg(name='variables', type=d.T.array)]),
          withVariables(variables): { combine+: { variables: if std.isArray(v=variables) then variables else [variables] } },
          '#withVariablesMixin':: d.fn(help='"Variables are the list of variables whose values will be retrieved and combined."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='variables', type=d.T.array)]),
          withVariablesMixin(variables): { combine+: { variables+: if std.isArray(v=variables) then variables else [variables] } },
        },
        '#policy':: d.obj(help='"Policy configures the specifics of patching behaviour."'),
        policy: {
          '#mergeOptions':: d.obj(help='"MergeOptions Specifies merge options on a field path"'),
          mergeOptions: {
            '#withAppendSlice':: d.fn(help='"Specifies that already existing elements in a merged slice should be preserved"', args=[d.arg(name='appendSlice', type=d.T.boolean)]),
            withAppendSlice(appendSlice): { policy+: { mergeOptions+: { appendSlice: appendSlice } } },
            '#withKeepMapValues':: d.fn(help='"Specifies that already existing values in a merged map should be preserved"', args=[d.arg(name='keepMapValues', type=d.T.boolean)]),
            withKeepMapValues(keepMapValues): { policy+: { mergeOptions+: { keepMapValues: keepMapValues } } },
          },
          '#withFromFieldPath':: d.fn(help="\"FromFieldPath specifies how to patch from a field path. The default is 'Optional', which means the patch will be a no-op if the specified fromFieldPath does not exist. Use 'Required' if the patch should fail if the specified path does not exist.\"", args=[d.arg(name='fromFieldPath', type=d.T.string)]),
          withFromFieldPath(fromFieldPath): { policy+: { fromFieldPath: fromFieldPath } },
        },
        '#transforms':: d.obj(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."'),
        transforms: {
          '#convert':: d.obj(help='"Convert is used to cast the input into the given output type."'),
          convert: {
            '#withFormat':: d.fn(help='"The expected input format. \\n * `quantity` - parses the input as a K8s [`resource.Quantity`](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#Quantity). Only used during `string -> float64` conversions. \\n If this property is null, the default conversion is applied."', args=[d.arg(name='format', type=d.T.string)]),
            withFormat(format): { convert+: { format: format } },
            '#withToType':: d.fn(help='"ToType is the type of the output of this transform."', args=[d.arg(name='toType', type=d.T.string)]),
            withToType(toType): { convert+: { toType: toType } },
          },
          '#match':: d.obj(help='"Match is a more complex version of Map that matches a list of patterns."'),
          match: {
            '#patterns':: d.obj(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."'),
            patterns: {
              '#withLiteral':: d.fn(help='"Literal exactly matches the input string (case sensitive). Is required if `type` is `literal`."', args=[d.arg(name='literal', type=d.T.string)]),
              withLiteral(literal): { literal: literal },
              '#withRegexp':: d.fn(help='"Regexp to match against the input string. Is required if `type` is `regexp`."', args=[d.arg(name='regexp', type=d.T.string)]),
              withRegexp(regexp): { regexp: regexp },
              '#withResult':: d.fn(help='"The value that is used as result of the transform if the pattern matches."', args=[d.arg(name='result', type=d.T.any)]),
              withResult(result): { result: result },
              '#withType':: d.fn(help='"Type specifies how the pattern matches the input. \\n * `literal` - the pattern value has to exactly match (case sensitive) the input string. This is the default. \\n * `regexp` - the pattern treated as a regular expression against which the input string is tested. Crossplane will throw an error if the key is not a valid regexp."', args=[d.arg(name='type', type=d.T.string)]),
              withType(type): { type: type },
            },
            '#withFallbackValue':: d.fn(help='"The fallback value that should be returned by the transform if now pattern matches."', args=[d.arg(name='fallbackValue', type=d.T.any)]),
            withFallbackValue(fallbackValue): { match+: { fallbackValue: fallbackValue } },
            '#withPatterns':: d.fn(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."', args=[d.arg(name='patterns', type=d.T.array)]),
            withPatterns(patterns): { match+: { patterns: if std.isArray(v=patterns) then patterns else [patterns] } },
            '#withPatternsMixin':: d.fn(help='"The patterns that should be tested against the input string. Patterns are tested in order. The value of the first match is used as result of this transform."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='patterns', type=d.T.array)]),
            withPatternsMixin(patterns): { match+: { patterns+: if std.isArray(v=patterns) then patterns else [patterns] } },
          },
          '#math':: d.obj(help='"Math is used to transform the input via mathematical operations such as multiplication."'),
          math: {
            '#withMultiply':: d.fn(help='"Multiply the value."', args=[d.arg(name='multiply', type=d.T.integer)]),
            withMultiply(multiply): { math+: { multiply: multiply } },
          },
          '#string':: d.obj(help='"String is used to transform the input into a string or a different kind of string. Note that the input does not necessarily need to be a string."'),
          string: {
            '#regexp':: d.obj(help='"Extract a match from the input using a regular expression."'),
            regexp: {
              '#withGroup':: d.fn(help='"Group number to match. 0 (the default) matches the entire expression."', args=[d.arg(name='group', type=d.T.integer)]),
              withGroup(group): { string+: { regexp+: { group: group } } },
              '#withMatch':: d.fn(help='"Match string. May optionally include submatches, aka capture groups. See https://pkg.go.dev/regexp/ for details."', args=[d.arg(name='match', type=d.T.string)]),
              withMatch(match): { string+: { regexp+: { match: match } } },
            },
            '#withConvert':: d.fn(help='"Optional conversion method to be specified. `ToUpper` and `ToLower` change the letter case of the input string. `ToBase64` and `FromBase64` perform a base64 conversion based on the input string. `ToJson` converts any input value into its raw JSON representation. `ToSha1`, `ToSha256` and `ToSha512` generate a hash value based on the input converted to JSON."', args=[d.arg(name='convert', type=d.T.string)]),
            withConvert(convert): { string+: { convert: convert } },
            '#withFmt':: d.fn(help='"Format the input using a Go format string. See https://golang.org/pkg/fmt/ for details."', args=[d.arg(name='fmt', type=d.T.string)]),
            withFmt(fmt): { string+: { fmt: fmt } },
            '#withTrim':: d.fn(help='"Trim the prefix or suffix from the input"', args=[d.arg(name='trim', type=d.T.string)]),
            withTrim(trim): { string+: { trim: trim } },
            '#withType':: d.fn(help='"Type of the string transform to be run."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { string+: { type: type } },
          },
          '#withMap':: d.fn(help='"Map uses the input as a key in the given map and returns the value."', args=[d.arg(name='map', type=d.T.object)]),
          withMap(map): { map: map },
          '#withMapMixin':: d.fn(help='"Map uses the input as a key in the given map and returns the value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='map', type=d.T.object)]),
          withMapMixin(map): { map+: map },
          '#withType':: d.fn(help='"Type of the transform to be run."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#withFromFieldPath':: d.fn(help='"FromFieldPath is the path of the field on the resource whose value is to be used as input. Required when type is FromCompositeFieldPath, FromEnvironmentFieldPath, ToCompositeFieldPath, ToEnvironmentFieldPath."', args=[d.arg(name='fromFieldPath', type=d.T.string)]),
        withFromFieldPath(fromFieldPath): { fromFieldPath: fromFieldPath },
        '#withPatchSetName':: d.fn(help='"PatchSetName to include patches from. Required when type is PatchSet."', args=[d.arg(name='patchSetName', type=d.T.string)]),
        withPatchSetName(patchSetName): { patchSetName: patchSetName },
        '#withToFieldPath':: d.fn(help="\"ToFieldPath is the path of the field on the resource whose value will be changed with the result of transforms. Leave empty if you'd like to propagate to the same path as fromFieldPath.\"", args=[d.arg(name='toFieldPath', type=d.T.string)]),
        withToFieldPath(toFieldPath): { toFieldPath: toFieldPath },
        '#withTransforms':: d.fn(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."', args=[d.arg(name='transforms', type=d.T.array)]),
        withTransforms(transforms): { transforms: if std.isArray(v=transforms) then transforms else [transforms] },
        '#withTransformsMixin':: d.fn(help='"Transforms are the list of functions that are used as a FIFO pipe for the input to be transformed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='transforms', type=d.T.array)]),
        withTransformsMixin(transforms): { transforms+: if std.isArray(v=transforms) then transforms else [transforms] },
        '#withType':: d.fn(help="\"Type sets the patching behaviour to be used. Each patch type may require its' own fields to be set on the Patch object.\"", args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#readinessChecks':: d.obj(help='"ReadinessChecks allows users to define custom readiness checks. All checks have to return true in order for resource to be considered ready. The default readiness check is to have the \\"Ready\\" condition to be \\"True\\"."'),
      readinessChecks: {
        '#withFieldPath':: d.fn(help='"FieldPath shows the path of the field whose value will be used."', args=[d.arg(name='fieldPath', type=d.T.string)]),
        withFieldPath(fieldPath): { fieldPath: fieldPath },
        '#withMatchInteger':: d.fn(help="\"MatchInt is the value you'd like to match if you're using \\\"MatchInt\\\" type.\"", args=[d.arg(name='matchInteger', type=d.T.integer)]),
        withMatchInteger(matchInteger): { matchInteger: matchInteger },
        '#withMatchString':: d.fn(help="\"MatchString is the value you'd like to match if you're using \\\"MatchString\\\" type.\"", args=[d.arg(name='matchString', type=d.T.string)]),
        withMatchString(matchString): { matchString: matchString },
        '#withType':: d.fn(help="\"Type indicates the type of probe you'd like to use.\"", args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#withBase':: d.fn(help='"Base is the target resource that the patches will be applied on."', args=[d.arg(name='base', type=d.T.object)]),
      withBase(base): { base: base },
      '#withBaseMixin':: d.fn(help='"Base is the target resource that the patches will be applied on."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='base', type=d.T.object)]),
      withBaseMixin(base): { base+: base },
      '#withConnectionDetails':: d.fn(help='"ConnectionDetails lists the propagation secret keys from this target resource to the composition instance connection secret."', args=[d.arg(name='connectionDetails', type=d.T.array)]),
      withConnectionDetails(connectionDetails): { connectionDetails: if std.isArray(v=connectionDetails) then connectionDetails else [connectionDetails] },
      '#withConnectionDetailsMixin':: d.fn(help='"ConnectionDetails lists the propagation secret keys from this target resource to the composition instance connection secret."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='connectionDetails', type=d.T.array)]),
      withConnectionDetailsMixin(connectionDetails): { connectionDetails+: if std.isArray(v=connectionDetails) then connectionDetails else [connectionDetails] },
      '#withName':: d.fn(help="\"A Name uniquely identifies this entry within its Composition's resources array. Names are optional but *strongly* recommended. When all entries in the resources array are named entries may added, deleted, and reordered as long as their names do not change. When entries are not named the length and order of the resources array should be treated as immutable. Either all or no entries must be named.\"", args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withPatches':: d.fn(help='"Patches will be applied as overlay to the base resource."', args=[d.arg(name='patches', type=d.T.array)]),
      withPatches(patches): { patches: if std.isArray(v=patches) then patches else [patches] },
      '#withPatchesMixin':: d.fn(help='"Patches will be applied as overlay to the base resource."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='patches', type=d.T.array)]),
      withPatchesMixin(patches): { patches+: if std.isArray(v=patches) then patches else [patches] },
      '#withReadinessChecks':: d.fn(help='"ReadinessChecks allows users to define custom readiness checks. All checks have to return true in order for resource to be considered ready. The default readiness check is to have the \\"Ready\\" condition to be \\"True\\"."', args=[d.arg(name='readinessChecks', type=d.T.array)]),
      withReadinessChecks(readinessChecks): { readinessChecks: if std.isArray(v=readinessChecks) then readinessChecks else [readinessChecks] },
      '#withReadinessChecksMixin':: d.fn(help='"ReadinessChecks allows users to define custom readiness checks. All checks have to return true in order for resource to be considered ready. The default readiness check is to have the \\"Ready\\" condition to be \\"True\\"."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='readinessChecks', type=d.T.array)]),
      withReadinessChecksMixin(readinessChecks): { readinessChecks+: if std.isArray(v=readinessChecks) then readinessChecks else [readinessChecks] },
    },
    '#withFunctions':: d.fn(help='"Functions is list of Composition Functions that will be used when a composite resource referring to this composition is created. At least one of resources and functions must be specified. If both are specified the resources will be rendered first, then passed to the functions for further processing. \\n THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice."', args=[d.arg(name='functions', type=d.T.array)]),
    withFunctions(functions): { spec+: { functions: if std.isArray(v=functions) then functions else [functions] } },
    '#withFunctionsMixin':: d.fn(help='"Functions is list of Composition Functions that will be used when a composite resource referring to this composition is created. At least one of resources and functions must be specified. If both are specified the resources will be rendered first, then passed to the functions for further processing. \\n THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='functions', type=d.T.array)]),
    withFunctionsMixin(functions): { spec+: { functions+: if std.isArray(v=functions) then functions else [functions] } },
    '#withPatchSets':: d.fn(help='"PatchSets define a named set of patches that may be included by any resource in this Composition. PatchSets cannot themselves refer to other PatchSets."', args=[d.arg(name='patchSets', type=d.T.array)]),
    withPatchSets(patchSets): { spec+: { patchSets: if std.isArray(v=patchSets) then patchSets else [patchSets] } },
    '#withPatchSetsMixin':: d.fn(help='"PatchSets define a named set of patches that may be included by any resource in this Composition. PatchSets cannot themselves refer to other PatchSets."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='patchSets', type=d.T.array)]),
    withPatchSetsMixin(patchSets): { spec+: { patchSets+: if std.isArray(v=patchSets) then patchSets else [patchSets] } },
    '#withResources':: d.fn(help='"Resources is a list of resource templates that will be used when a composite resource referring to this composition is created. At least one of resources and functions must be specififed. If both are specified the resources will be rendered first, then passed to the functions for further processing."', args=[d.arg(name='resources', type=d.T.array)]),
    withResources(resources): { spec+: { resources: if std.isArray(v=resources) then resources else [resources] } },
    '#withResourcesMixin':: d.fn(help='"Resources is a list of resource templates that will be used when a composite resource referring to this composition is created. At least one of resources and functions must be specififed. If both are specified the resources will be rendered first, then passed to the functions for further processing."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='resources', type=d.T.array)]),
    withResourcesMixin(resources): { spec+: { resources+: if std.isArray(v=resources) then resources else [resources] } },
    '#withWriteConnectionSecretsToNamespace':: d.fn(help='"WriteConnectionSecretsToNamespace specifies the namespace in which the connection secrets of composite resource dynamically provisioned using this composition will be created. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsWithStoreConfigRef. Currently, both could be set independently and connection details would be published to both without affecting each other as long as related fields at MR level specified."', args=[d.arg(name='writeConnectionSecretsToNamespace', type=d.T.string)]),
    withWriteConnectionSecretsToNamespace(writeConnectionSecretsToNamespace): { spec+: { writeConnectionSecretsToNamespace: writeConnectionSecretsToNamespace } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
