{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='target', url='', help='"Target is the Schema for the Targets API. Provides an EventBridge Target resource."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Target', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'cloudwatchevents.aws.upbound.io/v1beta1',
    kind: 'Target',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"TargetSpec defines the desired state of Target"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#batchTarget':: d.obj(help='"Parameters used when you are using the rule to invoke an Amazon Batch Job. Documented below. A maximum of 1 are allowed."'),
      batchTarget: {
        '#withArraySize':: d.fn(help='"The size of the array, if this is an array batch job. Valid values are integers between 2 and 10,000."', args=[d.arg(name='arraySize', type=d.T.number)]),
        withArraySize(arraySize): { arraySize: arraySize },
        '#withJobAttempts':: d.fn(help='"The number of times to attempt to retry, if the job fails. Valid values are 1 to 10."', args=[d.arg(name='jobAttempts', type=d.T.number)]),
        withJobAttempts(jobAttempts): { jobAttempts: jobAttempts },
        '#withJobDefinition':: d.fn(help='"The ARN or name of the job definition to use if the event target is an AWS Batch job. This job definition must already exist."', args=[d.arg(name='jobDefinition', type=d.T.string)]),
        withJobDefinition(jobDefinition): { jobDefinition: jobDefinition },
        '#withJobName':: d.fn(help='"The name to use for this execution of the job, if the target is an AWS Batch job."', args=[d.arg(name='jobName', type=d.T.string)]),
        withJobName(jobName): { jobName: jobName },
      },
      '#deadLetterConfig':: d.obj(help='"Parameters used when you are providing a dead letter config. Documented below. A maximum of 1 are allowed."'),
      deadLetterConfig: {
        '#withArn':: d.fn(help='"- ARN of the SQS queue specified as the target for the dead-letter queue."', args=[d.arg(name='arn', type=d.T.string)]),
        withArn(arn): { arn: arn },
      },
      '#ecsTarget':: d.obj(help='"Parameters used when you are using the rule to invoke Amazon ECS Task. Documented below. A maximum of 1 are allowed."'),
      ecsTarget: {
        '#networkConfiguration':: d.obj(help='"Use this if the ECS task uses the awsvpc network mode. This specifies the VPC subnets and security groups associated with the task, and whether a public IP address is to be used. Required if launch_type is FARGATE because the awsvpc mode is required for Fargate tasks."'),
        networkConfiguration: {
          '#withAssignPublicIp':: d.fn(help='"Assign a public IP address to the ENI (Fargate launch type only). Valid values are true or false. Default false."', args=[d.arg(name='assignPublicIp', type=d.T.boolean)]),
          withAssignPublicIp(assignPublicIp): { assignPublicIp: assignPublicIp },
          '#withSecurityGroups':: d.fn(help='"The security groups associated with the task or service. If you do not specify a security group, the default security group for the VPC is used."', args=[d.arg(name='securityGroups', type=d.T.array)]),
          withSecurityGroups(securityGroups): { securityGroups: if std.isArray(v=securityGroups) then securityGroups else [securityGroups] },
          '#withSecurityGroupsMixin':: d.fn(help='"The security groups associated with the task or service. If you do not specify a security group, the default security group for the VPC is used."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='securityGroups', type=d.T.array)]),
          withSecurityGroupsMixin(securityGroups): { securityGroups+: if std.isArray(v=securityGroups) then securityGroups else [securityGroups] },
          '#withSubnets':: d.fn(help='"The subnets associated with the task or service."', args=[d.arg(name='subnets', type=d.T.array)]),
          withSubnets(subnets): { subnets: if std.isArray(v=subnets) then subnets else [subnets] },
          '#withSubnetsMixin':: d.fn(help='"The subnets associated with the task or service."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='subnets', type=d.T.array)]),
          withSubnetsMixin(subnets): { subnets+: if std.isArray(v=subnets) then subnets else [subnets] },
        },
        '#placementConstraint':: d.obj(help='"An array of placement constraint objects to use for the task. You can specify up to 10 constraints per task (including constraints in the task definition and those specified at runtime). See Below."'),
        placementConstraint: {
          '#withExpression':: d.fn(help='"Cluster Query Language expression to apply to the constraint. Does not need to be specified for the distinctInstance type. For more information, see Cluster Query Language in the Amazon EC2 Container Service Developer Guide."', args=[d.arg(name='expression', type=d.T.string)]),
          withExpression(expression): { expression: expression },
          '#withType':: d.fn(help='"Type of constraint. The only valid values at this time are memberOf and distinctInstance."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#taskDefinitionArnRef':: d.obj(help='"Reference to a TaskDefinition in ecs to populate taskDefinitionArn."'),
        taskDefinitionArnRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { taskDefinitionArnRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { taskDefinitionArnRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { taskDefinitionArnRef+: { name: name } },
        },
        '#taskDefinitionArnSelector':: d.obj(help='"Selector for a TaskDefinition in ecs to populate taskDefinitionArn."'),
        taskDefinitionArnSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { taskDefinitionArnSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { taskDefinitionArnSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { taskDefinitionArnSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { taskDefinitionArnSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { taskDefinitionArnSelector+: { matchLabels+: matchLabels } },
        },
        '#withEnableEcsManagedTags':: d.fn(help='"Specifies whether to enable Amazon ECS managed tags for the task."', args=[d.arg(name='enableEcsManagedTags', type=d.T.boolean)]),
        withEnableEcsManagedTags(enableEcsManagedTags): { enableEcsManagedTags: enableEcsManagedTags },
        '#withEnableExecuteCommand':: d.fn(help='"Whether or not to enable the execute command functionality for the containers in this task. If true, this enables execute command functionality on all containers in the task."', args=[d.arg(name='enableExecuteCommand', type=d.T.boolean)]),
        withEnableExecuteCommand(enableExecuteCommand): { enableExecuteCommand: enableExecuteCommand },
        '#withGroup':: d.fn(help='"Specifies an ECS task group for the task. The maximum length is 255 characters."', args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { group: group },
        '#withLaunchType':: d.fn(help='"Specifies the launch type on which your task is running. The launch type that you specify here must match one of the launch type (compatibilities) of the target task. Valid values include: an empty string \\"\\" (to specify no launch type), EC2, or FARGATE."', args=[d.arg(name='launchType', type=d.T.string)]),
        withLaunchType(launchType): { launchType: launchType },
        '#withNetworkConfiguration':: d.fn(help='"Use this if the ECS task uses the awsvpc network mode. This specifies the VPC subnets and security groups associated with the task, and whether a public IP address is to be used. Required if launch_type is FARGATE because the awsvpc mode is required for Fargate tasks."', args=[d.arg(name='networkConfiguration', type=d.T.array)]),
        withNetworkConfiguration(networkConfiguration): { networkConfiguration: if std.isArray(v=networkConfiguration) then networkConfiguration else [networkConfiguration] },
        '#withNetworkConfigurationMixin':: d.fn(help='"Use this if the ECS task uses the awsvpc network mode. This specifies the VPC subnets and security groups associated with the task, and whether a public IP address is to be used. Required if launch_type is FARGATE because the awsvpc mode is required for Fargate tasks."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='networkConfiguration', type=d.T.array)]),
        withNetworkConfigurationMixin(networkConfiguration): { networkConfiguration+: if std.isArray(v=networkConfiguration) then networkConfiguration else [networkConfiguration] },
        '#withPlacementConstraint':: d.fn(help='"An array of placement constraint objects to use for the task. You can specify up to 10 constraints per task (including constraints in the task definition and those specified at runtime). See Below."', args=[d.arg(name='placementConstraint', type=d.T.array)]),
        withPlacementConstraint(placementConstraint): { placementConstraint: if std.isArray(v=placementConstraint) then placementConstraint else [placementConstraint] },
        '#withPlacementConstraintMixin':: d.fn(help='"An array of placement constraint objects to use for the task. You can specify up to 10 constraints per task (including constraints in the task definition and those specified at runtime). See Below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='placementConstraint', type=d.T.array)]),
        withPlacementConstraintMixin(placementConstraint): { placementConstraint+: if std.isArray(v=placementConstraint) then placementConstraint else [placementConstraint] },
        '#withPlatformVersion':: d.fn(help='"Specifies the platform version for the task. Specify only the numeric portion of the platform version, such as 1.1.0. This is used only if LaunchType is FARGATE. For more information about valid platform versions, see AWS Fargate Platform Versions."', args=[d.arg(name='platformVersion', type=d.T.string)]),
        withPlatformVersion(platformVersion): { platformVersion: platformVersion },
        '#withPropagateTags':: d.fn(help='"Specifies whether to propagate the tags from the task definition to the task. If no value is specified, the tags are not propagated. Tags can only be propagated to the task during task creation."', args=[d.arg(name='propagateTags', type=d.T.string)]),
        withPropagateTags(propagateTags): { propagateTags: propagateTags },
        '#withTags':: d.fn(help='"A map of tags to assign to ecs resources."', args=[d.arg(name='tags', type=d.T.object)]),
        withTags(tags): { tags: tags },
        '#withTagsMixin':: d.fn(help='"A map of tags to assign to ecs resources."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
        withTagsMixin(tags): { tags+: tags },
        '#withTaskCount':: d.fn(help='"The number of tasks to create based on the TaskDefinition. The default is 1."', args=[d.arg(name='taskCount', type=d.T.number)]),
        withTaskCount(taskCount): { taskCount: taskCount },
        '#withTaskDefinitionArn':: d.fn(help='"The ARN of the task definition to use if the event target is an Amazon ECS cluster."', args=[d.arg(name='taskDefinitionArn', type=d.T.string)]),
        withTaskDefinitionArn(taskDefinitionArn): { taskDefinitionArn: taskDefinitionArn },
      },
      '#eventBusNameRef':: d.obj(help='"Reference to a Bus to populate eventBusName."'),
      eventBusNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { eventBusNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { eventBusNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { eventBusNameRef+: { name: name } } } },
      },
      '#eventBusNameSelector':: d.obj(help='"Selector for a Bus to populate eventBusName."'),
      eventBusNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { eventBusNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { eventBusNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { eventBusNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { eventBusNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { eventBusNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#httpTarget':: d.obj(help='"Parameters used when you are using the rule to invoke an API Gateway REST endpoint. Documented below. A maximum of 1 is allowed."'),
      httpTarget: {
        '#withHeaderParameters':: d.fn(help='"Enables you to specify HTTP headers to add to the request."', args=[d.arg(name='headerParameters', type=d.T.object)]),
        withHeaderParameters(headerParameters): { headerParameters: headerParameters },
        '#withHeaderParametersMixin':: d.fn(help='"Enables you to specify HTTP headers to add to the request."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headerParameters', type=d.T.object)]),
        withHeaderParametersMixin(headerParameters): { headerParameters+: headerParameters },
        '#withPathParameterValues':: d.fn(help='"The list of values that correspond sequentially to any path variables in your endpoint ARN (for example arn:aws:execute-api:us-east-1:123456:myapi/*/POST/pets/*)."', args=[d.arg(name='pathParameterValues', type=d.T.array)]),
        withPathParameterValues(pathParameterValues): { pathParameterValues: if std.isArray(v=pathParameterValues) then pathParameterValues else [pathParameterValues] },
        '#withPathParameterValuesMixin':: d.fn(help='"The list of values that correspond sequentially to any path variables in your endpoint ARN (for example arn:aws:execute-api:us-east-1:123456:myapi/*/POST/pets/*)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='pathParameterValues', type=d.T.array)]),
        withPathParameterValuesMixin(pathParameterValues): { pathParameterValues+: if std.isArray(v=pathParameterValues) then pathParameterValues else [pathParameterValues] },
        '#withQueryStringParameters':: d.fn(help='"Represents keys/values of query string parameters that are appended to the invoked endpoint."', args=[d.arg(name='queryStringParameters', type=d.T.object)]),
        withQueryStringParameters(queryStringParameters): { queryStringParameters: queryStringParameters },
        '#withQueryStringParametersMixin':: d.fn(help='"Represents keys/values of query string parameters that are appended to the invoked endpoint."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='queryStringParameters', type=d.T.object)]),
        withQueryStringParametersMixin(queryStringParameters): { queryStringParameters+: queryStringParameters },
      },
      '#inputTransformer':: d.obj(help='"Parameters used when you are providing a custom input to a target based on certain event data. Conflicts with input and input_path."'),
      inputTransformer: {
        '#withInputPaths':: d.fn(help='"Key value pairs specified in the form of JSONPath (for example, time = $.time)"', args=[d.arg(name='inputPaths', type=d.T.object)]),
        withInputPaths(inputPaths): { inputPaths: inputPaths },
        '#withInputPathsMixin':: d.fn(help='"Key value pairs specified in the form of JSONPath (for example, time = $.time)"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='inputPaths', type=d.T.object)]),
        withInputPathsMixin(inputPaths): { inputPaths+: inputPaths },
        '#withInputTemplate':: d.fn(help='"Template to customize data sent to the target. Must be valid JSON. To send a string value, the string value must include double quotes.g., \\"\\\\\\"Your string goes here.\\\\\\\\nA new line.\\\\\\"\\', args=[d.arg(name='inputTemplate', type=d.T.string)]),
        withInputTemplate(inputTemplate): { inputTemplate: inputTemplate },
      },
      '#kinesisTarget':: d.obj(help='"Parameters used when you are using the rule to invoke an Amazon Kinesis Stream. Documented below. A maximum of 1 are allowed."'),
      kinesisTarget: {
        '#withPartitionKeyPath':: d.fn(help='"The JSON path to be extracted from the event and used as the partition key."', args=[d.arg(name='partitionKeyPath', type=d.T.string)]),
        withPartitionKeyPath(partitionKeyPath): { partitionKeyPath: partitionKeyPath },
      },
      '#redshiftTarget':: d.obj(help='"Parameters used when you are using the rule to invoke an Amazon Redshift Statement. Documented below. A maximum of 1 are allowed."'),
      redshiftTarget: {
        '#withDatabase':: d.fn(help='"The name of the database."', args=[d.arg(name='database', type=d.T.string)]),
        withDatabase(database): { database: database },
        '#withDbUser':: d.fn(help='"The database user name."', args=[d.arg(name='dbUser', type=d.T.string)]),
        withDbUser(dbUser): { dbUser: dbUser },
        '#withSecretsManagerArn':: d.fn(help='"The name or ARN of the secret that enables access to the database."', args=[d.arg(name='secretsManagerArn', type=d.T.string)]),
        withSecretsManagerArn(secretsManagerArn): { secretsManagerArn: secretsManagerArn },
        '#withSql':: d.fn(help='"The SQL statement text to run."', args=[d.arg(name='sql', type=d.T.string)]),
        withSql(sql): { sql: sql },
        '#withStatementName':: d.fn(help='"The name of the SQL statement."', args=[d.arg(name='statementName', type=d.T.string)]),
        withStatementName(statementName): { statementName: statementName },
        '#withWithEvent':: d.fn(help='"Indicates whether to send an event back to EventBridge after the SQL statement runs."', args=[d.arg(name='withEvent', type=d.T.boolean)]),
        withWithEvent(withEvent): { withEvent: withEvent },
      },
      '#retryPolicy':: d.obj(help='"Parameters used when you are providing retry policies. Documented below. A maximum of 1 are allowed."'),
      retryPolicy: {
        '#withMaximumEventAgeInSeconds':: d.fn(help='"The age in seconds to continue to make retry attempts."', args=[d.arg(name='maximumEventAgeInSeconds', type=d.T.number)]),
        withMaximumEventAgeInSeconds(maximumEventAgeInSeconds): { maximumEventAgeInSeconds: maximumEventAgeInSeconds },
        '#withMaximumRetryAttempts':: d.fn(help='"maximum number of retry attempts to make before the request fails"', args=[d.arg(name='maximumRetryAttempts', type=d.T.number)]),
        withMaximumRetryAttempts(maximumRetryAttempts): { maximumRetryAttempts: maximumRetryAttempts },
      },
      '#roleArnRef':: d.obj(help='"Reference to a Role in iam to populate roleArn."'),
      roleArnRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { roleArnRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { roleArnRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { roleArnRef+: { name: name } } } },
      },
      '#roleArnSelector':: d.obj(help='"Selector for a Role in iam to populate roleArn."'),
      roleArnSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { roleArnSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { roleArnSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { roleArnSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { roleArnSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { roleArnSelector+: { matchLabels+: matchLabels } } } },
      },
      '#ruleRef':: d.obj(help='"Reference to a Rule in cloudwatchevents to populate rule."'),
      ruleRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { ruleRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { ruleRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { ruleRef+: { name: name } } } },
      },
      '#ruleSelector':: d.obj(help='"Selector for a Rule in cloudwatchevents to populate rule."'),
      ruleSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { ruleSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { ruleSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { ruleSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { ruleSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { ruleSelector+: { matchLabels+: matchLabels } } } },
      },
      '#runCommandTargets':: d.obj(help='"Parameters used when you are using the rule to invoke Amazon EC2 Run Command. Documented below. A maximum of 5 are allowed."'),
      runCommandTargets: {
        '#withKey':: d.fn(help='"Can be either tag:tag-key or InstanceIds."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withValues':: d.fn(help='"If Key is tag:tag-key, Values is a list of tag values. If Key is InstanceIds, Values is a list of Amazon EC2 instance IDs."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"If Key is tag:tag-key, Values is a list of tag values. If Key is InstanceIds, Values is a list of Amazon EC2 instance IDs."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#sqsTarget':: d.obj(help='"Parameters used when you are using the rule to invoke an Amazon SQS Queue. Documented below. A maximum of 1 are allowed."'),
      sqsTarget: {
        '#withMessageGroupId':: d.fn(help='"The FIFO message group ID to use as the target."', args=[d.arg(name='messageGroupId', type=d.T.string)]),
        withMessageGroupId(messageGroupId): { messageGroupId: messageGroupId },
      },
      '#withArn':: d.fn(help='"The Amazon Resource Name (ARN) of the target."', args=[d.arg(name='arn', type=d.T.string)]),
      withArn(arn): { spec+: { forProvider+: { arn: arn } } },
      '#withBatchTarget':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon Batch Job. Documented below. A maximum of 1 are allowed."', args=[d.arg(name='batchTarget', type=d.T.array)]),
      withBatchTarget(batchTarget): { spec+: { forProvider+: { batchTarget: if std.isArray(v=batchTarget) then batchTarget else [batchTarget] } } },
      '#withBatchTargetMixin':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon Batch Job. Documented below. A maximum of 1 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='batchTarget', type=d.T.array)]),
      withBatchTargetMixin(batchTarget): { spec+: { forProvider+: { batchTarget+: if std.isArray(v=batchTarget) then batchTarget else [batchTarget] } } },
      '#withDeadLetterConfig':: d.fn(help='"Parameters used when you are providing a dead letter config. Documented below. A maximum of 1 are allowed."', args=[d.arg(name='deadLetterConfig', type=d.T.array)]),
      withDeadLetterConfig(deadLetterConfig): { spec+: { forProvider+: { deadLetterConfig: if std.isArray(v=deadLetterConfig) then deadLetterConfig else [deadLetterConfig] } } },
      '#withDeadLetterConfigMixin':: d.fn(help='"Parameters used when you are providing a dead letter config. Documented below. A maximum of 1 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='deadLetterConfig', type=d.T.array)]),
      withDeadLetterConfigMixin(deadLetterConfig): { spec+: { forProvider+: { deadLetterConfig+: if std.isArray(v=deadLetterConfig) then deadLetterConfig else [deadLetterConfig] } } },
      '#withEcsTarget':: d.fn(help='"Parameters used when you are using the rule to invoke Amazon ECS Task. Documented below. A maximum of 1 are allowed."', args=[d.arg(name='ecsTarget', type=d.T.array)]),
      withEcsTarget(ecsTarget): { spec+: { forProvider+: { ecsTarget: if std.isArray(v=ecsTarget) then ecsTarget else [ecsTarget] } } },
      '#withEcsTargetMixin':: d.fn(help='"Parameters used when you are using the rule to invoke Amazon ECS Task. Documented below. A maximum of 1 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ecsTarget', type=d.T.array)]),
      withEcsTargetMixin(ecsTarget): { spec+: { forProvider+: { ecsTarget+: if std.isArray(v=ecsTarget) then ecsTarget else [ecsTarget] } } },
      '#withEventBusName':: d.fn(help='"The event bus to associate with the rule. If you omit this, the default event bus is used."', args=[d.arg(name='eventBusName', type=d.T.string)]),
      withEventBusName(eventBusName): { spec+: { forProvider+: { eventBusName: eventBusName } } },
      '#withHttpTarget':: d.fn(help='"Parameters used when you are using the rule to invoke an API Gateway REST endpoint. Documented below. A maximum of 1 is allowed."', args=[d.arg(name='httpTarget', type=d.T.array)]),
      withHttpTarget(httpTarget): { spec+: { forProvider+: { httpTarget: if std.isArray(v=httpTarget) then httpTarget else [httpTarget] } } },
      '#withHttpTargetMixin':: d.fn(help='"Parameters used when you are using the rule to invoke an API Gateway REST endpoint. Documented below. A maximum of 1 is allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='httpTarget', type=d.T.array)]),
      withHttpTargetMixin(httpTarget): { spec+: { forProvider+: { httpTarget+: if std.isArray(v=httpTarget) then httpTarget else [httpTarget] } } },
      '#withInput':: d.fn(help='"Valid JSON text passed to the target. Conflicts with input_path and input_transformer."', args=[d.arg(name='input', type=d.T.string)]),
      withInput(input): { spec+: { forProvider+: { input: input } } },
      '#withInputPath':: d.fn(help='"The value of the JSONPath that is used for extracting part of the matched event when passing it to the target. Conflicts with input and input_transformer."', args=[d.arg(name='inputPath', type=d.T.string)]),
      withInputPath(inputPath): { spec+: { forProvider+: { inputPath: inputPath } } },
      '#withInputTransformer':: d.fn(help='"Parameters used when you are providing a custom input to a target based on certain event data. Conflicts with input and input_path."', args=[d.arg(name='inputTransformer', type=d.T.array)]),
      withInputTransformer(inputTransformer): { spec+: { forProvider+: { inputTransformer: if std.isArray(v=inputTransformer) then inputTransformer else [inputTransformer] } } },
      '#withInputTransformerMixin':: d.fn(help='"Parameters used when you are providing a custom input to a target based on certain event data. Conflicts with input and input_path."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='inputTransformer', type=d.T.array)]),
      withInputTransformerMixin(inputTransformer): { spec+: { forProvider+: { inputTransformer+: if std.isArray(v=inputTransformer) then inputTransformer else [inputTransformer] } } },
      '#withKinesisTarget':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon Kinesis Stream. Documented below. A maximum of 1 are allowed."', args=[d.arg(name='kinesisTarget', type=d.T.array)]),
      withKinesisTarget(kinesisTarget): { spec+: { forProvider+: { kinesisTarget: if std.isArray(v=kinesisTarget) then kinesisTarget else [kinesisTarget] } } },
      '#withKinesisTargetMixin':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon Kinesis Stream. Documented below. A maximum of 1 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='kinesisTarget', type=d.T.array)]),
      withKinesisTargetMixin(kinesisTarget): { spec+: { forProvider+: { kinesisTarget+: if std.isArray(v=kinesisTarget) then kinesisTarget else [kinesisTarget] } } },
      '#withRedshiftTarget':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon Redshift Statement. Documented below. A maximum of 1 are allowed."', args=[d.arg(name='redshiftTarget', type=d.T.array)]),
      withRedshiftTarget(redshiftTarget): { spec+: { forProvider+: { redshiftTarget: if std.isArray(v=redshiftTarget) then redshiftTarget else [redshiftTarget] } } },
      '#withRedshiftTargetMixin':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon Redshift Statement. Documented below. A maximum of 1 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='redshiftTarget', type=d.T.array)]),
      withRedshiftTargetMixin(redshiftTarget): { spec+: { forProvider+: { redshiftTarget+: if std.isArray(v=redshiftTarget) then redshiftTarget else [redshiftTarget] } } },
      '#withRegion':: d.fn(help="\"Region is the region you'd like your resource to be created in.\"", args=[d.arg(name='region', type=d.T.string)]),
      withRegion(region): { spec+: { forProvider+: { region: region } } },
      '#withRetryPolicy':: d.fn(help='"Parameters used when you are providing retry policies. Documented below. A maximum of 1 are allowed."', args=[d.arg(name='retryPolicy', type=d.T.array)]),
      withRetryPolicy(retryPolicy): { spec+: { forProvider+: { retryPolicy: if std.isArray(v=retryPolicy) then retryPolicy else [retryPolicy] } } },
      '#withRetryPolicyMixin':: d.fn(help='"Parameters used when you are providing retry policies. Documented below. A maximum of 1 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='retryPolicy', type=d.T.array)]),
      withRetryPolicyMixin(retryPolicy): { spec+: { forProvider+: { retryPolicy+: if std.isArray(v=retryPolicy) then retryPolicy else [retryPolicy] } } },
      '#withRoleArn':: d.fn(help='"The Amazon Resource Name (ARN) of the IAM role to be used for this target when the rule is triggered. Required if ecs_target is used or target in arn is EC2 instance, Kinesis data stream, Step Functions state machine, or Event Bus in different account or region."', args=[d.arg(name='roleArn', type=d.T.string)]),
      withRoleArn(roleArn): { spec+: { forProvider+: { roleArn: roleArn } } },
      '#withRule':: d.fn(help='"The name of the rule you want to add targets to."', args=[d.arg(name='rule', type=d.T.string)]),
      withRule(rule): { spec+: { forProvider+: { rule: rule } } },
      '#withRunCommandTargets':: d.fn(help='"Parameters used when you are using the rule to invoke Amazon EC2 Run Command. Documented below. A maximum of 5 are allowed."', args=[d.arg(name='runCommandTargets', type=d.T.array)]),
      withRunCommandTargets(runCommandTargets): { spec+: { forProvider+: { runCommandTargets: if std.isArray(v=runCommandTargets) then runCommandTargets else [runCommandTargets] } } },
      '#withRunCommandTargetsMixin':: d.fn(help='"Parameters used when you are using the rule to invoke Amazon EC2 Run Command. Documented below. A maximum of 5 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='runCommandTargets', type=d.T.array)]),
      withRunCommandTargetsMixin(runCommandTargets): { spec+: { forProvider+: { runCommandTargets+: if std.isArray(v=runCommandTargets) then runCommandTargets else [runCommandTargets] } } },
      '#withSqsTarget':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon SQS Queue. Documented below. A maximum of 1 are allowed."', args=[d.arg(name='sqsTarget', type=d.T.array)]),
      withSqsTarget(sqsTarget): { spec+: { forProvider+: { sqsTarget: if std.isArray(v=sqsTarget) then sqsTarget else [sqsTarget] } } },
      '#withSqsTargetMixin':: d.fn(help='"Parameters used when you are using the rule to invoke an Amazon SQS Queue. Documented below. A maximum of 1 are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sqsTarget', type=d.T.array)]),
      withSqsTargetMixin(sqsTarget): { spec+: { forProvider+: { sqsTarget+: if std.isArray(v=sqsTarget) then sqsTarget else [sqsTarget] } } },
      '#withTargetId':: d.fn(help='"The unique target assignment ID.  If missing, will generate a random, unique id."', args=[d.arg(name='targetId', type=d.T.string)]),
      withTargetId(targetId): { spec+: { forProvider+: { targetId: targetId } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
