{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='reservation', url='', help='"Reservation is the Schema for the Reservations API. Represents a reservation resource."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Reservation', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'compute.gcp.upbound.io/v1beta1',
    kind: 'Reservation',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"ReservationSpec defines the desired state of Reservation"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#shareSettings':: d.obj(help='"The share setting for reservations. Structure is documented below."'),
      shareSettings: {
        '#projectMap':: d.obj(help="\"A map of project number and project config. This is only valid when shareType's value is SPECIFIC_PROJECTS. Structure is documented below.\""),
        projectMap: {
          '#withId':: d.fn(help='"The identifier for this object. Format specified above."', args=[d.arg(name='id', type=d.T.string)]),
          withId(id): { id: id },
          '#withProjectId':: d.fn(help='"The project id/number, should be same as the key of this project config in the project map."', args=[d.arg(name='projectId', type=d.T.string)]),
          withProjectId(projectId): { projectId: projectId },
        },
        '#withProjectMap':: d.fn(help="\"A map of project number and project config. This is only valid when shareType's value is SPECIFIC_PROJECTS. Structure is documented below.\"", args=[d.arg(name='projectMap', type=d.T.array)]),
        withProjectMap(projectMap): { projectMap: if std.isArray(v=projectMap) then projectMap else [projectMap] },
        '#withProjectMapMixin':: d.fn(help="\"A map of project number and project config. This is only valid when shareType's value is SPECIFIC_PROJECTS. Structure is documented below.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='projectMap', type=d.T.array)]),
        withProjectMapMixin(projectMap): { projectMap+: if std.isArray(v=projectMap) then projectMap else [projectMap] },
        '#withShareType':: d.fn(help='"Type of sharing for this shared-reservation Possible values are: LOCAL, SPECIFIC_PROJECTS."', args=[d.arg(name='shareType', type=d.T.string)]),
        withShareType(shareType): { shareType: shareType },
      },
      '#specificReservation':: d.obj(help='"Reservation for instances with specific machine shapes. Structure is documented below."'),
      specificReservation: {
        '#instanceProperties':: d.obj(help='"The instance properties for the reservation. Structure is documented below."'),
        instanceProperties: {
          '#guestAccelerators':: d.obj(help='"Guest accelerator type and count. Structure is documented below."'),
          guestAccelerators: {
            '#withAcceleratorCount':: d.fn(help='"The number of the guest accelerator cards exposed to this instance."', args=[d.arg(name='acceleratorCount', type=d.T.number)]),
            withAcceleratorCount(acceleratorCount): { acceleratorCount: acceleratorCount },
            '#withAcceleratorType':: d.fn(help='"The full or partial URL of the accelerator type to attach to this instance. For example: projects/my-project/zones/us-central1-c/acceleratorTypes/nvidia-tesla-p100 If you are creating an instance template, specify only the accelerator name."', args=[d.arg(name='acceleratorType', type=d.T.string)]),
            withAcceleratorType(acceleratorType): { acceleratorType: acceleratorType },
          },
          '#localSsds':: d.obj(help='"The amount of local ssd to reserve with each instance. This reserves disks of type local-ssd. Structure is documented below."'),
          localSsds: {
            '#withDiskSizeGb':: d.fn(help='"The size of the disk in base-2 GB."', args=[d.arg(name='diskSizeGb', type=d.T.number)]),
            withDiskSizeGb(diskSizeGb): { diskSizeGb: diskSizeGb },
            '#withInterface':: d.fn(help='"The disk interface to use for attaching this disk. Default value is SCSI. Possible values are: SCSI, NVME."', args=[d.arg(name='interface', type=d.T.string)]),
            withInterface(interface): { interface: interface },
          },
          '#withGuestAccelerators':: d.fn(help='"Guest accelerator type and count. Structure is documented below."', args=[d.arg(name='guestAccelerators', type=d.T.array)]),
          withGuestAccelerators(guestAccelerators): { guestAccelerators: if std.isArray(v=guestAccelerators) then guestAccelerators else [guestAccelerators] },
          '#withGuestAcceleratorsMixin':: d.fn(help='"Guest accelerator type and count. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='guestAccelerators', type=d.T.array)]),
          withGuestAcceleratorsMixin(guestAccelerators): { guestAccelerators+: if std.isArray(v=guestAccelerators) then guestAccelerators else [guestAccelerators] },
          '#withLocalSsds':: d.fn(help='"The amount of local ssd to reserve with each instance. This reserves disks of type local-ssd. Structure is documented below."', args=[d.arg(name='localSsds', type=d.T.array)]),
          withLocalSsds(localSsds): { localSsds: if std.isArray(v=localSsds) then localSsds else [localSsds] },
          '#withLocalSsdsMixin':: d.fn(help='"The amount of local ssd to reserve with each instance. This reserves disks of type local-ssd. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='localSsds', type=d.T.array)]),
          withLocalSsdsMixin(localSsds): { localSsds+: if std.isArray(v=localSsds) then localSsds else [localSsds] },
          '#withMachineType':: d.fn(help='"The name of the machine type to reserve."', args=[d.arg(name='machineType', type=d.T.string)]),
          withMachineType(machineType): { machineType: machineType },
          '#withMinCpuPlatform':: d.fn(help='"The minimum CPU platform for the reservation. For example, \\"Intel Skylake\\". See the CPU platform availability reference](https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform#availablezones) for information on available CPU platforms."', args=[d.arg(name='minCpuPlatform', type=d.T.string)]),
          withMinCpuPlatform(minCpuPlatform): { minCpuPlatform: minCpuPlatform },
        },
        '#withCount':: d.fn(help='"The number of resources that are allocated."', args=[d.arg(name='count', type=d.T.number)]),
        withCount(count): { count: count },
        '#withInstanceProperties':: d.fn(help='"The instance properties for the reservation. Structure is documented below."', args=[d.arg(name='instanceProperties', type=d.T.array)]),
        withInstanceProperties(instanceProperties): { instanceProperties: if std.isArray(v=instanceProperties) then instanceProperties else [instanceProperties] },
        '#withInstancePropertiesMixin':: d.fn(help='"The instance properties for the reservation. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='instanceProperties', type=d.T.array)]),
        withInstancePropertiesMixin(instanceProperties): { instanceProperties+: if std.isArray(v=instanceProperties) then instanceProperties else [instanceProperties] },
      },
      '#withDescription':: d.fn(help='"An optional description of this resource."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withProject':: d.fn(help='"The ID of the project in which the resource belongs. If it is not provided, the provider project is used."', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withShareSettings':: d.fn(help='"The share setting for reservations. Structure is documented below."', args=[d.arg(name='shareSettings', type=d.T.array)]),
      withShareSettings(shareSettings): { spec+: { forProvider+: { shareSettings: if std.isArray(v=shareSettings) then shareSettings else [shareSettings] } } },
      '#withShareSettingsMixin':: d.fn(help='"The share setting for reservations. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='shareSettings', type=d.T.array)]),
      withShareSettingsMixin(shareSettings): { spec+: { forProvider+: { shareSettings+: if std.isArray(v=shareSettings) then shareSettings else [shareSettings] } } },
      '#withSpecificReservation':: d.fn(help='"Reservation for instances with specific machine shapes. Structure is documented below."', args=[d.arg(name='specificReservation', type=d.T.array)]),
      withSpecificReservation(specificReservation): { spec+: { forProvider+: { specificReservation: if std.isArray(v=specificReservation) then specificReservation else [specificReservation] } } },
      '#withSpecificReservationMixin':: d.fn(help='"Reservation for instances with specific machine shapes. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='specificReservation', type=d.T.array)]),
      withSpecificReservationMixin(specificReservation): { spec+: { forProvider+: { specificReservation+: if std.isArray(v=specificReservation) then specificReservation else [specificReservation] } } },
      '#withSpecificReservationRequired':: d.fn(help='"When set to true, only VMs that target this reservation by name can consume this reservation. Otherwise, it can be consumed by VMs with affinity for any reservation. Defaults to false."', args=[d.arg(name='specificReservationRequired', type=d.T.boolean)]),
      withSpecificReservationRequired(specificReservationRequired): { spec+: { forProvider+: { specificReservationRequired: specificReservationRequired } } },
      '#withZone':: d.fn(help='"The zone where the reservation is made."', args=[d.arg(name='zone', type=d.T.string)]),
      withZone(zone): { spec+: { forProvider+: { zone: zone } } },
    },
    '#initProvider':: d.obj(help='"THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice. InitProvider holds the same fields as ForProvider, with the exception of Identifier and other resource reference fields. The fields that are in InitProvider are merged into ForProvider when the resource is created. The same fields are also added to the terraform ignore_changes hook, to avoid updating them after creation. This is useful for fields that are required on creation, but we do not desire to update them after creation, for example because of an external controller is managing them, like an autoscaler."'),
    initProvider: {
      '#shareSettings':: d.obj(help='"The share setting for reservations. Structure is documented below."'),
      shareSettings: {
        '#projectMap':: d.obj(help="\"A map of project number and project config. This is only valid when shareType's value is SPECIFIC_PROJECTS. Structure is documented below.\""),
        projectMap: {
          '#withId':: d.fn(help='"The identifier for this object. Format specified above."', args=[d.arg(name='id', type=d.T.string)]),
          withId(id): { id: id },
          '#withProjectId':: d.fn(help='"The project id/number, should be same as the key of this project config in the project map."', args=[d.arg(name='projectId', type=d.T.string)]),
          withProjectId(projectId): { projectId: projectId },
        },
        '#withProjectMap':: d.fn(help="\"A map of project number and project config. This is only valid when shareType's value is SPECIFIC_PROJECTS. Structure is documented below.\"", args=[d.arg(name='projectMap', type=d.T.array)]),
        withProjectMap(projectMap): { projectMap: if std.isArray(v=projectMap) then projectMap else [projectMap] },
        '#withProjectMapMixin':: d.fn(help="\"A map of project number and project config. This is only valid when shareType's value is SPECIFIC_PROJECTS. Structure is documented below.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='projectMap', type=d.T.array)]),
        withProjectMapMixin(projectMap): { projectMap+: if std.isArray(v=projectMap) then projectMap else [projectMap] },
        '#withShareType':: d.fn(help='"Type of sharing for this shared-reservation Possible values are: LOCAL, SPECIFIC_PROJECTS."', args=[d.arg(name='shareType', type=d.T.string)]),
        withShareType(shareType): { shareType: shareType },
      },
      '#specificReservation':: d.obj(help='"Reservation for instances with specific machine shapes. Structure is documented below."'),
      specificReservation: {
        '#instanceProperties':: d.obj(help='"The instance properties for the reservation. Structure is documented below."'),
        instanceProperties: {
          '#guestAccelerators':: d.obj(help='"Guest accelerator type and count. Structure is documented below."'),
          guestAccelerators: {
            '#withAcceleratorCount':: d.fn(help='"The number of the guest accelerator cards exposed to this instance."', args=[d.arg(name='acceleratorCount', type=d.T.number)]),
            withAcceleratorCount(acceleratorCount): { acceleratorCount: acceleratorCount },
            '#withAcceleratorType':: d.fn(help='"The full or partial URL of the accelerator type to attach to this instance. For example: projects/my-project/zones/us-central1-c/acceleratorTypes/nvidia-tesla-p100 If you are creating an instance template, specify only the accelerator name."', args=[d.arg(name='acceleratorType', type=d.T.string)]),
            withAcceleratorType(acceleratorType): { acceleratorType: acceleratorType },
          },
          '#localSsds':: d.obj(help='"The amount of local ssd to reserve with each instance. This reserves disks of type local-ssd. Structure is documented below."'),
          localSsds: {
            '#withDiskSizeGb':: d.fn(help='"The size of the disk in base-2 GB."', args=[d.arg(name='diskSizeGb', type=d.T.number)]),
            withDiskSizeGb(diskSizeGb): { diskSizeGb: diskSizeGb },
            '#withInterface':: d.fn(help='"The disk interface to use for attaching this disk. Default value is SCSI. Possible values are: SCSI, NVME."', args=[d.arg(name='interface', type=d.T.string)]),
            withInterface(interface): { interface: interface },
          },
          '#withGuestAccelerators':: d.fn(help='"Guest accelerator type and count. Structure is documented below."', args=[d.arg(name='guestAccelerators', type=d.T.array)]),
          withGuestAccelerators(guestAccelerators): { guestAccelerators: if std.isArray(v=guestAccelerators) then guestAccelerators else [guestAccelerators] },
          '#withGuestAcceleratorsMixin':: d.fn(help='"Guest accelerator type and count. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='guestAccelerators', type=d.T.array)]),
          withGuestAcceleratorsMixin(guestAccelerators): { guestAccelerators+: if std.isArray(v=guestAccelerators) then guestAccelerators else [guestAccelerators] },
          '#withLocalSsds':: d.fn(help='"The amount of local ssd to reserve with each instance. This reserves disks of type local-ssd. Structure is documented below."', args=[d.arg(name='localSsds', type=d.T.array)]),
          withLocalSsds(localSsds): { localSsds: if std.isArray(v=localSsds) then localSsds else [localSsds] },
          '#withLocalSsdsMixin':: d.fn(help='"The amount of local ssd to reserve with each instance. This reserves disks of type local-ssd. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='localSsds', type=d.T.array)]),
          withLocalSsdsMixin(localSsds): { localSsds+: if std.isArray(v=localSsds) then localSsds else [localSsds] },
          '#withMachineType':: d.fn(help='"The name of the machine type to reserve."', args=[d.arg(name='machineType', type=d.T.string)]),
          withMachineType(machineType): { machineType: machineType },
          '#withMinCpuPlatform':: d.fn(help='"The minimum CPU platform for the reservation. For example, \\"Intel Skylake\\". See the CPU platform availability reference](https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform#availablezones) for information on available CPU platforms."', args=[d.arg(name='minCpuPlatform', type=d.T.string)]),
          withMinCpuPlatform(minCpuPlatform): { minCpuPlatform: minCpuPlatform },
        },
        '#withCount':: d.fn(help='"The number of resources that are allocated."', args=[d.arg(name='count', type=d.T.number)]),
        withCount(count): { count: count },
        '#withInstanceProperties':: d.fn(help='"The instance properties for the reservation. Structure is documented below."', args=[d.arg(name='instanceProperties', type=d.T.array)]),
        withInstanceProperties(instanceProperties): { instanceProperties: if std.isArray(v=instanceProperties) then instanceProperties else [instanceProperties] },
        '#withInstancePropertiesMixin':: d.fn(help='"The instance properties for the reservation. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='instanceProperties', type=d.T.array)]),
        withInstancePropertiesMixin(instanceProperties): { instanceProperties+: if std.isArray(v=instanceProperties) then instanceProperties else [instanceProperties] },
      },
      '#withDescription':: d.fn(help='"An optional description of this resource."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { initProvider+: { description: description } } },
      '#withProject':: d.fn(help='"The ID of the project in which the resource belongs. If it is not provided, the provider project is used."', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { initProvider+: { project: project } } },
      '#withShareSettings':: d.fn(help='"The share setting for reservations. Structure is documented below."', args=[d.arg(name='shareSettings', type=d.T.array)]),
      withShareSettings(shareSettings): { spec+: { initProvider+: { shareSettings: if std.isArray(v=shareSettings) then shareSettings else [shareSettings] } } },
      '#withShareSettingsMixin':: d.fn(help='"The share setting for reservations. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='shareSettings', type=d.T.array)]),
      withShareSettingsMixin(shareSettings): { spec+: { initProvider+: { shareSettings+: if std.isArray(v=shareSettings) then shareSettings else [shareSettings] } } },
      '#withSpecificReservation':: d.fn(help='"Reservation for instances with specific machine shapes. Structure is documented below."', args=[d.arg(name='specificReservation', type=d.T.array)]),
      withSpecificReservation(specificReservation): { spec+: { initProvider+: { specificReservation: if std.isArray(v=specificReservation) then specificReservation else [specificReservation] } } },
      '#withSpecificReservationMixin':: d.fn(help='"Reservation for instances with specific machine shapes. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='specificReservation', type=d.T.array)]),
      withSpecificReservationMixin(specificReservation): { spec+: { initProvider+: { specificReservation+: if std.isArray(v=specificReservation) then specificReservation else [specificReservation] } } },
      '#withSpecificReservationRequired':: d.fn(help='"When set to true, only VMs that target this reservation by name can consume this reservation. Otherwise, it can be consumed by VMs with affinity for any reservation. Defaults to false."', args=[d.arg(name='specificReservationRequired', type=d.T.boolean)]),
      withSpecificReservationRequired(specificReservationRequired): { spec+: { initProvider+: { specificReservationRequired: specificReservationRequired } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource. This field is planned to be deprecated in favor of the ManagementPolicies field in a future release. Currently, both could be set independently and non-default values would be honored if the feature flag is enabled. See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice. ManagementPolicies specify the array of actions Crossplane is allowed to take on the managed and external resources. This field is planned to replace the DeletionPolicy field in a future release. Currently, both could be set independently and non-default values would be honored if the feature flag is enabled. If both are custom, the DeletionPolicy field will be ignored. See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223 and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice. ManagementPolicies specify the array of actions Crossplane is allowed to take on the managed and external resources. This field is planned to replace the DeletionPolicy field in a future release. Currently, both could be set independently and non-default values would be honored if the feature flag is enabled. If both are custom, the DeletionPolicy field will be ignored. See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223 and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
