{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='syntheticMonitoringCheck', url='', help='"SyntheticMonitoringCheck is the Schema for the SyntheticMonitoringChecks API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of SyntheticMonitoringCheck', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'grafana.jet.crossplane.io/v1alpha1',
    kind: 'SyntheticMonitoringCheck',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"SyntheticMonitoringCheckSpec defines the desired state of SyntheticMonitoringCheck"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#settings':: d.obj(help='"Check settings. Should contain exactly one nested block."'),
      settings: {
        '#dns':: d.obj(help='"Settings for DNS check. The target must be a valid hostname (or IP address for `PTR` records)."'),
        dns: {
          '#validateAdditionalRrs':: d.obj(help='"Validate additional matches."'),
          validateAdditionalRrs: {
            '#withFailIfMatchesRegexp':: d.fn(help='"Fail if value matches regex."', args=[d.arg(name='failIfMatchesRegexp', type=d.T.array)]),
            withFailIfMatchesRegexp(failIfMatchesRegexp): { failIfMatchesRegexp: if std.isArray(v=failIfMatchesRegexp) then failIfMatchesRegexp else [failIfMatchesRegexp] },
            '#withFailIfMatchesRegexpMixin':: d.fn(help='"Fail if value matches regex."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfMatchesRegexp', type=d.T.array)]),
            withFailIfMatchesRegexpMixin(failIfMatchesRegexp): { failIfMatchesRegexp+: if std.isArray(v=failIfMatchesRegexp) then failIfMatchesRegexp else [failIfMatchesRegexp] },
            '#withFailIfNotMatchesRegexp':: d.fn(help='"Fail if value does not match regex."', args=[d.arg(name='failIfNotMatchesRegexp', type=d.T.array)]),
            withFailIfNotMatchesRegexp(failIfNotMatchesRegexp): { failIfNotMatchesRegexp: if std.isArray(v=failIfNotMatchesRegexp) then failIfNotMatchesRegexp else [failIfNotMatchesRegexp] },
            '#withFailIfNotMatchesRegexpMixin':: d.fn(help='"Fail if value does not match regex."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfNotMatchesRegexp', type=d.T.array)]),
            withFailIfNotMatchesRegexpMixin(failIfNotMatchesRegexp): { failIfNotMatchesRegexp+: if std.isArray(v=failIfNotMatchesRegexp) then failIfNotMatchesRegexp else [failIfNotMatchesRegexp] },
          },
          '#validateAnswerRrs':: d.obj(help='"Validate response answer."'),
          validateAnswerRrs: {
            '#withFailIfMatchesRegexp':: d.fn(help='"Fail if value matches regex."', args=[d.arg(name='failIfMatchesRegexp', type=d.T.array)]),
            withFailIfMatchesRegexp(failIfMatchesRegexp): { failIfMatchesRegexp: if std.isArray(v=failIfMatchesRegexp) then failIfMatchesRegexp else [failIfMatchesRegexp] },
            '#withFailIfMatchesRegexpMixin':: d.fn(help='"Fail if value matches regex."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfMatchesRegexp', type=d.T.array)]),
            withFailIfMatchesRegexpMixin(failIfMatchesRegexp): { failIfMatchesRegexp+: if std.isArray(v=failIfMatchesRegexp) then failIfMatchesRegexp else [failIfMatchesRegexp] },
            '#withFailIfNotMatchesRegexp':: d.fn(help='"Fail if value does not match regex."', args=[d.arg(name='failIfNotMatchesRegexp', type=d.T.array)]),
            withFailIfNotMatchesRegexp(failIfNotMatchesRegexp): { failIfNotMatchesRegexp: if std.isArray(v=failIfNotMatchesRegexp) then failIfNotMatchesRegexp else [failIfNotMatchesRegexp] },
            '#withFailIfNotMatchesRegexpMixin':: d.fn(help='"Fail if value does not match regex."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfNotMatchesRegexp', type=d.T.array)]),
            withFailIfNotMatchesRegexpMixin(failIfNotMatchesRegexp): { failIfNotMatchesRegexp+: if std.isArray(v=failIfNotMatchesRegexp) then failIfNotMatchesRegexp else [failIfNotMatchesRegexp] },
          },
          '#validateAuthorityRrs':: d.obj(help='"Validate response authority."'),
          validateAuthorityRrs: {
            '#withFailIfMatchesRegexp':: d.fn(help='"Fail if value matches regex."', args=[d.arg(name='failIfMatchesRegexp', type=d.T.array)]),
            withFailIfMatchesRegexp(failIfMatchesRegexp): { failIfMatchesRegexp: if std.isArray(v=failIfMatchesRegexp) then failIfMatchesRegexp else [failIfMatchesRegexp] },
            '#withFailIfMatchesRegexpMixin':: d.fn(help='"Fail if value matches regex."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfMatchesRegexp', type=d.T.array)]),
            withFailIfMatchesRegexpMixin(failIfMatchesRegexp): { failIfMatchesRegexp+: if std.isArray(v=failIfMatchesRegexp) then failIfMatchesRegexp else [failIfMatchesRegexp] },
            '#withFailIfNotMatchesRegexp':: d.fn(help='"Fail if value does not match regex."', args=[d.arg(name='failIfNotMatchesRegexp', type=d.T.array)]),
            withFailIfNotMatchesRegexp(failIfNotMatchesRegexp): { failIfNotMatchesRegexp: if std.isArray(v=failIfNotMatchesRegexp) then failIfNotMatchesRegexp else [failIfNotMatchesRegexp] },
            '#withFailIfNotMatchesRegexpMixin':: d.fn(help='"Fail if value does not match regex."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfNotMatchesRegexp', type=d.T.array)]),
            withFailIfNotMatchesRegexpMixin(failIfNotMatchesRegexp): { failIfNotMatchesRegexp+: if std.isArray(v=failIfNotMatchesRegexp) then failIfNotMatchesRegexp else [failIfNotMatchesRegexp] },
          },
          '#withIpVersion':: d.fn(help="\"Options are `V4`, `V6`, `Any`. Specifies whether the corresponding check will be performed using IPv4 or IPv6. The `Any` value indicates that IPv6 should be used, falling back to IPv4 if that's not available. Defaults to `V4`.\"", args=[d.arg(name='ipVersion', type=d.T.string)]),
          withIpVersion(ipVersion): { ipVersion: ipVersion },
          '#withPort':: d.fn(help='"Port to target. Defaults to `53`."', args=[d.arg(name='port', type=d.T.number)]),
          withPort(port): { port: port },
          '#withProtocol':: d.fn(help='"`TCP` or `UDP`. Defaults to `UDP`."', args=[d.arg(name='protocol', type=d.T.string)]),
          withProtocol(protocol): { protocol: protocol },
          '#withRecordType':: d.fn(help='"One of `ANY`, `A`, `AAAA`, `CNAME`, `MX`, `NS`, `PTR`, `SOA`, `SRV`, `TXT`. Defaults to `A`."', args=[d.arg(name='recordType', type=d.T.string)]),
          withRecordType(recordType): { recordType: recordType },
          '#withServer':: d.fn(help='"DNS server address to target. Defaults to `8.8.8.8`."', args=[d.arg(name='server', type=d.T.string)]),
          withServer(server): { server: server },
          '#withSourceIpAddress':: d.fn(help='"Source IP address."', args=[d.arg(name='sourceIpAddress', type=d.T.string)]),
          withSourceIpAddress(sourceIpAddress): { sourceIpAddress: sourceIpAddress },
          '#withValidRCodes':: d.fn(help='"List of valid response codes. Options include `NOERROR`, `BADALG`, `BADMODE`, `BADKEY`, `BADCOOKIE`, `BADNAME`, `BADSIG`, `BADTIME`, `BADTRUNC`, `BADVERS`, `FORMERR`, `NOTIMP`, `NOTAUTH`, `NOTZONE`, `NXDOMAIN`, `NXRRSET`, `REFUSED`, `SERVFAIL`, `YXDOMAIN`, `YXRRSET`."', args=[d.arg(name='validRCodes', type=d.T.array)]),
          withValidRCodes(validRCodes): { validRCodes: if std.isArray(v=validRCodes) then validRCodes else [validRCodes] },
          '#withValidRCodesMixin':: d.fn(help='"List of valid response codes. Options include `NOERROR`, `BADALG`, `BADMODE`, `BADKEY`, `BADCOOKIE`, `BADNAME`, `BADSIG`, `BADTIME`, `BADTRUNC`, `BADVERS`, `FORMERR`, `NOTIMP`, `NOTAUTH`, `NOTZONE`, `NXDOMAIN`, `NXRRSET`, `REFUSED`, `SERVFAIL`, `YXDOMAIN`, `YXRRSET`."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='validRCodes', type=d.T.array)]),
          withValidRCodesMixin(validRCodes): { validRCodes+: if std.isArray(v=validRCodes) then validRCodes else [validRCodes] },
          '#withValidateAdditionalRrs':: d.fn(help='"Validate additional matches."', args=[d.arg(name='validateAdditionalRrs', type=d.T.array)]),
          withValidateAdditionalRrs(validateAdditionalRrs): { validateAdditionalRrs: if std.isArray(v=validateAdditionalRrs) then validateAdditionalRrs else [validateAdditionalRrs] },
          '#withValidateAdditionalRrsMixin':: d.fn(help='"Validate additional matches."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='validateAdditionalRrs', type=d.T.array)]),
          withValidateAdditionalRrsMixin(validateAdditionalRrs): { validateAdditionalRrs+: if std.isArray(v=validateAdditionalRrs) then validateAdditionalRrs else [validateAdditionalRrs] },
          '#withValidateAnswerRrs':: d.fn(help='"Validate response answer."', args=[d.arg(name='validateAnswerRrs', type=d.T.array)]),
          withValidateAnswerRrs(validateAnswerRrs): { validateAnswerRrs: if std.isArray(v=validateAnswerRrs) then validateAnswerRrs else [validateAnswerRrs] },
          '#withValidateAnswerRrsMixin':: d.fn(help='"Validate response answer."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='validateAnswerRrs', type=d.T.array)]),
          withValidateAnswerRrsMixin(validateAnswerRrs): { validateAnswerRrs+: if std.isArray(v=validateAnswerRrs) then validateAnswerRrs else [validateAnswerRrs] },
          '#withValidateAuthorityRrs':: d.fn(help='"Validate response authority."', args=[d.arg(name='validateAuthorityRrs', type=d.T.array)]),
          withValidateAuthorityRrs(validateAuthorityRrs): { validateAuthorityRrs: if std.isArray(v=validateAuthorityRrs) then validateAuthorityRrs else [validateAuthorityRrs] },
          '#withValidateAuthorityRrsMixin':: d.fn(help='"Validate response authority."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='validateAuthorityRrs', type=d.T.array)]),
          withValidateAuthorityRrsMixin(validateAuthorityRrs): { validateAuthorityRrs+: if std.isArray(v=validateAuthorityRrs) then validateAuthorityRrs else [validateAuthorityRrs] },
        },
        '#http':: d.obj(help='"Settings for HTTP check. The target must be a URL (http or https)."'),
        http: {
          '#basicAuth':: d.obj(help='"Basic auth settings."'),
          basicAuth: {
            '#withPassword':: d.fn(help='"Basic auth password."', args=[d.arg(name='password', type=d.T.string)]),
            withPassword(password): { password: password },
            '#withUsername':: d.fn(help='"Basic auth username."', args=[d.arg(name='username', type=d.T.string)]),
            withUsername(username): { username: username },
          },
          '#failIfHeaderMatchesRegexp':: d.obj(help='"Check fails if headers match."'),
          failIfHeaderMatchesRegexp: {
            '#withAllowMissing':: d.fn(help='"Allow header to be missing from responses. Defaults to `false`."', args=[d.arg(name='allowMissing', type=d.T.boolean)]),
            withAllowMissing(allowMissing): { allowMissing: allowMissing },
            '#withHeader':: d.fn(help='"Header name."', args=[d.arg(name='header', type=d.T.string)]),
            withHeader(header): { header: header },
            '#withRegexp':: d.fn(help='"Regex that header value should match."', args=[d.arg(name='regexp', type=d.T.string)]),
            withRegexp(regexp): { regexp: regexp },
          },
          '#failIfHeaderNotMatchesRegexp':: d.obj(help='"Check fails if headers do not match."'),
          failIfHeaderNotMatchesRegexp: {
            '#withAllowMissing':: d.fn(help='"Allow header to be missing from responses. Defaults to `false`."', args=[d.arg(name='allowMissing', type=d.T.boolean)]),
            withAllowMissing(allowMissing): { allowMissing: allowMissing },
            '#withHeader':: d.fn(help='"Header name."', args=[d.arg(name='header', type=d.T.string)]),
            withHeader(header): { header: header },
            '#withRegexp':: d.fn(help='"Regex that header value should match."', args=[d.arg(name='regexp', type=d.T.string)]),
            withRegexp(regexp): { regexp: regexp },
          },
          '#tlsConfig':: d.obj(help='"TLS config."'),
          tlsConfig: {
            '#clientKeySecretRef':: d.obj(help='"Client key in PEM format."'),
            clientKeySecretRef: {
              '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { clientKeySecretRef+: { key: key } },
              '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { clientKeySecretRef+: { name: name } },
              '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { clientKeySecretRef+: { namespace: namespace } },
            },
            '#withCaCert':: d.fn(help='"CA certificate in PEM format."', args=[d.arg(name='caCert', type=d.T.string)]),
            withCaCert(caCert): { caCert: caCert },
            '#withClientCert':: d.fn(help='"Client certificate in PEM format."', args=[d.arg(name='clientCert', type=d.T.string)]),
            withClientCert(clientCert): { clientCert: clientCert },
            '#withInsecureSkipVerify':: d.fn(help='"Disable target certificate validation. Defaults to `false`."', args=[d.arg(name='insecureSkipVerify', type=d.T.boolean)]),
            withInsecureSkipVerify(insecureSkipVerify): { insecureSkipVerify: insecureSkipVerify },
            '#withServerName':: d.fn(help='"Used to verify the hostname for the targets."', args=[d.arg(name='serverName', type=d.T.string)]),
            withServerName(serverName): { serverName: serverName },
          },
          '#withBasicAuth':: d.fn(help='"Basic auth settings."', args=[d.arg(name='basicAuth', type=d.T.array)]),
          withBasicAuth(basicAuth): { basicAuth: if std.isArray(v=basicAuth) then basicAuth else [basicAuth] },
          '#withBasicAuthMixin':: d.fn(help='"Basic auth settings."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='basicAuth', type=d.T.array)]),
          withBasicAuthMixin(basicAuth): { basicAuth+: if std.isArray(v=basicAuth) then basicAuth else [basicAuth] },
          '#withBearerToken':: d.fn(help='"Token for use with bearer authorization header."', args=[d.arg(name='bearerToken', type=d.T.string)]),
          withBearerToken(bearerToken): { bearerToken: bearerToken },
          '#withBody':: d.fn(help='"The body of the HTTP request used in probe."', args=[d.arg(name='body', type=d.T.string)]),
          withBody(body): { body: body },
          '#withCacheBustingQueryParamName':: d.fn(help='"The name of the query parameter used to prevent the server from using a cached response. Each probe will assign a random value to this parameter each time a request is made."', args=[d.arg(name='cacheBustingQueryParamName', type=d.T.string)]),
          withCacheBustingQueryParamName(cacheBustingQueryParamName): { cacheBustingQueryParamName: cacheBustingQueryParamName },
          '#withFailIfBodyMatchesRegexp':: d.fn(help='"List of regexes. If any match the response body, the check will fail."', args=[d.arg(name='failIfBodyMatchesRegexp', type=d.T.array)]),
          withFailIfBodyMatchesRegexp(failIfBodyMatchesRegexp): { failIfBodyMatchesRegexp: if std.isArray(v=failIfBodyMatchesRegexp) then failIfBodyMatchesRegexp else [failIfBodyMatchesRegexp] },
          '#withFailIfBodyMatchesRegexpMixin':: d.fn(help='"List of regexes. If any match the response body, the check will fail."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfBodyMatchesRegexp', type=d.T.array)]),
          withFailIfBodyMatchesRegexpMixin(failIfBodyMatchesRegexp): { failIfBodyMatchesRegexp+: if std.isArray(v=failIfBodyMatchesRegexp) then failIfBodyMatchesRegexp else [failIfBodyMatchesRegexp] },
          '#withFailIfBodyNotMatchesRegexp':: d.fn(help='"List of regexes. If any do not match the response body, the check will fail."', args=[d.arg(name='failIfBodyNotMatchesRegexp', type=d.T.array)]),
          withFailIfBodyNotMatchesRegexp(failIfBodyNotMatchesRegexp): { failIfBodyNotMatchesRegexp: if std.isArray(v=failIfBodyNotMatchesRegexp) then failIfBodyNotMatchesRegexp else [failIfBodyNotMatchesRegexp] },
          '#withFailIfBodyNotMatchesRegexpMixin':: d.fn(help='"List of regexes. If any do not match the response body, the check will fail."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfBodyNotMatchesRegexp', type=d.T.array)]),
          withFailIfBodyNotMatchesRegexpMixin(failIfBodyNotMatchesRegexp): { failIfBodyNotMatchesRegexp+: if std.isArray(v=failIfBodyNotMatchesRegexp) then failIfBodyNotMatchesRegexp else [failIfBodyNotMatchesRegexp] },
          '#withFailIfHeaderMatchesRegexp':: d.fn(help='"Check fails if headers match."', args=[d.arg(name='failIfHeaderMatchesRegexp', type=d.T.array)]),
          withFailIfHeaderMatchesRegexp(failIfHeaderMatchesRegexp): { failIfHeaderMatchesRegexp: if std.isArray(v=failIfHeaderMatchesRegexp) then failIfHeaderMatchesRegexp else [failIfHeaderMatchesRegexp] },
          '#withFailIfHeaderMatchesRegexpMixin':: d.fn(help='"Check fails if headers match."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfHeaderMatchesRegexp', type=d.T.array)]),
          withFailIfHeaderMatchesRegexpMixin(failIfHeaderMatchesRegexp): { failIfHeaderMatchesRegexp+: if std.isArray(v=failIfHeaderMatchesRegexp) then failIfHeaderMatchesRegexp else [failIfHeaderMatchesRegexp] },
          '#withFailIfHeaderNotMatchesRegexp':: d.fn(help='"Check fails if headers do not match."', args=[d.arg(name='failIfHeaderNotMatchesRegexp', type=d.T.array)]),
          withFailIfHeaderNotMatchesRegexp(failIfHeaderNotMatchesRegexp): { failIfHeaderNotMatchesRegexp: if std.isArray(v=failIfHeaderNotMatchesRegexp) then failIfHeaderNotMatchesRegexp else [failIfHeaderNotMatchesRegexp] },
          '#withFailIfHeaderNotMatchesRegexpMixin':: d.fn(help='"Check fails if headers do not match."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failIfHeaderNotMatchesRegexp', type=d.T.array)]),
          withFailIfHeaderNotMatchesRegexpMixin(failIfHeaderNotMatchesRegexp): { failIfHeaderNotMatchesRegexp+: if std.isArray(v=failIfHeaderNotMatchesRegexp) then failIfHeaderNotMatchesRegexp else [failIfHeaderNotMatchesRegexp] },
          '#withFailIfNotSsl':: d.fn(help='"Fail if SSL is not present. Defaults to `false`."', args=[d.arg(name='failIfNotSsl', type=d.T.boolean)]),
          withFailIfNotSsl(failIfNotSsl): { failIfNotSsl: failIfNotSsl },
          '#withFailIfSsl':: d.fn(help='"Fail if SSL is present. Defaults to `false`."', args=[d.arg(name='failIfSsl', type=d.T.boolean)]),
          withFailIfSsl(failIfSsl): { failIfSsl: failIfSsl },
          '#withHeaders':: d.fn(help='"The HTTP headers set for the probe."', args=[d.arg(name='headers', type=d.T.array)]),
          withHeaders(headers): { headers: if std.isArray(v=headers) then headers else [headers] },
          '#withHeadersMixin':: d.fn(help='"The HTTP headers set for the probe."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headers', type=d.T.array)]),
          withHeadersMixin(headers): { headers+: if std.isArray(v=headers) then headers else [headers] },
          '#withIpVersion':: d.fn(help="\"Options are `V4`, `V6`, `Any`. Specifies whether the corresponding check will be performed using IPv4 or IPv6. The `Any` value indicates that IPv6 should be used, falling back to IPv4 if that's not available. Defaults to `V4`.\"", args=[d.arg(name='ipVersion', type=d.T.string)]),
          withIpVersion(ipVersion): { ipVersion: ipVersion },
          '#withMethod':: d.fn(help='"Request method. One of `GET`, `CONNECT`, `DELETE`, `HEAD`, `OPTIONS`, `POST`, `PUT`, `TRACE` Defaults to `GET`."', args=[d.arg(name='method', type=d.T.string)]),
          withMethod(method): { method: method },
          '#withNoFollowRedirects':: d.fn(help='"Do not follow redirects. Defaults to `false`."', args=[d.arg(name='noFollowRedirects', type=d.T.boolean)]),
          withNoFollowRedirects(noFollowRedirects): { noFollowRedirects: noFollowRedirects },
          '#withProxyUrl':: d.fn(help='"Proxy URL."', args=[d.arg(name='proxyUrl', type=d.T.string)]),
          withProxyUrl(proxyUrl): { proxyUrl: proxyUrl },
          '#withTlsConfig':: d.fn(help='"TLS config."', args=[d.arg(name='tlsConfig', type=d.T.array)]),
          withTlsConfig(tlsConfig): { tlsConfig: if std.isArray(v=tlsConfig) then tlsConfig else [tlsConfig] },
          '#withTlsConfigMixin':: d.fn(help='"TLS config."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tlsConfig', type=d.T.array)]),
          withTlsConfigMixin(tlsConfig): { tlsConfig+: if std.isArray(v=tlsConfig) then tlsConfig else [tlsConfig] },
          '#withValidHttpVersions':: d.fn(help='"List of valid HTTP versions. Options include `HTTP/1.0`, `HTTP/1.1`, `HTTP/2`"', args=[d.arg(name='validHttpVersions', type=d.T.array)]),
          withValidHttpVersions(validHttpVersions): { validHttpVersions: if std.isArray(v=validHttpVersions) then validHttpVersions else [validHttpVersions] },
          '#withValidHttpVersionsMixin':: d.fn(help='"List of valid HTTP versions. Options include `HTTP/1.0`, `HTTP/1.1`, `HTTP/2`"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='validHttpVersions', type=d.T.array)]),
          withValidHttpVersionsMixin(validHttpVersions): { validHttpVersions+: if std.isArray(v=validHttpVersions) then validHttpVersions else [validHttpVersions] },
          '#withValidStatusCodes':: d.fn(help='"Accepted status codes. If unset, defaults to 2xx."', args=[d.arg(name='validStatusCodes', type=d.T.array)]),
          withValidStatusCodes(validStatusCodes): { validStatusCodes: if std.isArray(v=validStatusCodes) then validStatusCodes else [validStatusCodes] },
          '#withValidStatusCodesMixin':: d.fn(help='"Accepted status codes. If unset, defaults to 2xx."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='validStatusCodes', type=d.T.array)]),
          withValidStatusCodesMixin(validStatusCodes): { validStatusCodes+: if std.isArray(v=validStatusCodes) then validStatusCodes else [validStatusCodes] },
        },
        '#ping':: d.obj(help='"Settings for ping (ICMP) check. The target must be a valid hostname or IP address."'),
        ping: {
          '#withDontFragment':: d.fn(help='"Set the DF-bit in the IP-header. Only works with ipV4. Defaults to `false`."', args=[d.arg(name='dontFragment', type=d.T.boolean)]),
          withDontFragment(dontFragment): { dontFragment: dontFragment },
          '#withIpVersion':: d.fn(help="\"Options are `V4`, `V6`, `Any`. Specifies whether the corresponding check will be performed using IPv4 or IPv6. The `Any` value indicates that IPv6 should be used, falling back to IPv4 if that's not available. Defaults to `V4`.\"", args=[d.arg(name='ipVersion', type=d.T.string)]),
          withIpVersion(ipVersion): { ipVersion: ipVersion },
          '#withPayloadSize':: d.fn(help='"Payload size. Defaults to `0`."', args=[d.arg(name='payloadSize', type=d.T.number)]),
          withPayloadSize(payloadSize): { payloadSize: payloadSize },
          '#withSourceIpAddress':: d.fn(help='"Source IP address."', args=[d.arg(name='sourceIpAddress', type=d.T.string)]),
          withSourceIpAddress(sourceIpAddress): { sourceIpAddress: sourceIpAddress },
        },
        '#tcp':: d.obj(help='"Settings for TCP check. The target must be of the form `<host>:<port>`, where the host portion must be a valid hostname or IP address."'),
        tcp: {
          '#queryResponse':: d.obj(help='"The query sent in the TCP probe and the expected associated response."'),
          queryResponse: {
            '#withExpect':: d.fn(help='"Response to expect."', args=[d.arg(name='expect', type=d.T.string)]),
            withExpect(expect): { expect: expect },
            '#withSend':: d.fn(help='"Data to send."', args=[d.arg(name='send', type=d.T.string)]),
            withSend(send): { send: send },
            '#withStartTls':: d.fn(help='"Upgrade TCP connection to TLS. Defaults to `false`."', args=[d.arg(name='startTls', type=d.T.boolean)]),
            withStartTls(startTls): { startTls: startTls },
          },
          '#tlsConfig':: d.obj(help='"TLS config."'),
          tlsConfig: {
            '#clientKeySecretRef':: d.obj(help='"Client key in PEM format."'),
            clientKeySecretRef: {
              '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { clientKeySecretRef+: { key: key } },
              '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { clientKeySecretRef+: { name: name } },
              '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { clientKeySecretRef+: { namespace: namespace } },
            },
            '#withCaCert':: d.fn(help='"CA certificate in PEM format."', args=[d.arg(name='caCert', type=d.T.string)]),
            withCaCert(caCert): { caCert: caCert },
            '#withClientCert':: d.fn(help='"Client certificate in PEM format."', args=[d.arg(name='clientCert', type=d.T.string)]),
            withClientCert(clientCert): { clientCert: clientCert },
            '#withInsecureSkipVerify':: d.fn(help='"Disable target certificate validation. Defaults to `false`."', args=[d.arg(name='insecureSkipVerify', type=d.T.boolean)]),
            withInsecureSkipVerify(insecureSkipVerify): { insecureSkipVerify: insecureSkipVerify },
            '#withServerName':: d.fn(help='"Used to verify the hostname for the targets."', args=[d.arg(name='serverName', type=d.T.string)]),
            withServerName(serverName): { serverName: serverName },
          },
          '#withIpVersion':: d.fn(help="\"Options are `V4`, `V6`, `Any`. Specifies whether the corresponding check will be performed using IPv4 or IPv6. The `Any` value indicates that IPv6 should be used, falling back to IPv4 if that's not available. Defaults to `V4`.\"", args=[d.arg(name='ipVersion', type=d.T.string)]),
          withIpVersion(ipVersion): { ipVersion: ipVersion },
          '#withQueryResponse':: d.fn(help='"The query sent in the TCP probe and the expected associated response."', args=[d.arg(name='queryResponse', type=d.T.array)]),
          withQueryResponse(queryResponse): { queryResponse: if std.isArray(v=queryResponse) then queryResponse else [queryResponse] },
          '#withQueryResponseMixin':: d.fn(help='"The query sent in the TCP probe and the expected associated response."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='queryResponse', type=d.T.array)]),
          withQueryResponseMixin(queryResponse): { queryResponse+: if std.isArray(v=queryResponse) then queryResponse else [queryResponse] },
          '#withSourceIpAddress':: d.fn(help='"Source IP address."', args=[d.arg(name='sourceIpAddress', type=d.T.string)]),
          withSourceIpAddress(sourceIpAddress): { sourceIpAddress: sourceIpAddress },
          '#withTls':: d.fn(help='"Whether or not TLS is used when the connection is initiated. Defaults to `false`."', args=[d.arg(name='tls', type=d.T.boolean)]),
          withTls(tls): { tls: tls },
          '#withTlsConfig':: d.fn(help='"TLS config."', args=[d.arg(name='tlsConfig', type=d.T.array)]),
          withTlsConfig(tlsConfig): { tlsConfig: if std.isArray(v=tlsConfig) then tlsConfig else [tlsConfig] },
          '#withTlsConfigMixin':: d.fn(help='"TLS config."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tlsConfig', type=d.T.array)]),
          withTlsConfigMixin(tlsConfig): { tlsConfig+: if std.isArray(v=tlsConfig) then tlsConfig else [tlsConfig] },
        },
        '#traceroute':: d.obj(help='"Settings for traceroute check. The target must be a valid hostname or IP address"'),
        traceroute: {
          '#withMaxHops':: d.fn(help='"Maximum TTL for the trace Defaults to `64`."', args=[d.arg(name='maxHops', type=d.T.number)]),
          withMaxHops(maxHops): { maxHops: maxHops },
          '#withMaxUnknownHops':: d.fn(help='"Maximum number of hosts to travers that give no response Defaults to `15`."', args=[d.arg(name='maxUnknownHops', type=d.T.number)]),
          withMaxUnknownHops(maxUnknownHops): { maxUnknownHops: maxUnknownHops },
          '#withPtrLookup':: d.fn(help='"Reverse lookup hostnames from IP addresses Defaults to `true`."', args=[d.arg(name='ptrLookup', type=d.T.boolean)]),
          withPtrLookup(ptrLookup): { ptrLookup: ptrLookup },
        },
        '#withDns':: d.fn(help='"Settings for DNS check. The target must be a valid hostname (or IP address for `PTR` records)."', args=[d.arg(name='dns', type=d.T.array)]),
        withDns(dns): { dns: if std.isArray(v=dns) then dns else [dns] },
        '#withDnsMixin':: d.fn(help='"Settings for DNS check. The target must be a valid hostname (or IP address for `PTR` records)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dns', type=d.T.array)]),
        withDnsMixin(dns): { dns+: if std.isArray(v=dns) then dns else [dns] },
        '#withHttp':: d.fn(help='"Settings for HTTP check. The target must be a URL (http or https)."', args=[d.arg(name='http', type=d.T.array)]),
        withHttp(http): { http: if std.isArray(v=http) then http else [http] },
        '#withHttpMixin':: d.fn(help='"Settings for HTTP check. The target must be a URL (http or https)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='http', type=d.T.array)]),
        withHttpMixin(http): { http+: if std.isArray(v=http) then http else [http] },
        '#withPing':: d.fn(help='"Settings for ping (ICMP) check. The target must be a valid hostname or IP address."', args=[d.arg(name='ping', type=d.T.array)]),
        withPing(ping): { ping: if std.isArray(v=ping) then ping else [ping] },
        '#withPingMixin':: d.fn(help='"Settings for ping (ICMP) check. The target must be a valid hostname or IP address."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ping', type=d.T.array)]),
        withPingMixin(ping): { ping+: if std.isArray(v=ping) then ping else [ping] },
        '#withTcp':: d.fn(help='"Settings for TCP check. The target must be of the form `<host>:<port>`, where the host portion must be a valid hostname or IP address."', args=[d.arg(name='tcp', type=d.T.array)]),
        withTcp(tcp): { tcp: if std.isArray(v=tcp) then tcp else [tcp] },
        '#withTcpMixin':: d.fn(help='"Settings for TCP check. The target must be of the form `<host>:<port>`, where the host portion must be a valid hostname or IP address."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tcp', type=d.T.array)]),
        withTcpMixin(tcp): { tcp+: if std.isArray(v=tcp) then tcp else [tcp] },
        '#withTraceroute':: d.fn(help='"Settings for traceroute check. The target must be a valid hostname or IP address"', args=[d.arg(name='traceroute', type=d.T.array)]),
        withTraceroute(traceroute): { traceroute: if std.isArray(v=traceroute) then traceroute else [traceroute] },
        '#withTracerouteMixin':: d.fn(help='"Settings for traceroute check. The target must be a valid hostname or IP address"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='traceroute', type=d.T.array)]),
        withTracerouteMixin(traceroute): { traceroute+: if std.isArray(v=traceroute) then traceroute else [traceroute] },
      },
      '#withAlertSensitivity':: d.fn(help='"Can be set to `none`, `low`, `medium`, or `high` to correspond to the check [alert levels](https://grafana.com/docs/grafana-cloud/synthetic-monitoring/synthetic-monitoring-alerting/). Defaults to `none`."', args=[d.arg(name='alertSensitivity', type=d.T.string)]),
      withAlertSensitivity(alertSensitivity): { spec+: { forProvider+: { alertSensitivity: alertSensitivity } } },
      '#withBasicMetricsOnly':: d.fn(help="\"Metrics are reduced by default. Set this to `false` if you'd like to publish all metrics. We maintain a [full list of metrics](https://github.com/grafana/synthetic-monitoring-agent/tree/main/internal/scraper/testdata) collected for each. Defaults to `true`.\"", args=[d.arg(name='basicMetricsOnly', type=d.T.boolean)]),
      withBasicMetricsOnly(basicMetricsOnly): { spec+: { forProvider+: { basicMetricsOnly: basicMetricsOnly } } },
      '#withEnabled':: d.fn(help='"Whether to enable the check. Defaults to `true`."', args=[d.arg(name='enabled', type=d.T.boolean)]),
      withEnabled(enabled): { spec+: { forProvider+: { enabled: enabled } } },
      '#withFrequency':: d.fn(help='"How often the check runs in milliseconds (the value is not truly a \\"frequency\\" but a \\"period\\"). The minimum acceptable value is 1 second (1000 ms), and the maximum is 120 seconds (120000 ms). Defaults to `60000`."', args=[d.arg(name='frequency', type=d.T.number)]),
      withFrequency(frequency): { spec+: { forProvider+: { frequency: frequency } } },
      '#withJob':: d.fn(help='"Name used for job label."', args=[d.arg(name='job', type=d.T.string)]),
      withJob(job): { spec+: { forProvider+: { job: job } } },
      '#withLabels':: d.fn(help='"Custom labels to be included with collected metrics and logs. The maximum number of labels that can be specified per check is 5. These are applied, along with the probe-specific labels, to the outgoing metrics. The names and values of the labels cannot be empty, and the maximum length is 32 bytes."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { forProvider+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"Custom labels to be included with collected metrics and logs. The maximum number of labels that can be specified per check is 5. These are applied, along with the probe-specific labels, to the outgoing metrics. The names and values of the labels cannot be empty, and the maximum length is 32 bytes."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { forProvider+: { labels+: labels } } },
      '#withProbes':: d.fn(help='"List of probe location IDs where this target will be checked from."', args=[d.arg(name='probes', type=d.T.array)]),
      withProbes(probes): { spec+: { forProvider+: { probes: if std.isArray(v=probes) then probes else [probes] } } },
      '#withProbesMixin':: d.fn(help='"List of probe location IDs where this target will be checked from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='probes', type=d.T.array)]),
      withProbesMixin(probes): { spec+: { forProvider+: { probes+: if std.isArray(v=probes) then probes else [probes] } } },
      '#withSettings':: d.fn(help='"Check settings. Should contain exactly one nested block."', args=[d.arg(name='settings', type=d.T.array)]),
      withSettings(settings): { spec+: { forProvider+: { settings: if std.isArray(v=settings) then settings else [settings] } } },
      '#withSettingsMixin':: d.fn(help='"Check settings. Should contain exactly one nested block."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='settings', type=d.T.array)]),
      withSettingsMixin(settings): { spec+: { forProvider+: { settings+: if std.isArray(v=settings) then settings else [settings] } } },
      '#withTarget':: d.fn(help='"Hostname to ping."', args=[d.arg(name='target', type=d.T.string)]),
      withTarget(target): { spec+: { forProvider+: { target: target } } },
      '#withTimeout':: d.fn(help='"Specifies the maximum running time for the check in milliseconds. The minimum acceptable value is 1 second (1000 ms), and the maximum 10 seconds (10000 ms). Defaults to `3000`."', args=[d.arg(name='timeout', type=d.T.number)]),
      withTimeout(timeout): { spec+: { forProvider+: { timeout: timeout } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
