{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='organization', url='', help='"Organization is the Schema for the Organizations API. An"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Organization', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'apigee.gcp.upbound.io/v1beta1',
    kind: 'Organization',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"OrganizationSpec defines the desired state of Organization"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#authorizedNetworkRef':: d.obj(help='"Reference to a Network in compute to populate authorizedNetwork."'),
      authorizedNetworkRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { authorizedNetworkRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { authorizedNetworkRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { authorizedNetworkRef+: { name: name } } } },
      },
      '#authorizedNetworkSelector':: d.obj(help='"Selector for a Network in compute to populate authorizedNetwork."'),
      authorizedNetworkSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { authorizedNetworkSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { authorizedNetworkSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { authorizedNetworkSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { authorizedNetworkSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { authorizedNetworkSelector+: { matchLabels+: matchLabels } } } },
      },
      '#properties':: d.obj(help='"Properties defined in the Apigee organization profile.\\nStructure is documented below."'),
      properties: {
        '#property':: d.obj(help='"List of all properties in the object.\\nStructure is documented below."'),
        property: {
          '#withName':: d.fn(help='"Name of the property."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withValue':: d.fn(help='"Value of the property."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#withProperty':: d.fn(help='"List of all properties in the object.\\nStructure is documented below."', args=[d.arg(name='property', type=d.T.array)]),
        withProperty(property): { property: if std.isArray(v=property) then property else [property] },
        '#withPropertyMixin':: d.fn(help='"List of all properties in the object.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='property', type=d.T.array)]),
        withPropertyMixin(property): { property+: if std.isArray(v=property) then property else [property] },
      },
      '#runtimeDatabaseEncryptionKeyNameRef':: d.obj(help='"Reference to a CryptoKey in kms to populate runtimeDatabaseEncryptionKeyName."'),
      runtimeDatabaseEncryptionKeyNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameRef+: { name: name } } } },
      },
      '#runtimeDatabaseEncryptionKeyNameSelector':: d.obj(help='"Selector for a CryptoKey in kms to populate runtimeDatabaseEncryptionKeyName."'),
      runtimeDatabaseEncryptionKeyNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#withAnalyticsRegion':: d.fn(help='"Primary GCP region for analytics data storage. For valid values, see Create an Apigee organization."', args=[d.arg(name='analyticsRegion', type=d.T.string)]),
      withAnalyticsRegion(analyticsRegion): { spec+: { forProvider+: { analyticsRegion: analyticsRegion } } },
      '#withApiConsumerDataEncryptionKeyName':: d.fn(help='"Cloud KMS key name used for encrypting API consumer data."', args=[d.arg(name='apiConsumerDataEncryptionKeyName', type=d.T.string)]),
      withApiConsumerDataEncryptionKeyName(apiConsumerDataEncryptionKeyName): { spec+: { forProvider+: { apiConsumerDataEncryptionKeyName: apiConsumerDataEncryptionKeyName } } },
      '#withApiConsumerDataLocation':: d.fn(help='"This field is needed only for customers using non-default data residency regions.\\nApigee stores some control plane data only in single region.\\nThis field determines which single region Apigee should use."', args=[d.arg(name='apiConsumerDataLocation', type=d.T.string)]),
      withApiConsumerDataLocation(apiConsumerDataLocation): { spec+: { forProvider+: { apiConsumerDataLocation: apiConsumerDataLocation } } },
      '#withAuthorizedNetwork':: d.fn(help='"Compute Engine network used for Service Networking to be peered with Apigee runtime instances.\\nSee Getting started with the Service Networking API.\\nValid only when RuntimeType is set to CLOUD. The value can be updated only when there are no runtime instances. For example: \\"default\\"."', args=[d.arg(name='authorizedNetwork', type=d.T.string)]),
      withAuthorizedNetwork(authorizedNetwork): { spec+: { forProvider+: { authorizedNetwork: authorizedNetwork } } },
      '#withBillingType':: d.fn(help='"Billing type of the Apigee organization. See Apigee pricing."', args=[d.arg(name='billingType', type=d.T.string)]),
      withBillingType(billingType): { spec+: { forProvider+: { billingType: billingType } } },
      '#withControlPlaneEncryptionKeyName':: d.fn(help='"Cloud KMS key name used for encrypting control plane data that is stored in a multi region.\\nOnly used for the data residency region \\"US\\" or \\"EU\\"."', args=[d.arg(name='controlPlaneEncryptionKeyName', type=d.T.string)]),
      withControlPlaneEncryptionKeyName(controlPlaneEncryptionKeyName): { spec+: { forProvider+: { controlPlaneEncryptionKeyName: controlPlaneEncryptionKeyName } } },
      '#withDescription':: d.fn(help='"Description of the Apigee organization."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withDisableVpcPeering':: d.fn(help='"Flag that specifies whether the VPC Peering through Private Google Access should be\\ndisabled between the consumer network and Apigee. Required if an authorizedNetwork\\non the consumer project is not provided, in which case the flag should be set to true.\\nValid only when RuntimeType is set to CLOUD. The value must be set before the creation\\nof any Apigee runtime instance and can be updated only when there are no runtime instances."', args=[d.arg(name='disableVpcPeering', type=d.T.boolean)]),
      withDisableVpcPeering(disableVpcPeering): { spec+: { forProvider+: { disableVpcPeering: disableVpcPeering } } },
      '#withDisplayName':: d.fn(help='"The display name of the Apigee organization."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { forProvider+: { displayName: displayName } } },
      '#withProjectId':: d.fn(help='"The project ID associated with the Apigee organization."', args=[d.arg(name='projectId', type=d.T.string)]),
      withProjectId(projectId): { spec+: { forProvider+: { projectId: projectId } } },
      '#withProperties':: d.fn(help='"Properties defined in the Apigee organization profile.\\nStructure is documented below."', args=[d.arg(name='properties', type=d.T.array)]),
      withProperties(properties): { spec+: { forProvider+: { properties: if std.isArray(v=properties) then properties else [properties] } } },
      '#withPropertiesMixin':: d.fn(help='"Properties defined in the Apigee organization profile.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='properties', type=d.T.array)]),
      withPropertiesMixin(properties): { spec+: { forProvider+: { properties+: if std.isArray(v=properties) then properties else [properties] } } },
      '#withRetention':: d.fn(help='"Optional. This setting is applicable only for organizations that are soft-deleted (i.e., BillingType\\nis not EVALUATION). It controls how long Organization data will be retained after the initial delete\\noperation completes. During this period, the Organization may be restored to its last known state.\\nAfter this period, the Organization will no longer be able to be restored.\\nDefault value is DELETION_RETENTION_UNSPECIFIED.\\nPossible values are: DELETION_RETENTION_UNSPECIFIED, MINIMUM."', args=[d.arg(name='retention', type=d.T.string)]),
      withRetention(retention): { spec+: { forProvider+: { retention: retention } } },
      '#withRuntimeDatabaseEncryptionKeyName':: d.fn(help='"Cloud KMS key name used for encrypting the data that is stored and replicated across runtime instances.\\nUpdate is not allowed after the organization is created.\\nIf not specified, a Google-Managed encryption key will be used.\\nValid only when RuntimeType is CLOUD. For example: projects/foo/locations/us/keyRings/bar/cryptoKeys/baz."', args=[d.arg(name='runtimeDatabaseEncryptionKeyName', type=d.T.string)]),
      withRuntimeDatabaseEncryptionKeyName(runtimeDatabaseEncryptionKeyName): { spec+: { forProvider+: { runtimeDatabaseEncryptionKeyName: runtimeDatabaseEncryptionKeyName } } },
      '#withRuntimeType':: d.fn(help='"Runtime type of the Apigee organization based on the Apigee subscription purchased.\\nDefault value is CLOUD.\\nPossible values are: CLOUD, HYBRID."', args=[d.arg(name='runtimeType', type=d.T.string)]),
      withRuntimeType(runtimeType): { spec+: { forProvider+: { runtimeType: runtimeType } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#authorizedNetworkRef':: d.obj(help='"Reference to a Network in compute to populate authorizedNetwork."'),
      authorizedNetworkRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { authorizedNetworkRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { authorizedNetworkRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { authorizedNetworkRef+: { name: name } } } },
      },
      '#authorizedNetworkSelector':: d.obj(help='"Selector for a Network in compute to populate authorizedNetwork."'),
      authorizedNetworkSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { authorizedNetworkSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { authorizedNetworkSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { authorizedNetworkSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { authorizedNetworkSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { authorizedNetworkSelector+: { matchLabels+: matchLabels } } } },
      },
      '#properties':: d.obj(help='"Properties defined in the Apigee organization profile.\\nStructure is documented below."'),
      properties: {
        '#property':: d.obj(help='"List of all properties in the object.\\nStructure is documented below."'),
        property: {
          '#withName':: d.fn(help='"Name of the property."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withValue':: d.fn(help='"Value of the property."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#withProperty':: d.fn(help='"List of all properties in the object.\\nStructure is documented below."', args=[d.arg(name='property', type=d.T.array)]),
        withProperty(property): { property: if std.isArray(v=property) then property else [property] },
        '#withPropertyMixin':: d.fn(help='"List of all properties in the object.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='property', type=d.T.array)]),
        withPropertyMixin(property): { property+: if std.isArray(v=property) then property else [property] },
      },
      '#runtimeDatabaseEncryptionKeyNameRef':: d.obj(help='"Reference to a CryptoKey in kms to populate runtimeDatabaseEncryptionKeyName."'),
      runtimeDatabaseEncryptionKeyNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameRef+: { name: name } } } },
      },
      '#runtimeDatabaseEncryptionKeyNameSelector':: d.obj(help='"Selector for a CryptoKey in kms to populate runtimeDatabaseEncryptionKeyName."'),
      runtimeDatabaseEncryptionKeyNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#withAnalyticsRegion':: d.fn(help='"Primary GCP region for analytics data storage. For valid values, see Create an Apigee organization."', args=[d.arg(name='analyticsRegion', type=d.T.string)]),
      withAnalyticsRegion(analyticsRegion): { spec+: { initProvider+: { analyticsRegion: analyticsRegion } } },
      '#withApiConsumerDataEncryptionKeyName':: d.fn(help='"Cloud KMS key name used for encrypting API consumer data."', args=[d.arg(name='apiConsumerDataEncryptionKeyName', type=d.T.string)]),
      withApiConsumerDataEncryptionKeyName(apiConsumerDataEncryptionKeyName): { spec+: { initProvider+: { apiConsumerDataEncryptionKeyName: apiConsumerDataEncryptionKeyName } } },
      '#withApiConsumerDataLocation':: d.fn(help='"This field is needed only for customers using non-default data residency regions.\\nApigee stores some control plane data only in single region.\\nThis field determines which single region Apigee should use."', args=[d.arg(name='apiConsumerDataLocation', type=d.T.string)]),
      withApiConsumerDataLocation(apiConsumerDataLocation): { spec+: { initProvider+: { apiConsumerDataLocation: apiConsumerDataLocation } } },
      '#withAuthorizedNetwork':: d.fn(help='"Compute Engine network used for Service Networking to be peered with Apigee runtime instances.\\nSee Getting started with the Service Networking API.\\nValid only when RuntimeType is set to CLOUD. The value can be updated only when there are no runtime instances. For example: \\"default\\"."', args=[d.arg(name='authorizedNetwork', type=d.T.string)]),
      withAuthorizedNetwork(authorizedNetwork): { spec+: { initProvider+: { authorizedNetwork: authorizedNetwork } } },
      '#withBillingType':: d.fn(help='"Billing type of the Apigee organization. See Apigee pricing."', args=[d.arg(name='billingType', type=d.T.string)]),
      withBillingType(billingType): { spec+: { initProvider+: { billingType: billingType } } },
      '#withControlPlaneEncryptionKeyName':: d.fn(help='"Cloud KMS key name used for encrypting control plane data that is stored in a multi region.\\nOnly used for the data residency region \\"US\\" or \\"EU\\"."', args=[d.arg(name='controlPlaneEncryptionKeyName', type=d.T.string)]),
      withControlPlaneEncryptionKeyName(controlPlaneEncryptionKeyName): { spec+: { initProvider+: { controlPlaneEncryptionKeyName: controlPlaneEncryptionKeyName } } },
      '#withDescription':: d.fn(help='"Description of the Apigee organization."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { initProvider+: { description: description } } },
      '#withDisableVpcPeering':: d.fn(help='"Flag that specifies whether the VPC Peering through Private Google Access should be\\ndisabled between the consumer network and Apigee. Required if an authorizedNetwork\\non the consumer project is not provided, in which case the flag should be set to true.\\nValid only when RuntimeType is set to CLOUD. The value must be set before the creation\\nof any Apigee runtime instance and can be updated only when there are no runtime instances."', args=[d.arg(name='disableVpcPeering', type=d.T.boolean)]),
      withDisableVpcPeering(disableVpcPeering): { spec+: { initProvider+: { disableVpcPeering: disableVpcPeering } } },
      '#withDisplayName':: d.fn(help='"The display name of the Apigee organization."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { initProvider+: { displayName: displayName } } },
      '#withProjectId':: d.fn(help='"The project ID associated with the Apigee organization."', args=[d.arg(name='projectId', type=d.T.string)]),
      withProjectId(projectId): { spec+: { initProvider+: { projectId: projectId } } },
      '#withProperties':: d.fn(help='"Properties defined in the Apigee organization profile.\\nStructure is documented below."', args=[d.arg(name='properties', type=d.T.array)]),
      withProperties(properties): { spec+: { initProvider+: { properties: if std.isArray(v=properties) then properties else [properties] } } },
      '#withPropertiesMixin':: d.fn(help='"Properties defined in the Apigee organization profile.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='properties', type=d.T.array)]),
      withPropertiesMixin(properties): { spec+: { initProvider+: { properties+: if std.isArray(v=properties) then properties else [properties] } } },
      '#withRetention':: d.fn(help='"Optional. This setting is applicable only for organizations that are soft-deleted (i.e., BillingType\\nis not EVALUATION). It controls how long Organization data will be retained after the initial delete\\noperation completes. During this period, the Organization may be restored to its last known state.\\nAfter this period, the Organization will no longer be able to be restored.\\nDefault value is DELETION_RETENTION_UNSPECIFIED.\\nPossible values are: DELETION_RETENTION_UNSPECIFIED, MINIMUM."', args=[d.arg(name='retention', type=d.T.string)]),
      withRetention(retention): { spec+: { initProvider+: { retention: retention } } },
      '#withRuntimeDatabaseEncryptionKeyName':: d.fn(help='"Cloud KMS key name used for encrypting the data that is stored and replicated across runtime instances.\\nUpdate is not allowed after the organization is created.\\nIf not specified, a Google-Managed encryption key will be used.\\nValid only when RuntimeType is CLOUD. For example: projects/foo/locations/us/keyRings/bar/cryptoKeys/baz."', args=[d.arg(name='runtimeDatabaseEncryptionKeyName', type=d.T.string)]),
      withRuntimeDatabaseEncryptionKeyName(runtimeDatabaseEncryptionKeyName): { spec+: { initProvider+: { runtimeDatabaseEncryptionKeyName: runtimeDatabaseEncryptionKeyName } } },
      '#withRuntimeType':: d.fn(help='"Runtime type of the Apigee organization based on the Apigee subscription purchased.\\nDefault value is CLOUD.\\nPossible values are: CLOUD, HYBRID."', args=[d.arg(name='runtimeType', type=d.T.string)]),
      withRuntimeType(runtimeType): { spec+: { initProvider+: { runtimeType: runtimeType } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which\\ncontains a name, metadata and a reference to secret store config to\\nwhich any connection details for this managed resource should be written.\\nConnection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used\\nfor this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret.\\n- Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource.\\nThis field is planned to be replaced in a future release in favor of\\nPublishConnectionDetailsTo. Currently, both could be set independently\\nand connection details would be published to both without affecting\\neach other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
