{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='runtime', url='', help='"Runtime is the Schema for the Runtimes API. A Cloud AI Platform Notebook runtime."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Runtime', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'notebooks.gcp.upbound.io/v1beta1',
    kind: 'Runtime',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"RuntimeSpec defines the desired state of Runtime"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#accessConfig':: d.obj(help='"The config settings for accessing runtime.\\nStructure is documented below."'),
      accessConfig: {
        '#withAccessType':: d.fn(help='"The type of access mode this instance. For valid values, see\\nhttps://cloud.google.com/vertex-ai/docs/workbench/reference/ rest/v1/projects.locations.runtimes#RuntimeAccessType."', args=[d.arg(name='accessType', type=d.T.string)]),
        withAccessType(accessType): { accessType: accessType },
        '#withRuntimeOwner':: d.fn(help='"The owner of this runtime after creation. Format: alias@example.com.\\nCurrently supports one owner only."', args=[d.arg(name='runtimeOwner', type=d.T.string)]),
        withRuntimeOwner(runtimeOwner): { runtimeOwner: runtimeOwner },
      },
      '#softwareConfig':: d.obj(help='"The config settings for software inside the runtime.\\nStructure is documented below."'),
      softwareConfig: {
        '#kernels':: d.obj(help='"Use a list of container images to use as Kernels in the notebook instance.\\nStructure is documented below."'),
        kernels: {
          '#withRepository':: d.fn(help='"The path to the container image repository.\\nFor example: gcr.io/{project_id}/{imageName}"', args=[d.arg(name='repository', type=d.T.string)]),
          withRepository(repository): { repository: repository },
          '#withTag':: d.fn(help='"The tag of the container image. If not specified, this defaults to the latest tag."', args=[d.arg(name='tag', type=d.T.string)]),
          withTag(tag): { tag: tag },
        },
        '#withCustomGpuDriverPath':: d.fn(help="\"Specify a custom Cloud Storage path where the GPU driver is stored.\\nIf not specified, we'll automatically choose from official GPU drivers.\"", args=[d.arg(name='customGpuDriverPath', type=d.T.string)]),
        withCustomGpuDriverPath(customGpuDriverPath): { customGpuDriverPath: customGpuDriverPath },
        '#withEnableHealthMonitoring':: d.fn(help='"Verifies core internal services are running. Default: True."', args=[d.arg(name='enableHealthMonitoring', type=d.T.boolean)]),
        withEnableHealthMonitoring(enableHealthMonitoring): { enableHealthMonitoring: enableHealthMonitoring },
        '#withIdleShutdown':: d.fn(help='"Runtime will automatically shutdown after idle_shutdown_time.\\nDefault: True"', args=[d.arg(name='idleShutdown', type=d.T.boolean)]),
        withIdleShutdown(idleShutdown): { idleShutdown: idleShutdown },
        '#withIdleShutdownTimeout':: d.fn(help='"Time in minutes to wait before shuting down runtime.\\nDefault: 180 minutes"', args=[d.arg(name='idleShutdownTimeout', type=d.T.number)]),
        withIdleShutdownTimeout(idleShutdownTimeout): { idleShutdownTimeout: idleShutdownTimeout },
        '#withInstallGpuDriver':: d.fn(help='"Install Nvidia Driver automatically."', args=[d.arg(name='installGpuDriver', type=d.T.boolean)]),
        withInstallGpuDriver(installGpuDriver): { installGpuDriver: installGpuDriver },
        '#withKernels':: d.fn(help='"Use a list of container images to use as Kernels in the notebook instance.\\nStructure is documented below."', args=[d.arg(name='kernels', type=d.T.array)]),
        withKernels(kernels): { kernels: if std.isArray(v=kernels) then kernels else [kernels] },
        '#withKernelsMixin':: d.fn(help='"Use a list of container images to use as Kernels in the notebook instance.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='kernels', type=d.T.array)]),
        withKernelsMixin(kernels): { kernels+: if std.isArray(v=kernels) then kernels else [kernels] },
        '#withNotebookUpgradeSchedule':: d.fn(help='"Cron expression in UTC timezone for schedule instance auto upgrade.\\nPlease follow the cron format."', args=[d.arg(name='notebookUpgradeSchedule', type=d.T.string)]),
        withNotebookUpgradeSchedule(notebookUpgradeSchedule): { notebookUpgradeSchedule: notebookUpgradeSchedule },
        '#withPostStartupScript':: d.fn(help='"Path to a Bash script that automatically runs after a notebook instance\\nfully boots up. The path must be a URL or\\nCloud Storage path (gs://path-to-file/file-name)."', args=[d.arg(name='postStartupScript', type=d.T.string)]),
        withPostStartupScript(postStartupScript): { postStartupScript: postStartupScript },
        '#withPostStartupScriptBehavior':: d.fn(help='"Behavior for the post startup script.\\nPossible values are: POST_STARTUP_SCRIPT_BEHAVIOR_UNSPECIFIED, RUN_EVERY_START, DOWNLOAD_AND_RUN_EVERY_START."', args=[d.arg(name='postStartupScriptBehavior', type=d.T.string)]),
        withPostStartupScriptBehavior(postStartupScriptBehavior): { postStartupScriptBehavior: postStartupScriptBehavior },
      },
      '#virtualMachine':: d.obj(help='"Use a Compute Engine VM image to start the managed notebook instance.\\nStructure is documented below."'),
      virtualMachine: {
        '#virtualMachineConfig':: d.obj(help='"Virtual Machine configuration settings.\\nStructure is documented below."'),
        virtualMachineConfig: {
          '#acceleratorConfig':: d.obj(help='"The Compute Engine accelerator configuration for this runtime.\\nStructure is documented below."'),
          acceleratorConfig: {
            '#withCoreCount':: d.fn(help='"Count of cores of this accelerator."', args=[d.arg(name='coreCount', type=d.T.number)]),
            withCoreCount(coreCount): { coreCount: coreCount },
            '#withType':: d.fn(help='"Specifies the type of the disk, either SCRATCH or PERSISTENT.\\nIf not specified, the default is PERSISTENT."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
          },
          '#containerImages':: d.obj(help='"Use a list of container images to start the notebook instance.\\nStructure is documented below."'),
          containerImages: {
            '#withRepository':: d.fn(help='"The path to the container image repository.\\nFor example: gcr.io/{project_id}/{imageName}"', args=[d.arg(name='repository', type=d.T.string)]),
            withRepository(repository): { repository: repository },
            '#withTag':: d.fn(help='"The tag of the container image. If not specified, this defaults to the latest tag."', args=[d.arg(name='tag', type=d.T.string)]),
            withTag(tag): { tag: tag },
          },
          '#dataDisk':: d.obj(help='"Data disk option configuration settings.\\nStructure is documented below."'),
          dataDisk: {
            '#initializeParams':: d.obj(help='"Input only. Specifies the parameters for a new disk that will\\nbe created alongside the new instance. Use initialization\\nparameters to create boot disks or local SSDs attached to the\\nnew instance. This property is mutually exclusive with the\\nsource property; you can only define one or the other, but not\\nboth.\\nStructure is documented below."'),
            initializeParams: {
              '#withDescription':: d.fn(help='"Provide this property when creating the disk."', args=[d.arg(name='description', type=d.T.string)]),
              withDescription(description): { description: description },
              '#withDiskName':: d.fn(help='"Specifies the disk name. If not specified, the default is\\nto use the name of the instance. If the disk with the\\ninstance name exists already in the given zone/region, a\\nnew name will be automatically generated."', args=[d.arg(name='diskName', type=d.T.string)]),
              withDiskName(diskName): { diskName: diskName },
              '#withDiskSizeGb':: d.fn(help='"Specifies the size of the disk in base-2 GB. If not\\nspecified, the disk will be the same size as the image\\n(usually 10GB). If specified, the size must be equal to\\nor larger than 10GB. Default 100 GB."', args=[d.arg(name='diskSizeGb', type=d.T.number)]),
              withDiskSizeGb(diskSizeGb): { diskSizeGb: diskSizeGb },
              '#withDiskType':: d.fn(help='"The type of the boot disk attached to this runtime,\\ndefaults to standard persistent disk. For valid values,\\nsee https://cloud.google.com/vertex-ai/docs/workbench/ reference/rest/v1/projects.locations.runtimes#disktype"', args=[d.arg(name='diskType', type=d.T.string)]),
              withDiskType(diskType): { diskType: diskType },
              '#withLabels':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."', args=[d.arg(name='labels', type=d.T.object)]),
              withLabels(labels): { labels: labels },
              '#withLabelsMixin':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
              withLabelsMixin(labels): { labels+: labels },
            },
            '#withInitializeParams':: d.fn(help='"Input only. Specifies the parameters for a new disk that will\\nbe created alongside the new instance. Use initialization\\nparameters to create boot disks or local SSDs attached to the\\nnew instance. This property is mutually exclusive with the\\nsource property; you can only define one or the other, but not\\nboth.\\nStructure is documented below."', args=[d.arg(name='initializeParams', type=d.T.array)]),
            withInitializeParams(initializeParams): { initializeParams: if std.isArray(v=initializeParams) then initializeParams else [initializeParams] },
            '#withInitializeParamsMixin':: d.fn(help='"Input only. Specifies the parameters for a new disk that will\\nbe created alongside the new instance. Use initialization\\nparameters to create boot disks or local SSDs attached to the\\nnew instance. This property is mutually exclusive with the\\nsource property; you can only define one or the other, but not\\nboth.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='initializeParams', type=d.T.array)]),
            withInitializeParamsMixin(initializeParams): { initializeParams+: if std.isArray(v=initializeParams) then initializeParams else [initializeParams] },
            '#withInterface':: d.fn(help='"\\"Specifies the disk interface to use for attaching this disk,\\nwhich is either SCSI or NVME. The default is SCSI. Persistent\\ndisks must always use SCSI and the request will fail if you attempt\\nto attach a persistent disk in any other format than SCSI. Local SSDs\\ncan use either NVME or SCSI. For performance characteristics of SCSI\\nover NVMe, see Local SSD performance. Valid values: * NVME * SCSI\\"."', args=[d.arg(name='interface', type=d.T.string)]),
            withInterface(interface): { interface: interface },
            '#withMode':: d.fn(help='"The mode in which to attach this disk, either READ_WRITE\\nor READ_ONLY. If not specified, the default is to attach\\nthe disk in READ_WRITE mode."', args=[d.arg(name='mode', type=d.T.string)]),
            withMode(mode): { mode: mode },
            '#withSource':: d.fn(help='"Specifies a valid partial or full URL to an existing\\nPersistent Disk resource."', args=[d.arg(name='source', type=d.T.string)]),
            withSource(source): { source: source },
            '#withType':: d.fn(help='"Specifies the type of the disk, either SCRATCH or PERSISTENT.\\nIf not specified, the default is PERSISTENT."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
          },
          '#encryptionConfig':: d.obj(help='"Encryption settings for virtual machine data disk.\\nStructure is documented below."'),
          encryptionConfig: {
            '#withKmsKey':: d.fn(help='"The Cloud KMS resource identifier of the customer-managed\\nencryption key used to protect a resource, such as a disks.\\nIt has the following format:\\nprojects/{PROJECT_ID}/locations/{REGION}/keyRings/ {KEY_RING_NAME}/cryptoKeys/{KEY_NAME}"', args=[d.arg(name='kmsKey', type=d.T.string)]),
            withKmsKey(kmsKey): { kmsKey: kmsKey },
          },
          '#shieldedInstanceConfig':: d.obj(help='"Shielded VM Instance configuration settings.\\nStructure is documented below."'),
          shieldedInstanceConfig: {
            '#withEnableIntegrityMonitoring':: d.fn(help='"Defines whether the instance has integrity monitoring enabled.\\nEnables monitoring and attestation of the boot integrity of\\nthe instance. The attestation is performed against the\\nintegrity policy baseline. This baseline is initially derived\\nfrom the implicitly trusted boot image when the instance is\\ncreated. Enabled by default."', args=[d.arg(name='enableIntegrityMonitoring', type=d.T.boolean)]),
            withEnableIntegrityMonitoring(enableIntegrityMonitoring): { enableIntegrityMonitoring: enableIntegrityMonitoring },
            '#withEnableSecureBoot':: d.fn(help='"Defines whether the instance has Secure Boot enabled.Secure\\nBoot helps ensure that the system only runs authentic software\\nby verifying the digital signature of all boot components, and\\nhalting the boot process if signature verification fails.\\nDisabled by default."', args=[d.arg(name='enableSecureBoot', type=d.T.boolean)]),
            withEnableSecureBoot(enableSecureBoot): { enableSecureBoot: enableSecureBoot },
            '#withEnableVtpm':: d.fn(help='"Defines whether the instance has the vTPM enabled. Enabled by\\ndefault."', args=[d.arg(name='enableVtpm', type=d.T.boolean)]),
            withEnableVtpm(enableVtpm): { enableVtpm: enableVtpm },
          },
          '#withAcceleratorConfig':: d.fn(help='"The Compute Engine accelerator configuration for this runtime.\\nStructure is documented below."', args=[d.arg(name='acceleratorConfig', type=d.T.array)]),
          withAcceleratorConfig(acceleratorConfig): { acceleratorConfig: if std.isArray(v=acceleratorConfig) then acceleratorConfig else [acceleratorConfig] },
          '#withAcceleratorConfigMixin':: d.fn(help='"The Compute Engine accelerator configuration for this runtime.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='acceleratorConfig', type=d.T.array)]),
          withAcceleratorConfigMixin(acceleratorConfig): { acceleratorConfig+: if std.isArray(v=acceleratorConfig) then acceleratorConfig else [acceleratorConfig] },
          '#withContainerImages':: d.fn(help='"Use a list of container images to start the notebook instance.\\nStructure is documented below."', args=[d.arg(name='containerImages', type=d.T.array)]),
          withContainerImages(containerImages): { containerImages: if std.isArray(v=containerImages) then containerImages else [containerImages] },
          '#withContainerImagesMixin':: d.fn(help='"Use a list of container images to start the notebook instance.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='containerImages', type=d.T.array)]),
          withContainerImagesMixin(containerImages): { containerImages+: if std.isArray(v=containerImages) then containerImages else [containerImages] },
          '#withDataDisk':: d.fn(help='"Data disk option configuration settings.\\nStructure is documented below."', args=[d.arg(name='dataDisk', type=d.T.array)]),
          withDataDisk(dataDisk): { dataDisk: if std.isArray(v=dataDisk) then dataDisk else [dataDisk] },
          '#withDataDiskMixin':: d.fn(help='"Data disk option configuration settings.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dataDisk', type=d.T.array)]),
          withDataDiskMixin(dataDisk): { dataDisk+: if std.isArray(v=dataDisk) then dataDisk else [dataDisk] },
          '#withEncryptionConfig':: d.fn(help='"Encryption settings for virtual machine data disk.\\nStructure is documented below."', args=[d.arg(name='encryptionConfig', type=d.T.array)]),
          withEncryptionConfig(encryptionConfig): { encryptionConfig: if std.isArray(v=encryptionConfig) then encryptionConfig else [encryptionConfig] },
          '#withEncryptionConfigMixin':: d.fn(help='"Encryption settings for virtual machine data disk.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='encryptionConfig', type=d.T.array)]),
          withEncryptionConfigMixin(encryptionConfig): { encryptionConfig+: if std.isArray(v=encryptionConfig) then encryptionConfig else [encryptionConfig] },
          '#withInternalIpOnly':: d.fn(help='"If true, runtime will only have internal IP addresses. By default,\\nruntimes are not restricted to internal IP addresses, and will\\nhave ephemeral external IP addresses assigned to each vm. This\\ninternal_ip_only restriction can only be enabled for subnetwork\\nenabled networks, and all dependencies must be configured to be\\naccessible without external IP addresses."', args=[d.arg(name='internalIpOnly', type=d.T.boolean)]),
          withInternalIpOnly(internalIpOnly): { internalIpOnly: internalIpOnly },
          '#withLabels':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."', args=[d.arg(name='labels', type=d.T.object)]),
          withLabels(labels): { labels: labels },
          '#withLabelsMixin':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
          withLabelsMixin(labels): { labels+: labels },
          '#withMachineType':: d.fn(help='"The Compute Engine machine type used for runtimes."', args=[d.arg(name='machineType', type=d.T.string)]),
          withMachineType(machineType): { machineType: machineType },
          '#withMetadata':: d.fn(help='"The Compute Engine metadata entries to add to virtual machine.\\n(see [Project and instance metadata](https://cloud.google.com\\n/compute/docs/storing-retrieving-metadata#project_and_instance\\n_metadata))."', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadata(metadata): { metadata: metadata },
          '#withMetadataMixin':: d.fn(help='"The Compute Engine metadata entries to add to virtual machine.\\n(see [Project and instance metadata](https://cloud.google.com\\n/compute/docs/storing-retrieving-metadata#project_and_instance\\n_metadata))."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadataMixin(metadata): { metadata+: metadata },
          '#withNetwork':: d.fn(help='"The Compute Engine network to be used for machine communications.\\nCannot be specified with subnetwork. If neither network nor\\nsubnet is specified, the \\"default\\" network of the project is\\nused, if it exists. A full URL or partial URI. Examples:"', args=[d.arg(name='network', type=d.T.string)]),
          withNetwork(network): { network: network },
          '#withNicType':: d.fn(help='"The type of vNIC to be used on this interface. This may be gVNIC\\nor VirtioNet.\\nPossible values are: UNSPECIFIED_NIC_TYPE, VIRTIO_NET, GVNIC."', args=[d.arg(name='nicType', type=d.T.string)]),
          withNicType(nicType): { nicType: nicType },
          '#withReservedIpRange':: d.fn(help="\"Reserved IP Range name is used for VPC Peering. The\\nsubnetwork allocation will use the range name if it's assigned.\"", args=[d.arg(name='reservedIpRange', type=d.T.string)]),
          withReservedIpRange(reservedIpRange): { reservedIpRange: reservedIpRange },
          '#withShieldedInstanceConfig':: d.fn(help='"Shielded VM Instance configuration settings.\\nStructure is documented below."', args=[d.arg(name='shieldedInstanceConfig', type=d.T.array)]),
          withShieldedInstanceConfig(shieldedInstanceConfig): { shieldedInstanceConfig: if std.isArray(v=shieldedInstanceConfig) then shieldedInstanceConfig else [shieldedInstanceConfig] },
          '#withShieldedInstanceConfigMixin':: d.fn(help='"Shielded VM Instance configuration settings.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='shieldedInstanceConfig', type=d.T.array)]),
          withShieldedInstanceConfigMixin(shieldedInstanceConfig): { shieldedInstanceConfig+: if std.isArray(v=shieldedInstanceConfig) then shieldedInstanceConfig else [shieldedInstanceConfig] },
          '#withSubnet':: d.fn(help='"The Compute Engine subnetwork to be used for machine\\ncommunications. Cannot be specified with network. A full URL or\\npartial URI are valid. Examples:"', args=[d.arg(name='subnet', type=d.T.string)]),
          withSubnet(subnet): { subnet: subnet },
          '#withTags':: d.fn(help='"The Compute Engine tags to add to runtime (see [Tagging instances]\\n(https://cloud.google.com/compute/docs/\\nlabel-or-tag-resources#tags))."', args=[d.arg(name='tags', type=d.T.array)]),
          withTags(tags): { tags: if std.isArray(v=tags) then tags else [tags] },
          '#withTagsMixin':: d.fn(help='"The Compute Engine tags to add to runtime (see [Tagging instances]\\n(https://cloud.google.com/compute/docs/\\nlabel-or-tag-resources#tags))."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.array)]),
          withTagsMixin(tags): { tags+: if std.isArray(v=tags) then tags else [tags] },
        },
        '#withVirtualMachineConfig':: d.fn(help='"Virtual Machine configuration settings.\\nStructure is documented below."', args=[d.arg(name='virtualMachineConfig', type=d.T.array)]),
        withVirtualMachineConfig(virtualMachineConfig): { virtualMachineConfig: if std.isArray(v=virtualMachineConfig) then virtualMachineConfig else [virtualMachineConfig] },
        '#withVirtualMachineConfigMixin':: d.fn(help='"Virtual Machine configuration settings.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='virtualMachineConfig', type=d.T.array)]),
        withVirtualMachineConfigMixin(virtualMachineConfig): { virtualMachineConfig+: if std.isArray(v=virtualMachineConfig) then virtualMachineConfig else [virtualMachineConfig] },
      },
      '#withAccessConfig':: d.fn(help='"The config settings for accessing runtime.\\nStructure is documented below."', args=[d.arg(name='accessConfig', type=d.T.array)]),
      withAccessConfig(accessConfig): { spec+: { forProvider+: { accessConfig: if std.isArray(v=accessConfig) then accessConfig else [accessConfig] } } },
      '#withAccessConfigMixin':: d.fn(help='"The config settings for accessing runtime.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='accessConfig', type=d.T.array)]),
      withAccessConfigMixin(accessConfig): { spec+: { forProvider+: { accessConfig+: if std.isArray(v=accessConfig) then accessConfig else [accessConfig] } } },
      '#withLabels':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { forProvider+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { forProvider+: { labels+: labels } } },
      '#withLocation':: d.fn(help='"A reference to the zone where the machine resides."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { forProvider+: { location: location } } },
      '#withProject':: d.fn(help='"The ID of the project in which the resource belongs.\\nIf it is not provided, the provider project is used."', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withSoftwareConfig':: d.fn(help='"The config settings for software inside the runtime.\\nStructure is documented below."', args=[d.arg(name='softwareConfig', type=d.T.array)]),
      withSoftwareConfig(softwareConfig): { spec+: { forProvider+: { softwareConfig: if std.isArray(v=softwareConfig) then softwareConfig else [softwareConfig] } } },
      '#withSoftwareConfigMixin':: d.fn(help='"The config settings for software inside the runtime.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='softwareConfig', type=d.T.array)]),
      withSoftwareConfigMixin(softwareConfig): { spec+: { forProvider+: { softwareConfig+: if std.isArray(v=softwareConfig) then softwareConfig else [softwareConfig] } } },
      '#withVirtualMachine':: d.fn(help='"Use a Compute Engine VM image to start the managed notebook instance.\\nStructure is documented below."', args=[d.arg(name='virtualMachine', type=d.T.array)]),
      withVirtualMachine(virtualMachine): { spec+: { forProvider+: { virtualMachine: if std.isArray(v=virtualMachine) then virtualMachine else [virtualMachine] } } },
      '#withVirtualMachineMixin':: d.fn(help='"Use a Compute Engine VM image to start the managed notebook instance.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='virtualMachine', type=d.T.array)]),
      withVirtualMachineMixin(virtualMachine): { spec+: { forProvider+: { virtualMachine+: if std.isArray(v=virtualMachine) then virtualMachine else [virtualMachine] } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#accessConfig':: d.obj(help='"The config settings for accessing runtime.\\nStructure is documented below."'),
      accessConfig: {
        '#withAccessType':: d.fn(help='"The type of access mode this instance. For valid values, see\\nhttps://cloud.google.com/vertex-ai/docs/workbench/reference/ rest/v1/projects.locations.runtimes#RuntimeAccessType."', args=[d.arg(name='accessType', type=d.T.string)]),
        withAccessType(accessType): { accessType: accessType },
        '#withRuntimeOwner':: d.fn(help='"The owner of this runtime after creation. Format: alias@example.com.\\nCurrently supports one owner only."', args=[d.arg(name='runtimeOwner', type=d.T.string)]),
        withRuntimeOwner(runtimeOwner): { runtimeOwner: runtimeOwner },
      },
      '#softwareConfig':: d.obj(help='"The config settings for software inside the runtime.\\nStructure is documented below."'),
      softwareConfig: {
        '#kernels':: d.obj(help='"Use a list of container images to use as Kernels in the notebook instance.\\nStructure is documented below."'),
        kernels: {
          '#withRepository':: d.fn(help='"The path to the container image repository.\\nFor example: gcr.io/{project_id}/{imageName}"', args=[d.arg(name='repository', type=d.T.string)]),
          withRepository(repository): { repository: repository },
          '#withTag':: d.fn(help='"The tag of the container image. If not specified, this defaults to the latest tag."', args=[d.arg(name='tag', type=d.T.string)]),
          withTag(tag): { tag: tag },
        },
        '#withCustomGpuDriverPath':: d.fn(help="\"Specify a custom Cloud Storage path where the GPU driver is stored.\\nIf not specified, we'll automatically choose from official GPU drivers.\"", args=[d.arg(name='customGpuDriverPath', type=d.T.string)]),
        withCustomGpuDriverPath(customGpuDriverPath): { customGpuDriverPath: customGpuDriverPath },
        '#withEnableHealthMonitoring':: d.fn(help='"Verifies core internal services are running. Default: True."', args=[d.arg(name='enableHealthMonitoring', type=d.T.boolean)]),
        withEnableHealthMonitoring(enableHealthMonitoring): { enableHealthMonitoring: enableHealthMonitoring },
        '#withIdleShutdown':: d.fn(help='"Runtime will automatically shutdown after idle_shutdown_time.\\nDefault: True"', args=[d.arg(name='idleShutdown', type=d.T.boolean)]),
        withIdleShutdown(idleShutdown): { idleShutdown: idleShutdown },
        '#withIdleShutdownTimeout':: d.fn(help='"Time in minutes to wait before shuting down runtime.\\nDefault: 180 minutes"', args=[d.arg(name='idleShutdownTimeout', type=d.T.number)]),
        withIdleShutdownTimeout(idleShutdownTimeout): { idleShutdownTimeout: idleShutdownTimeout },
        '#withInstallGpuDriver':: d.fn(help='"Install Nvidia Driver automatically."', args=[d.arg(name='installGpuDriver', type=d.T.boolean)]),
        withInstallGpuDriver(installGpuDriver): { installGpuDriver: installGpuDriver },
        '#withKernels':: d.fn(help='"Use a list of container images to use as Kernels in the notebook instance.\\nStructure is documented below."', args=[d.arg(name='kernels', type=d.T.array)]),
        withKernels(kernels): { kernels: if std.isArray(v=kernels) then kernels else [kernels] },
        '#withKernelsMixin':: d.fn(help='"Use a list of container images to use as Kernels in the notebook instance.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='kernels', type=d.T.array)]),
        withKernelsMixin(kernels): { kernels+: if std.isArray(v=kernels) then kernels else [kernels] },
        '#withNotebookUpgradeSchedule':: d.fn(help='"Cron expression in UTC timezone for schedule instance auto upgrade.\\nPlease follow the cron format."', args=[d.arg(name='notebookUpgradeSchedule', type=d.T.string)]),
        withNotebookUpgradeSchedule(notebookUpgradeSchedule): { notebookUpgradeSchedule: notebookUpgradeSchedule },
        '#withPostStartupScript':: d.fn(help='"Path to a Bash script that automatically runs after a notebook instance\\nfully boots up. The path must be a URL or\\nCloud Storage path (gs://path-to-file/file-name)."', args=[d.arg(name='postStartupScript', type=d.T.string)]),
        withPostStartupScript(postStartupScript): { postStartupScript: postStartupScript },
        '#withPostStartupScriptBehavior':: d.fn(help='"Behavior for the post startup script.\\nPossible values are: POST_STARTUP_SCRIPT_BEHAVIOR_UNSPECIFIED, RUN_EVERY_START, DOWNLOAD_AND_RUN_EVERY_START."', args=[d.arg(name='postStartupScriptBehavior', type=d.T.string)]),
        withPostStartupScriptBehavior(postStartupScriptBehavior): { postStartupScriptBehavior: postStartupScriptBehavior },
      },
      '#virtualMachine':: d.obj(help='"Use a Compute Engine VM image to start the managed notebook instance.\\nStructure is documented below."'),
      virtualMachine: {
        '#virtualMachineConfig':: d.obj(help='"Virtual Machine configuration settings.\\nStructure is documented below."'),
        virtualMachineConfig: {
          '#acceleratorConfig':: d.obj(help='"The Compute Engine accelerator configuration for this runtime.\\nStructure is documented below."'),
          acceleratorConfig: {
            '#withCoreCount':: d.fn(help='"Count of cores of this accelerator."', args=[d.arg(name='coreCount', type=d.T.number)]),
            withCoreCount(coreCount): { coreCount: coreCount },
            '#withType':: d.fn(help='"Specifies the type of the disk, either SCRATCH or PERSISTENT.\\nIf not specified, the default is PERSISTENT."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
          },
          '#containerImages':: d.obj(help='"Use a list of container images to start the notebook instance.\\nStructure is documented below."'),
          containerImages: {
            '#withRepository':: d.fn(help='"The path to the container image repository.\\nFor example: gcr.io/{project_id}/{imageName}"', args=[d.arg(name='repository', type=d.T.string)]),
            withRepository(repository): { repository: repository },
            '#withTag':: d.fn(help='"The tag of the container image. If not specified, this defaults to the latest tag."', args=[d.arg(name='tag', type=d.T.string)]),
            withTag(tag): { tag: tag },
          },
          '#dataDisk':: d.obj(help='"Data disk option configuration settings.\\nStructure is documented below."'),
          dataDisk: {
            '#initializeParams':: d.obj(help='"Input only. Specifies the parameters for a new disk that will\\nbe created alongside the new instance. Use initialization\\nparameters to create boot disks or local SSDs attached to the\\nnew instance. This property is mutually exclusive with the\\nsource property; you can only define one or the other, but not\\nboth.\\nStructure is documented below."'),
            initializeParams: {
              '#withDescription':: d.fn(help='"Provide this property when creating the disk."', args=[d.arg(name='description', type=d.T.string)]),
              withDescription(description): { description: description },
              '#withDiskName':: d.fn(help='"Specifies the disk name. If not specified, the default is\\nto use the name of the instance. If the disk with the\\ninstance name exists already in the given zone/region, a\\nnew name will be automatically generated."', args=[d.arg(name='diskName', type=d.T.string)]),
              withDiskName(diskName): { diskName: diskName },
              '#withDiskSizeGb':: d.fn(help='"Specifies the size of the disk in base-2 GB. If not\\nspecified, the disk will be the same size as the image\\n(usually 10GB). If specified, the size must be equal to\\nor larger than 10GB. Default 100 GB."', args=[d.arg(name='diskSizeGb', type=d.T.number)]),
              withDiskSizeGb(diskSizeGb): { diskSizeGb: diskSizeGb },
              '#withDiskType':: d.fn(help='"The type of the boot disk attached to this runtime,\\ndefaults to standard persistent disk. For valid values,\\nsee https://cloud.google.com/vertex-ai/docs/workbench/ reference/rest/v1/projects.locations.runtimes#disktype"', args=[d.arg(name='diskType', type=d.T.string)]),
              withDiskType(diskType): { diskType: diskType },
              '#withLabels':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."', args=[d.arg(name='labels', type=d.T.object)]),
              withLabels(labels): { labels: labels },
              '#withLabelsMixin':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
              withLabelsMixin(labels): { labels+: labels },
            },
            '#withInitializeParams':: d.fn(help='"Input only. Specifies the parameters for a new disk that will\\nbe created alongside the new instance. Use initialization\\nparameters to create boot disks or local SSDs attached to the\\nnew instance. This property is mutually exclusive with the\\nsource property; you can only define one or the other, but not\\nboth.\\nStructure is documented below."', args=[d.arg(name='initializeParams', type=d.T.array)]),
            withInitializeParams(initializeParams): { initializeParams: if std.isArray(v=initializeParams) then initializeParams else [initializeParams] },
            '#withInitializeParamsMixin':: d.fn(help='"Input only. Specifies the parameters for a new disk that will\\nbe created alongside the new instance. Use initialization\\nparameters to create boot disks or local SSDs attached to the\\nnew instance. This property is mutually exclusive with the\\nsource property; you can only define one or the other, but not\\nboth.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='initializeParams', type=d.T.array)]),
            withInitializeParamsMixin(initializeParams): { initializeParams+: if std.isArray(v=initializeParams) then initializeParams else [initializeParams] },
            '#withInterface':: d.fn(help='"\\"Specifies the disk interface to use for attaching this disk,\\nwhich is either SCSI or NVME. The default is SCSI. Persistent\\ndisks must always use SCSI and the request will fail if you attempt\\nto attach a persistent disk in any other format than SCSI. Local SSDs\\ncan use either NVME or SCSI. For performance characteristics of SCSI\\nover NVMe, see Local SSD performance. Valid values: * NVME * SCSI\\"."', args=[d.arg(name='interface', type=d.T.string)]),
            withInterface(interface): { interface: interface },
            '#withMode':: d.fn(help='"The mode in which to attach this disk, either READ_WRITE\\nor READ_ONLY. If not specified, the default is to attach\\nthe disk in READ_WRITE mode."', args=[d.arg(name='mode', type=d.T.string)]),
            withMode(mode): { mode: mode },
            '#withSource':: d.fn(help='"Specifies a valid partial or full URL to an existing\\nPersistent Disk resource."', args=[d.arg(name='source', type=d.T.string)]),
            withSource(source): { source: source },
            '#withType':: d.fn(help='"Specifies the type of the disk, either SCRATCH or PERSISTENT.\\nIf not specified, the default is PERSISTENT."', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
          },
          '#encryptionConfig':: d.obj(help='"Encryption settings for virtual machine data disk.\\nStructure is documented below."'),
          encryptionConfig: {
            '#withKmsKey':: d.fn(help='"The Cloud KMS resource identifier of the customer-managed\\nencryption key used to protect a resource, such as a disks.\\nIt has the following format:\\nprojects/{PROJECT_ID}/locations/{REGION}/keyRings/ {KEY_RING_NAME}/cryptoKeys/{KEY_NAME}"', args=[d.arg(name='kmsKey', type=d.T.string)]),
            withKmsKey(kmsKey): { kmsKey: kmsKey },
          },
          '#shieldedInstanceConfig':: d.obj(help='"Shielded VM Instance configuration settings.\\nStructure is documented below."'),
          shieldedInstanceConfig: {
            '#withEnableIntegrityMonitoring':: d.fn(help='"Defines whether the instance has integrity monitoring enabled.\\nEnables monitoring and attestation of the boot integrity of\\nthe instance. The attestation is performed against the\\nintegrity policy baseline. This baseline is initially derived\\nfrom the implicitly trusted boot image when the instance is\\ncreated. Enabled by default."', args=[d.arg(name='enableIntegrityMonitoring', type=d.T.boolean)]),
            withEnableIntegrityMonitoring(enableIntegrityMonitoring): { enableIntegrityMonitoring: enableIntegrityMonitoring },
            '#withEnableSecureBoot':: d.fn(help='"Defines whether the instance has Secure Boot enabled.Secure\\nBoot helps ensure that the system only runs authentic software\\nby verifying the digital signature of all boot components, and\\nhalting the boot process if signature verification fails.\\nDisabled by default."', args=[d.arg(name='enableSecureBoot', type=d.T.boolean)]),
            withEnableSecureBoot(enableSecureBoot): { enableSecureBoot: enableSecureBoot },
            '#withEnableVtpm':: d.fn(help='"Defines whether the instance has the vTPM enabled. Enabled by\\ndefault."', args=[d.arg(name='enableVtpm', type=d.T.boolean)]),
            withEnableVtpm(enableVtpm): { enableVtpm: enableVtpm },
          },
          '#withAcceleratorConfig':: d.fn(help='"The Compute Engine accelerator configuration for this runtime.\\nStructure is documented below."', args=[d.arg(name='acceleratorConfig', type=d.T.array)]),
          withAcceleratorConfig(acceleratorConfig): { acceleratorConfig: if std.isArray(v=acceleratorConfig) then acceleratorConfig else [acceleratorConfig] },
          '#withAcceleratorConfigMixin':: d.fn(help='"The Compute Engine accelerator configuration for this runtime.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='acceleratorConfig', type=d.T.array)]),
          withAcceleratorConfigMixin(acceleratorConfig): { acceleratorConfig+: if std.isArray(v=acceleratorConfig) then acceleratorConfig else [acceleratorConfig] },
          '#withContainerImages':: d.fn(help='"Use a list of container images to start the notebook instance.\\nStructure is documented below."', args=[d.arg(name='containerImages', type=d.T.array)]),
          withContainerImages(containerImages): { containerImages: if std.isArray(v=containerImages) then containerImages else [containerImages] },
          '#withContainerImagesMixin':: d.fn(help='"Use a list of container images to start the notebook instance.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='containerImages', type=d.T.array)]),
          withContainerImagesMixin(containerImages): { containerImages+: if std.isArray(v=containerImages) then containerImages else [containerImages] },
          '#withDataDisk':: d.fn(help='"Data disk option configuration settings.\\nStructure is documented below."', args=[d.arg(name='dataDisk', type=d.T.array)]),
          withDataDisk(dataDisk): { dataDisk: if std.isArray(v=dataDisk) then dataDisk else [dataDisk] },
          '#withDataDiskMixin':: d.fn(help='"Data disk option configuration settings.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dataDisk', type=d.T.array)]),
          withDataDiskMixin(dataDisk): { dataDisk+: if std.isArray(v=dataDisk) then dataDisk else [dataDisk] },
          '#withEncryptionConfig':: d.fn(help='"Encryption settings for virtual machine data disk.\\nStructure is documented below."', args=[d.arg(name='encryptionConfig', type=d.T.array)]),
          withEncryptionConfig(encryptionConfig): { encryptionConfig: if std.isArray(v=encryptionConfig) then encryptionConfig else [encryptionConfig] },
          '#withEncryptionConfigMixin':: d.fn(help='"Encryption settings for virtual machine data disk.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='encryptionConfig', type=d.T.array)]),
          withEncryptionConfigMixin(encryptionConfig): { encryptionConfig+: if std.isArray(v=encryptionConfig) then encryptionConfig else [encryptionConfig] },
          '#withInternalIpOnly':: d.fn(help='"If true, runtime will only have internal IP addresses. By default,\\nruntimes are not restricted to internal IP addresses, and will\\nhave ephemeral external IP addresses assigned to each vm. This\\ninternal_ip_only restriction can only be enabled for subnetwork\\nenabled networks, and all dependencies must be configured to be\\naccessible without external IP addresses."', args=[d.arg(name='internalIpOnly', type=d.T.boolean)]),
          withInternalIpOnly(internalIpOnly): { internalIpOnly: internalIpOnly },
          '#withLabels':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."', args=[d.arg(name='labels', type=d.T.object)]),
          withLabels(labels): { labels: labels },
          '#withLabelsMixin':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
          withLabelsMixin(labels): { labels+: labels },
          '#withMachineType':: d.fn(help='"The Compute Engine machine type used for runtimes."', args=[d.arg(name='machineType', type=d.T.string)]),
          withMachineType(machineType): { machineType: machineType },
          '#withMetadata':: d.fn(help='"The Compute Engine metadata entries to add to virtual machine.\\n(see [Project and instance metadata](https://cloud.google.com\\n/compute/docs/storing-retrieving-metadata#project_and_instance\\n_metadata))."', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadata(metadata): { metadata: metadata },
          '#withMetadataMixin':: d.fn(help='"The Compute Engine metadata entries to add to virtual machine.\\n(see [Project and instance metadata](https://cloud.google.com\\n/compute/docs/storing-retrieving-metadata#project_and_instance\\n_metadata))."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadataMixin(metadata): { metadata+: metadata },
          '#withNetwork':: d.fn(help='"The Compute Engine network to be used for machine communications.\\nCannot be specified with subnetwork. If neither network nor\\nsubnet is specified, the \\"default\\" network of the project is\\nused, if it exists. A full URL or partial URI. Examples:"', args=[d.arg(name='network', type=d.T.string)]),
          withNetwork(network): { network: network },
          '#withNicType':: d.fn(help='"The type of vNIC to be used on this interface. This may be gVNIC\\nor VirtioNet.\\nPossible values are: UNSPECIFIED_NIC_TYPE, VIRTIO_NET, GVNIC."', args=[d.arg(name='nicType', type=d.T.string)]),
          withNicType(nicType): { nicType: nicType },
          '#withReservedIpRange':: d.fn(help="\"Reserved IP Range name is used for VPC Peering. The\\nsubnetwork allocation will use the range name if it's assigned.\"", args=[d.arg(name='reservedIpRange', type=d.T.string)]),
          withReservedIpRange(reservedIpRange): { reservedIpRange: reservedIpRange },
          '#withShieldedInstanceConfig':: d.fn(help='"Shielded VM Instance configuration settings.\\nStructure is documented below."', args=[d.arg(name='shieldedInstanceConfig', type=d.T.array)]),
          withShieldedInstanceConfig(shieldedInstanceConfig): { shieldedInstanceConfig: if std.isArray(v=shieldedInstanceConfig) then shieldedInstanceConfig else [shieldedInstanceConfig] },
          '#withShieldedInstanceConfigMixin':: d.fn(help='"Shielded VM Instance configuration settings.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='shieldedInstanceConfig', type=d.T.array)]),
          withShieldedInstanceConfigMixin(shieldedInstanceConfig): { shieldedInstanceConfig+: if std.isArray(v=shieldedInstanceConfig) then shieldedInstanceConfig else [shieldedInstanceConfig] },
          '#withSubnet':: d.fn(help='"The Compute Engine subnetwork to be used for machine\\ncommunications. Cannot be specified with network. A full URL or\\npartial URI are valid. Examples:"', args=[d.arg(name='subnet', type=d.T.string)]),
          withSubnet(subnet): { subnet: subnet },
          '#withTags':: d.fn(help='"The Compute Engine tags to add to runtime (see [Tagging instances]\\n(https://cloud.google.com/compute/docs/\\nlabel-or-tag-resources#tags))."', args=[d.arg(name='tags', type=d.T.array)]),
          withTags(tags): { tags: if std.isArray(v=tags) then tags else [tags] },
          '#withTagsMixin':: d.fn(help='"The Compute Engine tags to add to runtime (see [Tagging instances]\\n(https://cloud.google.com/compute/docs/\\nlabel-or-tag-resources#tags))."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.array)]),
          withTagsMixin(tags): { tags+: if std.isArray(v=tags) then tags else [tags] },
        },
        '#withVirtualMachineConfig':: d.fn(help='"Virtual Machine configuration settings.\\nStructure is documented below."', args=[d.arg(name='virtualMachineConfig', type=d.T.array)]),
        withVirtualMachineConfig(virtualMachineConfig): { virtualMachineConfig: if std.isArray(v=virtualMachineConfig) then virtualMachineConfig else [virtualMachineConfig] },
        '#withVirtualMachineConfigMixin':: d.fn(help='"Virtual Machine configuration settings.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='virtualMachineConfig', type=d.T.array)]),
        withVirtualMachineConfigMixin(virtualMachineConfig): { virtualMachineConfig+: if std.isArray(v=virtualMachineConfig) then virtualMachineConfig else [virtualMachineConfig] },
      },
      '#withAccessConfig':: d.fn(help='"The config settings for accessing runtime.\\nStructure is documented below."', args=[d.arg(name='accessConfig', type=d.T.array)]),
      withAccessConfig(accessConfig): { spec+: { initProvider+: { accessConfig: if std.isArray(v=accessConfig) then accessConfig else [accessConfig] } } },
      '#withAccessConfigMixin':: d.fn(help='"The config settings for accessing runtime.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='accessConfig', type=d.T.array)]),
      withAccessConfigMixin(accessConfig): { spec+: { initProvider+: { accessConfig+: if std.isArray(v=accessConfig) then accessConfig else [accessConfig] } } },
      '#withLabels':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { initProvider+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"The labels to associate with this runtime. Label keys must\\ncontain 1 to 63 characters, and must conform to [RFC 1035]\\n(https://www.ietf.org/rfc/rfc1035.txt). Label values may be\\nempty, but, if present, must contain 1 to 63 characters, and must\\nconform to RFC 1035. No\\nmore than 32 labels can be associated with a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { initProvider+: { labels+: labels } } },
      '#withProject':: d.fn(help='"The ID of the project in which the resource belongs.\\nIf it is not provided, the provider project is used."', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { initProvider+: { project: project } } },
      '#withSoftwareConfig':: d.fn(help='"The config settings for software inside the runtime.\\nStructure is documented below."', args=[d.arg(name='softwareConfig', type=d.T.array)]),
      withSoftwareConfig(softwareConfig): { spec+: { initProvider+: { softwareConfig: if std.isArray(v=softwareConfig) then softwareConfig else [softwareConfig] } } },
      '#withSoftwareConfigMixin':: d.fn(help='"The config settings for software inside the runtime.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='softwareConfig', type=d.T.array)]),
      withSoftwareConfigMixin(softwareConfig): { spec+: { initProvider+: { softwareConfig+: if std.isArray(v=softwareConfig) then softwareConfig else [softwareConfig] } } },
      '#withVirtualMachine':: d.fn(help='"Use a Compute Engine VM image to start the managed notebook instance.\\nStructure is documented below."', args=[d.arg(name='virtualMachine', type=d.T.array)]),
      withVirtualMachine(virtualMachine): { spec+: { initProvider+: { virtualMachine: if std.isArray(v=virtualMachine) then virtualMachine else [virtualMachine] } } },
      '#withVirtualMachineMixin':: d.fn(help='"Use a Compute Engine VM image to start the managed notebook instance.\\nStructure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='virtualMachine', type=d.T.array)]),
      withVirtualMachineMixin(virtualMachine): { spec+: { initProvider+: { virtualMachine+: if std.isArray(v=virtualMachine) then virtualMachine else [virtualMachine] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which\\ncontains a name, metadata and a reference to secret store config to\\nwhich any connection details for this managed resource should be written.\\nConnection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used\\nfor this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret.\\n- Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource.\\nThis field is planned to be replaced in a future release in favor of\\nPublishConnectionDetailsTo. Currently, both could be set independently\\nand connection details would be published to both without affecting\\neach other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
