{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='report', url='', help='"Report is the Schema for the Reports API. Note: This resource is available only with Grafana Enterprise 7.+. Official documentation https://grafana.com/docs/grafana/latest/dashboards/create-reports/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/reporting/"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Report', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'enterprise.grafana.crossplane.io/v1alpha1',
    kind: 'Report',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"ReportSpec defines the desired state of Report"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#dashboardRef':: d.obj(help='"Reference to a Dashboard in oss to populate dashboardUid."'),
      dashboardRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { dashboardRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { dashboardRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { dashboardRef+: { name: name } } } },
      },
      '#dashboardSelector':: d.obj(help='"Selector for a Dashboard in oss to populate dashboardUid."'),
      dashboardSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { dashboardSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { dashboardSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { dashboardSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { dashboardSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { dashboardSelector+: { matchLabels+: matchLabels } } } },
      },
      '#dashboards':: d.obj(help='"(Block List) List of dashboards to render into the report (see below for nested schema)\\nList of dashboards to render into the report"'),
      dashboards: {
        '#timeRange':: d.obj(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."'),
        timeRange: {
          '#withFrom':: d.fn(help='"(String) Start of the time range.\\nStart of the time range."', args=[d.arg(name='from', type=d.T.string)]),
          withFrom(from): { from: from },
          '#withTo':: d.fn(help='"(String) End of the time range.\\nEnd of the time range."', args=[d.arg(name='to', type=d.T.string)]),
          withTo(to): { to: to },
        },
        '#withReportVariables':: d.fn(help='"(Map of String) Add report variables to the dashboard. Values should be separated by commas.\\nAdd report variables to the dashboard. Values should be separated by commas."', args=[d.arg(name='reportVariables', type=d.T.object)]),
        withReportVariables(reportVariables): { reportVariables: reportVariables },
        '#withReportVariablesMixin':: d.fn(help='"(Map of String) Add report variables to the dashboard. Values should be separated by commas.\\nAdd report variables to the dashboard. Values should be separated by commas."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='reportVariables', type=d.T.object)]),
        withReportVariablesMixin(reportVariables): { reportVariables+: reportVariables },
        '#withTimeRange':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."', args=[d.arg(name='timeRange', type=d.T.array)]),
        withTimeRange(timeRange): { timeRange: if std.isArray(v=timeRange) then timeRange else [timeRange] },
        '#withTimeRangeMixin':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='timeRange', type=d.T.array)]),
        withTimeRangeMixin(timeRange): { timeRange+: if std.isArray(v=timeRange) then timeRange else [timeRange] },
        '#withUid':: d.fn(help='"(String) Dashboard uid.\\nDashboard uid."', args=[d.arg(name='uid', type=d.T.string)]),
        withUid(uid): { uid: uid },
      },
      '#organizationRef':: d.obj(help='"Reference to a Organization in oss to populate orgId."'),
      organizationRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { organizationRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { organizationRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { organizationRef+: { name: name } } } },
      },
      '#organizationSelector':: d.obj(help='"Selector for a Organization in oss to populate orgId."'),
      organizationSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { organizationSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { organizationSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { organizationSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { organizationSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { organizationSelector+: { matchLabels+: matchLabels } } } },
      },
      '#schedule':: d.obj(help='"(Block List, Min: 1, Max: 1) Schedule of the report. (see below for nested schema)\\nSchedule of the report."'),
      schedule: {
        '#withCustomInterval':: d.fn(help='"(String) Custom interval of the report.\\nNote: This field is only available when frequency is set to custom.\\nCustom interval of the report.\\n**Note:** This field is only available when frequency is set to `custom`."', args=[d.arg(name='customInterval', type=d.T.string)]),
        withCustomInterval(customInterval): { customInterval: customInterval },
        '#withEndTime':: d.fn(help='"01-02T15:04:05 format if you want to set a custom timezone\\nEnd time of the report. If empty, the report will be sent indefinitely (according to frequency). Note that times will be saved as UTC in Grafana. Use 2006-01-02T15:04:05 format if you want to set a custom timezone"', args=[d.arg(name='endTime', type=d.T.string)]),
        withEndTime(endTime): { endTime: endTime },
        '#withFrequency':: d.fn(help='"(String) Frequency of the report. Allowed values: never, once, hourly, daily, weekly, monthly, custom.\\nFrequency of the report. Allowed values: `never`, `once`, `hourly`, `daily`, `weekly`, `monthly`, `custom`."', args=[d.arg(name='frequency', type=d.T.string)]),
        withFrequency(frequency): { frequency: frequency },
        '#withLastDayOfMonth':: d.fn(help='"(Boolean) Send the report on the last day of the month Defaults to false.\\nSend the report on the last day of the month Defaults to `false`."', args=[d.arg(name='lastDayOfMonth', type=d.T.boolean)]),
        withLastDayOfMonth(lastDayOfMonth): { lastDayOfMonth: lastDayOfMonth },
        '#withStartTime':: d.fn(help='"01-02T15:04:05 format if you want to set a custom timezone\\nStart time of the report. If empty, the start date will be set to the creation time. Note that times will be saved as UTC in Grafana. Use 2006-01-02T15:04:05 format if you want to set a custom timezone"', args=[d.arg(name='startTime', type=d.T.string)]),
        withStartTime(startTime): { startTime: startTime },
        '#withTimezone':: d.fn(help='"(String) Set the report time zone. Defaults to GMT.\\nSet the report time zone. Defaults to `GMT`."', args=[d.arg(name='timezone', type=d.T.string)]),
        withTimezone(timezone): { timezone: timezone },
        '#withWorkdaysOnly':: d.fn(help='"(Boolean) Whether to send the report only on work days. Defaults to false.\\nWhether to send the report only on work days. Defaults to `false`."', args=[d.arg(name='workdaysOnly', type=d.T.boolean)]),
        withWorkdaysOnly(workdaysOnly): { workdaysOnly: workdaysOnly },
      },
      '#timeRange':: d.obj(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."'),
      timeRange: {
        '#withFrom':: d.fn(help='"(String) Start of the time range.\\nStart of the time range."', args=[d.arg(name='from', type=d.T.string)]),
        withFrom(from): { from: from },
        '#withTo':: d.fn(help='"(String) End of the time range.\\nEnd of the time range."', args=[d.arg(name='to', type=d.T.string)]),
        withTo(to): { to: to },
      },
      '#withDashboardUid':: d.fn(help='"(String, Deprecated) Dashboard to be sent in the report.\\nDashboard to be sent in the report."', args=[d.arg(name='dashboardUid', type=d.T.string)]),
      withDashboardUid(dashboardUid): { spec+: { forProvider+: { dashboardUid: dashboardUid } } },
      '#withDashboards':: d.fn(help='"(Block List) List of dashboards to render into the report (see below for nested schema)\\nList of dashboards to render into the report"', args=[d.arg(name='dashboards', type=d.T.array)]),
      withDashboards(dashboards): { spec+: { forProvider+: { dashboards: if std.isArray(v=dashboards) then dashboards else [dashboards] } } },
      '#withDashboardsMixin':: d.fn(help='"(Block List) List of dashboards to render into the report (see below for nested schema)\\nList of dashboards to render into the report"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dashboards', type=d.T.array)]),
      withDashboardsMixin(dashboards): { spec+: { forProvider+: { dashboards+: if std.isArray(v=dashboards) then dashboards else [dashboards] } } },
      '#withFormats':: d.fn(help='"(Set of String) Specifies what kind of attachment to generate for the report. Allowed values: pdf, csv, image.\\nSpecifies what kind of attachment to generate for the report. Allowed values: `pdf`, `csv`, `image`."', args=[d.arg(name='formats', type=d.T.array)]),
      withFormats(formats): { spec+: { forProvider+: { formats: if std.isArray(v=formats) then formats else [formats] } } },
      '#withFormatsMixin':: d.fn(help='"(Set of String) Specifies what kind of attachment to generate for the report. Allowed values: pdf, csv, image.\\nSpecifies what kind of attachment to generate for the report. Allowed values: `pdf`, `csv`, `image`."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='formats', type=d.T.array)]),
      withFormatsMixin(formats): { spec+: { forProvider+: { formats+: if std.isArray(v=formats) then formats else [formats] } } },
      '#withIncludeDashboardLink':: d.fn(help='"(Boolean) Whether to include a link to the dashboard in the report. Defaults to true.\\nWhether to include a link to the dashboard in the report. Defaults to `true`."', args=[d.arg(name='includeDashboardLink', type=d.T.boolean)]),
      withIncludeDashboardLink(includeDashboardLink): { spec+: { forProvider+: { includeDashboardLink: includeDashboardLink } } },
      '#withIncludeTableCsv':: d.fn(help='"(Boolean) Whether to include a CSV file of table panel data. Defaults to false.\\nWhether to include a CSV file of table panel data. Defaults to `false`."', args=[d.arg(name='includeTableCsv', type=d.T.boolean)]),
      withIncludeTableCsv(includeTableCsv): { spec+: { forProvider+: { includeTableCsv: includeTableCsv } } },
      '#withLayout':: d.fn(help='"(String) Layout of the report. Allowed values: simple, grid. Defaults to grid.\\nLayout of the report. Allowed values: `simple`, `grid`. Defaults to `grid`."', args=[d.arg(name='layout', type=d.T.string)]),
      withLayout(layout): { spec+: { forProvider+: { layout: layout } } },
      '#withMessage':: d.fn(help='"(String) Message to be sent in the report.\\nMessage to be sent in the report."', args=[d.arg(name='message', type=d.T.string)]),
      withMessage(message): { spec+: { forProvider+: { message: message } } },
      '#withName':: d.fn(help='"(String) Name of the report.\\nName of the report."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { forProvider+: { name: name } } },
      '#withOrgId':: d.fn(help='"(String) The Organization ID. If not set, the Org ID defined in the provider block will be used.\\nThe Organization ID. If not set, the Org ID defined in the provider block will be used."', args=[d.arg(name='orgId', type=d.T.string)]),
      withOrgId(orgId): { spec+: { forProvider+: { orgId: orgId } } },
      '#withOrientation':: d.fn(help='"(String) Orientation of the report. Allowed values: landscape, portrait. Defaults to landscape.\\nOrientation of the report. Allowed values: `landscape`, `portrait`. Defaults to `landscape`."', args=[d.arg(name='orientation', type=d.T.string)]),
      withOrientation(orientation): { spec+: { forProvider+: { orientation: orientation } } },
      '#withRecipients':: d.fn(help='"(List of String) List of recipients of the report.\\nList of recipients of the report."', args=[d.arg(name='recipients', type=d.T.array)]),
      withRecipients(recipients): { spec+: { forProvider+: { recipients: if std.isArray(v=recipients) then recipients else [recipients] } } },
      '#withRecipientsMixin':: d.fn(help='"(List of String) List of recipients of the report.\\nList of recipients of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='recipients', type=d.T.array)]),
      withRecipientsMixin(recipients): { spec+: { forProvider+: { recipients+: if std.isArray(v=recipients) then recipients else [recipients] } } },
      '#withReplyTo':: d.fn(help='"to email address of the report.\\nReply-to email address of the report."', args=[d.arg(name='replyTo', type=d.T.string)]),
      withReplyTo(replyTo): { spec+: { forProvider+: { replyTo: replyTo } } },
      '#withSchedule':: d.fn(help='"(Block List, Min: 1, Max: 1) Schedule of the report. (see below for nested schema)\\nSchedule of the report."', args=[d.arg(name='schedule', type=d.T.array)]),
      withSchedule(schedule): { spec+: { forProvider+: { schedule: if std.isArray(v=schedule) then schedule else [schedule] } } },
      '#withScheduleMixin':: d.fn(help='"(Block List, Min: 1, Max: 1) Schedule of the report. (see below for nested schema)\\nSchedule of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='schedule', type=d.T.array)]),
      withScheduleMixin(schedule): { spec+: { forProvider+: { schedule+: if std.isArray(v=schedule) then schedule else [schedule] } } },
      '#withTimeRange':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."', args=[d.arg(name='timeRange', type=d.T.array)]),
      withTimeRange(timeRange): { spec+: { forProvider+: { timeRange: if std.isArray(v=timeRange) then timeRange else [timeRange] } } },
      '#withTimeRangeMixin':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='timeRange', type=d.T.array)]),
      withTimeRangeMixin(timeRange): { spec+: { forProvider+: { timeRange+: if std.isArray(v=timeRange) then timeRange else [timeRange] } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#dashboardRef':: d.obj(help='"Reference to a Dashboard in oss to populate dashboardUid."'),
      dashboardRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { dashboardRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { dashboardRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { dashboardRef+: { name: name } } } },
      },
      '#dashboardSelector':: d.obj(help='"Selector for a Dashboard in oss to populate dashboardUid."'),
      dashboardSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { dashboardSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { dashboardSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { dashboardSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { dashboardSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { dashboardSelector+: { matchLabels+: matchLabels } } } },
      },
      '#dashboards':: d.obj(help='"(Block List) List of dashboards to render into the report (see below for nested schema)\\nList of dashboards to render into the report"'),
      dashboards: {
        '#timeRange':: d.obj(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."'),
        timeRange: {
          '#withFrom':: d.fn(help='"(String) Start of the time range.\\nStart of the time range."', args=[d.arg(name='from', type=d.T.string)]),
          withFrom(from): { from: from },
          '#withTo':: d.fn(help='"(String) End of the time range.\\nEnd of the time range."', args=[d.arg(name='to', type=d.T.string)]),
          withTo(to): { to: to },
        },
        '#withReportVariables':: d.fn(help='"(Map of String) Add report variables to the dashboard. Values should be separated by commas.\\nAdd report variables to the dashboard. Values should be separated by commas."', args=[d.arg(name='reportVariables', type=d.T.object)]),
        withReportVariables(reportVariables): { reportVariables: reportVariables },
        '#withReportVariablesMixin':: d.fn(help='"(Map of String) Add report variables to the dashboard. Values should be separated by commas.\\nAdd report variables to the dashboard. Values should be separated by commas."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='reportVariables', type=d.T.object)]),
        withReportVariablesMixin(reportVariables): { reportVariables+: reportVariables },
        '#withTimeRange':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."', args=[d.arg(name='timeRange', type=d.T.array)]),
        withTimeRange(timeRange): { timeRange: if std.isArray(v=timeRange) then timeRange else [timeRange] },
        '#withTimeRangeMixin':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='timeRange', type=d.T.array)]),
        withTimeRangeMixin(timeRange): { timeRange+: if std.isArray(v=timeRange) then timeRange else [timeRange] },
        '#withUid':: d.fn(help='"(String) Dashboard uid.\\nDashboard uid."', args=[d.arg(name='uid', type=d.T.string)]),
        withUid(uid): { uid: uid },
      },
      '#organizationRef':: d.obj(help='"Reference to a Organization in oss to populate orgId."'),
      organizationRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { organizationRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { organizationRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { organizationRef+: { name: name } } } },
      },
      '#organizationSelector':: d.obj(help='"Selector for a Organization in oss to populate orgId."'),
      organizationSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { organizationSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { organizationSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { organizationSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { organizationSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { organizationSelector+: { matchLabels+: matchLabels } } } },
      },
      '#schedule':: d.obj(help='"(Block List, Min: 1, Max: 1) Schedule of the report. (see below for nested schema)\\nSchedule of the report."'),
      schedule: {
        '#withCustomInterval':: d.fn(help='"(String) Custom interval of the report.\\nNote: This field is only available when frequency is set to custom.\\nCustom interval of the report.\\n**Note:** This field is only available when frequency is set to `custom`."', args=[d.arg(name='customInterval', type=d.T.string)]),
        withCustomInterval(customInterval): { customInterval: customInterval },
        '#withEndTime':: d.fn(help='"01-02T15:04:05 format if you want to set a custom timezone\\nEnd time of the report. If empty, the report will be sent indefinitely (according to frequency). Note that times will be saved as UTC in Grafana. Use 2006-01-02T15:04:05 format if you want to set a custom timezone"', args=[d.arg(name='endTime', type=d.T.string)]),
        withEndTime(endTime): { endTime: endTime },
        '#withFrequency':: d.fn(help='"(String) Frequency of the report. Allowed values: never, once, hourly, daily, weekly, monthly, custom.\\nFrequency of the report. Allowed values: `never`, `once`, `hourly`, `daily`, `weekly`, `monthly`, `custom`."', args=[d.arg(name='frequency', type=d.T.string)]),
        withFrequency(frequency): { frequency: frequency },
        '#withLastDayOfMonth':: d.fn(help='"(Boolean) Send the report on the last day of the month Defaults to false.\\nSend the report on the last day of the month Defaults to `false`."', args=[d.arg(name='lastDayOfMonth', type=d.T.boolean)]),
        withLastDayOfMonth(lastDayOfMonth): { lastDayOfMonth: lastDayOfMonth },
        '#withStartTime':: d.fn(help='"01-02T15:04:05 format if you want to set a custom timezone\\nStart time of the report. If empty, the start date will be set to the creation time. Note that times will be saved as UTC in Grafana. Use 2006-01-02T15:04:05 format if you want to set a custom timezone"', args=[d.arg(name='startTime', type=d.T.string)]),
        withStartTime(startTime): { startTime: startTime },
        '#withTimezone':: d.fn(help='"(String) Set the report time zone. Defaults to GMT.\\nSet the report time zone. Defaults to `GMT`."', args=[d.arg(name='timezone', type=d.T.string)]),
        withTimezone(timezone): { timezone: timezone },
        '#withWorkdaysOnly':: d.fn(help='"(Boolean) Whether to send the report only on work days. Defaults to false.\\nWhether to send the report only on work days. Defaults to `false`."', args=[d.arg(name='workdaysOnly', type=d.T.boolean)]),
        withWorkdaysOnly(workdaysOnly): { workdaysOnly: workdaysOnly },
      },
      '#timeRange':: d.obj(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."'),
      timeRange: {
        '#withFrom':: d.fn(help='"(String) Start of the time range.\\nStart of the time range."', args=[d.arg(name='from', type=d.T.string)]),
        withFrom(from): { from: from },
        '#withTo':: d.fn(help='"(String) End of the time range.\\nEnd of the time range."', args=[d.arg(name='to', type=d.T.string)]),
        withTo(to): { to: to },
      },
      '#withDashboardUid':: d.fn(help='"(String, Deprecated) Dashboard to be sent in the report.\\nDashboard to be sent in the report."', args=[d.arg(name='dashboardUid', type=d.T.string)]),
      withDashboardUid(dashboardUid): { spec+: { initProvider+: { dashboardUid: dashboardUid } } },
      '#withDashboards':: d.fn(help='"(Block List) List of dashboards to render into the report (see below for nested schema)\\nList of dashboards to render into the report"', args=[d.arg(name='dashboards', type=d.T.array)]),
      withDashboards(dashboards): { spec+: { initProvider+: { dashboards: if std.isArray(v=dashboards) then dashboards else [dashboards] } } },
      '#withDashboardsMixin':: d.fn(help='"(Block List) List of dashboards to render into the report (see below for nested schema)\\nList of dashboards to render into the report"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dashboards', type=d.T.array)]),
      withDashboardsMixin(dashboards): { spec+: { initProvider+: { dashboards+: if std.isArray(v=dashboards) then dashboards else [dashboards] } } },
      '#withFormats':: d.fn(help='"(Set of String) Specifies what kind of attachment to generate for the report. Allowed values: pdf, csv, image.\\nSpecifies what kind of attachment to generate for the report. Allowed values: `pdf`, `csv`, `image`."', args=[d.arg(name='formats', type=d.T.array)]),
      withFormats(formats): { spec+: { initProvider+: { formats: if std.isArray(v=formats) then formats else [formats] } } },
      '#withFormatsMixin':: d.fn(help='"(Set of String) Specifies what kind of attachment to generate for the report. Allowed values: pdf, csv, image.\\nSpecifies what kind of attachment to generate for the report. Allowed values: `pdf`, `csv`, `image`."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='formats', type=d.T.array)]),
      withFormatsMixin(formats): { spec+: { initProvider+: { formats+: if std.isArray(v=formats) then formats else [formats] } } },
      '#withIncludeDashboardLink':: d.fn(help='"(Boolean) Whether to include a link to the dashboard in the report. Defaults to true.\\nWhether to include a link to the dashboard in the report. Defaults to `true`."', args=[d.arg(name='includeDashboardLink', type=d.T.boolean)]),
      withIncludeDashboardLink(includeDashboardLink): { spec+: { initProvider+: { includeDashboardLink: includeDashboardLink } } },
      '#withIncludeTableCsv':: d.fn(help='"(Boolean) Whether to include a CSV file of table panel data. Defaults to false.\\nWhether to include a CSV file of table panel data. Defaults to `false`."', args=[d.arg(name='includeTableCsv', type=d.T.boolean)]),
      withIncludeTableCsv(includeTableCsv): { spec+: { initProvider+: { includeTableCsv: includeTableCsv } } },
      '#withLayout':: d.fn(help='"(String) Layout of the report. Allowed values: simple, grid. Defaults to grid.\\nLayout of the report. Allowed values: `simple`, `grid`. Defaults to `grid`."', args=[d.arg(name='layout', type=d.T.string)]),
      withLayout(layout): { spec+: { initProvider+: { layout: layout } } },
      '#withMessage':: d.fn(help='"(String) Message to be sent in the report.\\nMessage to be sent in the report."', args=[d.arg(name='message', type=d.T.string)]),
      withMessage(message): { spec+: { initProvider+: { message: message } } },
      '#withName':: d.fn(help='"(String) Name of the report.\\nName of the report."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { initProvider+: { name: name } } },
      '#withOrgId':: d.fn(help='"(String) The Organization ID. If not set, the Org ID defined in the provider block will be used.\\nThe Organization ID. If not set, the Org ID defined in the provider block will be used."', args=[d.arg(name='orgId', type=d.T.string)]),
      withOrgId(orgId): { spec+: { initProvider+: { orgId: orgId } } },
      '#withOrientation':: d.fn(help='"(String) Orientation of the report. Allowed values: landscape, portrait. Defaults to landscape.\\nOrientation of the report. Allowed values: `landscape`, `portrait`. Defaults to `landscape`."', args=[d.arg(name='orientation', type=d.T.string)]),
      withOrientation(orientation): { spec+: { initProvider+: { orientation: orientation } } },
      '#withRecipients':: d.fn(help='"(List of String) List of recipients of the report.\\nList of recipients of the report."', args=[d.arg(name='recipients', type=d.T.array)]),
      withRecipients(recipients): { spec+: { initProvider+: { recipients: if std.isArray(v=recipients) then recipients else [recipients] } } },
      '#withRecipientsMixin':: d.fn(help='"(List of String) List of recipients of the report.\\nList of recipients of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='recipients', type=d.T.array)]),
      withRecipientsMixin(recipients): { spec+: { initProvider+: { recipients+: if std.isArray(v=recipients) then recipients else [recipients] } } },
      '#withReplyTo':: d.fn(help='"to email address of the report.\\nReply-to email address of the report."', args=[d.arg(name='replyTo', type=d.T.string)]),
      withReplyTo(replyTo): { spec+: { initProvider+: { replyTo: replyTo } } },
      '#withSchedule':: d.fn(help='"(Block List, Min: 1, Max: 1) Schedule of the report. (see below for nested schema)\\nSchedule of the report."', args=[d.arg(name='schedule', type=d.T.array)]),
      withSchedule(schedule): { spec+: { initProvider+: { schedule: if std.isArray(v=schedule) then schedule else [schedule] } } },
      '#withScheduleMixin':: d.fn(help='"(Block List, Min: 1, Max: 1) Schedule of the report. (see below for nested schema)\\nSchedule of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='schedule', type=d.T.array)]),
      withScheduleMixin(schedule): { spec+: { initProvider+: { schedule+: if std.isArray(v=schedule) then schedule else [schedule] } } },
      '#withTimeRange':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."', args=[d.arg(name='timeRange', type=d.T.array)]),
      withTimeRange(timeRange): { spec+: { initProvider+: { timeRange: if std.isArray(v=timeRange) then timeRange else [timeRange] } } },
      '#withTimeRangeMixin':: d.fn(help='"(Block List, Max: 1, Deprecated) Time range of the report. (see below for nested schema)\\nTime range of the report."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='timeRange', type=d.T.array)]),
      withTimeRangeMixin(timeRange): { spec+: { initProvider+: { timeRange+: if std.isArray(v=timeRange) then timeRange else [timeRange] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which\\ncontains a name, metadata and a reference to secret store config to\\nwhich any connection details for this managed resource should be written.\\nConnection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used\\nfor this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret.\\n- Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource.\\nThis field is planned to be replaced in a future release in favor of\\nPublishConnectionDetailsTo. Currently, both could be set independently\\nand connection details would be published to both without affecting\\neach other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
