{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='application', url='', help='"Application is the Schema for the Applications API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Application', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'applications.azuread.upbound.io/v1beta1',
    kind: 'Application',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"ApplicationSpec defines the desired state of Application"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#api':: d.obj(help=''),
      api: {
        '#oauth2PermissionScope':: d.obj(help='"One or more `oauth2_permission_scope` blocks to describe delegated permissions exposed by the web API represented by this application"'),
        oauth2PermissionScope: {
          '#withAdminConsentDescription':: d.fn(help='"Delegated permission description that appears in all tenant-wide admin consent experiences, intended to be read by an administrator granting the permission on behalf of all users"', args=[d.arg(name='adminConsentDescription', type=d.T.string)]),
          withAdminConsentDescription(adminConsentDescription): { adminConsentDescription: adminConsentDescription },
          '#withAdminConsentDisplayName':: d.fn(help='"Display name for the delegated permission, intended to be read by an administrator granting the permission on behalf of all users"', args=[d.arg(name='adminConsentDisplayName', type=d.T.string)]),
          withAdminConsentDisplayName(adminConsentDisplayName): { adminConsentDisplayName: adminConsentDisplayName },
          '#withEnabled':: d.fn(help='"Determines if the permission scope is enabled"', args=[d.arg(name='enabled', type=d.T.boolean)]),
          withEnabled(enabled): { enabled: enabled },
          '#withId':: d.fn(help='"An ID used to uniquely identify this synchronization sec. The unique identifier of the delegated permission"', args=[d.arg(name='id', type=d.T.string)]),
          withId(id): { id: id },
          '#withType':: d.fn(help='"Whether this delegated permission should be considered safe for non-admin users to consent to on behalf of themselves, or whether an administrator should be required for consent to the permissions"', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
          '#withUserConsentDescription':: d.fn(help='"Delegated permission description that appears in the end user consent experience, intended to be read by a user consenting on their own behalf"', args=[d.arg(name='userConsentDescription', type=d.T.string)]),
          withUserConsentDescription(userConsentDescription): { userConsentDescription: userConsentDescription },
          '#withUserConsentDisplayName':: d.fn(help='"Display name for the delegated permission that appears in the end user consent experience"', args=[d.arg(name='userConsentDisplayName', type=d.T.string)]),
          withUserConsentDisplayName(userConsentDisplayName): { userConsentDisplayName: userConsentDisplayName },
          '#withValue':: d.fn(help='"The value of the secret. The value that is used for the `scp` claim in OAuth 2.0 access tokens"', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#withKnownClientApplications':: d.fn(help='"Used for bundling consent if you have a solution that contains two parts: a client app and a custom web API app"', args=[d.arg(name='knownClientApplications', type=d.T.array)]),
        withKnownClientApplications(knownClientApplications): { knownClientApplications: if std.isArray(v=knownClientApplications) then knownClientApplications else [knownClientApplications] },
        '#withKnownClientApplicationsMixin':: d.fn(help='"Used for bundling consent if you have a solution that contains two parts: a client app and a custom web API app"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='knownClientApplications', type=d.T.array)]),
        withKnownClientApplicationsMixin(knownClientApplications): { knownClientApplications+: if std.isArray(v=knownClientApplications) then knownClientApplications else [knownClientApplications] },
        '#withMappedClaimsEnabled':: d.fn(help='"Allows an application to use claims mapping without specifying a custom signing key"', args=[d.arg(name='mappedClaimsEnabled', type=d.T.boolean)]),
        withMappedClaimsEnabled(mappedClaimsEnabled): { mappedClaimsEnabled: mappedClaimsEnabled },
        '#withOauth2PermissionScope':: d.fn(help='"One or more `oauth2_permission_scope` blocks to describe delegated permissions exposed by the web API represented by this application"', args=[d.arg(name='oauth2PermissionScope', type=d.T.array)]),
        withOauth2PermissionScope(oauth2PermissionScope): { oauth2PermissionScope: if std.isArray(v=oauth2PermissionScope) then oauth2PermissionScope else [oauth2PermissionScope] },
        '#withOauth2PermissionScopeMixin':: d.fn(help='"One or more `oauth2_permission_scope` blocks to describe delegated permissions exposed by the web API represented by this application"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='oauth2PermissionScope', type=d.T.array)]),
        withOauth2PermissionScopeMixin(oauth2PermissionScope): { oauth2PermissionScope+: if std.isArray(v=oauth2PermissionScope) then oauth2PermissionScope else [oauth2PermissionScope] },
        '#withRequestedAccessTokenVersion':: d.fn(help='"The access token version expected by this resource"', args=[d.arg(name='requestedAccessTokenVersion', type=d.T.number)]),
        withRequestedAccessTokenVersion(requestedAccessTokenVersion): { requestedAccessTokenVersion: requestedAccessTokenVersion },
      },
      '#appRole':: d.obj(help=''),
      appRole: {
        '#withAllowedMemberTypes':: d.fn(help='"Specifies whether this app role definition can be assigned to users and groups by setting to `User`, or to other applications (that are accessing this application in a standalone scenario) by setting to `Application`, or to both"', args=[d.arg(name='allowedMemberTypes', type=d.T.array)]),
        withAllowedMemberTypes(allowedMemberTypes): { allowedMemberTypes: if std.isArray(v=allowedMemberTypes) then allowedMemberTypes else [allowedMemberTypes] },
        '#withAllowedMemberTypesMixin':: d.fn(help='"Specifies whether this app role definition can be assigned to users and groups by setting to `User`, or to other applications (that are accessing this application in a standalone scenario) by setting to `Application`, or to both"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedMemberTypes', type=d.T.array)]),
        withAllowedMemberTypesMixin(allowedMemberTypes): { allowedMemberTypes+: if std.isArray(v=allowedMemberTypes) then allowedMemberTypes else [allowedMemberTypes] },
        '#withDescription':: d.fn(help='"Description of the app role that appears when the role is being assigned and, if the role functions as an application permissions, during the consent experiences"', args=[d.arg(name='description', type=d.T.string)]),
        withDescription(description): { description: description },
        '#withDisplayName':: d.fn(help='"Display name for the app role that appears during app role assignment and in consent experiences"', args=[d.arg(name='displayName', type=d.T.string)]),
        withDisplayName(displayName): { displayName: displayName },
        '#withEnabled':: d.fn(help='"Determines if the app role is enabled"', args=[d.arg(name='enabled', type=d.T.boolean)]),
        withEnabled(enabled): { enabled: enabled },
        '#withId':: d.fn(help='"An ID used to uniquely identify this synchronization sec. The unique identifier of the app role"', args=[d.arg(name='id', type=d.T.string)]),
        withId(id): { id: id },
        '#withValue':: d.fn(help='"The value of the secret. The value that is used for the `roles` claim in ID tokens and OAuth 2.0 access tokens that are authenticating an assigned service or user principal"', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { value: value },
      },
      '#featureTags':: d.obj(help='"Block of features to configure for this application using tags"'),
      featureTags: {
        '#withCustomSingleSignOn':: d.fn(help='"Whether this application represents a custom SAML application for linked service principals"', args=[d.arg(name='customSingleSignOn', type=d.T.boolean)]),
        withCustomSingleSignOn(customSingleSignOn): { customSingleSignOn: customSingleSignOn },
        '#withEnterprise':: d.fn(help='"Whether this application represents an Enterprise Application for linked service principals"', args=[d.arg(name='enterprise', type=d.T.boolean)]),
        withEnterprise(enterprise): { enterprise: enterprise },
        '#withGallery':: d.fn(help='"Whether this application represents a gallery application for linked service principals"', args=[d.arg(name='gallery', type=d.T.boolean)]),
        withGallery(gallery): { gallery: gallery },
        '#withHide':: d.fn(help='"Whether this application is invisible to users in My Apps and Office 365 Launcher"', args=[d.arg(name='hide', type=d.T.boolean)]),
        withHide(hide): { hide: hide },
      },
      '#optionalClaims':: d.obj(help=''),
      optionalClaims: {
        '#accessToken':: d.obj(help=''),
        accessToken: {
          '#withAdditionalProperties':: d.fn(help='"List of additional properties of the claim. If a property exists in this list, it modifies the behaviour of the optional claim"', args=[d.arg(name='additionalProperties', type=d.T.array)]),
          withAdditionalProperties(additionalProperties): { additionalProperties: if std.isArray(v=additionalProperties) then additionalProperties else [additionalProperties] },
          '#withAdditionalPropertiesMixin':: d.fn(help='"List of additional properties of the claim. If a property exists in this list, it modifies the behaviour of the optional claim"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalProperties', type=d.T.array)]),
          withAdditionalPropertiesMixin(additionalProperties): { additionalProperties+: if std.isArray(v=additionalProperties) then additionalProperties else [additionalProperties] },
          '#withEssential':: d.fn(help='"Whether the claim specified by the client is necessary to ensure a smooth authorization experience"', args=[d.arg(name='essential', type=d.T.boolean)]),
          withEssential(essential): { essential: essential },
          '#withName':: d.fn(help='"The name of the optional claim"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withSource':: d.fn(help='"The source of the claim. If `source` is absent, the claim is a predefined optional claim. If `source` is `user`, the value of `name` is the extension property from the user object"', args=[d.arg(name='source', type=d.T.string)]),
          withSource(source): { source: source },
        },
        '#idToken':: d.obj(help=''),
        idToken: {
          '#withAdditionalProperties':: d.fn(help='"List of additional properties of the claim. If a property exists in this list, it modifies the behaviour of the optional claim"', args=[d.arg(name='additionalProperties', type=d.T.array)]),
          withAdditionalProperties(additionalProperties): { additionalProperties: if std.isArray(v=additionalProperties) then additionalProperties else [additionalProperties] },
          '#withAdditionalPropertiesMixin':: d.fn(help='"List of additional properties of the claim. If a property exists in this list, it modifies the behaviour of the optional claim"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalProperties', type=d.T.array)]),
          withAdditionalPropertiesMixin(additionalProperties): { additionalProperties+: if std.isArray(v=additionalProperties) then additionalProperties else [additionalProperties] },
          '#withEssential':: d.fn(help='"Whether the claim specified by the client is necessary to ensure a smooth authorization experience"', args=[d.arg(name='essential', type=d.T.boolean)]),
          withEssential(essential): { essential: essential },
          '#withName':: d.fn(help='"The name of the optional claim"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withSource':: d.fn(help='"The source of the claim. If `source` is absent, the claim is a predefined optional claim. If `source` is `user`, the value of `name` is the extension property from the user object"', args=[d.arg(name='source', type=d.T.string)]),
          withSource(source): { source: source },
        },
        '#saml2Token':: d.obj(help=''),
        saml2Token: {
          '#withAdditionalProperties':: d.fn(help='"List of additional properties of the claim. If a property exists in this list, it modifies the behaviour of the optional claim"', args=[d.arg(name='additionalProperties', type=d.T.array)]),
          withAdditionalProperties(additionalProperties): { additionalProperties: if std.isArray(v=additionalProperties) then additionalProperties else [additionalProperties] },
          '#withAdditionalPropertiesMixin':: d.fn(help='"List of additional properties of the claim. If a property exists in this list, it modifies the behaviour of the optional claim"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalProperties', type=d.T.array)]),
          withAdditionalPropertiesMixin(additionalProperties): { additionalProperties+: if std.isArray(v=additionalProperties) then additionalProperties else [additionalProperties] },
          '#withEssential':: d.fn(help='"Whether the claim specified by the client is necessary to ensure a smooth authorization experience"', args=[d.arg(name='essential', type=d.T.boolean)]),
          withEssential(essential): { essential: essential },
          '#withName':: d.fn(help='"The name of the optional claim"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withSource':: d.fn(help='"The source of the claim. If `source` is absent, the claim is a predefined optional claim. If `source` is `user`, the value of `name` is the extension property from the user object"', args=[d.arg(name='source', type=d.T.string)]),
          withSource(source): { source: source },
        },
        '#withAccessToken':: d.fn(help='', args=[d.arg(name='accessToken', type=d.T.array)]),
        withAccessToken(accessToken): { accessToken: if std.isArray(v=accessToken) then accessToken else [accessToken] },
        '#withAccessTokenMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='accessToken', type=d.T.array)]),
        withAccessTokenMixin(accessToken): { accessToken+: if std.isArray(v=accessToken) then accessToken else [accessToken] },
        '#withIdToken':: d.fn(help='', args=[d.arg(name='idToken', type=d.T.array)]),
        withIdToken(idToken): { idToken: if std.isArray(v=idToken) then idToken else [idToken] },
        '#withIdTokenMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='idToken', type=d.T.array)]),
        withIdTokenMixin(idToken): { idToken+: if std.isArray(v=idToken) then idToken else [idToken] },
        '#withSaml2Token':: d.fn(help='', args=[d.arg(name='saml2Token', type=d.T.array)]),
        withSaml2Token(saml2Token): { saml2Token: if std.isArray(v=saml2Token) then saml2Token else [saml2Token] },
        '#withSaml2TokenMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='saml2Token', type=d.T.array)]),
        withSaml2TokenMixin(saml2Token): { saml2Token+: if std.isArray(v=saml2Token) then saml2Token else [saml2Token] },
      },
      '#publicClient':: d.obj(help=''),
      publicClient: {
        '#withRedirectUris':: d.fn(help='"The URLs where user tokens are sent for sign-in, or the redirect URIs where OAuth 2.0 authorization codes and access tokens are sent"', args=[d.arg(name='redirectUris', type=d.T.array)]),
        withRedirectUris(redirectUris): { redirectUris: if std.isArray(v=redirectUris) then redirectUris else [redirectUris] },
        '#withRedirectUrisMixin':: d.fn(help='"The URLs where user tokens are sent for sign-in, or the redirect URIs where OAuth 2.0 authorization codes and access tokens are sent"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='redirectUris', type=d.T.array)]),
        withRedirectUrisMixin(redirectUris): { redirectUris+: if std.isArray(v=redirectUris) then redirectUris else [redirectUris] },
      },
      '#requiredResourceAccess':: d.obj(help=''),
      requiredResourceAccess: {
        '#resourceAccess':: d.obj(help=''),
        resourceAccess: {
          '#withId':: d.fn(help='"An ID used to uniquely identify this synchronization sec."', args=[d.arg(name='id', type=d.T.string)]),
          withId(id): { id: id },
          '#withType':: d.fn(help='', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#withResourceAccess':: d.fn(help='', args=[d.arg(name='resourceAccess', type=d.T.array)]),
        withResourceAccess(resourceAccess): { resourceAccess: if std.isArray(v=resourceAccess) then resourceAccess else [resourceAccess] },
        '#withResourceAccessMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='resourceAccess', type=d.T.array)]),
        withResourceAccessMixin(resourceAccess): { resourceAccess+: if std.isArray(v=resourceAccess) then resourceAccess else [resourceAccess] },
        '#withResourceAppId':: d.fn(help='"An ID used to uniquely identify this synchronization sec."', args=[d.arg(name='resourceAppId', type=d.T.string)]),
        withResourceAppId(resourceAppId): { resourceAppId: resourceAppId },
      },
      '#singlePageApplication':: d.obj(help=''),
      singlePageApplication: {
        '#withRedirectUris':: d.fn(help='"The URLs where user tokens are sent for sign-in, or the redirect URIs where OAuth 2.0 authorization codes and access tokens are sent"', args=[d.arg(name='redirectUris', type=d.T.array)]),
        withRedirectUris(redirectUris): { redirectUris: if std.isArray(v=redirectUris) then redirectUris else [redirectUris] },
        '#withRedirectUrisMixin':: d.fn(help='"The URLs where user tokens are sent for sign-in, or the redirect URIs where OAuth 2.0 authorization codes and access tokens are sent"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='redirectUris', type=d.T.array)]),
        withRedirectUrisMixin(redirectUris): { redirectUris+: if std.isArray(v=redirectUris) then redirectUris else [redirectUris] },
      },
      '#web':: d.obj(help=''),
      web: {
        '#implicitGrant':: d.obj(help=''),
        implicitGrant: {
          '#withAccessTokenIssuanceEnabled':: d.fn(help='"Whether this web application can request an access token using OAuth 2.0 implicit flow"', args=[d.arg(name='accessTokenIssuanceEnabled', type=d.T.boolean)]),
          withAccessTokenIssuanceEnabled(accessTokenIssuanceEnabled): { accessTokenIssuanceEnabled: accessTokenIssuanceEnabled },
          '#withIdTokenIssuanceEnabled':: d.fn(help='"Whether this web application can request an ID token using OAuth 2.0 implicit flow"', args=[d.arg(name='idTokenIssuanceEnabled', type=d.T.boolean)]),
          withIdTokenIssuanceEnabled(idTokenIssuanceEnabled): { idTokenIssuanceEnabled: idTokenIssuanceEnabled },
        },
        '#withHomepageUrl':: d.fn(help='"Home page or landing page of the application"', args=[d.arg(name='homepageUrl', type=d.T.string)]),
        withHomepageUrl(homepageUrl): { homepageUrl: homepageUrl },
        '#withImplicitGrant':: d.fn(help='', args=[d.arg(name='implicitGrant', type=d.T.array)]),
        withImplicitGrant(implicitGrant): { implicitGrant: if std.isArray(v=implicitGrant) then implicitGrant else [implicitGrant] },
        '#withImplicitGrantMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='implicitGrant', type=d.T.array)]),
        withImplicitGrantMixin(implicitGrant): { implicitGrant+: if std.isArray(v=implicitGrant) then implicitGrant else [implicitGrant] },
        '#withLogoutUrl':: d.fn(help="\"The URL that will be used by Microsoft's authorization service to sign out a user using front-channel, back-channel or SAML logout protocols\"", args=[d.arg(name='logoutUrl', type=d.T.string)]),
        withLogoutUrl(logoutUrl): { logoutUrl: logoutUrl },
        '#withRedirectUris':: d.fn(help='"The URLs where user tokens are sent for sign-in, or the redirect URIs where OAuth 2.0 authorization codes and access tokens are sent"', args=[d.arg(name='redirectUris', type=d.T.array)]),
        withRedirectUris(redirectUris): { redirectUris: if std.isArray(v=redirectUris) then redirectUris else [redirectUris] },
        '#withRedirectUrisMixin':: d.fn(help='"The URLs where user tokens are sent for sign-in, or the redirect URIs where OAuth 2.0 authorization codes and access tokens are sent"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='redirectUris', type=d.T.array)]),
        withRedirectUrisMixin(redirectUris): { redirectUris+: if std.isArray(v=redirectUris) then redirectUris else [redirectUris] },
      },
      '#withApi':: d.fn(help='', args=[d.arg(name='api', type=d.T.array)]),
      withApi(api): { spec+: { forProvider+: { api: if std.isArray(v=api) then api else [api] } } },
      '#withApiMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='api', type=d.T.array)]),
      withApiMixin(api): { spec+: { forProvider+: { api+: if std.isArray(v=api) then api else [api] } } },
      '#withAppRole':: d.fn(help='', args=[d.arg(name='appRole', type=d.T.array)]),
      withAppRole(appRole): { spec+: { forProvider+: { appRole: if std.isArray(v=appRole) then appRole else [appRole] } } },
      '#withAppRoleMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='appRole', type=d.T.array)]),
      withAppRoleMixin(appRole): { spec+: { forProvider+: { appRole+: if std.isArray(v=appRole) then appRole else [appRole] } } },
      '#withDescription':: d.fn(help='"Description of the application as shown to end users"', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withDeviceOnlyAuthEnabled':: d.fn(help='"Specifies whether this application supports device authentication without a user."', args=[d.arg(name='deviceOnlyAuthEnabled', type=d.T.boolean)]),
      withDeviceOnlyAuthEnabled(deviceOnlyAuthEnabled): { spec+: { forProvider+: { deviceOnlyAuthEnabled: deviceOnlyAuthEnabled } } },
      '#withDisplayName':: d.fn(help='"The display name for the application"', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { forProvider+: { displayName: displayName } } },
      '#withFallbackPublicClientEnabled':: d.fn(help="\"Specifies whether the application is a public client. Appropriate for apps using token grant flows that don't use a redirect URI\"", args=[d.arg(name='fallbackPublicClientEnabled', type=d.T.boolean)]),
      withFallbackPublicClientEnabled(fallbackPublicClientEnabled): { spec+: { forProvider+: { fallbackPublicClientEnabled: fallbackPublicClientEnabled } } },
      '#withFeatureTags':: d.fn(help='"Block of features to configure for this application using tags"', args=[d.arg(name='featureTags', type=d.T.array)]),
      withFeatureTags(featureTags): { spec+: { forProvider+: { featureTags: if std.isArray(v=featureTags) then featureTags else [featureTags] } } },
      '#withFeatureTagsMixin':: d.fn(help='"Block of features to configure for this application using tags"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='featureTags', type=d.T.array)]),
      withFeatureTagsMixin(featureTags): { spec+: { forProvider+: { featureTags+: if std.isArray(v=featureTags) then featureTags else [featureTags] } } },
      '#withGroupMembershipClaims':: d.fn(help='"Configures the `groups` claim issued in a user or OAuth 2.0 access token that the app expects"', args=[d.arg(name='groupMembershipClaims', type=d.T.array)]),
      withGroupMembershipClaims(groupMembershipClaims): { spec+: { forProvider+: { groupMembershipClaims: if std.isArray(v=groupMembershipClaims) then groupMembershipClaims else [groupMembershipClaims] } } },
      '#withGroupMembershipClaimsMixin':: d.fn(help='"Configures the `groups` claim issued in a user or OAuth 2.0 access token that the app expects"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='groupMembershipClaims', type=d.T.array)]),
      withGroupMembershipClaimsMixin(groupMembershipClaims): { spec+: { forProvider+: { groupMembershipClaims+: if std.isArray(v=groupMembershipClaims) then groupMembershipClaims else [groupMembershipClaims] } } },
      '#withIdentifierUris':: d.fn(help='"The user-defined URI(s) that uniquely identify an application within its Azure AD tenant, or within a verified custom domain if the application is multi-tenant"', args=[d.arg(name='identifierUris', type=d.T.array)]),
      withIdentifierUris(identifierUris): { spec+: { forProvider+: { identifierUris: if std.isArray(v=identifierUris) then identifierUris else [identifierUris] } } },
      '#withIdentifierUrisMixin':: d.fn(help='"The user-defined URI(s) that uniquely identify an application within its Azure AD tenant, or within a verified custom domain if the application is multi-tenant"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='identifierUris', type=d.T.array)]),
      withIdentifierUrisMixin(identifierUris): { spec+: { forProvider+: { identifierUris+: if std.isArray(v=identifierUris) then identifierUris else [identifierUris] } } },
      '#withLogoImage':: d.fn(help='"Base64 encoded logo image in gif, png or jpeg format"', args=[d.arg(name='logoImage', type=d.T.string)]),
      withLogoImage(logoImage): { spec+: { forProvider+: { logoImage: logoImage } } },
      '#withMarketingUrl':: d.fn(help="\"URL of the application's marketing page\"", args=[d.arg(name='marketingUrl', type=d.T.string)]),
      withMarketingUrl(marketingUrl): { spec+: { forProvider+: { marketingUrl: marketingUrl } } },
      '#withNotes':: d.fn(help='"User-specified notes relevant for the management of the application"', args=[d.arg(name='notes', type=d.T.string)]),
      withNotes(notes): { spec+: { forProvider+: { notes: notes } } },
      '#withOauth2PostResponseRequired':: d.fn(help='"Specifies whether, as part of OAuth 2.0 token requests, Azure AD allows POST requests, as opposed to GET requests."', args=[d.arg(name='oauth2PostResponseRequired', type=d.T.boolean)]),
      withOauth2PostResponseRequired(oauth2PostResponseRequired): { spec+: { forProvider+: { oauth2PostResponseRequired: oauth2PostResponseRequired } } },
      '#withOptionalClaims':: d.fn(help='', args=[d.arg(name='optionalClaims', type=d.T.array)]),
      withOptionalClaims(optionalClaims): { spec+: { forProvider+: { optionalClaims: if std.isArray(v=optionalClaims) then optionalClaims else [optionalClaims] } } },
      '#withOptionalClaimsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='optionalClaims', type=d.T.array)]),
      withOptionalClaimsMixin(optionalClaims): { spec+: { forProvider+: { optionalClaims+: if std.isArray(v=optionalClaims) then optionalClaims else [optionalClaims] } } },
      '#withOwners':: d.fn(help='"A list of object IDs of principals that will be granted ownership of the application"', args=[d.arg(name='owners', type=d.T.array)]),
      withOwners(owners): { spec+: { forProvider+: { owners: if std.isArray(v=owners) then owners else [owners] } } },
      '#withOwnersMixin':: d.fn(help='"A list of object IDs of principals that will be granted ownership of the application"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='owners', type=d.T.array)]),
      withOwnersMixin(owners): { spec+: { forProvider+: { owners+: if std.isArray(v=owners) then owners else [owners] } } },
      '#withPreventDuplicateNames':: d.fn(help='"If `true`, will return an error if an existing application is found with the same name"', args=[d.arg(name='preventDuplicateNames', type=d.T.boolean)]),
      withPreventDuplicateNames(preventDuplicateNames): { spec+: { forProvider+: { preventDuplicateNames: preventDuplicateNames } } },
      '#withPrivacyStatementUrl':: d.fn(help="\"URL of the application's privacy statement\"", args=[d.arg(name='privacyStatementUrl', type=d.T.string)]),
      withPrivacyStatementUrl(privacyStatementUrl): { spec+: { forProvider+: { privacyStatementUrl: privacyStatementUrl } } },
      '#withPublicClient':: d.fn(help='', args=[d.arg(name='publicClient', type=d.T.array)]),
      withPublicClient(publicClient): { spec+: { forProvider+: { publicClient: if std.isArray(v=publicClient) then publicClient else [publicClient] } } },
      '#withPublicClientMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='publicClient', type=d.T.array)]),
      withPublicClientMixin(publicClient): { spec+: { forProvider+: { publicClient+: if std.isArray(v=publicClient) then publicClient else [publicClient] } } },
      '#withRequiredResourceAccess':: d.fn(help='', args=[d.arg(name='requiredResourceAccess', type=d.T.array)]),
      withRequiredResourceAccess(requiredResourceAccess): { spec+: { forProvider+: { requiredResourceAccess: if std.isArray(v=requiredResourceAccess) then requiredResourceAccess else [requiredResourceAccess] } } },
      '#withRequiredResourceAccessMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='requiredResourceAccess', type=d.T.array)]),
      withRequiredResourceAccessMixin(requiredResourceAccess): { spec+: { forProvider+: { requiredResourceAccess+: if std.isArray(v=requiredResourceAccess) then requiredResourceAccess else [requiredResourceAccess] } } },
      '#withSignInAudience':: d.fn(help='"The Microsoft account types that are supported for the current application"', args=[d.arg(name='signInAudience', type=d.T.string)]),
      withSignInAudience(signInAudience): { spec+: { forProvider+: { signInAudience: signInAudience } } },
      '#withSinglePageApplication':: d.fn(help='', args=[d.arg(name='singlePageApplication', type=d.T.array)]),
      withSinglePageApplication(singlePageApplication): { spec+: { forProvider+: { singlePageApplication: if std.isArray(v=singlePageApplication) then singlePageApplication else [singlePageApplication] } } },
      '#withSinglePageApplicationMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='singlePageApplication', type=d.T.array)]),
      withSinglePageApplicationMixin(singlePageApplication): { spec+: { forProvider+: { singlePageApplication+: if std.isArray(v=singlePageApplication) then singlePageApplication else [singlePageApplication] } } },
      '#withSupportUrl':: d.fn(help="\"URL of the application's support page\"", args=[d.arg(name='supportUrl', type=d.T.string)]),
      withSupportUrl(supportUrl): { spec+: { forProvider+: { supportUrl: supportUrl } } },
      '#withTags':: d.fn(help='"A set of tags to apply to the application"', args=[d.arg(name='tags', type=d.T.array)]),
      withTags(tags): { spec+: { forProvider+: { tags: if std.isArray(v=tags) then tags else [tags] } } },
      '#withTagsMixin':: d.fn(help='"A set of tags to apply to the application"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.array)]),
      withTagsMixin(tags): { spec+: { forProvider+: { tags+: if std.isArray(v=tags) then tags else [tags] } } },
      '#withTemplateId':: d.fn(help='"An ID used to uniquely identify this synchronization sec. Unique ID of the application template from which this application is created"', args=[d.arg(name='templateId', type=d.T.string)]),
      withTemplateId(templateId): { spec+: { forProvider+: { templateId: templateId } } },
      '#withTermsOfServiceUrl':: d.fn(help="\"URL of the application's terms of service statement\"", args=[d.arg(name='termsOfServiceUrl', type=d.T.string)]),
      withTermsOfServiceUrl(termsOfServiceUrl): { spec+: { forProvider+: { termsOfServiceUrl: termsOfServiceUrl } } },
      '#withWeb':: d.fn(help='', args=[d.arg(name='web', type=d.T.array)]),
      withWeb(web): { spec+: { forProvider+: { web: if std.isArray(v=web) then web else [web] } } },
      '#withWebMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='web', type=d.T.array)]),
      withWebMixin(web): { spec+: { forProvider+: { web+: if std.isArray(v=web) then web else [web] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
