{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='function', url='', help='"Function is the Schema for the Functions API. A Cloud Function that contains user computation executed in response to an event."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Function', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'cloudfunctions2.gcp.upbound.io/v1beta1',
    kind: 'Function',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"FunctionSpec defines the desired state of Function"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#buildConfig':: d.obj(help='"Describes the Build step of the function that builds a container from the given source. Structure is documented below."'),
      buildConfig: {
        '#source':: d.obj(help='"The location of the function source code. Structure is documented below."'),
        source: {
          '#repoSource':: d.obj(help='"If provided, get the source from this location in a Cloud Source Repository. Structure is documented below."'),
          repoSource: {
            '#withBranchName':: d.fn(help='"Regex matching branches to build."', args=[d.arg(name='branchName', type=d.T.string)]),
            withBranchName(branchName): { branchName: branchName },
            '#withCommitSha':: d.fn(help='"Regex matching tags to build."', args=[d.arg(name='commitSha', type=d.T.string)]),
            withCommitSha(commitSha): { commitSha: commitSha },
            '#withDir':: d.fn(help='"Directory, relative to the source root, in which to run the build."', args=[d.arg(name='dir', type=d.T.string)]),
            withDir(dir): { dir: dir },
            '#withInvertRegex':: d.fn(help='"Only trigger a build if the revision regex does NOT match the revision regex."', args=[d.arg(name='invertRegex', type=d.T.boolean)]),
            withInvertRegex(invertRegex): { invertRegex: invertRegex },
            '#withProjectId':: d.fn(help="\"Project identifier (preferrably project number but can also be the project ID) of the project that contains the secret. If not set, it will be populated with the function's project assuming that the secret exists in the same project as of the function.\"", args=[d.arg(name='projectId', type=d.T.string)]),
            withProjectId(projectId): { projectId: projectId },
            '#withRepoName':: d.fn(help='"Name of the Cloud Source Repository."', args=[d.arg(name='repoName', type=d.T.string)]),
            withRepoName(repoName): { repoName: repoName },
            '#withTagName':: d.fn(help='"Regex matching tags to build."', args=[d.arg(name='tagName', type=d.T.string)]),
            withTagName(tagName): { tagName: tagName },
          },
          '#storageSource':: d.obj(help='"If provided, get the source from this location in Google Cloud Storage. Structure is documented below."'),
          storageSource: {
            '#bucketRef':: d.obj(help='"Reference to a Bucket in storage to populate bucket."'),
            bucketRef: {
              '#policy':: d.obj(help='"Policies for referencing."'),
              policy: {
                '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
                withResolution(resolution): { bucketRef+: { policy+: { resolution: resolution } } },
                '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
                withResolve(resolve): { bucketRef+: { policy+: { resolve: resolve } } },
              },
              '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { bucketRef+: { name: name } },
            },
            '#bucketSelector':: d.obj(help='"Selector for a Bucket in storage to populate bucket."'),
            bucketSelector: {
              '#policy':: d.obj(help='"Policies for selection."'),
              policy: {
                '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
                withResolution(resolution): { bucketSelector+: { policy+: { resolution: resolution } } },
                '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
                withResolve(resolve): { bucketSelector+: { policy+: { resolve: resolve } } },
              },
              '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
              withMatchControllerRef(matchControllerRef): { bucketSelector+: { matchControllerRef: matchControllerRef } },
              '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabels(matchLabels): { bucketSelector+: { matchLabels: matchLabels } },
              '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabelsMixin(matchLabels): { bucketSelector+: { matchLabels+: matchLabels } },
            },
            '#objectRef':: d.obj(help='"Reference to a BucketObject in storage to populate object."'),
            objectRef: {
              '#policy':: d.obj(help='"Policies for referencing."'),
              policy: {
                '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
                withResolution(resolution): { objectRef+: { policy+: { resolution: resolution } } },
                '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
                withResolve(resolve): { objectRef+: { policy+: { resolve: resolve } } },
              },
              '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { objectRef+: { name: name } },
            },
            '#objectSelector':: d.obj(help='"Selector for a BucketObject in storage to populate object."'),
            objectSelector: {
              '#policy':: d.obj(help='"Policies for selection."'),
              policy: {
                '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
                withResolution(resolution): { objectSelector+: { policy+: { resolution: resolution } } },
                '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
                withResolve(resolve): { objectSelector+: { policy+: { resolve: resolve } } },
              },
              '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
              withMatchControllerRef(matchControllerRef): { objectSelector+: { matchControllerRef: matchControllerRef } },
              '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabels(matchLabels): { objectSelector+: { matchLabels: matchLabels } },
              '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabelsMixin(matchLabels): { objectSelector+: { matchLabels+: matchLabels } },
            },
            '#withBucket':: d.fn(help='"Google Cloud Storage bucket containing the source"', args=[d.arg(name='bucket', type=d.T.string)]),
            withBucket(bucket): { bucket: bucket },
            '#withGeneration':: d.fn(help='"Google Cloud Storage generation for the object. If the generation is omitted, the latest generation will be used."', args=[d.arg(name='generation', type=d.T.number)]),
            withGeneration(generation): { generation: generation },
            '#withObject':: d.fn(help='"Google Cloud Storage object containing the source."', args=[d.arg(name='object', type=d.T.string)]),
            withObject(object): { object: object },
          },
          '#withRepoSource':: d.fn(help='"If provided, get the source from this location in a Cloud Source Repository. Structure is documented below."', args=[d.arg(name='repoSource', type=d.T.array)]),
          withRepoSource(repoSource): { repoSource: if std.isArray(v=repoSource) then repoSource else [repoSource] },
          '#withRepoSourceMixin':: d.fn(help='"If provided, get the source from this location in a Cloud Source Repository. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='repoSource', type=d.T.array)]),
          withRepoSourceMixin(repoSource): { repoSource+: if std.isArray(v=repoSource) then repoSource else [repoSource] },
          '#withStorageSource':: d.fn(help='"If provided, get the source from this location in Google Cloud Storage. Structure is documented below."', args=[d.arg(name='storageSource', type=d.T.array)]),
          withStorageSource(storageSource): { storageSource: if std.isArray(v=storageSource) then storageSource else [storageSource] },
          '#withStorageSourceMixin':: d.fn(help='"If provided, get the source from this location in Google Cloud Storage. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='storageSource', type=d.T.array)]),
          withStorageSourceMixin(storageSource): { storageSource+: if std.isArray(v=storageSource) then storageSource else [storageSource] },
        },
        '#withDockerRepository':: d.fn(help='"User managed repository created in Artifact Registry optionally with a customer managed encryption key."', args=[d.arg(name='dockerRepository', type=d.T.string)]),
        withDockerRepository(dockerRepository): { dockerRepository: dockerRepository },
        '#withEntryPoint':: d.fn(help='"The name of the function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified. For backward compatibility, if function with given name is not found, then the system will try to use function named \\"function\\". For Node.js this is name of a function exported by the module specified in source_location."', args=[d.arg(name='entryPoint', type=d.T.string)]),
        withEntryPoint(entryPoint): { entryPoint: entryPoint },
        '#withEnvironmentVariables':: d.fn(help='"User-provided build-time environment variables for the function."', args=[d.arg(name='environmentVariables', type=d.T.object)]),
        withEnvironmentVariables(environmentVariables): { environmentVariables: environmentVariables },
        '#withEnvironmentVariablesMixin':: d.fn(help='"User-provided build-time environment variables for the function."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='environmentVariables', type=d.T.object)]),
        withEnvironmentVariablesMixin(environmentVariables): { environmentVariables+: environmentVariables },
        '#withRuntime':: d.fn(help='"The runtime in which to run the function. Required when deploying a new function, optional when updating an existing function."', args=[d.arg(name='runtime', type=d.T.string)]),
        withRuntime(runtime): { runtime: runtime },
        '#withSource':: d.fn(help='"The location of the function source code. Structure is documented below."', args=[d.arg(name='source', type=d.T.array)]),
        withSource(source): { source: if std.isArray(v=source) then source else [source] },
        '#withSourceMixin':: d.fn(help='"The location of the function source code. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='source', type=d.T.array)]),
        withSourceMixin(source): { source+: if std.isArray(v=source) then source else [source] },
        '#withWorkerPool':: d.fn(help='"Name of the Cloud Build Custom Worker Pool that should be used to build the function."', args=[d.arg(name='workerPool', type=d.T.string)]),
        withWorkerPool(workerPool): { workerPool: workerPool },
        '#workerPoolRef':: d.obj(help='"Reference to a WorkerPool in cloudbuild to populate workerPool."'),
        workerPoolRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { workerPoolRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { workerPoolRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { workerPoolRef+: { name: name } },
        },
        '#workerPoolSelector':: d.obj(help='"Selector for a WorkerPool in cloudbuild to populate workerPool."'),
        workerPoolSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { workerPoolSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { workerPoolSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { workerPoolSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { workerPoolSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { workerPoolSelector+: { matchLabels+: matchLabels } },
        },
      },
      '#eventTrigger':: d.obj(help='"An Eventarc trigger managed by Google Cloud Functions that fires events in response to a condition in another service. Structure is documented below."'),
      eventTrigger: {
        '#eventFilters':: d.obj(help='"Criteria used to filter events. Structure is documented below."'),
        eventFilters: {
          '#valueRef':: d.obj(help='"Reference to a Bucket in storage to populate value."'),
          valueRef: {
            '#policy':: d.obj(help='"Policies for referencing."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { valueRef+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { valueRef+: { policy+: { resolve: resolve } } },
            },
            '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { valueRef+: { name: name } },
          },
          '#valueSelector':: d.obj(help='"Selector for a Bucket in storage to populate value."'),
          valueSelector: {
            '#policy':: d.obj(help='"Policies for selection."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { valueSelector+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { valueSelector+: { policy+: { resolve: resolve } } },
            },
            '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
            withMatchControllerRef(matchControllerRef): { valueSelector+: { matchControllerRef: matchControllerRef } },
            '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabels(matchLabels): { valueSelector+: { matchLabels: matchLabels } },
            '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabelsMixin(matchLabels): { valueSelector+: { matchLabels+: matchLabels } },
          },
          '#withAttribute':: d.fn(help="\"'Required. The name of a CloudEvents attribute. Currently, only a subset of attributes are supported for filtering. Use the gcloud eventarc providers describe command to learn more about events and their attributes. Do not filter for the 'type' attribute here, as this is already achieved by the resource's event_type attribute.\"", args=[d.arg(name='attribute', type=d.T.string)]),
          withAttribute(attribute): { attribute: attribute },
          '#withOperator':: d.fn(help="\"Optional. The operator used for matching the events with the value of the filter. If not specified, only events that have an exact key-value pair specified in the filter are matched. The only allowed value is match-path-pattern. See documentation on path patterns here'\"", args=[d.arg(name='operator', type=d.T.string)]),
          withOperator(operator): { operator: operator },
          '#withValue':: d.fn(help='"Required. The value for the attribute. If the operator field is set as match-path-pattern, this value can be a path pattern instead of an exact value."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#pubsubTopicRef':: d.obj(help='"Reference to a Topic in pubsub to populate pubsubTopic."'),
        pubsubTopicRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { pubsubTopicRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { pubsubTopicRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { pubsubTopicRef+: { name: name } },
        },
        '#pubsubTopicSelector':: d.obj(help='"Selector for a Topic in pubsub to populate pubsubTopic."'),
        pubsubTopicSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { pubsubTopicSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { pubsubTopicSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { pubsubTopicSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { pubsubTopicSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { pubsubTopicSelector+: { matchLabels+: matchLabels } },
        },
        '#serviceAccountEmailRef':: d.obj(help='"Reference to a ServiceAccount in cloudplatform to populate serviceAccountEmail."'),
        serviceAccountEmailRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { serviceAccountEmailRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { serviceAccountEmailRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { serviceAccountEmailRef+: { name: name } },
        },
        '#serviceAccountEmailSelector':: d.obj(help='"Selector for a ServiceAccount in cloudplatform to populate serviceAccountEmail."'),
        serviceAccountEmailSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { serviceAccountEmailSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { serviceAccountEmailSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { serviceAccountEmailSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { serviceAccountEmailSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { serviceAccountEmailSelector+: { matchLabels+: matchLabels } },
        },
        '#withEventFilters':: d.fn(help='"Criteria used to filter events. Structure is documented below."', args=[d.arg(name='eventFilters', type=d.T.array)]),
        withEventFilters(eventFilters): { eventFilters: if std.isArray(v=eventFilters) then eventFilters else [eventFilters] },
        '#withEventFiltersMixin':: d.fn(help='"Criteria used to filter events. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='eventFilters', type=d.T.array)]),
        withEventFiltersMixin(eventFilters): { eventFilters+: if std.isArray(v=eventFilters) then eventFilters else [eventFilters] },
        '#withEventType':: d.fn(help='"Required. The type of event to observe."', args=[d.arg(name='eventType', type=d.T.string)]),
        withEventType(eventType): { eventType: eventType },
        '#withPubsubTopic':: d.fn(help='"The name of a Pub/Sub topic in the same project that will be used as the transport topic for the event delivery."', args=[d.arg(name='pubsubTopic', type=d.T.string)]),
        withPubsubTopic(pubsubTopic): { pubsubTopic: pubsubTopic },
        '#withRetryPolicy':: d.fn(help="\"Describes the retry policy in case of function's execution failure. Retried execution is charged as any other execution. Possible values are RETRY_POLICY_UNSPECIFIED, RETRY_POLICY_DO_NOT_RETRY, and RETRY_POLICY_RETRY.\"", args=[d.arg(name='retryPolicy', type=d.T.string)]),
        withRetryPolicy(retryPolicy): { retryPolicy: retryPolicy },
        '#withServiceAccountEmail':: d.fn(help='"The email of the service account for this function."', args=[d.arg(name='serviceAccountEmail', type=d.T.string)]),
        withServiceAccountEmail(serviceAccountEmail): { serviceAccountEmail: serviceAccountEmail },
        '#withTriggerRegion':: d.fn(help='"The region that the trigger will be in. The trigger will only receive events originating in this region. It can be the same region as the function, a different region or multi-region, or the global region. If not provided, defaults to the same region as the function."', args=[d.arg(name='triggerRegion', type=d.T.string)]),
        withTriggerRegion(triggerRegion): { triggerRegion: triggerRegion },
      },
      '#serviceConfig':: d.obj(help='"Describes the Service being deployed. Structure is documented below."'),
      serviceConfig: {
        '#secretEnvironmentVariables':: d.obj(help='"Secret environment variables configuration. Structure is documented below."'),
        secretEnvironmentVariables: {
          '#secretRef':: d.obj(help='"Reference to a Secret in secretmanager to populate secret."'),
          secretRef: {
            '#policy':: d.obj(help='"Policies for referencing."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { secretRef+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { secretRef+: { policy+: { resolve: resolve } } },
            },
            '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { secretRef+: { name: name } },
          },
          '#secretSelector':: d.obj(help='"Selector for a Secret in secretmanager to populate secret."'),
          secretSelector: {
            '#policy':: d.obj(help='"Policies for selection."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { secretSelector+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { secretSelector+: { policy+: { resolve: resolve } } },
            },
            '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
            withMatchControllerRef(matchControllerRef): { secretSelector+: { matchControllerRef: matchControllerRef } },
            '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabels(matchLabels): { secretSelector+: { matchLabels: matchLabels } },
            '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabelsMixin(matchLabels): { secretSelector+: { matchLabels+: matchLabels } },
          },
          '#withKey':: d.fn(help='"Name of the environment variable."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withProjectId':: d.fn(help="\"Project identifier (preferrably project number but can also be the project ID) of the project that contains the secret. If not set, it will be populated with the function's project assuming that the secret exists in the same project as of the function.\"", args=[d.arg(name='projectId', type=d.T.string)]),
          withProjectId(projectId): { projectId: projectId },
          '#withSecret':: d.fn(help='"Name of the secret in secret manager (not the full resource name)."', args=[d.arg(name='secret', type=d.T.string)]),
          withSecret(secret): { secret: secret },
          '#withVersion':: d.fn(help="\"Version of the secret (version number or the string 'latest'). It is preferable to use latest version with secret volumes as secret value changes are reflected immediately.\"", args=[d.arg(name='version', type=d.T.string)]),
          withVersion(version): { version: version },
        },
        '#secretVolumes':: d.obj(help='"Secret volumes configuration. Structure is documented below."'),
        secretVolumes: {
          '#secretRef':: d.obj(help='"Reference to a Secret in secretmanager to populate secret."'),
          secretRef: {
            '#policy':: d.obj(help='"Policies for referencing."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { secretRef+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { secretRef+: { policy+: { resolve: resolve } } },
            },
            '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { secretRef+: { name: name } },
          },
          '#secretSelector':: d.obj(help='"Selector for a Secret in secretmanager to populate secret."'),
          secretSelector: {
            '#policy':: d.obj(help='"Policies for selection."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { secretSelector+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { secretSelector+: { policy+: { resolve: resolve } } },
            },
            '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
            withMatchControllerRef(matchControllerRef): { secretSelector+: { matchControllerRef: matchControllerRef } },
            '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabels(matchLabels): { secretSelector+: { matchLabels: matchLabels } },
            '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabelsMixin(matchLabels): { secretSelector+: { matchLabels+: matchLabels } },
          },
          '#versions':: d.obj(help="\"List of secret versions to mount for this secret. If empty, the latest version of the secret will be made available in a file named after the secret under the mount point.' Structure is documented below.\""),
          versions: {
            '#withPath':: d.fn(help="\"Relative path of the file under the mount path where the secret value for this version will be fetched and made available. For example, setting the mountPath as '/etc/secrets' and path as secret_foo would mount the secret value file at /etc/secrets/secret_foo.\"", args=[d.arg(name='path', type=d.T.string)]),
            withPath(path): { path: path },
            '#withVersion':: d.fn(help="\"Version of the secret (version number or the string 'latest'). It is preferable to use latest version with secret volumes as secret value changes are reflected immediately.\"", args=[d.arg(name='version', type=d.T.string)]),
            withVersion(version): { version: version },
          },
          '#withMountPath':: d.fn(help='"The path within the container to mount the secret volume. For example, setting the mountPath as /etc/secrets would mount the secret value files under the /etc/secrets directory. This directory will also be completely shadowed and unavailable to mount any other secrets. Recommended mount path: /etc/secrets"', args=[d.arg(name='mountPath', type=d.T.string)]),
          withMountPath(mountPath): { mountPath: mountPath },
          '#withProjectId':: d.fn(help="\"Project identifier (preferrably project number but can also be the project ID) of the project that contains the secret. If not set, it will be populated with the function's project assuming that the secret exists in the same project as of the function.\"", args=[d.arg(name='projectId', type=d.T.string)]),
          withProjectId(projectId): { projectId: projectId },
          '#withSecret':: d.fn(help='"Name of the secret in secret manager (not the full resource name)."', args=[d.arg(name='secret', type=d.T.string)]),
          withSecret(secret): { secret: secret },
          '#withVersions':: d.fn(help="\"List of secret versions to mount for this secret. If empty, the latest version of the secret will be made available in a file named after the secret under the mount point.' Structure is documented below.\"", args=[d.arg(name='versions', type=d.T.array)]),
          withVersions(versions): { versions: if std.isArray(v=versions) then versions else [versions] },
          '#withVersionsMixin':: d.fn(help="\"List of secret versions to mount for this secret. If empty, the latest version of the secret will be made available in a file named after the secret under the mount point.' Structure is documented below.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='versions', type=d.T.array)]),
          withVersionsMixin(versions): { versions+: if std.isArray(v=versions) then versions else [versions] },
        },
        '#serviceAccountEmailRef':: d.obj(help='"Reference to a ServiceAccount in cloudplatform to populate serviceAccountEmail."'),
        serviceAccountEmailRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { serviceAccountEmailRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { serviceAccountEmailRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { serviceAccountEmailRef+: { name: name } },
        },
        '#serviceAccountEmailSelector':: d.obj(help='"Selector for a ServiceAccount in cloudplatform to populate serviceAccountEmail."'),
        serviceAccountEmailSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { serviceAccountEmailSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { serviceAccountEmailSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { serviceAccountEmailSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { serviceAccountEmailSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { serviceAccountEmailSelector+: { matchLabels+: matchLabels } },
        },
        '#withAllTrafficOnLatestRevision':: d.fn(help='"Whether 100% of traffic is routed to the latest revision. Defaults to true."', args=[d.arg(name='allTrafficOnLatestRevision', type=d.T.boolean)]),
        withAllTrafficOnLatestRevision(allTrafficOnLatestRevision): { allTrafficOnLatestRevision: allTrafficOnLatestRevision },
        '#withAvailableCpu':: d.fn(help='"The number of CPUs used in a single container instance. Default value is calculated from available memory."', args=[d.arg(name='availableCpu', type=d.T.string)]),
        withAvailableCpu(availableCpu): { availableCpu: availableCpu },
        '#withAvailableMemory':: d.fn(help='"The amount of memory available for a function. Defaults to 256M. Supported units are k, M, G, Mi, Gi. If no unit is supplied the value is interpreted as bytes."', args=[d.arg(name='availableMemory', type=d.T.string)]),
        withAvailableMemory(availableMemory): { availableMemory: availableMemory },
        '#withEnvironmentVariables':: d.fn(help='"Environment variables that shall be available during function execution."', args=[d.arg(name='environmentVariables', type=d.T.object)]),
        withEnvironmentVariables(environmentVariables): { environmentVariables: environmentVariables },
        '#withEnvironmentVariablesMixin':: d.fn(help='"Environment variables that shall be available during function execution."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='environmentVariables', type=d.T.object)]),
        withEnvironmentVariablesMixin(environmentVariables): { environmentVariables+: environmentVariables },
        '#withIngressSettings':: d.fn(help='"Available ingress settings. Defaults to \\"ALLOW_ALL\\" if unspecified. Default value is ALLOW_ALL. Possible values are ALLOW_ALL, ALLOW_INTERNAL_ONLY, and ALLOW_INTERNAL_AND_GCLB."', args=[d.arg(name='ingressSettings', type=d.T.string)]),
        withIngressSettings(ingressSettings): { ingressSettings: ingressSettings },
        '#withMaxInstanceCount':: d.fn(help='"The limit on the maximum number of function instances that may coexist at a given time."', args=[d.arg(name='maxInstanceCount', type=d.T.number)]),
        withMaxInstanceCount(maxInstanceCount): { maxInstanceCount: maxInstanceCount },
        '#withMaxInstanceRequestConcurrency':: d.fn(help='"Sets the maximum number of concurrent requests that each instance can receive. Defaults to 1."', args=[d.arg(name='maxInstanceRequestConcurrency', type=d.T.number)]),
        withMaxInstanceRequestConcurrency(maxInstanceRequestConcurrency): { maxInstanceRequestConcurrency: maxInstanceRequestConcurrency },
        '#withMinInstanceCount':: d.fn(help='"The limit on the minimum number of function instances that may coexist at a given time."', args=[d.arg(name='minInstanceCount', type=d.T.number)]),
        withMinInstanceCount(minInstanceCount): { minInstanceCount: minInstanceCount },
        '#withSecretEnvironmentVariables':: d.fn(help='"Secret environment variables configuration. Structure is documented below."', args=[d.arg(name='secretEnvironmentVariables', type=d.T.array)]),
        withSecretEnvironmentVariables(secretEnvironmentVariables): { secretEnvironmentVariables: if std.isArray(v=secretEnvironmentVariables) then secretEnvironmentVariables else [secretEnvironmentVariables] },
        '#withSecretEnvironmentVariablesMixin':: d.fn(help='"Secret environment variables configuration. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='secretEnvironmentVariables', type=d.T.array)]),
        withSecretEnvironmentVariablesMixin(secretEnvironmentVariables): { secretEnvironmentVariables+: if std.isArray(v=secretEnvironmentVariables) then secretEnvironmentVariables else [secretEnvironmentVariables] },
        '#withSecretVolumes':: d.fn(help='"Secret volumes configuration. Structure is documented below."', args=[d.arg(name='secretVolumes', type=d.T.array)]),
        withSecretVolumes(secretVolumes): { secretVolumes: if std.isArray(v=secretVolumes) then secretVolumes else [secretVolumes] },
        '#withSecretVolumesMixin':: d.fn(help='"Secret volumes configuration. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='secretVolumes', type=d.T.array)]),
        withSecretVolumesMixin(secretVolumes): { secretVolumes+: if std.isArray(v=secretVolumes) then secretVolumes else [secretVolumes] },
        '#withService':: d.fn(help='"Name of the service associated with a Function."', args=[d.arg(name='service', type=d.T.string)]),
        withService(service): { service: service },
        '#withServiceAccountEmail':: d.fn(help='"The email of the service account for this function."', args=[d.arg(name='serviceAccountEmail', type=d.T.string)]),
        withServiceAccountEmail(serviceAccountEmail): { serviceAccountEmail: serviceAccountEmail },
        '#withTimeoutSeconds':: d.fn(help='"The function execution timeout. Execution is considered failed and can be terminated if the function is not completed at the end of the timeout period. Defaults to 60 seconds."', args=[d.arg(name='timeoutSeconds', type=d.T.number)]),
        withTimeoutSeconds(timeoutSeconds): { timeoutSeconds: timeoutSeconds },
        '#withVpcConnector':: d.fn(help='"The Serverless VPC Access connector that this cloud function can connect to."', args=[d.arg(name='vpcConnector', type=d.T.string)]),
        withVpcConnector(vpcConnector): { vpcConnector: vpcConnector },
        '#withVpcConnectorEgressSettings':: d.fn(help='"Available egress settings. Possible values are VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED, PRIVATE_RANGES_ONLY, and ALL_TRAFFIC."', args=[d.arg(name='vpcConnectorEgressSettings', type=d.T.string)]),
        withVpcConnectorEgressSettings(vpcConnectorEgressSettings): { vpcConnectorEgressSettings: vpcConnectorEgressSettings },
      },
      '#withBuildConfig':: d.fn(help='"Describes the Build step of the function that builds a container from the given source. Structure is documented below."', args=[d.arg(name='buildConfig', type=d.T.array)]),
      withBuildConfig(buildConfig): { spec+: { forProvider+: { buildConfig: if std.isArray(v=buildConfig) then buildConfig else [buildConfig] } } },
      '#withBuildConfigMixin':: d.fn(help='"Describes the Build step of the function that builds a container from the given source. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='buildConfig', type=d.T.array)]),
      withBuildConfigMixin(buildConfig): { spec+: { forProvider+: { buildConfig+: if std.isArray(v=buildConfig) then buildConfig else [buildConfig] } } },
      '#withDescription':: d.fn(help='"User-provided description of a function."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withEventTrigger':: d.fn(help='"An Eventarc trigger managed by Google Cloud Functions that fires events in response to a condition in another service. Structure is documented below."', args=[d.arg(name='eventTrigger', type=d.T.array)]),
      withEventTrigger(eventTrigger): { spec+: { forProvider+: { eventTrigger: if std.isArray(v=eventTrigger) then eventTrigger else [eventTrigger] } } },
      '#withEventTriggerMixin':: d.fn(help='"An Eventarc trigger managed by Google Cloud Functions that fires events in response to a condition in another service. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='eventTrigger', type=d.T.array)]),
      withEventTriggerMixin(eventTrigger): { spec+: { forProvider+: { eventTrigger+: if std.isArray(v=eventTrigger) then eventTrigger else [eventTrigger] } } },
      '#withLabels':: d.fn(help='"A set of key/value label pairs associated with this Cloud Function."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { forProvider+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"A set of key/value label pairs associated with this Cloud Function."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { forProvider+: { labels+: labels } } },
      '#withLocation':: d.fn(help='"The location of this cloud function."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { forProvider+: { location: location } } },
      '#withProject':: d.fn(help='"The ID of the project in which the resource belongs. If it is not provided, the provider project is used."', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withServiceConfig':: d.fn(help='"Describes the Service being deployed. Structure is documented below."', args=[d.arg(name='serviceConfig', type=d.T.array)]),
      withServiceConfig(serviceConfig): { spec+: { forProvider+: { serviceConfig: if std.isArray(v=serviceConfig) then serviceConfig else [serviceConfig] } } },
      '#withServiceConfigMixin':: d.fn(help='"Describes the Service being deployed. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='serviceConfig', type=d.T.array)]),
      withServiceConfigMixin(serviceConfig): { spec+: { forProvider+: { serviceConfig+: if std.isArray(v=serviceConfig) then serviceConfig else [serviceConfig] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
