{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='slo', url='', help='"SLO is the Schema for the SLOs API. Resource manages Grafana SLOs. Official documentation https://grafana.com/docs/grafana-cloud/alerting-and-irm/slo/API documentation https://grafana.com/docs/grafana-cloud/alerting-and-irm/slo/api/Additional Information On Alerting Rule Annotations and Labels https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating/"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of SLO', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'slo.grafana.crossplane.io/v1alpha1',
    kind: 'SLO',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"SLOSpec defines the desired state of SLO"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#alerting':: d.obj(help='"term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating. (see below for nested schema)\\nConfigures the alerting rules that will be generated for each\\ntime window associated with the SLO. Grafana SLOs can generate\\nalerts when the short-term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating."'),
      alerting: {
        '#advancedOptions':: d.obj(help='"(Block List, Max: 1) Advanced Options for Alert Rules (see below for nested schema)\\nAdvanced Options for Alert Rules"'),
        advancedOptions: {
          '#withMinFailures':: d.fn(help='"(Number) Minimum number of failed events to trigger an alert\\nMinimum number of failed events to trigger an alert"', args=[d.arg(name='minFailures', type=d.T.number)]),
          withMinFailures(minFailures): { minFailures: minFailures },
        },
        '#annotation':: d.obj(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations will be attached to all alerts generated by any of these rules."'),
        annotation: {
          '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#fastburn':: d.obj(help='"(Block List, Max: 1) Alerting Rules generated for Fast Burn alerts (see below for nested schema)\\nAlerting Rules generated for Fast Burn alerts"'),
        fastburn: {
          '#annotation':: d.obj(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Fast Burn alerts."'),
          annotation: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Fast Burn alerts."'),
          label: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withAnnotation':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Fast Burn alerts."', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotation(annotation): { annotation: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withAnnotationMixin':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Fast Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotationMixin(annotation): { annotation+: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Fast Burn alerts."', args=[d.arg(name='label', type=d.T.array)]),
          withLabel(label): { label: if std.isArray(v=label) then label else [label] },
          '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Fast Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
          withLabelMixin(label): { label+: if std.isArray(v=label) then label else [label] },
        },
        '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels will be attached to all alerts generated by any of these rules."'),
        label: {
          '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#slowburn':: d.obj(help='"(Block List, Max: 1) Alerting Rules generated for Slow Burn alerts (see below for nested schema)\\nAlerting Rules generated for Slow Burn alerts"'),
        slowburn: {
          '#annotation':: d.obj(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Slow Burn alerts."'),
          annotation: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Slow Burn alerts."'),
          label: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withAnnotation':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Slow Burn alerts."', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotation(annotation): { annotation: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withAnnotationMixin':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Slow Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotationMixin(annotation): { annotation+: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Slow Burn alerts."', args=[d.arg(name='label', type=d.T.array)]),
          withLabel(label): { label: if std.isArray(v=label) then label else [label] },
          '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Slow Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
          withLabelMixin(label): { label+: if std.isArray(v=label) then label else [label] },
        },
        '#withAdvancedOptions':: d.fn(help='"(Block List, Max: 1) Advanced Options for Alert Rules (see below for nested schema)\\nAdvanced Options for Alert Rules"', args=[d.arg(name='advancedOptions', type=d.T.array)]),
        withAdvancedOptions(advancedOptions): { advancedOptions: if std.isArray(v=advancedOptions) then advancedOptions else [advancedOptions] },
        '#withAdvancedOptionsMixin':: d.fn(help='"(Block List, Max: 1) Advanced Options for Alert Rules (see below for nested schema)\\nAdvanced Options for Alert Rules"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='advancedOptions', type=d.T.array)]),
        withAdvancedOptionsMixin(advancedOptions): { advancedOptions+: if std.isArray(v=advancedOptions) then advancedOptions else [advancedOptions] },
        '#withAnnotation':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations will be attached to all alerts generated by any of these rules."', args=[d.arg(name='annotation', type=d.T.array)]),
        withAnnotation(annotation): { annotation: if std.isArray(v=annotation) then annotation else [annotation] },
        '#withAnnotationMixin':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations will be attached to all alerts generated by any of these rules."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotation', type=d.T.array)]),
        withAnnotationMixin(annotation): { annotation+: if std.isArray(v=annotation) then annotation else [annotation] },
        '#withFastburn':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Fast Burn alerts (see below for nested schema)\\nAlerting Rules generated for Fast Burn alerts"', args=[d.arg(name='fastburn', type=d.T.array)]),
        withFastburn(fastburn): { fastburn: if std.isArray(v=fastburn) then fastburn else [fastburn] },
        '#withFastburnMixin':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Fast Burn alerts (see below for nested schema)\\nAlerting Rules generated for Fast Burn alerts"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='fastburn', type=d.T.array)]),
        withFastburnMixin(fastburn): { fastburn+: if std.isArray(v=fastburn) then fastburn else [fastburn] },
        '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels will be attached to all alerts generated by any of these rules."', args=[d.arg(name='label', type=d.T.array)]),
        withLabel(label): { label: if std.isArray(v=label) then label else [label] },
        '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels will be attached to all alerts generated by any of these rules."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
        withLabelMixin(label): { label+: if std.isArray(v=label) then label else [label] },
        '#withSlowburn':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Slow Burn alerts (see below for nested schema)\\nAlerting Rules generated for Slow Burn alerts"', args=[d.arg(name='slowburn', type=d.T.array)]),
        withSlowburn(slowburn): { slowburn: if std.isArray(v=slowburn) then slowburn else [slowburn] },
        '#withSlowburnMixin':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Slow Burn alerts (see below for nested schema)\\nAlerting Rules generated for Slow Burn alerts"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='slowburn', type=d.T.array)]),
        withSlowburnMixin(slowburn): { slowburn+: if std.isArray(v=slowburn) then slowburn else [slowburn] },
      },
      '#destinationDatasource':: d.obj(help='"(Block List, Max: 1) Destination Datasource sets the datasource defined for an SLO (see below for nested schema)\\nDestination Datasource sets the datasource defined for an SLO"'),
      destinationDatasource: {
        '#ref':: d.obj(help='"Reference to a DataSource in oss to populate uid."'),
        ref: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { ref+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { ref+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { ref+: { name: name } },
        },
        '#selector':: d.obj(help='"Selector for a DataSource in oss to populate uid."'),
        selector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { selector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { selector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { selector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { selector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { selector+: { matchLabels+: matchLabels } },
        },
        '#withUid':: d.fn(help='"(String) UID for the Mimir Datasource\\nUID for the Mimir Datasource"', args=[d.arg(name='uid', type=d.T.string)]),
        withUid(uid): { uid: uid },
      },
      '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nAdditional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\'),
      label: {
        '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { value: value },
      },
      '#objectives':: d.obj(help='"(Block List, Min: 1) Over each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget. (see below for nested schema)\\nOver each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget."'),
      objectives: {
        '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met.\\nValue between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.number)]),
        withValue(value): { value: value },
        '#withWindow':: d.fn(help='"parsable time duration string like 24h, 60m. This is the time window the objective is measured over.\\nA Prometheus-parsable time duration string like 24h, 60m. This is the time window the objective is measured over."', args=[d.arg(name='window', type=d.T.string)]),
        withWindow(window): { window: window },
      },
      '#query':: d.obj(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nQuery describes the indicator that will be measured against the objective. Freeform Query types are currently supported."'),
      query: {
        '#freeform':: d.obj(help='"(Block List, Max: 1) (see below for nested schema)"'),
        freeform: {
          '#withQuery':: d.fn(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nFreeform Query Field"', args=[d.arg(name='query', type=d.T.string)]),
          withQuery(query): { query: query },
        },
        '#ratio':: d.obj(help='"(Block List, Max: 1) (see below for nested schema)"'),
        ratio: {
          '#withGroupByLabels':: d.fn(help='"label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\"\\nDefines Group By Labels used for per-label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\', args=[d.arg(name='groupByLabels', type=d.T.array)]),
          withGroupByLabels(groupByLabels): { groupByLabels: if std.isArray(v=groupByLabels) then groupByLabels else [groupByLabels] },
          '#withGroupByLabelsMixin':: d.fn(help='"label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\"\\nDefines Group By Labels used for per-label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='groupByLabels', type=d.T.array)]),
          withGroupByLabelsMixin(groupByLabels): { groupByLabels+: if std.isArray(v=groupByLabels) then groupByLabels else [groupByLabels] },
          '#withSuccessMetric':: d.fn(help='"(String) Counter metric for success events (numerator)\\nCounter metric for success events (numerator)"', args=[d.arg(name='successMetric', type=d.T.string)]),
          withSuccessMetric(successMetric): { successMetric: successMetric },
          '#withTotalMetric':: d.fn(help='"(String) Metric for total events (denominator)\\nMetric for total events (denominator)"', args=[d.arg(name='totalMetric', type=d.T.string)]),
          withTotalMetric(totalMetric): { totalMetric: totalMetric },
        },
        '#withFreeform':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"', args=[d.arg(name='freeform', type=d.T.array)]),
        withFreeform(freeform): { freeform: if std.isArray(v=freeform) then freeform else [freeform] },
        '#withFreeformMixin':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='freeform', type=d.T.array)]),
        withFreeformMixin(freeform): { freeform+: if std.isArray(v=freeform) then freeform else [freeform] },
        '#withRatio':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"', args=[d.arg(name='ratio', type=d.T.array)]),
        withRatio(ratio): { ratio: if std.isArray(v=ratio) then ratio else [ratio] },
        '#withRatioMixin':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ratio', type=d.T.array)]),
        withRatioMixin(ratio): { ratio+: if std.isArray(v=ratio) then ratio else [ratio] },
        '#withType':: d.fn(help='"(String) Query type must be one of: \\"freeform\\", \\"query\\", \\"ratio\\", or \\"threshold\\"\\nQuery type must be one of: \\"freeform\\", \\"query\\", \\"ratio\\", or \\"threshold\\', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#withAlerting':: d.fn(help='"term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating. (see below for nested schema)\\nConfigures the alerting rules that will be generated for each\\ntime window associated with the SLO. Grafana SLOs can generate\\nalerts when the short-term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating."', args=[d.arg(name='alerting', type=d.T.array)]),
      withAlerting(alerting): { spec+: { forProvider+: { alerting: if std.isArray(v=alerting) then alerting else [alerting] } } },
      '#withAlertingMixin':: d.fn(help='"term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating. (see below for nested schema)\\nConfigures the alerting rules that will be generated for each\\ntime window associated with the SLO. Grafana SLOs can generate\\nalerts when the short-term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='alerting', type=d.T.array)]),
      withAlertingMixin(alerting): { spec+: { forProvider+: { alerting+: if std.isArray(v=alerting) then alerting else [alerting] } } },
      '#withDescription':: d.fn(help='"text field that can provide more context to an SLO.\\nDescription is a free-text field that can provide more context to an SLO."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withDestinationDatasource':: d.fn(help='"(Block List, Max: 1) Destination Datasource sets the datasource defined for an SLO (see below for nested schema)\\nDestination Datasource sets the datasource defined for an SLO"', args=[d.arg(name='destinationDatasource', type=d.T.array)]),
      withDestinationDatasource(destinationDatasource): { spec+: { forProvider+: { destinationDatasource: if std.isArray(v=destinationDatasource) then destinationDatasource else [destinationDatasource] } } },
      '#withDestinationDatasourceMixin':: d.fn(help='"(Block List, Max: 1) Destination Datasource sets the datasource defined for an SLO (see below for nested schema)\\nDestination Datasource sets the datasource defined for an SLO"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='destinationDatasource', type=d.T.array)]),
      withDestinationDatasourceMixin(destinationDatasource): { spec+: { forProvider+: { destinationDatasource+: if std.isArray(v=destinationDatasource) then destinationDatasource else [destinationDatasource] } } },
      '#withFolderUid':: d.fn(help='"(String) UID for the SLO folder\\nUID for the SLO folder"', args=[d.arg(name='folderUid', type=d.T.string)]),
      withFolderUid(folderUid): { spec+: { forProvider+: { folderUid: folderUid } } },
      '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nAdditional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\', args=[d.arg(name='label', type=d.T.array)]),
      withLabel(label): { spec+: { forProvider+: { label: if std.isArray(v=label) then label else [label] } } },
      '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nAdditional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
      withLabelMixin(label): { spec+: { forProvider+: { label+: if std.isArray(v=label) then label else [label] } } },
      '#withName':: d.fn(help='"(String) Name should be a short description of your indicator. Consider names like \\"API Availability\\"\\nName should be a short description of your indicator. Consider names like \\"API Availability\\', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { forProvider+: { name: name } } },
      '#withObjectives':: d.fn(help='"(Block List, Min: 1) Over each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget. (see below for nested schema)\\nOver each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget."', args=[d.arg(name='objectives', type=d.T.array)]),
      withObjectives(objectives): { spec+: { forProvider+: { objectives: if std.isArray(v=objectives) then objectives else [objectives] } } },
      '#withObjectivesMixin':: d.fn(help='"(Block List, Min: 1) Over each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget. (see below for nested schema)\\nOver each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='objectives', type=d.T.array)]),
      withObjectivesMixin(objectives): { spec+: { forProvider+: { objectives+: if std.isArray(v=objectives) then objectives else [objectives] } } },
      '#withQuery':: d.fn(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nQuery describes the indicator that will be measured against the objective. Freeform Query types are currently supported."', args=[d.arg(name='query', type=d.T.array)]),
      withQuery(query): { spec+: { forProvider+: { query: if std.isArray(v=query) then query else [query] } } },
      '#withQueryMixin':: d.fn(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nQuery describes the indicator that will be measured against the objective. Freeform Query types are currently supported."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='query', type=d.T.array)]),
      withQueryMixin(query): { spec+: { forProvider+: { query+: if std.isArray(v=query) then query else [query] } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#alerting':: d.obj(help='"term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating. (see below for nested schema)\\nConfigures the alerting rules that will be generated for each\\ntime window associated with the SLO. Grafana SLOs can generate\\nalerts when the short-term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating."'),
      alerting: {
        '#advancedOptions':: d.obj(help='"(Block List, Max: 1) Advanced Options for Alert Rules (see below for nested schema)\\nAdvanced Options for Alert Rules"'),
        advancedOptions: {
          '#withMinFailures':: d.fn(help='"(Number) Minimum number of failed events to trigger an alert\\nMinimum number of failed events to trigger an alert"', args=[d.arg(name='minFailures', type=d.T.number)]),
          withMinFailures(minFailures): { minFailures: minFailures },
        },
        '#annotation':: d.obj(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations will be attached to all alerts generated by any of these rules."'),
        annotation: {
          '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#fastburn':: d.obj(help='"(Block List, Max: 1) Alerting Rules generated for Fast Burn alerts (see below for nested schema)\\nAlerting Rules generated for Fast Burn alerts"'),
        fastburn: {
          '#annotation':: d.obj(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Fast Burn alerts."'),
          annotation: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Fast Burn alerts."'),
          label: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withAnnotation':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Fast Burn alerts."', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotation(annotation): { annotation: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withAnnotationMixin':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Fast Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotationMixin(annotation): { annotation+: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Fast Burn alerts."', args=[d.arg(name='label', type=d.T.array)]),
          withLabel(label): { label: if std.isArray(v=label) then label else [label] },
          '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Fast Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
          withLabelMixin(label): { label+: if std.isArray(v=label) then label else [label] },
        },
        '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels will be attached to all alerts generated by any of these rules."'),
        label: {
          '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#slowburn':: d.obj(help='"(Block List, Max: 1) Alerting Rules generated for Slow Burn alerts (see below for nested schema)\\nAlerting Rules generated for Slow Burn alerts"'),
        slowburn: {
          '#annotation':: d.obj(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Slow Burn alerts."'),
          annotation: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Slow Burn alerts."'),
          label: {
            '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { key: key },
            '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withAnnotation':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Slow Burn alerts."', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotation(annotation): { annotation: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withAnnotationMixin':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations to attach only to Slow Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotation', type=d.T.array)]),
          withAnnotationMixin(annotation): { annotation+: if std.isArray(v=annotation) then annotation else [annotation] },
          '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Slow Burn alerts."', args=[d.arg(name='label', type=d.T.array)]),
          withLabel(label): { label: if std.isArray(v=label) then label else [label] },
          '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels to attach only to Slow Burn alerts."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
          withLabelMixin(label): { label+: if std.isArray(v=label) then label else [label] },
        },
        '#withAdvancedOptions':: d.fn(help='"(Block List, Max: 1) Advanced Options for Alert Rules (see below for nested schema)\\nAdvanced Options for Alert Rules"', args=[d.arg(name='advancedOptions', type=d.T.array)]),
        withAdvancedOptions(advancedOptions): { advancedOptions: if std.isArray(v=advancedOptions) then advancedOptions else [advancedOptions] },
        '#withAdvancedOptionsMixin':: d.fn(help='"(Block List, Max: 1) Advanced Options for Alert Rules (see below for nested schema)\\nAdvanced Options for Alert Rules"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='advancedOptions', type=d.T.array)]),
        withAdvancedOptionsMixin(advancedOptions): { advancedOptions+: if std.isArray(v=advancedOptions) then advancedOptions else [advancedOptions] },
        '#withAnnotation':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations will be attached to all alerts generated by any of these rules."', args=[d.arg(name='annotation', type=d.T.array)]),
        withAnnotation(annotation): { annotation: if std.isArray(v=annotation) then annotation else [annotation] },
        '#withAnnotationMixin':: d.fn(help='"(Block List) Annotations will be attached to all alerts generated by any of these rules. (see below for nested schema)\\nAnnotations will be attached to all alerts generated by any of these rules."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotation', type=d.T.array)]),
        withAnnotationMixin(annotation): { annotation+: if std.isArray(v=annotation) then annotation else [annotation] },
        '#withFastburn':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Fast Burn alerts (see below for nested schema)\\nAlerting Rules generated for Fast Burn alerts"', args=[d.arg(name='fastburn', type=d.T.array)]),
        withFastburn(fastburn): { fastburn: if std.isArray(v=fastburn) then fastburn else [fastburn] },
        '#withFastburnMixin':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Fast Burn alerts (see below for nested schema)\\nAlerting Rules generated for Fast Burn alerts"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='fastburn', type=d.T.array)]),
        withFastburnMixin(fastburn): { fastburn+: if std.isArray(v=fastburn) then fastburn else [fastburn] },
        '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels will be attached to all alerts generated by any of these rules."', args=[d.arg(name='label', type=d.T.array)]),
        withLabel(label): { label: if std.isArray(v=label) then label else [label] },
        '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nLabels will be attached to all alerts generated by any of these rules."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
        withLabelMixin(label): { label+: if std.isArray(v=label) then label else [label] },
        '#withSlowburn':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Slow Burn alerts (see below for nested schema)\\nAlerting Rules generated for Slow Burn alerts"', args=[d.arg(name='slowburn', type=d.T.array)]),
        withSlowburn(slowburn): { slowburn: if std.isArray(v=slowburn) then slowburn else [slowburn] },
        '#withSlowburnMixin':: d.fn(help='"(Block List, Max: 1) Alerting Rules generated for Slow Burn alerts (see below for nested schema)\\nAlerting Rules generated for Slow Burn alerts"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='slowburn', type=d.T.array)]),
        withSlowburnMixin(slowburn): { slowburn+: if std.isArray(v=slowburn) then slowburn else [slowburn] },
      },
      '#destinationDatasource':: d.obj(help='"(Block List, Max: 1) Destination Datasource sets the datasource defined for an SLO (see below for nested schema)\\nDestination Datasource sets the datasource defined for an SLO"'),
      destinationDatasource: {
        '#ref':: d.obj(help='"Reference to a DataSource in oss to populate uid."'),
        ref: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { ref+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { ref+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { ref+: { name: name } },
        },
        '#selector':: d.obj(help='"Selector for a DataSource in oss to populate uid."'),
        selector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { selector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { selector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { selector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { selector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { selector+: { matchLabels+: matchLabels } },
        },
        '#withUid':: d.fn(help='"(String) UID for the Mimir Datasource\\nUID for the Mimir Datasource"', args=[d.arg(name='uid', type=d.T.string)]),
        withUid(uid): { uid: uid },
      },
      '#label':: d.obj(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nAdditional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\'),
      label: {
        '#withKey':: d.fn(help='"(String)"', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { value: value },
      },
      '#objectives':: d.obj(help='"(Block List, Min: 1) Over each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget. (see below for nested schema)\\nOver each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget."'),
      objectives: {
        '#withValue':: d.fn(help='"(Number) Value between 0 and 1. If the value of the query is above the objective, the SLO is met.\\nValue between 0 and 1. If the value of the query is above the objective, the SLO is met."', args=[d.arg(name='value', type=d.T.number)]),
        withValue(value): { value: value },
        '#withWindow':: d.fn(help='"parsable time duration string like 24h, 60m. This is the time window the objective is measured over.\\nA Prometheus-parsable time duration string like 24h, 60m. This is the time window the objective is measured over."', args=[d.arg(name='window', type=d.T.string)]),
        withWindow(window): { window: window },
      },
      '#query':: d.obj(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nQuery describes the indicator that will be measured against the objective. Freeform Query types are currently supported."'),
      query: {
        '#freeform':: d.obj(help='"(Block List, Max: 1) (see below for nested schema)"'),
        freeform: {
          '#withQuery':: d.fn(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nFreeform Query Field"', args=[d.arg(name='query', type=d.T.string)]),
          withQuery(query): { query: query },
        },
        '#ratio':: d.obj(help='"(Block List, Max: 1) (see below for nested schema)"'),
        ratio: {
          '#withGroupByLabels':: d.fn(help='"label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\"\\nDefines Group By Labels used for per-label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\', args=[d.arg(name='groupByLabels', type=d.T.array)]),
          withGroupByLabels(groupByLabels): { groupByLabels: if std.isArray(v=groupByLabels) then groupByLabels else [groupByLabels] },
          '#withGroupByLabelsMixin':: d.fn(help='"label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\"\\nDefines Group By Labels used for per-label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='groupByLabels', type=d.T.array)]),
          withGroupByLabelsMixin(groupByLabels): { groupByLabels+: if std.isArray(v=groupByLabels) then groupByLabels else [groupByLabels] },
          '#withSuccessMetric':: d.fn(help='"(String) Counter metric for success events (numerator)\\nCounter metric for success events (numerator)"', args=[d.arg(name='successMetric', type=d.T.string)]),
          withSuccessMetric(successMetric): { successMetric: successMetric },
          '#withTotalMetric':: d.fn(help='"(String) Metric for total events (denominator)\\nMetric for total events (denominator)"', args=[d.arg(name='totalMetric', type=d.T.string)]),
          withTotalMetric(totalMetric): { totalMetric: totalMetric },
        },
        '#withFreeform':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"', args=[d.arg(name='freeform', type=d.T.array)]),
        withFreeform(freeform): { freeform: if std.isArray(v=freeform) then freeform else [freeform] },
        '#withFreeformMixin':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='freeform', type=d.T.array)]),
        withFreeformMixin(freeform): { freeform+: if std.isArray(v=freeform) then freeform else [freeform] },
        '#withRatio':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"', args=[d.arg(name='ratio', type=d.T.array)]),
        withRatio(ratio): { ratio: if std.isArray(v=ratio) then ratio else [ratio] },
        '#withRatioMixin':: d.fn(help='"(Block List, Max: 1) (see below for nested schema)"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ratio', type=d.T.array)]),
        withRatioMixin(ratio): { ratio+: if std.isArray(v=ratio) then ratio else [ratio] },
        '#withType':: d.fn(help='"(String) Query type must be one of: \\"freeform\\", \\"query\\", \\"ratio\\", or \\"threshold\\"\\nQuery type must be one of: \\"freeform\\", \\"query\\", \\"ratio\\", or \\"threshold\\', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#withAlerting':: d.fn(help='"term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating. (see below for nested schema)\\nConfigures the alerting rules that will be generated for each\\ntime window associated with the SLO. Grafana SLOs can generate\\nalerts when the short-term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating."', args=[d.arg(name='alerting', type=d.T.array)]),
      withAlerting(alerting): { spec+: { initProvider+: { alerting: if std.isArray(v=alerting) then alerting else [alerting] } } },
      '#withAlertingMixin':: d.fn(help='"term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating. (see below for nested schema)\\nConfigures the alerting rules that will be generated for each\\ntime window associated with the SLO. Grafana SLOs can generate\\nalerts when the short-term error budget burn is very high, the\\nlong-term error budget burn rate is high, or when the remaining\\nerror budget is below a certain threshold. Annotations and Labels support templating."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='alerting', type=d.T.array)]),
      withAlertingMixin(alerting): { spec+: { initProvider+: { alerting+: if std.isArray(v=alerting) then alerting else [alerting] } } },
      '#withDescription':: d.fn(help='"text field that can provide more context to an SLO.\\nDescription is a free-text field that can provide more context to an SLO."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { initProvider+: { description: description } } },
      '#withDestinationDatasource':: d.fn(help='"(Block List, Max: 1) Destination Datasource sets the datasource defined for an SLO (see below for nested schema)\\nDestination Datasource sets the datasource defined for an SLO"', args=[d.arg(name='destinationDatasource', type=d.T.array)]),
      withDestinationDatasource(destinationDatasource): { spec+: { initProvider+: { destinationDatasource: if std.isArray(v=destinationDatasource) then destinationDatasource else [destinationDatasource] } } },
      '#withDestinationDatasourceMixin':: d.fn(help='"(Block List, Max: 1) Destination Datasource sets the datasource defined for an SLO (see below for nested schema)\\nDestination Datasource sets the datasource defined for an SLO"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='destinationDatasource', type=d.T.array)]),
      withDestinationDatasourceMixin(destinationDatasource): { spec+: { initProvider+: { destinationDatasource+: if std.isArray(v=destinationDatasource) then destinationDatasource else [destinationDatasource] } } },
      '#withFolderUid':: d.fn(help='"(String) UID for the SLO folder\\nUID for the SLO folder"', args=[d.arg(name='folderUid', type=d.T.string)]),
      withFolderUid(folderUid): { spec+: { initProvider+: { folderUid: folderUid } } },
      '#withLabel':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nAdditional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\', args=[d.arg(name='label', type=d.T.array)]),
      withLabel(label): { spec+: { initProvider+: { label: if std.isArray(v=label) then label else [label] } } },
      '#withLabelMixin':: d.fn(help='"\\"^[a-zA-Z_][a-zA-Z0-9_]*$\\" (see below for nested schema)\\nAdditional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand. Labels must adhere to Prometheus label name schema - \\"^[a-zA-Z_][a-zA-Z0-9_]*$\\\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='label', type=d.T.array)]),
      withLabelMixin(label): { spec+: { initProvider+: { label+: if std.isArray(v=label) then label else [label] } } },
      '#withName':: d.fn(help='"(String) Name should be a short description of your indicator. Consider names like \\"API Availability\\"\\nName should be a short description of your indicator. Consider names like \\"API Availability\\', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { initProvider+: { name: name } } },
      '#withObjectives':: d.fn(help='"(Block List, Min: 1) Over each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget. (see below for nested schema)\\nOver each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget."', args=[d.arg(name='objectives', type=d.T.array)]),
      withObjectives(objectives): { spec+: { initProvider+: { objectives: if std.isArray(v=objectives) then objectives else [objectives] } } },
      '#withObjectivesMixin':: d.fn(help='"(Block List, Min: 1) Over each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget. (see below for nested schema)\\nOver each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='objectives', type=d.T.array)]),
      withObjectivesMixin(objectives): { spec+: { initProvider+: { objectives+: if std.isArray(v=objectives) then objectives else [objectives] } } },
      '#withQuery':: d.fn(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nQuery describes the indicator that will be measured against the objective. Freeform Query types are currently supported."', args=[d.arg(name='query', type=d.T.array)]),
      withQuery(query): { spec+: { initProvider+: { query: if std.isArray(v=query) then query else [query] } } },
      '#withQueryMixin':: d.fn(help='"(Block List, Min: 1) Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported. (see below for nested schema)\\nQuery describes the indicator that will be measured against the objective. Freeform Query types are currently supported."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='query', type=d.T.array)]),
      withQueryMixin(query): { spec+: { initProvider+: { query+: if std.isArray(v=query) then query else [query] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which\\ncontains a name, metadata and a reference to secret store config to\\nwhich any connection details for this managed resource should be written.\\nConnection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used\\nfor this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret.\\n- Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource.\\nThis field is planned to be replaced in a future release in favor of\\nPublishConnectionDetailsTo. Currently, both could be set independently\\nand connection details would be published to both without affecting\\neach other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
