{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='runBook', url='', help='"RunBook is the Schema for the RunBooks API. Manages a Automation Runbook."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of RunBook', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'automation.azure.upbound.io/v1beta2',
    kind: 'RunBook',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"RunBookSpec defines the desired state of RunBook"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#automationAccountNameRef':: d.obj(help='"Reference to a Account in automation to populate automationAccountName."'),
      automationAccountNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { automationAccountNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { automationAccountNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { automationAccountNameRef+: { name: name } } } },
      },
      '#automationAccountNameSelector':: d.obj(help='"Selector for a Account in automation to populate automationAccountName."'),
      automationAccountNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { automationAccountNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { automationAccountNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { automationAccountNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { automationAccountNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { automationAccountNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#draft':: d.obj(help='"A draft block as defined below ."'),
      draft: {
        '#contentLink':: d.obj(help='"A publish_content_link block as defined above."'),
        contentLink: {
          '#hash':: d.obj(help='"A hash block as defined below."'),
          hash: {
            '#withAlgorithm':: d.fn(help='"Specifies the hash algorithm used to hash the content."', args=[d.arg(name='algorithm', type=d.T.string)]),
            withAlgorithm(algorithm): { spec+: { forProvider+: { draft+: { contentLink+: { hash+: { algorithm: algorithm } } } } } },
            '#withValue':: d.fn(help='"Specifies the expected hash value of the content."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { spec+: { forProvider+: { draft+: { contentLink+: { hash+: { value: value } } } } } },
          },
          '#withUri':: d.fn(help='"The URI of the runbook content."', args=[d.arg(name='uri', type=d.T.string)]),
          withUri(uri): { spec+: { forProvider+: { draft+: { contentLink+: { uri: uri } } } } },
          '#withVersion':: d.fn(help='"Specifies the version of the content"', args=[d.arg(name='version', type=d.T.string)]),
          withVersion(version): { spec+: { forProvider+: { draft+: { contentLink+: { version: version } } } } },
        },
        '#parameters':: d.obj(help='"A list of parameters block as defined below."'),
        parameters: {
          '#withDefaultValue':: d.fn(help='"Specifies the default value of the parameter."', args=[d.arg(name='defaultValue', type=d.T.string)]),
          withDefaultValue(defaultValue): { defaultValue: defaultValue },
          '#withKey':: d.fn(help='"The name of the parameter."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withMandatory':: d.fn(help='"Whether this parameter is mandatory."', args=[d.arg(name='mandatory', type=d.T.boolean)]),
          withMandatory(mandatory): { mandatory: mandatory },
          '#withPosition':: d.fn(help='"Specifies the position of the parameter."', args=[d.arg(name='position', type=d.T.number)]),
          withPosition(position): { position: position },
          '#withType':: d.fn(help='"Specifies the type of this parameter."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#withEditModeEnabled':: d.fn(help='"Whether the draft in edit mode."', args=[d.arg(name='editModeEnabled', type=d.T.boolean)]),
        withEditModeEnabled(editModeEnabled): { spec+: { forProvider+: { draft+: { editModeEnabled: editModeEnabled } } } },
        '#withOutputTypes':: d.fn(help='"Specifies the output types of the runbook."', args=[d.arg(name='outputTypes', type=d.T.array)]),
        withOutputTypes(outputTypes): { spec+: { forProvider+: { draft+: { outputTypes: if std.isArray(v=outputTypes) then outputTypes else [outputTypes] } } } },
        '#withOutputTypesMixin':: d.fn(help='"Specifies the output types of the runbook."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='outputTypes', type=d.T.array)]),
        withOutputTypesMixin(outputTypes): { spec+: { forProvider+: { draft+: { outputTypes+: if std.isArray(v=outputTypes) then outputTypes else [outputTypes] } } } },
        '#withParameters':: d.fn(help='"A list of parameters block as defined below."', args=[d.arg(name='parameters', type=d.T.array)]),
        withParameters(parameters): { spec+: { forProvider+: { draft+: { parameters: if std.isArray(v=parameters) then parameters else [parameters] } } } },
        '#withParametersMixin':: d.fn(help='"A list of parameters block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='parameters', type=d.T.array)]),
        withParametersMixin(parameters): { spec+: { forProvider+: { draft+: { parameters+: if std.isArray(v=parameters) then parameters else [parameters] } } } },
      },
      '#jobSchedule':: d.obj(help=''),
      jobSchedule: {
        '#withJobScheduleId':: d.fn(help='"The Automation Runbook ID."', args=[d.arg(name='jobScheduleId', type=d.T.string)]),
        withJobScheduleId(jobScheduleId): { jobScheduleId: jobScheduleId },
        '#withParameters':: d.fn(help='"A list of parameters block as defined below."', args=[d.arg(name='parameters', type=d.T.object)]),
        withParameters(parameters): { parameters: parameters },
        '#withParametersMixin':: d.fn(help='"A list of parameters block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='parameters', type=d.T.object)]),
        withParametersMixin(parameters): { parameters+: parameters },
        '#withRunOn':: d.fn(help='', args=[d.arg(name='runOn', type=d.T.string)]),
        withRunOn(runOn): { runOn: runOn },
        '#withScheduleName':: d.fn(help='"Specifies the name of the Runbook. Changing this forces a new resource to be created."', args=[d.arg(name='scheduleName', type=d.T.string)]),
        withScheduleName(scheduleName): { scheduleName: scheduleName },
      },
      '#publishContentLink':: d.obj(help='"One publish_content_link block as defined below."'),
      publishContentLink: {
        '#hash':: d.obj(help='"A hash block as defined below."'),
        hash: {
          '#withAlgorithm':: d.fn(help='"Specifies the hash algorithm used to hash the content."', args=[d.arg(name='algorithm', type=d.T.string)]),
          withAlgorithm(algorithm): { spec+: { forProvider+: { publishContentLink+: { hash+: { algorithm: algorithm } } } } },
          '#withValue':: d.fn(help='"Specifies the expected hash value of the content."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { spec+: { forProvider+: { publishContentLink+: { hash+: { value: value } } } } },
        },
        '#withUri':: d.fn(help='"The URI of the runbook content."', args=[d.arg(name='uri', type=d.T.string)]),
        withUri(uri): { spec+: { forProvider+: { publishContentLink+: { uri: uri } } } },
        '#withVersion':: d.fn(help='"Specifies the version of the content"', args=[d.arg(name='version', type=d.T.string)]),
        withVersion(version): { spec+: { forProvider+: { publishContentLink+: { version: version } } } },
      },
      '#resourceGroupNameRef':: d.obj(help='"Reference to a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { resourceGroupNameRef+: { name: name } } } },
      },
      '#resourceGroupNameSelector':: d.obj(help='"Selector for a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#withAutomationAccountName':: d.fn(help='"The name of the automation account in which the Runbook is created. Changing this forces a new resource to be created."', args=[d.arg(name='automationAccountName', type=d.T.string)]),
      withAutomationAccountName(automationAccountName): { spec+: { forProvider+: { automationAccountName: automationAccountName } } },
      '#withContent':: d.fn(help='"The desired content of the runbook."', args=[d.arg(name='content', type=d.T.string)]),
      withContent(content): { spec+: { forProvider+: { content: content } } },
      '#withDescription':: d.fn(help='"A description for this credential."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withJobSchedule':: d.fn(help='', args=[d.arg(name='jobSchedule', type=d.T.array)]),
      withJobSchedule(jobSchedule): { spec+: { forProvider+: { jobSchedule: if std.isArray(v=jobSchedule) then jobSchedule else [jobSchedule] } } },
      '#withJobScheduleMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='jobSchedule', type=d.T.array)]),
      withJobScheduleMixin(jobSchedule): { spec+: { forProvider+: { jobSchedule+: if std.isArray(v=jobSchedule) then jobSchedule else [jobSchedule] } } },
      '#withLocation':: d.fn(help='"Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { forProvider+: { location: location } } },
      '#withLogActivityTraceLevel':: d.fn(help='"Specifies the activity-level tracing options of the runbook, available only for Graphical runbooks. Possible values are 0 for None, 9 for Basic, and 15 for Detailed. Must turn on Verbose logging in order to see the tracing."', args=[d.arg(name='logActivityTraceLevel', type=d.T.number)]),
      withLogActivityTraceLevel(logActivityTraceLevel): { spec+: { forProvider+: { logActivityTraceLevel: logActivityTraceLevel } } },
      '#withLogProgress':: d.fn(help='"Progress log option."', args=[d.arg(name='logProgress', type=d.T.boolean)]),
      withLogProgress(logProgress): { spec+: { forProvider+: { logProgress: logProgress } } },
      '#withLogVerbose':: d.fn(help='"Verbose log option."', args=[d.arg(name='logVerbose', type=d.T.boolean)]),
      withLogVerbose(logVerbose): { spec+: { forProvider+: { logVerbose: logVerbose } } },
      '#withName':: d.fn(help='"Specifies the name of the Runbook. Changing this forces a new resource to be created."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { forProvider+: { name: name } } },
      '#withResourceGroupName':: d.fn(help='"The name of the resource group in which the Runbook is created. Changing this forces a new resource to be created."', args=[d.arg(name='resourceGroupName', type=d.T.string)]),
      withResourceGroupName(resourceGroupName): { spec+: { forProvider+: { resourceGroupName: resourceGroupName } } },
      '#withRunbookType':: d.fn(help='"The type of the runbook - can be either Graph, GraphPowerShell, GraphPowerShellWorkflow, PowerShellWorkflow, PowerShell, PowerShell72, Python3, Python2 or Script. Changing this forces a new resource to be created."', args=[d.arg(name='runbookType', type=d.T.string)]),
      withRunbookType(runbookType): { spec+: { forProvider+: { runbookType: runbookType } } },
      '#withTags':: d.fn(help='"A mapping of tags to assign to the resource."', args=[d.arg(name='tags', type=d.T.object)]),
      withTags(tags): { spec+: { forProvider+: { tags: tags } } },
      '#withTagsMixin':: d.fn(help='"A mapping of tags to assign to the resource."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
      withTagsMixin(tags): { spec+: { forProvider+: { tags+: tags } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#automationAccountNameRef':: d.obj(help='"Reference to a Account in automation to populate automationAccountName."'),
      automationAccountNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { automationAccountNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { automationAccountNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { automationAccountNameRef+: { name: name } } } },
      },
      '#automationAccountNameSelector':: d.obj(help='"Selector for a Account in automation to populate automationAccountName."'),
      automationAccountNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { automationAccountNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { automationAccountNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { automationAccountNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { automationAccountNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { automationAccountNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#draft':: d.obj(help='"A draft block as defined below ."'),
      draft: {
        '#contentLink':: d.obj(help='"A publish_content_link block as defined above."'),
        contentLink: {
          '#hash':: d.obj(help='"A hash block as defined below."'),
          hash: {
            '#withAlgorithm':: d.fn(help='"Specifies the hash algorithm used to hash the content."', args=[d.arg(name='algorithm', type=d.T.string)]),
            withAlgorithm(algorithm): { spec+: { initProvider+: { draft+: { contentLink+: { hash+: { algorithm: algorithm } } } } } },
            '#withValue':: d.fn(help='"Specifies the expected hash value of the content."', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { spec+: { initProvider+: { draft+: { contentLink+: { hash+: { value: value } } } } } },
          },
          '#withUri':: d.fn(help='"The URI of the runbook content."', args=[d.arg(name='uri', type=d.T.string)]),
          withUri(uri): { spec+: { initProvider+: { draft+: { contentLink+: { uri: uri } } } } },
          '#withVersion':: d.fn(help='"Specifies the version of the content"', args=[d.arg(name='version', type=d.T.string)]),
          withVersion(version): { spec+: { initProvider+: { draft+: { contentLink+: { version: version } } } } },
        },
        '#parameters':: d.obj(help='"A list of parameters block as defined below."'),
        parameters: {
          '#withDefaultValue':: d.fn(help='"Specifies the default value of the parameter."', args=[d.arg(name='defaultValue', type=d.T.string)]),
          withDefaultValue(defaultValue): { defaultValue: defaultValue },
          '#withKey':: d.fn(help='"The name of the parameter."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { key: key },
          '#withMandatory':: d.fn(help='"Whether this parameter is mandatory."', args=[d.arg(name='mandatory', type=d.T.boolean)]),
          withMandatory(mandatory): { mandatory: mandatory },
          '#withPosition':: d.fn(help='"Specifies the position of the parameter."', args=[d.arg(name='position', type=d.T.number)]),
          withPosition(position): { position: position },
          '#withType':: d.fn(help='"Specifies the type of this parameter."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#withEditModeEnabled':: d.fn(help='"Whether the draft in edit mode."', args=[d.arg(name='editModeEnabled', type=d.T.boolean)]),
        withEditModeEnabled(editModeEnabled): { spec+: { initProvider+: { draft+: { editModeEnabled: editModeEnabled } } } },
        '#withOutputTypes':: d.fn(help='"Specifies the output types of the runbook."', args=[d.arg(name='outputTypes', type=d.T.array)]),
        withOutputTypes(outputTypes): { spec+: { initProvider+: { draft+: { outputTypes: if std.isArray(v=outputTypes) then outputTypes else [outputTypes] } } } },
        '#withOutputTypesMixin':: d.fn(help='"Specifies the output types of the runbook."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='outputTypes', type=d.T.array)]),
        withOutputTypesMixin(outputTypes): { spec+: { initProvider+: { draft+: { outputTypes+: if std.isArray(v=outputTypes) then outputTypes else [outputTypes] } } } },
        '#withParameters':: d.fn(help='"A list of parameters block as defined below."', args=[d.arg(name='parameters', type=d.T.array)]),
        withParameters(parameters): { spec+: { initProvider+: { draft+: { parameters: if std.isArray(v=parameters) then parameters else [parameters] } } } },
        '#withParametersMixin':: d.fn(help='"A list of parameters block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='parameters', type=d.T.array)]),
        withParametersMixin(parameters): { spec+: { initProvider+: { draft+: { parameters+: if std.isArray(v=parameters) then parameters else [parameters] } } } },
      },
      '#jobSchedule':: d.obj(help=''),
      jobSchedule: {
        '#withJobScheduleId':: d.fn(help='"The Automation Runbook ID."', args=[d.arg(name='jobScheduleId', type=d.T.string)]),
        withJobScheduleId(jobScheduleId): { jobScheduleId: jobScheduleId },
        '#withParameters':: d.fn(help='"A list of parameters block as defined below."', args=[d.arg(name='parameters', type=d.T.object)]),
        withParameters(parameters): { parameters: parameters },
        '#withParametersMixin':: d.fn(help='"A list of parameters block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='parameters', type=d.T.object)]),
        withParametersMixin(parameters): { parameters+: parameters },
        '#withRunOn':: d.fn(help='', args=[d.arg(name='runOn', type=d.T.string)]),
        withRunOn(runOn): { runOn: runOn },
        '#withScheduleName':: d.fn(help='"Specifies the name of the Runbook. Changing this forces a new resource to be created."', args=[d.arg(name='scheduleName', type=d.T.string)]),
        withScheduleName(scheduleName): { scheduleName: scheduleName },
      },
      '#publishContentLink':: d.obj(help='"One publish_content_link block as defined below."'),
      publishContentLink: {
        '#hash':: d.obj(help='"A hash block as defined below."'),
        hash: {
          '#withAlgorithm':: d.fn(help='"Specifies the hash algorithm used to hash the content."', args=[d.arg(name='algorithm', type=d.T.string)]),
          withAlgorithm(algorithm): { spec+: { initProvider+: { publishContentLink+: { hash+: { algorithm: algorithm } } } } },
          '#withValue':: d.fn(help='"Specifies the expected hash value of the content."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { spec+: { initProvider+: { publishContentLink+: { hash+: { value: value } } } } },
        },
        '#withUri':: d.fn(help='"The URI of the runbook content."', args=[d.arg(name='uri', type=d.T.string)]),
        withUri(uri): { spec+: { initProvider+: { publishContentLink+: { uri: uri } } } },
        '#withVersion':: d.fn(help='"Specifies the version of the content"', args=[d.arg(name='version', type=d.T.string)]),
        withVersion(version): { spec+: { initProvider+: { publishContentLink+: { version: version } } } },
      },
      '#resourceGroupNameRef':: d.obj(help='"Reference to a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { resourceGroupNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { resourceGroupNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { resourceGroupNameRef+: { name: name } } } },
      },
      '#resourceGroupNameSelector':: d.obj(help='"Selector for a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { resourceGroupNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { resourceGroupNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { resourceGroupNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { resourceGroupNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { resourceGroupNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#withAutomationAccountName':: d.fn(help='"The name of the automation account in which the Runbook is created. Changing this forces a new resource to be created."', args=[d.arg(name='automationAccountName', type=d.T.string)]),
      withAutomationAccountName(automationAccountName): { spec+: { initProvider+: { automationAccountName: automationAccountName } } },
      '#withContent':: d.fn(help='"The desired content of the runbook."', args=[d.arg(name='content', type=d.T.string)]),
      withContent(content): { spec+: { initProvider+: { content: content } } },
      '#withDescription':: d.fn(help='"A description for this credential."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { initProvider+: { description: description } } },
      '#withJobSchedule':: d.fn(help='', args=[d.arg(name='jobSchedule', type=d.T.array)]),
      withJobSchedule(jobSchedule): { spec+: { initProvider+: { jobSchedule: if std.isArray(v=jobSchedule) then jobSchedule else [jobSchedule] } } },
      '#withJobScheduleMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='jobSchedule', type=d.T.array)]),
      withJobScheduleMixin(jobSchedule): { spec+: { initProvider+: { jobSchedule+: if std.isArray(v=jobSchedule) then jobSchedule else [jobSchedule] } } },
      '#withLocation':: d.fn(help='"Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { initProvider+: { location: location } } },
      '#withLogActivityTraceLevel':: d.fn(help='"Specifies the activity-level tracing options of the runbook, available only for Graphical runbooks. Possible values are 0 for None, 9 for Basic, and 15 for Detailed. Must turn on Verbose logging in order to see the tracing."', args=[d.arg(name='logActivityTraceLevel', type=d.T.number)]),
      withLogActivityTraceLevel(logActivityTraceLevel): { spec+: { initProvider+: { logActivityTraceLevel: logActivityTraceLevel } } },
      '#withLogProgress':: d.fn(help='"Progress log option."', args=[d.arg(name='logProgress', type=d.T.boolean)]),
      withLogProgress(logProgress): { spec+: { initProvider+: { logProgress: logProgress } } },
      '#withLogVerbose':: d.fn(help='"Verbose log option."', args=[d.arg(name='logVerbose', type=d.T.boolean)]),
      withLogVerbose(logVerbose): { spec+: { initProvider+: { logVerbose: logVerbose } } },
      '#withName':: d.fn(help='"Specifies the name of the Runbook. Changing this forces a new resource to be created."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { initProvider+: { name: name } } },
      '#withResourceGroupName':: d.fn(help='"The name of the resource group in which the Runbook is created. Changing this forces a new resource to be created."', args=[d.arg(name='resourceGroupName', type=d.T.string)]),
      withResourceGroupName(resourceGroupName): { spec+: { initProvider+: { resourceGroupName: resourceGroupName } } },
      '#withRunbookType':: d.fn(help='"The type of the runbook - can be either Graph, GraphPowerShell, GraphPowerShellWorkflow, PowerShellWorkflow, PowerShell, PowerShell72, Python3, Python2 or Script. Changing this forces a new resource to be created."', args=[d.arg(name='runbookType', type=d.T.string)]),
      withRunbookType(runbookType): { spec+: { initProvider+: { runbookType: runbookType } } },
      '#withTags':: d.fn(help='"A mapping of tags to assign to the resource."', args=[d.arg(name='tags', type=d.T.object)]),
      withTags(tags): { spec+: { initProvider+: { tags: tags } } },
      '#withTagsMixin':: d.fn(help='"A mapping of tags to assign to the resource."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
      withTagsMixin(tags): { spec+: { initProvider+: { tags+: tags } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which\\ncontains a name, metadata and a reference to secret store config to\\nwhich any connection details for this managed resource should be written.\\nConnection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used\\nfor this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret.\\n- Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource.\\nThis field is planned to be replaced in a future release in favor of\\nPublishConnectionDetailsTo. Currently, both could be set independently\\nand connection details would be published to both without affecting\\neach other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
