{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='service', url='', help='"Service is the Schema for the Services API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Service', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'cloudrun.gcp.jet.crossplane.io/v1alpha1',
    kind: 'Service',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'true',
  }),
  '#spec':: d.obj(help='"ServiceSpec defines the desired state of Service"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#metadata':: d.obj(help='"Metadata associated with this Service, including name, namespace, labels, and annotations."'),
      metadata: {
        '#withAnnotations':: d.fn(help="\"Annotations is a key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. More info: http://kubernetes.io/docs/user-guide/annotations \\n **Note**: The Cloud Run API may add additional annotations that were not provided in your config. If terraform plan shows a diff where a server-side annotation is added, you can add it to your config or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field. \\n Cloud Run (fully managed) uses the following annotation keys to configure features on a Service: \\n - 'run.googleapis.com/ingress' sets the [ingress settings](https://cloud.google.com/sdk/gcloud/reference/run/deploy#--ingress) for the Service. For example, '\\\"run.googleapis.com/ingress\\\" = \\\"all\\\"'.\"", args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { annotations: annotations },
        '#withAnnotationsMixin':: d.fn(help="\"Annotations is a key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. More info: http://kubernetes.io/docs/user-guide/annotations \\n **Note**: The Cloud Run API may add additional annotations that were not provided in your config. If terraform plan shows a diff where a server-side annotation is added, you can add it to your config or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field. \\n Cloud Run (fully managed) uses the following annotation keys to configure features on a Service: \\n - 'run.googleapis.com/ingress' sets the [ingress settings](https://cloud.google.com/sdk/gcloud/reference/run/deploy#--ingress) for the Service. For example, '\\\"run.googleapis.com/ingress\\\" = \\\"all\\\"'.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { annotations+: annotations },
        '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and routes. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { labels: labels },
        '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and routes. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { labels+: labels },
        '#withNamespace':: d.fn(help='"In Cloud Run the namespace must be equal to either the project ID or project number."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { namespace: namespace },
      },
      '#template':: d.obj(help="\"template holds the latest specification for the Revision to be stamped out. The template references the container image, and may also include labels and annotations that should be attached to the Revision. To correlate a Revision, and/or to force a Revision to be created when the spec doesn't otherwise change, a nonce label may be provided in the template metadata. For more details, see: https://github.com/knative/serving/blob/master/docs/client-conventions.md#associate-modifications-with-revisions \\n Cloud Run does not currently support referencing a build that is responsible for materializing the container image from source.\""),
      template: {
        '#metadata':: d.obj(help='"Optional metadata for this Revision, including labels and annotations. Name will be generated by the Configuration. To set minimum instances for this revision, use the \\"autoscaling.knative.dev/minScale\\" annotation key. To set maximum instances for this revision, use the \\"autoscaling.knative.dev/maxScale\\" annotation key. To set Cloud SQL connections for the revision, use the \\"run.googleapis.com/cloudsql-instances\\" annotation key."'),
        metadata: {
          '#withAnnotations':: d.fn(help='"Annotations is a key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. More info: http://kubernetes.io/docs/user-guide/annotations \\n **Note**: The Cloud Run API may add additional annotations that were not provided in your config. If terraform plan shows a diff where a server-side annotation is added, you can add it to your config or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field."', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotations(annotations): { annotations: annotations },
          '#withAnnotationsMixin':: d.fn(help='"Annotations is a key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. More info: http://kubernetes.io/docs/user-guide/annotations \\n **Note**: The Cloud Run API may add additional annotations that were not provided in your config. If terraform plan shows a diff where a server-side annotation is added, you can add it to your config or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
          withAnnotationsMixin(annotations): { annotations+: annotations },
          '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and routes. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
          withLabels(labels): { labels: labels },
          '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and routes. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
          withLabelsMixin(labels): { labels+: labels },
          '#withName':: d.fn(help='"Name must be unique within a namespace, within a Cloud Run region. Is required when creating resources. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withNamespace':: d.fn(help="\"In Cloud Run the namespace must be equal to either the project ID or project number. It will default to the resource's project.\"", args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { namespace: namespace },
        },
        '#spec':: d.obj(help='"RevisionSpec holds the desired state of the Revision (from the client)."'),
        spec: {
          '#containers':: d.obj(help='"Container defines the unit of execution for this Revision. In the context of a Revision, we disallow a number of the fields of this Container, including: name, ports, and volumeMounts. The runtime contract is documented here: https://github.com/knative/serving/blob/master/docs/runtime-contract.md"'),
          containers: {
            '#env':: d.obj(help='"List of environment variables to set in the container."'),
            env: {
              '#withName':: d.fn(help='"Name of the environment variable."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { name: name },
              '#withValue':: d.fn(help='"Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any route environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \\"\\"."', args=[d.arg(name='value', type=d.T.string)]),
              withValue(value): { value: value },
            },
            '#envFrom':: d.obj(help='"List of sources to populate environment variables in the container. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence."'),
            envFrom: {
              '#configMapRef':: d.obj(help='"The ConfigMap to select from."'),
              configMapRef: {
                '#localObjectReference':: d.obj(help='"The ConfigMap to select from."'),
                localObjectReference: {
                  '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
                  withName(name): { name: name },
                },
                '#withLocalObjectReference':: d.fn(help='"The ConfigMap to select from."', args=[d.arg(name='localObjectReference', type=d.T.array)]),
                withLocalObjectReference(localObjectReference): { localObjectReference: if std.isArray(v=localObjectReference) then localObjectReference else [localObjectReference] },
                '#withLocalObjectReferenceMixin':: d.fn(help='"The ConfigMap to select from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='localObjectReference', type=d.T.array)]),
                withLocalObjectReferenceMixin(localObjectReference): { localObjectReference+: if std.isArray(v=localObjectReference) then localObjectReference else [localObjectReference] },
                '#withOptional':: d.fn(help='"Specify whether the ConfigMap must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
                withOptional(optional): { optional: optional },
              },
              '#secretRef':: d.obj(help='"The Secret to select from."'),
              secretRef: {
                '#localObjectReference':: d.obj(help='"The Secret to select from."'),
                localObjectReference: {
                  '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
                  withName(name): { name: name },
                },
                '#withLocalObjectReference':: d.fn(help='"The Secret to select from."', args=[d.arg(name='localObjectReference', type=d.T.array)]),
                withLocalObjectReference(localObjectReference): { localObjectReference: if std.isArray(v=localObjectReference) then localObjectReference else [localObjectReference] },
                '#withLocalObjectReferenceMixin':: d.fn(help='"The Secret to select from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='localObjectReference', type=d.T.array)]),
                withLocalObjectReferenceMixin(localObjectReference): { localObjectReference+: if std.isArray(v=localObjectReference) then localObjectReference else [localObjectReference] },
                '#withOptional':: d.fn(help='"Specify whether the Secret must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
                withOptional(optional): { optional: optional },
              },
              '#withConfigMapRef':: d.fn(help='"The ConfigMap to select from."', args=[d.arg(name='configMapRef', type=d.T.array)]),
              withConfigMapRef(configMapRef): { configMapRef: if std.isArray(v=configMapRef) then configMapRef else [configMapRef] },
              '#withConfigMapRefMixin':: d.fn(help='"The ConfigMap to select from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='configMapRef', type=d.T.array)]),
              withConfigMapRefMixin(configMapRef): { configMapRef+: if std.isArray(v=configMapRef) then configMapRef else [configMapRef] },
              '#withPrefix':: d.fn(help='"An optional identifier to prepend to each key in the ConfigMap."', args=[d.arg(name='prefix', type=d.T.string)]),
              withPrefix(prefix): { prefix: prefix },
              '#withSecretRef':: d.fn(help='"The Secret to select from."', args=[d.arg(name='secretRef', type=d.T.array)]),
              withSecretRef(secretRef): { secretRef: if std.isArray(v=secretRef) then secretRef else [secretRef] },
              '#withSecretRefMixin':: d.fn(help='"The Secret to select from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='secretRef', type=d.T.array)]),
              withSecretRefMixin(secretRef): { secretRef+: if std.isArray(v=secretRef) then secretRef else [secretRef] },
            },
            '#ports':: d.obj(help='"List of open ports in the container. More Info: https://cloud.google.com/run/docs/reference/rest/v1/RevisionSpec#ContainerPort"'),
            ports: {
              '#withContainerPort':: d.fn(help='"Port number."', args=[d.arg(name='containerPort', type=d.T.integer)]),
              withContainerPort(containerPort): { containerPort: containerPort },
              '#withName':: d.fn(help='"Name of the port."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { name: name },
              '#withProtocol':: d.fn(help='"Protocol used on port. Defaults to TCP."', args=[d.arg(name='protocol', type=d.T.string)]),
              withProtocol(protocol): { protocol: protocol },
            },
            '#resources':: d.obj(help='"Compute Resources required by this container. Used to set values such as max memory More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits"'),
            resources: {
              '#withLimits':: d.fn(help="\"Limits describes the maximum amount of compute resources allowed. The values of the map is string form of the 'quantity' k8s type: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go\"", args=[d.arg(name='limits', type=d.T.object)]),
              withLimits(limits): { limits: limits },
              '#withLimitsMixin':: d.fn(help="\"Limits describes the maximum amount of compute resources allowed. The values of the map is string form of the 'quantity' k8s type: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='limits', type=d.T.object)]),
              withLimitsMixin(limits): { limits+: limits },
              '#withRequests':: d.fn(help="\"Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. The values of the map is string form of the 'quantity' k8s type: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go\"", args=[d.arg(name='requests', type=d.T.object)]),
              withRequests(requests): { requests: requests },
              '#withRequestsMixin':: d.fn(help="\"Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. The values of the map is string form of the 'quantity' k8s type: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='requests', type=d.T.object)]),
              withRequestsMixin(requests): { requests+: requests },
            },
            '#withArgs':: d.fn(help="\"Arguments to the entrypoint. The docker image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell\"", args=[d.arg(name='args', type=d.T.array)]),
            withArgs(args): { args: if std.isArray(v=args) then args else [args] },
            '#withArgsMixin':: d.fn(help="\"Arguments to the entrypoint. The docker image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='args', type=d.T.array)]),
            withArgsMixin(args): { args+: if std.isArray(v=args) then args else [args] },
            '#withCommand':: d.fn(help="\"Entrypoint array. Not executed within a shell. The docker image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell\"", args=[d.arg(name='command', type=d.T.array)]),
            withCommand(command): { command: if std.isArray(v=command) then command else [command] },
            '#withCommandMixin':: d.fn(help="\"Entrypoint array. Not executed within a shell. The docker image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='command', type=d.T.array)]),
            withCommandMixin(command): { command+: if std.isArray(v=command) then command else [command] },
            '#withEnv':: d.fn(help='"List of environment variables to set in the container."', args=[d.arg(name='env', type=d.T.array)]),
            withEnv(env): { env: if std.isArray(v=env) then env else [env] },
            '#withEnvFrom':: d.fn(help='"List of sources to populate environment variables in the container. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence."', args=[d.arg(name='envFrom', type=d.T.array)]),
            withEnvFrom(envFrom): { envFrom: if std.isArray(v=envFrom) then envFrom else [envFrom] },
            '#withEnvFromMixin':: d.fn(help='"List of sources to populate environment variables in the container. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='envFrom', type=d.T.array)]),
            withEnvFromMixin(envFrom): { envFrom+: if std.isArray(v=envFrom) then envFrom else [envFrom] },
            '#withEnvMixin':: d.fn(help='"List of environment variables to set in the container."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='env', type=d.T.array)]),
            withEnvMixin(env): { env+: if std.isArray(v=env) then env else [env] },
            '#withImage':: d.fn(help='"Docker image name. This is most often a reference to a container located in the container registry, such as gcr.io/cloudrun/hello More info: https://kubernetes.io/docs/concepts/containers/images"', args=[d.arg(name='image', type=d.T.string)]),
            withImage(image): { image: image },
            '#withPorts':: d.fn(help='"List of open ports in the container. More Info: https://cloud.google.com/run/docs/reference/rest/v1/RevisionSpec#ContainerPort"', args=[d.arg(name='ports', type=d.T.array)]),
            withPorts(ports): { ports: if std.isArray(v=ports) then ports else [ports] },
            '#withPortsMixin':: d.fn(help='"List of open ports in the container. More Info: https://cloud.google.com/run/docs/reference/rest/v1/RevisionSpec#ContainerPort"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ports', type=d.T.array)]),
            withPortsMixin(ports): { ports+: if std.isArray(v=ports) then ports else [ports] },
            '#withResources':: d.fn(help='"Compute Resources required by this container. Used to set values such as max memory More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits"', args=[d.arg(name='resources', type=d.T.array)]),
            withResources(resources): { resources: if std.isArray(v=resources) then resources else [resources] },
            '#withResourcesMixin':: d.fn(help='"Compute Resources required by this container. Used to set values such as max memory More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='resources', type=d.T.array)]),
            withResourcesMixin(resources): { resources+: if std.isArray(v=resources) then resources else [resources] },
            '#withWorkingDir':: d.fn(help="\"Container's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image.\"", args=[d.arg(name='workingDir', type=d.T.string)]),
            withWorkingDir(workingDir): { workingDir: workingDir },
          },
          '#withContainerConcurrency':: d.fn(help="\"ContainerConcurrency specifies the maximum allowed in-flight (concurrent) requests per container of the Revision. Values are: - '0' thread-safe, the system should manage the max concurrency. This is the default value. - '1' not-thread-safe. Single concurrency - '2-N' thread-safe, max concurrency of N\"", args=[d.arg(name='containerConcurrency', type=d.T.integer)]),
          withContainerConcurrency(containerConcurrency): { containerConcurrency: containerConcurrency },
          '#withContainers':: d.fn(help='"Container defines the unit of execution for this Revision. In the context of a Revision, we disallow a number of the fields of this Container, including: name, ports, and volumeMounts. The runtime contract is documented here: https://github.com/knative/serving/blob/master/docs/runtime-contract.md"', args=[d.arg(name='containers', type=d.T.array)]),
          withContainers(containers): { containers: if std.isArray(v=containers) then containers else [containers] },
          '#withContainersMixin':: d.fn(help='"Container defines the unit of execution for this Revision. In the context of a Revision, we disallow a number of the fields of this Container, including: name, ports, and volumeMounts. The runtime contract is documented here: https://github.com/knative/serving/blob/master/docs/runtime-contract.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='containers', type=d.T.array)]),
          withContainersMixin(containers): { containers+: if std.isArray(v=containers) then containers else [containers] },
          '#withServiceAccountName':: d.fn(help="\"Email address of the IAM service account associated with the revision of the service. The service account represents the identity of the running revision, and determines what permissions the revision has. If not provided, the revision will use the project's default service account.\"", args=[d.arg(name='serviceAccountName', type=d.T.string)]),
          withServiceAccountName(serviceAccountName): { serviceAccountName: serviceAccountName },
          '#withTimeoutSeconds':: d.fn(help='"TimeoutSeconds holds the max duration the instance is allowed for responding to a request."', args=[d.arg(name='timeoutSeconds', type=d.T.integer)]),
          withTimeoutSeconds(timeoutSeconds): { timeoutSeconds: timeoutSeconds },
        },
        '#withMetadata':: d.fn(help='"Optional metadata for this Revision, including labels and annotations. Name will be generated by the Configuration. To set minimum instances for this revision, use the \\"autoscaling.knative.dev/minScale\\" annotation key. To set maximum instances for this revision, use the \\"autoscaling.knative.dev/maxScale\\" annotation key. To set Cloud SQL connections for the revision, use the \\"run.googleapis.com/cloudsql-instances\\" annotation key."', args=[d.arg(name='metadata', type=d.T.array)]),
        withMetadata(metadata): { metadata: if std.isArray(v=metadata) then metadata else [metadata] },
        '#withMetadataMixin':: d.fn(help='"Optional metadata for this Revision, including labels and annotations. Name will be generated by the Configuration. To set minimum instances for this revision, use the \\"autoscaling.knative.dev/minScale\\" annotation key. To set maximum instances for this revision, use the \\"autoscaling.knative.dev/maxScale\\" annotation key. To set Cloud SQL connections for the revision, use the \\"run.googleapis.com/cloudsql-instances\\" annotation key."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.array)]),
        withMetadataMixin(metadata): { metadata+: if std.isArray(v=metadata) then metadata else [metadata] },
        '#withSpec':: d.fn(help='"RevisionSpec holds the desired state of the Revision (from the client)."', args=[d.arg(name='spec', type=d.T.array)]),
        withSpec(spec): { spec: if std.isArray(v=spec) then spec else [spec] },
        '#withSpecMixin':: d.fn(help='"RevisionSpec holds the desired state of the Revision (from the client)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='spec', type=d.T.array)]),
        withSpecMixin(spec): { spec+: if std.isArray(v=spec) then spec else [spec] },
      },
      '#traffic':: d.obj(help='"Traffic specifies how to distribute traffic over a collection of Knative Revisions and Configurations"'),
      traffic: {
        '#withLatestRevision':: d.fn(help='"LatestRevision may be optionally provided to indicate that the latest ready Revision of the Configuration should be used for this traffic target. When provided LatestRevision must be true if RevisionName is empty; it must be false when RevisionName is non-empty."', args=[d.arg(name='latestRevision', type=d.T.boolean)]),
        withLatestRevision(latestRevision): { latestRevision: latestRevision },
        '#withPercent':: d.fn(help='"Percent specifies percent of the traffic to this Revision or Configuration."', args=[d.arg(name='percent', type=d.T.integer)]),
        withPercent(percent): { percent: percent },
        '#withRevisionName':: d.fn(help='"RevisionName of a specific revision to which to send this portion of traffic."', args=[d.arg(name='revisionName', type=d.T.string)]),
        withRevisionName(revisionName): { revisionName: revisionName },
      },
      '#withAutogenerateRevisionName':: d.fn(help='', args=[d.arg(name='autogenerateRevisionName', type=d.T.boolean)]),
      withAutogenerateRevisionName(autogenerateRevisionName): { spec+: { forProvider+: { autogenerateRevisionName: autogenerateRevisionName } } },
      '#withLocation':: d.fn(help='"The location of the cloud run instance. eg us-central1"', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { forProvider+: { location: location } } },
      '#withMetadata':: d.fn(help='"Metadata associated with this Service, including name, namespace, labels, and annotations."', args=[d.arg(name='metadata', type=d.T.array)]),
      withMetadata(metadata): { spec+: { forProvider+: { metadata: if std.isArray(v=metadata) then metadata else [metadata] } } },
      '#withMetadataMixin':: d.fn(help='"Metadata associated with this Service, including name, namespace, labels, and annotations."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.array)]),
      withMetadataMixin(metadata): { spec+: { forProvider+: { metadata+: if std.isArray(v=metadata) then metadata else [metadata] } } },
      '#withName':: d.fn(help='"Name must be unique within a namespace, within a Cloud Run region. Is required when creating resources. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { forProvider+: { name: name } } },
      '#withProject':: d.fn(help='', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withTemplate':: d.fn(help="\"template holds the latest specification for the Revision to be stamped out. The template references the container image, and may also include labels and annotations that should be attached to the Revision. To correlate a Revision, and/or to force a Revision to be created when the spec doesn't otherwise change, a nonce label may be provided in the template metadata. For more details, see: https://github.com/knative/serving/blob/master/docs/client-conventions.md#associate-modifications-with-revisions \\n Cloud Run does not currently support referencing a build that is responsible for materializing the container image from source.\"", args=[d.arg(name='template', type=d.T.array)]),
      withTemplate(template): { spec+: { forProvider+: { template: if std.isArray(v=template) then template else [template] } } },
      '#withTemplateMixin':: d.fn(help="\"template holds the latest specification for the Revision to be stamped out. The template references the container image, and may also include labels and annotations that should be attached to the Revision. To correlate a Revision, and/or to force a Revision to be created when the spec doesn't otherwise change, a nonce label may be provided in the template metadata. For more details, see: https://github.com/knative/serving/blob/master/docs/client-conventions.md#associate-modifications-with-revisions \\n Cloud Run does not currently support referencing a build that is responsible for materializing the container image from source.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='template', type=d.T.array)]),
      withTemplateMixin(template): { spec+: { forProvider+: { template+: if std.isArray(v=template) then template else [template] } } },
      '#withTraffic':: d.fn(help='"Traffic specifies how to distribute traffic over a collection of Knative Revisions and Configurations"', args=[d.arg(name='traffic', type=d.T.array)]),
      withTraffic(traffic): { spec+: { forProvider+: { traffic: if std.isArray(v=traffic) then traffic else [traffic] } } },
      '#withTrafficMixin':: d.fn(help='"Traffic specifies how to distribute traffic over a collection of Knative Revisions and Configurations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='traffic', type=d.T.array)]),
      withTrafficMixin(traffic): { spec+: { forProvider+: { traffic+: if std.isArray(v=traffic) then traffic else [traffic] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
