{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='springCloudService', url='', help='"SpringCloudService is the Schema for the SpringCloudServices API. Manages an Azure Spring Cloud Service."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of SpringCloudService', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'appplatform.azure.upbound.io/v1beta1',
    kind: 'SpringCloudService',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"SpringCloudServiceSpec defines the desired state of SpringCloudService"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#configServerGitSetting':: d.obj(help='"A config_server_git_setting block as defined below. This field is applicable only for Spring Cloud Service with basic and standard tier."'),
      configServerGitSetting: {
        '#httpBasicAuth':: d.obj(help='"A http_basic_auth block as defined below."'),
        httpBasicAuth: {
          '#passwordSecretRef':: d.obj(help='"The password used to access the Git repository server, required when the Git repository server supports HTTP Basic Authentication."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#withUsername':: d.fn(help="\"The username that's used to access the Git repository server, required when the Git repository server supports HTTP Basic Authentication.\"", args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
        },
        '#repository':: d.obj(help='"One or more repository blocks as defined below."'),
        repository: {
          '#httpBasicAuth':: d.obj(help='"A http_basic_auth block as defined below."'),
          httpBasicAuth: {
            '#passwordSecretRef':: d.obj(help='"The password used to access the Git repository server, required when the Git repository server supports HTTP Basic Authentication."'),
            passwordSecretRef: {
              '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { passwordSecretRef+: { key: key } },
              '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { passwordSecretRef+: { name: name } },
              '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
            },
            '#withUsername':: d.fn(help="\"The username that's used to access the Git repository server, required when the Git repository server supports HTTP Basic Authentication.\"", args=[d.arg(name='username', type=d.T.string)]),
            withUsername(username): { username: username },
          },
          '#sshAuth':: d.obj(help='"A ssh_auth block as defined below."'),
          sshAuth: {
            '#hostKeySecretRef':: d.obj(help='"The host key of the Git repository server, should not include the algorithm prefix as covered by host-key-algorithm."'),
            hostKeySecretRef: {
              '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { hostKeySecretRef+: { key: key } },
              '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { hostKeySecretRef+: { name: name } },
              '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { hostKeySecretRef+: { namespace: namespace } },
            },
            '#privateKeySecretRef':: d.obj(help='"The SSH private key to access the Git repository, required when the URI starts with git@ or ssh://."'),
            privateKeySecretRef: {
              '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { privateKeySecretRef+: { key: key } },
              '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { privateKeySecretRef+: { name: name } },
              '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { privateKeySecretRef+: { namespace: namespace } },
            },
            '#withHostKeyAlgorithm':: d.fn(help='"The host key algorithm, should be ssh-dss, ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, or ecdsa-sha2-nistp521. Required only if host-key exists."', args=[d.arg(name='hostKeyAlgorithm', type=d.T.string)]),
            withHostKeyAlgorithm(hostKeyAlgorithm): { hostKeyAlgorithm: hostKeyAlgorithm },
            '#withStrictHostKeyCheckingEnabled':: d.fn(help='"Indicates whether the Config Server instance will fail to start if the host_key does not match. Defaults to true."', args=[d.arg(name='strictHostKeyCheckingEnabled', type=d.T.boolean)]),
            withStrictHostKeyCheckingEnabled(strictHostKeyCheckingEnabled): { strictHostKeyCheckingEnabled: strictHostKeyCheckingEnabled },
          },
          '#withHttpBasicAuth':: d.fn(help='"A http_basic_auth block as defined below."', args=[d.arg(name='httpBasicAuth', type=d.T.array)]),
          withHttpBasicAuth(httpBasicAuth): { httpBasicAuth: if std.isArray(v=httpBasicAuth) then httpBasicAuth else [httpBasicAuth] },
          '#withHttpBasicAuthMixin':: d.fn(help='"A http_basic_auth block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='httpBasicAuth', type=d.T.array)]),
          withHttpBasicAuthMixin(httpBasicAuth): { httpBasicAuth+: if std.isArray(v=httpBasicAuth) then httpBasicAuth else [httpBasicAuth] },
          '#withLabel':: d.fn(help='"The default label of the Git repository, should be the branch name, tag name, or commit-id of the repository."', args=[d.arg(name='label', type=d.T.string)]),
          withLabel(label): { label: label },
          '#withName':: d.fn(help='"A name to identify on the Git repository, required only if repos exists. Changing this forces a new resource to be created."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withPattern':: d.fn(help='"An array of strings used to match an application name. For each pattern, use the {application}/{profile} format with wildcards."', args=[d.arg(name='pattern', type=d.T.array)]),
          withPattern(pattern): { pattern: if std.isArray(v=pattern) then pattern else [pattern] },
          '#withPatternMixin':: d.fn(help='"An array of strings used to match an application name. For each pattern, use the {application}/{profile} format with wildcards."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='pattern', type=d.T.array)]),
          withPatternMixin(pattern): { pattern+: if std.isArray(v=pattern) then pattern else [pattern] },
          '#withSearchPaths':: d.fn(help='"An array of strings used to search subdirectories of the Git repository."', args=[d.arg(name='searchPaths', type=d.T.array)]),
          withSearchPaths(searchPaths): { searchPaths: if std.isArray(v=searchPaths) then searchPaths else [searchPaths] },
          '#withSearchPathsMixin':: d.fn(help='"An array of strings used to search subdirectories of the Git repository."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='searchPaths', type=d.T.array)]),
          withSearchPathsMixin(searchPaths): { searchPaths+: if std.isArray(v=searchPaths) then searchPaths else [searchPaths] },
          '#withSshAuth':: d.fn(help='"A ssh_auth block as defined below."', args=[d.arg(name='sshAuth', type=d.T.array)]),
          withSshAuth(sshAuth): { sshAuth: if std.isArray(v=sshAuth) then sshAuth else [sshAuth] },
          '#withSshAuthMixin':: d.fn(help='"A ssh_auth block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sshAuth', type=d.T.array)]),
          withSshAuthMixin(sshAuth): { sshAuth+: if std.isArray(v=sshAuth) then sshAuth else [sshAuth] },
          '#withUri':: d.fn(help="\"The URI of the Git repository that's used as the Config Server back end should be started with http://, https://, git@, or ssh://.\"", args=[d.arg(name='uri', type=d.T.string)]),
          withUri(uri): { uri: uri },
        },
        '#sshAuth':: d.obj(help='"A ssh_auth block as defined below."'),
        sshAuth: {
          '#hostKeySecretRef':: d.obj(help='"The host key of the Git repository server, should not include the algorithm prefix as covered by host-key-algorithm."'),
          hostKeySecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { hostKeySecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { hostKeySecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { hostKeySecretRef+: { namespace: namespace } },
          },
          '#privateKeySecretRef':: d.obj(help='"The SSH private key to access the Git repository, required when the URI starts with git@ or ssh://."'),
          privateKeySecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { privateKeySecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { privateKeySecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { privateKeySecretRef+: { namespace: namespace } },
          },
          '#withHostKeyAlgorithm':: d.fn(help='"The host key algorithm, should be ssh-dss, ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, or ecdsa-sha2-nistp521. Required only if host-key exists."', args=[d.arg(name='hostKeyAlgorithm', type=d.T.string)]),
          withHostKeyAlgorithm(hostKeyAlgorithm): { hostKeyAlgorithm: hostKeyAlgorithm },
          '#withStrictHostKeyCheckingEnabled':: d.fn(help='"Indicates whether the Config Server instance will fail to start if the host_key does not match. Defaults to true."', args=[d.arg(name='strictHostKeyCheckingEnabled', type=d.T.boolean)]),
          withStrictHostKeyCheckingEnabled(strictHostKeyCheckingEnabled): { strictHostKeyCheckingEnabled: strictHostKeyCheckingEnabled },
        },
        '#withHttpBasicAuth':: d.fn(help='"A http_basic_auth block as defined below."', args=[d.arg(name='httpBasicAuth', type=d.T.array)]),
        withHttpBasicAuth(httpBasicAuth): { httpBasicAuth: if std.isArray(v=httpBasicAuth) then httpBasicAuth else [httpBasicAuth] },
        '#withHttpBasicAuthMixin':: d.fn(help='"A http_basic_auth block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='httpBasicAuth', type=d.T.array)]),
        withHttpBasicAuthMixin(httpBasicAuth): { httpBasicAuth+: if std.isArray(v=httpBasicAuth) then httpBasicAuth else [httpBasicAuth] },
        '#withLabel':: d.fn(help='"The default label of the Git repository, should be the branch name, tag name, or commit-id of the repository."', args=[d.arg(name='label', type=d.T.string)]),
        withLabel(label): { label: label },
        '#withRepository':: d.fn(help='"One or more repository blocks as defined below."', args=[d.arg(name='repository', type=d.T.array)]),
        withRepository(repository): { repository: if std.isArray(v=repository) then repository else [repository] },
        '#withRepositoryMixin':: d.fn(help='"One or more repository blocks as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='repository', type=d.T.array)]),
        withRepositoryMixin(repository): { repository+: if std.isArray(v=repository) then repository else [repository] },
        '#withSearchPaths':: d.fn(help='"An array of strings used to search subdirectories of the Git repository."', args=[d.arg(name='searchPaths', type=d.T.array)]),
        withSearchPaths(searchPaths): { searchPaths: if std.isArray(v=searchPaths) then searchPaths else [searchPaths] },
        '#withSearchPathsMixin':: d.fn(help='"An array of strings used to search subdirectories of the Git repository."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='searchPaths', type=d.T.array)]),
        withSearchPathsMixin(searchPaths): { searchPaths+: if std.isArray(v=searchPaths) then searchPaths else [searchPaths] },
        '#withSshAuth':: d.fn(help='"A ssh_auth block as defined below."', args=[d.arg(name='sshAuth', type=d.T.array)]),
        withSshAuth(sshAuth): { sshAuth: if std.isArray(v=sshAuth) then sshAuth else [sshAuth] },
        '#withSshAuthMixin':: d.fn(help='"A ssh_auth block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sshAuth', type=d.T.array)]),
        withSshAuthMixin(sshAuth): { sshAuth+: if std.isArray(v=sshAuth) then sshAuth else [sshAuth] },
        '#withUri':: d.fn(help='"The URI of the default Git repository used as the Config Server back end, should be started with http://, https://, git@, or ssh://."', args=[d.arg(name='uri', type=d.T.string)]),
        withUri(uri): { uri: uri },
      },
      '#network':: d.obj(help='"A network block as defined below. Changing this forces a new resource to be created."'),
      network: {
        '#appSubnetIdRef':: d.obj(help='"Reference to a Subnet in network to populate appSubnetId."'),
        appSubnetIdRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { appSubnetIdRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { appSubnetIdRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { appSubnetIdRef+: { name: name } },
        },
        '#appSubnetIdSelector':: d.obj(help='"Selector for a Subnet in network to populate appSubnetId."'),
        appSubnetIdSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { appSubnetIdSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { appSubnetIdSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { appSubnetIdSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { appSubnetIdSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { appSubnetIdSelector+: { matchLabels+: matchLabels } },
        },
        '#serviceRuntimeSubnetIdRef':: d.obj(help='"Reference to a Subnet in network to populate serviceRuntimeSubnetId."'),
        serviceRuntimeSubnetIdRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { serviceRuntimeSubnetIdRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { serviceRuntimeSubnetIdRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { serviceRuntimeSubnetIdRef+: { name: name } },
        },
        '#serviceRuntimeSubnetIdSelector':: d.obj(help='"Selector for a Subnet in network to populate serviceRuntimeSubnetId."'),
        serviceRuntimeSubnetIdSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { serviceRuntimeSubnetIdSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { serviceRuntimeSubnetIdSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { serviceRuntimeSubnetIdSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { serviceRuntimeSubnetIdSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { serviceRuntimeSubnetIdSelector+: { matchLabels+: matchLabels } },
        },
        '#withAppNetworkResourceGroup':: d.fn(help='"Specifies the Name of the resource group containing network resources of Azure Spring Cloud Apps. Changing this forces a new resource to be created."', args=[d.arg(name='appNetworkResourceGroup', type=d.T.string)]),
        withAppNetworkResourceGroup(appNetworkResourceGroup): { appNetworkResourceGroup: appNetworkResourceGroup },
        '#withAppSubnetId':: d.fn(help='"Specifies the ID of the Subnet which should host the Spring Boot Applications deployed in this Spring Cloud Service. Changing this forces a new resource to be created."', args=[d.arg(name='appSubnetId', type=d.T.string)]),
        withAppSubnetId(appSubnetId): { appSubnetId: appSubnetId },
        '#withCidrRanges':: d.fn(help='"A list of (at least 3) CIDR ranges (at least /16) which are used to host the Spring Cloud infrastructure, which must not overlap with any existing CIDR ranges in the Subnet. Changing this forces a new resource to be created."', args=[d.arg(name='cidrRanges', type=d.T.array)]),
        withCidrRanges(cidrRanges): { cidrRanges: if std.isArray(v=cidrRanges) then cidrRanges else [cidrRanges] },
        '#withCidrRangesMixin':: d.fn(help='"A list of (at least 3) CIDR ranges (at least /16) which are used to host the Spring Cloud infrastructure, which must not overlap with any existing CIDR ranges in the Subnet. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='cidrRanges', type=d.T.array)]),
        withCidrRangesMixin(cidrRanges): { cidrRanges+: if std.isArray(v=cidrRanges) then cidrRanges else [cidrRanges] },
        '#withReadTimeoutSeconds':: d.fn(help='"Ingress read time out in seconds. Changing this forces a new resource to be created."', args=[d.arg(name='readTimeoutSeconds', type=d.T.number)]),
        withReadTimeoutSeconds(readTimeoutSeconds): { readTimeoutSeconds: readTimeoutSeconds },
        '#withServiceRuntimeNetworkResourceGroup':: d.fn(help='"Specifies the Name of the resource group containing network resources of Azure Spring Cloud Service Runtime. Changing this forces a new resource to be created."', args=[d.arg(name='serviceRuntimeNetworkResourceGroup', type=d.T.string)]),
        withServiceRuntimeNetworkResourceGroup(serviceRuntimeNetworkResourceGroup): { serviceRuntimeNetworkResourceGroup: serviceRuntimeNetworkResourceGroup },
        '#withServiceRuntimeSubnetId':: d.fn(help='"Specifies the ID of the Subnet where the Service Runtime components of the Spring Cloud Service will exist. Changing this forces a new resource to be created."', args=[d.arg(name='serviceRuntimeSubnetId', type=d.T.string)]),
        withServiceRuntimeSubnetId(serviceRuntimeSubnetId): { serviceRuntimeSubnetId: serviceRuntimeSubnetId },
      },
      '#resourceGroupNameRef':: d.obj(help='"Reference to a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { resourceGroupNameRef+: { name: name } } } },
      },
      '#resourceGroupNameSelector':: d.obj(help='"Selector for a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#trace':: d.obj(help='"A trace block as defined below."'),
      trace: {
        '#connectionStringRef':: d.obj(help='"Reference to a ApplicationInsights in insights to populate connectionString."'),
        connectionStringRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { connectionStringRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { connectionStringRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { connectionStringRef+: { name: name } },
        },
        '#connectionStringSelector':: d.obj(help='"Selector for a ApplicationInsights in insights to populate connectionString."'),
        connectionStringSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { connectionStringSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { connectionStringSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { connectionStringSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { connectionStringSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { connectionStringSelector+: { matchLabels+: matchLabels } },
        },
        '#withConnectionString':: d.fn(help='"The connection string used for Application Insights."', args=[d.arg(name='connectionString', type=d.T.string)]),
        withConnectionString(connectionString): { connectionString: connectionString },
        '#withSampleRate':: d.fn(help='"The sampling rate of Application Insights Agent. Must be between 0.0 and 100.0. Defaults to 10.0."', args=[d.arg(name='sampleRate', type=d.T.number)]),
        withSampleRate(sampleRate): { sampleRate: sampleRate },
      },
      '#withBuildAgentPoolSize':: d.fn(help="\"Specifies the size for this Spring Cloud Service's default build agent pool. Possible values are S1, S2, S3, S4 and S5. This field is applicable only for Spring Cloud Service with enterprise tier.\"", args=[d.arg(name='buildAgentPoolSize', type=d.T.string)]),
      withBuildAgentPoolSize(buildAgentPoolSize): { spec+: { forProvider+: { buildAgentPoolSize: buildAgentPoolSize } } },
      '#withConfigServerGitSetting':: d.fn(help='"A config_server_git_setting block as defined below. This field is applicable only for Spring Cloud Service with basic and standard tier."', args=[d.arg(name='configServerGitSetting', type=d.T.array)]),
      withConfigServerGitSetting(configServerGitSetting): { spec+: { forProvider+: { configServerGitSetting: if std.isArray(v=configServerGitSetting) then configServerGitSetting else [configServerGitSetting] } } },
      '#withConfigServerGitSettingMixin':: d.fn(help='"A config_server_git_setting block as defined below. This field is applicable only for Spring Cloud Service with basic and standard tier."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='configServerGitSetting', type=d.T.array)]),
      withConfigServerGitSettingMixin(configServerGitSetting): { spec+: { forProvider+: { configServerGitSetting+: if std.isArray(v=configServerGitSetting) then configServerGitSetting else [configServerGitSetting] } } },
      '#withLocation':: d.fn(help='"Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { forProvider+: { location: location } } },
      '#withLogStreamPublicEndpointEnabled':: d.fn(help='"Should the log stream in vnet injection instance could be accessed from Internet?"', args=[d.arg(name='logStreamPublicEndpointEnabled', type=d.T.boolean)]),
      withLogStreamPublicEndpointEnabled(logStreamPublicEndpointEnabled): { spec+: { forProvider+: { logStreamPublicEndpointEnabled: logStreamPublicEndpointEnabled } } },
      '#withNetwork':: d.fn(help='"A network block as defined below. Changing this forces a new resource to be created."', args=[d.arg(name='network', type=d.T.array)]),
      withNetwork(network): { spec+: { forProvider+: { network: if std.isArray(v=network) then network else [network] } } },
      '#withNetworkMixin':: d.fn(help='"A network block as defined below. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='network', type=d.T.array)]),
      withNetworkMixin(network): { spec+: { forProvider+: { network+: if std.isArray(v=network) then network else [network] } } },
      '#withResourceGroupName':: d.fn(help='"Specifies The name of the resource group in which to create the Spring Cloud Service. Changing this forces a new resource to be created."', args=[d.arg(name='resourceGroupName', type=d.T.string)]),
      withResourceGroupName(resourceGroupName): { spec+: { forProvider+: { resourceGroupName: resourceGroupName } } },
      '#withServiceRegistryEnabled':: d.fn(help='"Whether enable the default Service Registry. This field is applicable only for Spring Cloud Service with enterprise tier."', args=[d.arg(name='serviceRegistryEnabled', type=d.T.boolean)]),
      withServiceRegistryEnabled(serviceRegistryEnabled): { spec+: { forProvider+: { serviceRegistryEnabled: serviceRegistryEnabled } } },
      '#withSkuName':: d.fn(help='"Specifies the SKU Name for this Spring Cloud Service. Possible values are B0, S0 and E0. Defaults to S0. Changing this forces a new resource to be created."', args=[d.arg(name='skuName', type=d.T.string)]),
      withSkuName(skuName): { spec+: { forProvider+: { skuName: skuName } } },
      '#withTags':: d.fn(help='"A mapping of tags to assign to the resource."', args=[d.arg(name='tags', type=d.T.object)]),
      withTags(tags): { spec+: { forProvider+: { tags: tags } } },
      '#withTagsMixin':: d.fn(help='"A mapping of tags to assign to the resource."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
      withTagsMixin(tags): { spec+: { forProvider+: { tags+: tags } } },
      '#withTrace':: d.fn(help='"A trace block as defined below."', args=[d.arg(name='trace', type=d.T.array)]),
      withTrace(trace): { spec+: { forProvider+: { trace: if std.isArray(v=trace) then trace else [trace] } } },
      '#withTraceMixin':: d.fn(help='"A trace block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='trace', type=d.T.array)]),
      withTraceMixin(trace): { spec+: { forProvider+: { trace+: if std.isArray(v=trace) then trace else [trace] } } },
      '#withZoneRedundant':: d.fn(help='"Whether zone redundancy is enabled for this Spring Cloud Service. Defaults to false."', args=[d.arg(name='zoneRedundant', type=d.T.boolean)]),
      withZoneRedundant(zoneRedundant): { spec+: { forProvider+: { zoneRedundant: zoneRedundant } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
