{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='regionBackendService', url='', help='"RegionBackendService is the Schema for the RegionBackendServices API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of RegionBackendService', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'compute.gcp.jet.crossplane.io/v1alpha1',
    kind: 'RegionBackendService',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"RegionBackendServiceSpec defines the desired state of RegionBackendService"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#backend':: d.obj(help='"The set of backends that serve this RegionBackendService."'),
      backend: {
        '#withBalancingMode':: d.fn(help='"Specifies the balancing mode for this backend. Default value: \\"CONNECTION\\" Possible values: [\\"UTILIZATION\\", \\"RATE\\", \\"CONNECTION\\"]"', args=[d.arg(name='balancingMode', type=d.T.string)]),
        withBalancingMode(balancingMode): { balancingMode: balancingMode },
        '#withCapacityScaler':: d.fn(help="\"A multiplier applied to the group's maximum servicing capacity (based on UTILIZATION, RATE or CONNECTION). \\n ~\u003e**NOTE**: This field cannot be set for INTERNAL region backend services (default loadBalancingScheme), but is required for non-INTERNAL backend service. The total capacity_scaler for all backends must be non-zero. \\n A setting of 0 means the group is completely drained, offering 0% of its available Capacity. Valid range is [0.0,1.0].\"", args=[d.arg(name='capacityScaler', type=d.T.number)]),
        withCapacityScaler(capacityScaler): { capacityScaler: capacityScaler },
        '#withDescription':: d.fn(help='"An optional description of this resource. Provide this property when you create the resource."', args=[d.arg(name='description', type=d.T.string)]),
        withDescription(description): { description: description },
        '#withFailover':: d.fn(help='"This field designates whether this is a failover backend. More than one failover backend can be configured for a given RegionBackendService."', args=[d.arg(name='failover', type=d.T.boolean)]),
        withFailover(failover): { failover: failover },
        '#withGroup':: d.fn(help="\"The fully-qualified URL of an Instance Group or Network Endpoint Group resource. In case of instance group this defines the list of instances that serve traffic. Member virtual machine instances from each instance group must live in the same zone as the instance group itself. No two backends in a backend service are allowed to use same Instance Group resource. \\n For Network Endpoint Groups this defines list of endpoints. All endpoints of Network Endpoint Group must be hosted on instances located in the same zone as the Network Endpoint Group. \\n Backend services cannot mix Instance Group and Network Endpoint Group backends. \\n When the 'load_balancing_scheme' is INTERNAL, only instance groups are supported. \\n Note that you must specify an Instance Group or Network Endpoint Group resource using the fully-qualified URL, rather than a partial URL.\"", args=[d.arg(name='group', type=d.T.string)]),
        withGroup(group): { group: group },
        '#withMaxConnections':: d.fn(help='"The max number of simultaneous connections for the group. Can be used with either CONNECTION or UTILIZATION balancing modes. Cannot be set for INTERNAL backend services. \\n For CONNECTION mode, either maxConnections or one of maxConnectionsPerInstance or maxConnectionsPerEndpoint, as appropriate for group type, must be set."', args=[d.arg(name='maxConnections', type=d.T.integer)]),
        withMaxConnections(maxConnections): { maxConnections: maxConnections },
        '#withMaxConnectionsPerEndpoint':: d.fn(help='"The max number of simultaneous connections that a single backend network endpoint can handle. Cannot be set for INTERNAL backend services. \\n This is used to calculate the capacity of the group. Can be used in either CONNECTION or UTILIZATION balancing modes. For CONNECTION mode, either maxConnections or maxConnectionsPerEndpoint must be set."', args=[d.arg(name='maxConnectionsPerEndpoint', type=d.T.integer)]),
        withMaxConnectionsPerEndpoint(maxConnectionsPerEndpoint): { maxConnectionsPerEndpoint: maxConnectionsPerEndpoint },
        '#withMaxConnectionsPerInstance':: d.fn(help='"The max number of simultaneous connections that a single backend instance can handle. Cannot be set for INTERNAL backend services. \\n This is used to calculate the capacity of the group. Can be used in either CONNECTION or UTILIZATION balancing modes. For CONNECTION mode, either maxConnections or maxConnectionsPerInstance must be set."', args=[d.arg(name='maxConnectionsPerInstance', type=d.T.integer)]),
        withMaxConnectionsPerInstance(maxConnectionsPerInstance): { maxConnectionsPerInstance: maxConnectionsPerInstance },
        '#withMaxRate':: d.fn(help='"The max requests per second (RPS) of the group. Cannot be set for INTERNAL backend services. \\n Can be used with either RATE or UTILIZATION balancing modes, but required if RATE mode. Either maxRate or one of maxRatePerInstance or maxRatePerEndpoint, as appropriate for group type, must be set."', args=[d.arg(name='maxRate', type=d.T.integer)]),
        withMaxRate(maxRate): { maxRate: maxRate },
        '#withMaxRatePerEndpoint':: d.fn(help='"The max requests per second (RPS) that a single backend network endpoint can handle. This is used to calculate the capacity of the group. Can be used in either balancing mode. For RATE mode, either maxRate or maxRatePerEndpoint must be set. Cannot be set for INTERNAL backend services."', args=[d.arg(name='maxRatePerEndpoint', type=d.T.number)]),
        withMaxRatePerEndpoint(maxRatePerEndpoint): { maxRatePerEndpoint: maxRatePerEndpoint },
        '#withMaxRatePerInstance':: d.fn(help='"The max requests per second (RPS) that a single backend instance can handle. This is used to calculate the capacity of the group. Can be used in either balancing mode. For RATE mode, either maxRate or maxRatePerInstance must be set. Cannot be set for INTERNAL backend services."', args=[d.arg(name='maxRatePerInstance', type=d.T.number)]),
        withMaxRatePerInstance(maxRatePerInstance): { maxRatePerInstance: maxRatePerInstance },
        '#withMaxUtilization':: d.fn(help='"Used when balancingMode is UTILIZATION. This ratio defines the CPU utilization target for the group. Valid range is [0.0, 1.0]. Cannot be set for INTERNAL backend services."', args=[d.arg(name='maxUtilization', type=d.T.number)]),
        withMaxUtilization(maxUtilization): { maxUtilization: maxUtilization },
      },
      '#cdnPolicy':: d.obj(help='"Cloud CDN configuration for this BackendService."'),
      cdnPolicy: {
        '#cacheKeyPolicy':: d.obj(help='"The CacheKeyPolicy for this CdnPolicy."'),
        cacheKeyPolicy: {
          '#withIncludeHost':: d.fn(help='"If true requests to different hosts will be cached separately."', args=[d.arg(name='includeHost', type=d.T.boolean)]),
          withIncludeHost(includeHost): { includeHost: includeHost },
          '#withIncludeProtocol':: d.fn(help='"If true, http and https requests will be cached separately."', args=[d.arg(name='includeProtocol', type=d.T.boolean)]),
          withIncludeProtocol(includeProtocol): { includeProtocol: includeProtocol },
          '#withIncludeQueryString':: d.fn(help='"If true, include query string parameters in the cache key according to query_string_whitelist and query_string_blacklist. If neither is set, the entire query string will be included. \\n If false, the query string will be excluded from the cache key entirely."', args=[d.arg(name='includeQueryString', type=d.T.boolean)]),
          withIncludeQueryString(includeQueryString): { includeQueryString: includeQueryString },
          '#withQueryStringBlacklist':: d.fn(help="\"Names of query string parameters to exclude in cache keys. \\n All other parameters will be included. Either specify query_string_whitelist or query_string_blacklist, not both. '\u0026' and '=' will be percent encoded and not treated as delimiters.\"", args=[d.arg(name='queryStringBlacklist', type=d.T.array)]),
          withQueryStringBlacklist(queryStringBlacklist): { queryStringBlacklist: if std.isArray(v=queryStringBlacklist) then queryStringBlacklist else [queryStringBlacklist] },
          '#withQueryStringBlacklistMixin':: d.fn(help="\"Names of query string parameters to exclude in cache keys. \\n All other parameters will be included. Either specify query_string_whitelist or query_string_blacklist, not both. '\u0026' and '=' will be percent encoded and not treated as delimiters.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='queryStringBlacklist', type=d.T.array)]),
          withQueryStringBlacklistMixin(queryStringBlacklist): { queryStringBlacklist+: if std.isArray(v=queryStringBlacklist) then queryStringBlacklist else [queryStringBlacklist] },
          '#withQueryStringWhitelist':: d.fn(help="\"Names of query string parameters to include in cache keys. \\n All other parameters will be excluded. Either specify query_string_whitelist or query_string_blacklist, not both. '\u0026' and '=' will be percent encoded and not treated as delimiters.\"", args=[d.arg(name='queryStringWhitelist', type=d.T.array)]),
          withQueryStringWhitelist(queryStringWhitelist): { queryStringWhitelist: if std.isArray(v=queryStringWhitelist) then queryStringWhitelist else [queryStringWhitelist] },
          '#withQueryStringWhitelistMixin':: d.fn(help="\"Names of query string parameters to include in cache keys. \\n All other parameters will be excluded. Either specify query_string_whitelist or query_string_blacklist, not both. '\u0026' and '=' will be percent encoded and not treated as delimiters.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='queryStringWhitelist', type=d.T.array)]),
          withQueryStringWhitelistMixin(queryStringWhitelist): { queryStringWhitelist+: if std.isArray(v=queryStringWhitelist) then queryStringWhitelist else [queryStringWhitelist] },
        },
        '#negativeCachingPolicy':: d.obj(help="\"Sets a cache TTL for the specified HTTP status code. negativeCaching must be enabled to configure negativeCachingPolicy. Omitting the policy and leaving negativeCaching enabled will use Cloud CDN's default cache TTLs.\""),
        negativeCachingPolicy: {
          '#withCode':: d.fn(help='"The HTTP status code to define a TTL against. Only HTTP status codes 300, 301, 308, 404, 405, 410, 421, 451 and 501 can be specified as values, and you cannot specify a status code more than once."', args=[d.arg(name='code', type=d.T.integer)]),
          withCode(code): { code: code },
        },
        '#withCacheKeyPolicy':: d.fn(help='"The CacheKeyPolicy for this CdnPolicy."', args=[d.arg(name='cacheKeyPolicy', type=d.T.array)]),
        withCacheKeyPolicy(cacheKeyPolicy): { cacheKeyPolicy: if std.isArray(v=cacheKeyPolicy) then cacheKeyPolicy else [cacheKeyPolicy] },
        '#withCacheKeyPolicyMixin':: d.fn(help='"The CacheKeyPolicy for this CdnPolicy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='cacheKeyPolicy', type=d.T.array)]),
        withCacheKeyPolicyMixin(cacheKeyPolicy): { cacheKeyPolicy+: if std.isArray(v=cacheKeyPolicy) then cacheKeyPolicy else [cacheKeyPolicy] },
        '#withCacheMode':: d.fn(help='"Specifies the cache setting for all responses from this backend. The possible values are: USE_ORIGIN_HEADERS, FORCE_CACHE_ALL and CACHE_ALL_STATIC Possible values: [\\"USE_ORIGIN_HEADERS\\", \\"FORCE_CACHE_ALL\\", \\"CACHE_ALL_STATIC\\"]"', args=[d.arg(name='cacheMode', type=d.T.string)]),
        withCacheMode(cacheMode): { cacheMode: cacheMode },
        '#withClientTtl':: d.fn(help='"Specifies the maximum allowed TTL for cached content served by this origin."', args=[d.arg(name='clientTtl', type=d.T.integer)]),
        withClientTtl(clientTtl): { clientTtl: clientTtl },
        '#withDefaultTtl':: d.fn(help='"Specifies the default TTL for cached content served by this origin for responses that do not have an existing valid TTL (max-age or s-max-age)."', args=[d.arg(name='defaultTtl', type=d.T.integer)]),
        withDefaultTtl(defaultTtl): { defaultTtl: defaultTtl },
        '#withMaxTtl':: d.fn(help='"Specifies the maximum allowed TTL for cached content served by this origin."', args=[d.arg(name='maxTtl', type=d.T.integer)]),
        withMaxTtl(maxTtl): { maxTtl: maxTtl },
        '#withNegativeCaching':: d.fn(help='"Negative caching allows per-status code TTLs to be set, in order to apply fine-grained caching for common errors or redirects."', args=[d.arg(name='negativeCaching', type=d.T.boolean)]),
        withNegativeCaching(negativeCaching): { negativeCaching: negativeCaching },
        '#withNegativeCachingPolicy':: d.fn(help="\"Sets a cache TTL for the specified HTTP status code. negativeCaching must be enabled to configure negativeCachingPolicy. Omitting the policy and leaving negativeCaching enabled will use Cloud CDN's default cache TTLs.\"", args=[d.arg(name='negativeCachingPolicy', type=d.T.array)]),
        withNegativeCachingPolicy(negativeCachingPolicy): { negativeCachingPolicy: if std.isArray(v=negativeCachingPolicy) then negativeCachingPolicy else [negativeCachingPolicy] },
        '#withNegativeCachingPolicyMixin':: d.fn(help="\"Sets a cache TTL for the specified HTTP status code. negativeCaching must be enabled to configure negativeCachingPolicy. Omitting the policy and leaving negativeCaching enabled will use Cloud CDN's default cache TTLs.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='negativeCachingPolicy', type=d.T.array)]),
        withNegativeCachingPolicyMixin(negativeCachingPolicy): { negativeCachingPolicy+: if std.isArray(v=negativeCachingPolicy) then negativeCachingPolicy else [negativeCachingPolicy] },
        '#withServeWhileStale':: d.fn(help='"Serve existing content from the cache (if available) when revalidating content with the origin, or when an error is encountered when refreshing the cache."', args=[d.arg(name='serveWhileStale', type=d.T.integer)]),
        withServeWhileStale(serveWhileStale): { serveWhileStale: serveWhileStale },
        '#withSignedUrlCacheMaxAgeSec':: d.fn(help='"Maximum number of seconds the response to a signed URL request will be considered fresh, defaults to 1hr (3600s). After this time period, the response will be revalidated before being served. \\n When serving responses to signed URL requests, Cloud CDN will internally behave as though all responses from this backend had a \\"Cache-Control: public, max-age=[TTL]\\" header, regardless of any existing Cache-Control header. The actual headers served in responses will not be altered."', args=[d.arg(name='signedUrlCacheMaxAgeSec', type=d.T.integer)]),
        withSignedUrlCacheMaxAgeSec(signedUrlCacheMaxAgeSec): { signedUrlCacheMaxAgeSec: signedUrlCacheMaxAgeSec },
      },
      '#circuitBreakers':: d.obj(help="\"Settings controlling the volume of connections to a backend service. This field is applicable only when the 'load_balancing_scheme' is set to INTERNAL_MANAGED and the 'protocol' is set to HTTP, HTTPS, or HTTP2.\""),
      circuitBreakers: {
        '#withMaxConnections':: d.fn(help='"The maximum number of connections to the backend cluster. Defaults to 1024."', args=[d.arg(name='maxConnections', type=d.T.integer)]),
        withMaxConnections(maxConnections): { maxConnections: maxConnections },
        '#withMaxPendingRequests':: d.fn(help='"The maximum number of pending requests to the backend cluster. Defaults to 1024."', args=[d.arg(name='maxPendingRequests', type=d.T.integer)]),
        withMaxPendingRequests(maxPendingRequests): { maxPendingRequests: maxPendingRequests },
        '#withMaxRequests':: d.fn(help='"The maximum number of parallel requests to the backend cluster. Defaults to 1024."', args=[d.arg(name='maxRequests', type=d.T.integer)]),
        withMaxRequests(maxRequests): { maxRequests: maxRequests },
        '#withMaxRequestsPerConnection':: d.fn(help='"Maximum requests for a single backend connection. This parameter is respected by both the HTTP/1.1 and HTTP/2 implementations. If not specified, there is no limit. Setting this parameter to 1 will effectively disable keep alive."', args=[d.arg(name='maxRequestsPerConnection', type=d.T.integer)]),
        withMaxRequestsPerConnection(maxRequestsPerConnection): { maxRequestsPerConnection: maxRequestsPerConnection },
        '#withMaxRetries':: d.fn(help='"The maximum number of parallel retries to the backend cluster. Defaults to 3."', args=[d.arg(name='maxRetries', type=d.T.integer)]),
        withMaxRetries(maxRetries): { maxRetries: maxRetries },
      },
      '#consistentHash':: d.obj(help="\"Consistent Hash-based load balancing can be used to provide soft session affinity based on HTTP headers, cookies or other properties. This load balancing policy is applicable only for HTTP connections. The affinity to a particular destination host will be lost when one or more hosts are added/removed from the destination service. This field specifies parameters that control consistent hashing. This field only applies when all of the following are true - * 'load_balancing_scheme' is set to INTERNAL_MANAGED * 'protocol' is set to HTTP, HTTPS, or HTTP2 * 'locality_lb_policy' is set to MAGLEV or RING_HASH\""),
      consistentHash: {
        '#httpCookie':: d.obj(help='"Hash is based on HTTP Cookie. This field describes a HTTP cookie that will be used as the hash key for the consistent hash load balancer. If the cookie is not present, it will be generated. This field is applicable if the sessionAffinity is set to HTTP_COOKIE."'),
        httpCookie: {
          '#ttl':: d.obj(help='"Lifetime of the cookie."'),
          ttl: {
            '#withNanos':: d.fn(help="\"Span of time that's a fraction of a second at nanosecond resolution. Durations less than one second are represented with a 0 seconds field and a positive nanos field. Must be from 0 to 999,999,999 inclusive.\"", args=[d.arg(name='nanos', type=d.T.integer)]),
            withNanos(nanos): { nanos: nanos },
            '#withSeconds':: d.fn(help='"Span of time at a resolution of a second. Must be from 0 to 315,576,000,000 inclusive."', args=[d.arg(name='seconds', type=d.T.integer)]),
            withSeconds(seconds): { seconds: seconds },
          },
          '#withName':: d.fn(help='"Name of the cookie."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withPath':: d.fn(help='"Path to set for the cookie."', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { path: path },
          '#withTtl':: d.fn(help='"Lifetime of the cookie."', args=[d.arg(name='ttl', type=d.T.array)]),
          withTtl(ttl): { ttl: if std.isArray(v=ttl) then ttl else [ttl] },
          '#withTtlMixin':: d.fn(help='"Lifetime of the cookie."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ttl', type=d.T.array)]),
          withTtlMixin(ttl): { ttl+: if std.isArray(v=ttl) then ttl else [ttl] },
        },
        '#withHttpCookie':: d.fn(help='"Hash is based on HTTP Cookie. This field describes a HTTP cookie that will be used as the hash key for the consistent hash load balancer. If the cookie is not present, it will be generated. This field is applicable if the sessionAffinity is set to HTTP_COOKIE."', args=[d.arg(name='httpCookie', type=d.T.array)]),
        withHttpCookie(httpCookie): { httpCookie: if std.isArray(v=httpCookie) then httpCookie else [httpCookie] },
        '#withHttpCookieMixin':: d.fn(help='"Hash is based on HTTP Cookie. This field describes a HTTP cookie that will be used as the hash key for the consistent hash load balancer. If the cookie is not present, it will be generated. This field is applicable if the sessionAffinity is set to HTTP_COOKIE."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='httpCookie', type=d.T.array)]),
        withHttpCookieMixin(httpCookie): { httpCookie+: if std.isArray(v=httpCookie) then httpCookie else [httpCookie] },
        '#withHttpHeaderName':: d.fn(help='"The hash based on the value of the specified header field. This field is applicable if the sessionAffinity is set to HEADER_FIELD."', args=[d.arg(name='httpHeaderName', type=d.T.string)]),
        withHttpHeaderName(httpHeaderName): { httpHeaderName: httpHeaderName },
        '#withMinimumRingSize':: d.fn(help='"The minimum number of virtual nodes to use for the hash ring. Larger ring sizes result in more granular load distributions. If the number of hosts in the load balancing pool is larger than the ring size, each host will be assigned a single virtual node. Defaults to 1024."', args=[d.arg(name='minimumRingSize', type=d.T.integer)]),
        withMinimumRingSize(minimumRingSize): { minimumRingSize: minimumRingSize },
      },
      '#failoverPolicy':: d.obj(help='"Policy for failovers."'),
      failoverPolicy: {
        '#withDisableConnectionDrainOnFailover':: d.fn(help='"On failover or failback, this field indicates whether connection drain will be honored. Setting this to true has the following effect: connections to the old active pool are not drained. Connections to the new active pool use the timeout of 10 min (currently fixed). Setting to false has the following effect: both old and new connections will have a drain timeout of 10 min. This can be set to true only if the protocol is TCP. The default is false."', args=[d.arg(name='disableConnectionDrainOnFailover', type=d.T.boolean)]),
        withDisableConnectionDrainOnFailover(disableConnectionDrainOnFailover): { disableConnectionDrainOnFailover: disableConnectionDrainOnFailover },
        '#withDropTrafficIfUnhealthy':: d.fn(help='"This option is used only when no healthy VMs are detected in the primary and backup instance groups. When set to true, traffic is dropped. When set to false, new connections are sent across all VMs in the primary group. The default is false."', args=[d.arg(name='dropTrafficIfUnhealthy', type=d.T.boolean)]),
        withDropTrafficIfUnhealthy(dropTrafficIfUnhealthy): { dropTrafficIfUnhealthy: dropTrafficIfUnhealthy },
        '#withFailoverRatio':: d.fn(help="\"The value of the field must be in [0, 1]. If the ratio of the healthy VMs in the primary backend is at or below this number, traffic arriving at the load-balanced IP will be directed to the failover backend. In case where 'failoverRatio' is not set or all the VMs in the backup backend are unhealthy, the traffic will be directed back to the primary backend in the \\\"force\\\" mode, where traffic will be spread to the healthy VMs with the best effort, or to all VMs when no VM is healthy. This field is only used with l4 load balancing.\"", args=[d.arg(name='failoverRatio', type=d.T.number)]),
        withFailoverRatio(failoverRatio): { failoverRatio: failoverRatio },
      },
      '#iap':: d.obj(help='"Settings for enabling Cloud Identity Aware Proxy"'),
      iap: {
        '#oauth2ClientSecretSecretRef':: d.obj(help='"OAuth2 Client Secret for IAP"'),
        oauth2ClientSecretSecretRef: {
          '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { oauth2ClientSecretSecretRef+: { key: key } },
          '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { oauth2ClientSecretSecretRef+: { name: name } },
          '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { oauth2ClientSecretSecretRef+: { namespace: namespace } },
        },
        '#withOauth2ClientId':: d.fn(help='"OAuth2 Client ID for IAP"', args=[d.arg(name='oauth2ClientId', type=d.T.string)]),
        withOauth2ClientId(oauth2ClientId): { oauth2ClientId: oauth2ClientId },
      },
      '#logConfig':: d.obj(help='"This field denotes the logging options for the load balancer traffic served by this backend service. If logging is enabled, logs will be exported to Stackdriver."'),
      logConfig: {
        '#withEnable':: d.fn(help='"Whether to enable logging for the load balancer traffic served by this backend service."', args=[d.arg(name='enable', type=d.T.boolean)]),
        withEnable(enable): { enable: enable },
        '#withSampleRate':: d.fn(help='"This field can only be specified if logging is enabled for this backend service. The value of the field must be in [0, 1]. This configures the sampling rate of requests to the load balancer where 1.0 means all logged requests are reported and 0.0 means no logged requests are reported. The default value is 1.0."', args=[d.arg(name='sampleRate', type=d.T.number)]),
        withSampleRate(sampleRate): { sampleRate: sampleRate },
      },
      '#outlierDetection':: d.obj(help="\"Settings controlling eviction of unhealthy hosts from the load balancing pool. This field is applicable only when the 'load_balancing_scheme' is set to INTERNAL_MANAGED and the 'protocol' is set to HTTP, HTTPS, or HTTP2.\""),
      outlierDetection: {
        '#baseEjectionTime':: d.obj(help='"The base time that a host is ejected for. The real time is equal to the base time multiplied by the number of times the host has been ejected. Defaults to 30000ms or 30s."'),
        baseEjectionTime: {
          '#withNanos':: d.fn(help="\"Span of time that's a fraction of a second at nanosecond resolution. Durations less than one second are represented with a 0 'seconds' field and a positive 'nanos' field. Must be from 0 to 999,999,999 inclusive.\"", args=[d.arg(name='nanos', type=d.T.integer)]),
          withNanos(nanos): { nanos: nanos },
          '#withSeconds':: d.fn(help='"Span of time at a resolution of a second. Must be from 0 to 315,576,000,000 inclusive."', args=[d.arg(name='seconds', type=d.T.integer)]),
          withSeconds(seconds): { seconds: seconds },
        },
        '#interval':: d.obj(help='"Time interval between ejection sweep analysis. This can result in both new ejections as well as hosts being returned to service. Defaults to 10 seconds."'),
        interval: {
          '#withNanos':: d.fn(help="\"Span of time that's a fraction of a second at nanosecond resolution. Durations less than one second are represented with a 0 'seconds' field and a positive 'nanos' field. Must be from 0 to 999,999,999 inclusive.\"", args=[d.arg(name='nanos', type=d.T.integer)]),
          withNanos(nanos): { nanos: nanos },
          '#withSeconds':: d.fn(help='"Span of time at a resolution of a second. Must be from 0 to 315,576,000,000 inclusive."', args=[d.arg(name='seconds', type=d.T.integer)]),
          withSeconds(seconds): { seconds: seconds },
        },
        '#withBaseEjectionTime':: d.fn(help='"The base time that a host is ejected for. The real time is equal to the base time multiplied by the number of times the host has been ejected. Defaults to 30000ms or 30s."', args=[d.arg(name='baseEjectionTime', type=d.T.array)]),
        withBaseEjectionTime(baseEjectionTime): { baseEjectionTime: if std.isArray(v=baseEjectionTime) then baseEjectionTime else [baseEjectionTime] },
        '#withBaseEjectionTimeMixin':: d.fn(help='"The base time that a host is ejected for. The real time is equal to the base time multiplied by the number of times the host has been ejected. Defaults to 30000ms or 30s."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='baseEjectionTime', type=d.T.array)]),
        withBaseEjectionTimeMixin(baseEjectionTime): { baseEjectionTime+: if std.isArray(v=baseEjectionTime) then baseEjectionTime else [baseEjectionTime] },
        '#withConsecutiveErrors':: d.fn(help='"Number of errors before a host is ejected from the connection pool. When the backend host is accessed over HTTP, a 5xx return code qualifies as an error. Defaults to 5."', args=[d.arg(name='consecutiveErrors', type=d.T.integer)]),
        withConsecutiveErrors(consecutiveErrors): { consecutiveErrors: consecutiveErrors },
        '#withConsecutiveGatewayFailure':: d.fn(help='"The number of consecutive gateway failures (502, 503, 504 status or connection errors that are mapped to one of those status codes) before a consecutive gateway failure ejection occurs. Defaults to 5."', args=[d.arg(name='consecutiveGatewayFailure', type=d.T.integer)]),
        withConsecutiveGatewayFailure(consecutiveGatewayFailure): { consecutiveGatewayFailure: consecutiveGatewayFailure },
        '#withEnforcingConsecutiveErrors':: d.fn(help='"The percentage chance that a host will be actually ejected when an outlier status is detected through consecutive 5xx. This setting can be used to disable ejection or to ramp it up slowly. Defaults to 100."', args=[d.arg(name='enforcingConsecutiveErrors', type=d.T.integer)]),
        withEnforcingConsecutiveErrors(enforcingConsecutiveErrors): { enforcingConsecutiveErrors: enforcingConsecutiveErrors },
        '#withEnforcingConsecutiveGatewayFailure':: d.fn(help='"The percentage chance that a host will be actually ejected when an outlier status is detected through consecutive gateway failures. This setting can be used to disable ejection or to ramp it up slowly. Defaults to 0."', args=[d.arg(name='enforcingConsecutiveGatewayFailure', type=d.T.integer)]),
        withEnforcingConsecutiveGatewayFailure(enforcingConsecutiveGatewayFailure): { enforcingConsecutiveGatewayFailure: enforcingConsecutiveGatewayFailure },
        '#withEnforcingSuccessRate':: d.fn(help='"The percentage chance that a host will be actually ejected when an outlier status is detected through success rate statistics. This setting can be used to disable ejection or to ramp it up slowly. Defaults to 100."', args=[d.arg(name='enforcingSuccessRate', type=d.T.integer)]),
        withEnforcingSuccessRate(enforcingSuccessRate): { enforcingSuccessRate: enforcingSuccessRate },
        '#withInterval':: d.fn(help='"Time interval between ejection sweep analysis. This can result in both new ejections as well as hosts being returned to service. Defaults to 10 seconds."', args=[d.arg(name='interval', type=d.T.array)]),
        withInterval(interval): { interval: if std.isArray(v=interval) then interval else [interval] },
        '#withIntervalMixin':: d.fn(help='"Time interval between ejection sweep analysis. This can result in both new ejections as well as hosts being returned to service. Defaults to 10 seconds."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='interval', type=d.T.array)]),
        withIntervalMixin(interval): { interval+: if std.isArray(v=interval) then interval else [interval] },
        '#withMaxEjectionPercent':: d.fn(help='"Maximum percentage of hosts in the load balancing pool for the backend service that can be ejected. Defaults to 10%."', args=[d.arg(name='maxEjectionPercent', type=d.T.integer)]),
        withMaxEjectionPercent(maxEjectionPercent): { maxEjectionPercent: maxEjectionPercent },
        '#withSuccessRateMinimumHosts':: d.fn(help='"The number of hosts in a cluster that must have enough request volume to detect success rate outliers. If the number of hosts is less than this setting, outlier detection via success rate statistics is not performed for any host in the cluster. Defaults to 5."', args=[d.arg(name='successRateMinimumHosts', type=d.T.integer)]),
        withSuccessRateMinimumHosts(successRateMinimumHosts): { successRateMinimumHosts: successRateMinimumHosts },
        '#withSuccessRateRequestVolume':: d.fn(help='"The minimum number of total requests that must be collected in one interval (as defined by the interval duration above) to include this host in success rate based outlier detection. If the volume is lower than this setting, outlier detection via success rate statistics is not performed for that host. Defaults to 100."', args=[d.arg(name='successRateRequestVolume', type=d.T.integer)]),
        withSuccessRateRequestVolume(successRateRequestVolume): { successRateRequestVolume: successRateRequestVolume },
        '#withSuccessRateStdevFactor':: d.fn(help='"This factor is used to determine the ejection threshold for success rate outlier ejection. The ejection threshold is the difference between the mean success rate, and the product of this factor and the standard deviation of the mean success rate: mean - (stdev * success_rate_stdev_factor). This factor is divided by a thousand to get a double. That is, if the desired factor is 1.9, the runtime value should be 1900. Defaults to 1900."', args=[d.arg(name='successRateStdevFactor', type=d.T.integer)]),
        withSuccessRateStdevFactor(successRateStdevFactor): { successRateStdevFactor: successRateStdevFactor },
      },
      '#withAffinityCookieTtlSec':: d.fn(help='"Lifetime of cookies in seconds if session_affinity is GENERATED_COOKIE. If set to 0, the cookie is non-persistent and lasts only until the end of the browser session (or equivalent). The maximum allowed value for TTL is one day. \\n When the load balancing scheme is INTERNAL, this field is not used."', args=[d.arg(name='affinityCookieTtlSec', type=d.T.integer)]),
      withAffinityCookieTtlSec(affinityCookieTtlSec): { spec+: { forProvider+: { affinityCookieTtlSec: affinityCookieTtlSec } } },
      '#withBackend':: d.fn(help='"The set of backends that serve this RegionBackendService."', args=[d.arg(name='backend', type=d.T.array)]),
      withBackend(backend): { spec+: { forProvider+: { backend: if std.isArray(v=backend) then backend else [backend] } } },
      '#withBackendMixin':: d.fn(help='"The set of backends that serve this RegionBackendService."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='backend', type=d.T.array)]),
      withBackendMixin(backend): { spec+: { forProvider+: { backend+: if std.isArray(v=backend) then backend else [backend] } } },
      '#withCdnPolicy':: d.fn(help='"Cloud CDN configuration for this BackendService."', args=[d.arg(name='cdnPolicy', type=d.T.array)]),
      withCdnPolicy(cdnPolicy): { spec+: { forProvider+: { cdnPolicy: if std.isArray(v=cdnPolicy) then cdnPolicy else [cdnPolicy] } } },
      '#withCdnPolicyMixin':: d.fn(help='"Cloud CDN configuration for this BackendService."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='cdnPolicy', type=d.T.array)]),
      withCdnPolicyMixin(cdnPolicy): { spec+: { forProvider+: { cdnPolicy+: if std.isArray(v=cdnPolicy) then cdnPolicy else [cdnPolicy] } } },
      '#withCircuitBreakers':: d.fn(help="\"Settings controlling the volume of connections to a backend service. This field is applicable only when the 'load_balancing_scheme' is set to INTERNAL_MANAGED and the 'protocol' is set to HTTP, HTTPS, or HTTP2.\"", args=[d.arg(name='circuitBreakers', type=d.T.array)]),
      withCircuitBreakers(circuitBreakers): { spec+: { forProvider+: { circuitBreakers: if std.isArray(v=circuitBreakers) then circuitBreakers else [circuitBreakers] } } },
      '#withCircuitBreakersMixin':: d.fn(help="\"Settings controlling the volume of connections to a backend service. This field is applicable only when the 'load_balancing_scheme' is set to INTERNAL_MANAGED and the 'protocol' is set to HTTP, HTTPS, or HTTP2.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='circuitBreakers', type=d.T.array)]),
      withCircuitBreakersMixin(circuitBreakers): { spec+: { forProvider+: { circuitBreakers+: if std.isArray(v=circuitBreakers) then circuitBreakers else [circuitBreakers] } } },
      '#withConnectionDrainingTimeoutSec':: d.fn(help='"Time for which instance will be drained (not accept new connections, but still work to finish started)."', args=[d.arg(name='connectionDrainingTimeoutSec', type=d.T.integer)]),
      withConnectionDrainingTimeoutSec(connectionDrainingTimeoutSec): { spec+: { forProvider+: { connectionDrainingTimeoutSec: connectionDrainingTimeoutSec } } },
      '#withConsistentHash':: d.fn(help="\"Consistent Hash-based load balancing can be used to provide soft session affinity based on HTTP headers, cookies or other properties. This load balancing policy is applicable only for HTTP connections. The affinity to a particular destination host will be lost when one or more hosts are added/removed from the destination service. This field specifies parameters that control consistent hashing. This field only applies when all of the following are true - * 'load_balancing_scheme' is set to INTERNAL_MANAGED * 'protocol' is set to HTTP, HTTPS, or HTTP2 * 'locality_lb_policy' is set to MAGLEV or RING_HASH\"", args=[d.arg(name='consistentHash', type=d.T.array)]),
      withConsistentHash(consistentHash): { spec+: { forProvider+: { consistentHash: if std.isArray(v=consistentHash) then consistentHash else [consistentHash] } } },
      '#withConsistentHashMixin':: d.fn(help="\"Consistent Hash-based load balancing can be used to provide soft session affinity based on HTTP headers, cookies or other properties. This load balancing policy is applicable only for HTTP connections. The affinity to a particular destination host will be lost when one or more hosts are added/removed from the destination service. This field specifies parameters that control consistent hashing. This field only applies when all of the following are true - * 'load_balancing_scheme' is set to INTERNAL_MANAGED * 'protocol' is set to HTTP, HTTPS, or HTTP2 * 'locality_lb_policy' is set to MAGLEV or RING_HASH\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='consistentHash', type=d.T.array)]),
      withConsistentHashMixin(consistentHash): { spec+: { forProvider+: { consistentHash+: if std.isArray(v=consistentHash) then consistentHash else [consistentHash] } } },
      '#withDescription':: d.fn(help='"An optional description of this resource."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withEnableCdn':: d.fn(help='"If true, enable Cloud CDN for this RegionBackendService."', args=[d.arg(name='enableCdn', type=d.T.boolean)]),
      withEnableCdn(enableCdn): { spec+: { forProvider+: { enableCdn: enableCdn } } },
      '#withFailoverPolicy':: d.fn(help='"Policy for failovers."', args=[d.arg(name='failoverPolicy', type=d.T.array)]),
      withFailoverPolicy(failoverPolicy): { spec+: { forProvider+: { failoverPolicy: if std.isArray(v=failoverPolicy) then failoverPolicy else [failoverPolicy] } } },
      '#withFailoverPolicyMixin':: d.fn(help='"Policy for failovers."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='failoverPolicy', type=d.T.array)]),
      withFailoverPolicyMixin(failoverPolicy): { spec+: { forProvider+: { failoverPolicy+: if std.isArray(v=failoverPolicy) then failoverPolicy else [failoverPolicy] } } },
      '#withHealthChecks':: d.fn(help='"The set of URLs to HealthCheck resources for health checking this RegionBackendService. Currently at most one health check can be specified. \\n A health check must be specified unless the backend service uses an internet or serverless NEG as a backend."', args=[d.arg(name='healthChecks', type=d.T.array)]),
      withHealthChecks(healthChecks): { spec+: { forProvider+: { healthChecks: if std.isArray(v=healthChecks) then healthChecks else [healthChecks] } } },
      '#withHealthChecksMixin':: d.fn(help='"The set of URLs to HealthCheck resources for health checking this RegionBackendService. Currently at most one health check can be specified. \\n A health check must be specified unless the backend service uses an internet or serverless NEG as a backend."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='healthChecks', type=d.T.array)]),
      withHealthChecksMixin(healthChecks): { spec+: { forProvider+: { healthChecks+: if std.isArray(v=healthChecks) then healthChecks else [healthChecks] } } },
      '#withIap':: d.fn(help='"Settings for enabling Cloud Identity Aware Proxy"', args=[d.arg(name='iap', type=d.T.array)]),
      withIap(iap): { spec+: { forProvider+: { iap: if std.isArray(v=iap) then iap else [iap] } } },
      '#withIapMixin':: d.fn(help='"Settings for enabling Cloud Identity Aware Proxy"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='iap', type=d.T.array)]),
      withIapMixin(iap): { spec+: { forProvider+: { iap+: if std.isArray(v=iap) then iap else [iap] } } },
      '#withLoadBalancingScheme':: d.fn(help='"Indicates what kind of load balancing this regional backend service will be used for. A backend service created for one type of load balancing cannot be used with the other(s). Default value: \\"INTERNAL\\" Possible values: [\\"EXTERNAL\\", \\"INTERNAL\\", \\"INTERNAL_MANAGED\\"]"', args=[d.arg(name='loadBalancingScheme', type=d.T.string)]),
      withLoadBalancingScheme(loadBalancingScheme): { spec+: { forProvider+: { loadBalancingScheme: loadBalancingScheme } } },
      '#withLocalityLbPolicy':: d.fn(help="\"The load balancing algorithm used within the scope of the locality. The possible values are - \\n * ROUND_ROBIN - This is a simple policy in which each healthy backend is selected in round robin order. \\n * LEAST_REQUEST - An O(1) algorithm which selects two random healthy hosts and picks the host which has fewer active requests. \\n * RING_HASH - The ring/modulo hash load balancer implements consistent hashing to backends. The algorithm has the property that the addition/removal of a host from a set of N hosts only affects 1/N of the requests. \\n * RANDOM - The load balancer selects a random healthy host. \\n * ORIGINAL_DESTINATION - Backend host is selected based on the client connection metadata, i.e., connections are opened to the same address as the destination address of the incoming connection before the connection was redirected to the load balancer. \\n * MAGLEV - used as a drop in replacement for the ring hash load balancer. Maglev is not as stable as ring hash but has faster table lookup build times and host selection times. For more information about Maglev, refer to https://ai.google/research/pubs/pub44824 \\n This field is applicable only when the 'load_balancing_scheme' is set to INTERNAL_MANAGED and the 'protocol' is set to HTTP, HTTPS, or HTTP2. Possible values: [\\\"ROUND_ROBIN\\\", \\\"LEAST_REQUEST\\\", \\\"RING_HASH\\\", \\\"RANDOM\\\", \\\"ORIGINAL_DESTINATION\\\", \\\"MAGLEV\\\"]\"", args=[d.arg(name='localityLbPolicy', type=d.T.string)]),
      withLocalityLbPolicy(localityLbPolicy): { spec+: { forProvider+: { localityLbPolicy: localityLbPolicy } } },
      '#withLogConfig':: d.fn(help='"This field denotes the logging options for the load balancer traffic served by this backend service. If logging is enabled, logs will be exported to Stackdriver."', args=[d.arg(name='logConfig', type=d.T.array)]),
      withLogConfig(logConfig): { spec+: { forProvider+: { logConfig: if std.isArray(v=logConfig) then logConfig else [logConfig] } } },
      '#withLogConfigMixin':: d.fn(help='"This field denotes the logging options for the load balancer traffic served by this backend service. If logging is enabled, logs will be exported to Stackdriver."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='logConfig', type=d.T.array)]),
      withLogConfigMixin(logConfig): { spec+: { forProvider+: { logConfig+: if std.isArray(v=logConfig) then logConfig else [logConfig] } } },
      '#withName':: d.fn(help="\"Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?' which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.\"", args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { forProvider+: { name: name } } },
      '#withNetwork':: d.fn(help='"The URL of the network to which this backend service belongs. This field can only be specified when the load balancing scheme is set to INTERNAL."', args=[d.arg(name='network', type=d.T.string)]),
      withNetwork(network): { spec+: { forProvider+: { network: network } } },
      '#withOutlierDetection':: d.fn(help="\"Settings controlling eviction of unhealthy hosts from the load balancing pool. This field is applicable only when the 'load_balancing_scheme' is set to INTERNAL_MANAGED and the 'protocol' is set to HTTP, HTTPS, or HTTP2.\"", args=[d.arg(name='outlierDetection', type=d.T.array)]),
      withOutlierDetection(outlierDetection): { spec+: { forProvider+: { outlierDetection: if std.isArray(v=outlierDetection) then outlierDetection else [outlierDetection] } } },
      '#withOutlierDetectionMixin':: d.fn(help="\"Settings controlling eviction of unhealthy hosts from the load balancing pool. This field is applicable only when the 'load_balancing_scheme' is set to INTERNAL_MANAGED and the 'protocol' is set to HTTP, HTTPS, or HTTP2.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='outlierDetection', type=d.T.array)]),
      withOutlierDetectionMixin(outlierDetection): { spec+: { forProvider+: { outlierDetection+: if std.isArray(v=outlierDetection) then outlierDetection else [outlierDetection] } } },
      '#withPortName':: d.fn(help='"A named port on a backend instance group representing the port for communication to the backend VMs in that group. Required when the loadBalancingScheme is EXTERNAL, INTERNAL_MANAGED, or INTERNAL_SELF_MANAGED and the backends are instance groups. The named port must be defined on each backend instance group. This parameter has no meaning if the backends are NEGs. API sets a default of \\"http\\" if not given. Must be omitted when the loadBalancingScheme is INTERNAL (Internal TCP/UDP Load Balancing)."', args=[d.arg(name='portName', type=d.T.string)]),
      withPortName(portName): { spec+: { forProvider+: { portName: portName } } },
      '#withProject':: d.fn(help='', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withProtocol':: d.fn(help='"The protocol this RegionBackendService uses to communicate with backends. The default is HTTP. **NOTE**: HTTP2 is only valid for beta HTTP/2 load balancer types and may result in errors if used with the GA API. Possible values: [\\"HTTP\\", \\"HTTPS\\", \\"HTTP2\\", \\"SSL\\", \\"TCP\\", \\"UDP\\", \\"GRPC\\", \\"UNSPECIFIED\\"]"', args=[d.arg(name='protocol', type=d.T.string)]),
      withProtocol(protocol): { spec+: { forProvider+: { protocol: protocol } } },
      '#withRegion':: d.fn(help='"The Region in which the created backend service should reside. If it is not provided, the provider region is used."', args=[d.arg(name='region', type=d.T.string)]),
      withRegion(region): { spec+: { forProvider+: { region: region } } },
      '#withSessionAffinity':: d.fn(help='"Type of session affinity to use. The default is NONE. Session affinity is not applicable if the protocol is UDP. Possible values: [\\"NONE\\", \\"CLIENT_IP\\", \\"CLIENT_IP_PORT_PROTO\\", \\"CLIENT_IP_PROTO\\", \\"GENERATED_COOKIE\\", \\"HEADER_FIELD\\", \\"HTTP_COOKIE\\", \\"CLIENT_IP_NO_DESTINATION\\"]"', args=[d.arg(name='sessionAffinity', type=d.T.string)]),
      withSessionAffinity(sessionAffinity): { spec+: { forProvider+: { sessionAffinity: sessionAffinity } } },
      '#withTimeoutSec':: d.fn(help='"How many seconds to wait for the backend before considering it a failed request. Default is 30 seconds. Valid range is [1, 86400]."', args=[d.arg(name='timeoutSec', type=d.T.integer)]),
      withTimeoutSec(timeoutSec): { spec+: { forProvider+: { timeoutSec: timeoutSec } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
