{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='flexibleAppVersion', url='', help='"FlexibleAppVersion is the Schema for the FlexibleAppVersions API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of FlexibleAppVersion', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'appengine.gcp.jet.crossplane.io/v1alpha1',
    kind: 'FlexibleAppVersion',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'true',
  }),
  '#spec':: d.obj(help='"FlexibleAppVersionSpec defines the desired state of FlexibleAppVersion"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#apiConfig':: d.obj(help='"Serving configuration for Google Cloud Endpoints."'),
      apiConfig: {
        '#withAuthFailAction':: d.fn(help='"Action to take when users access resources that require authentication. Default value: \\"AUTH_FAIL_ACTION_REDIRECT\\" Possible values: [\\"AUTH_FAIL_ACTION_REDIRECT\\", \\"AUTH_FAIL_ACTION_UNAUTHORIZED\\"]"', args=[d.arg(name='authFailAction', type=d.T.string)]),
        withAuthFailAction(authFailAction): { authFailAction: authFailAction },
        '#withLogin':: d.fn(help='"Level of login required to access this resource. Default value: \\"LOGIN_OPTIONAL\\" Possible values: [\\"LOGIN_OPTIONAL\\", \\"LOGIN_ADMIN\\", \\"LOGIN_REQUIRED\\"]"', args=[d.arg(name='login', type=d.T.string)]),
        withLogin(login): { login: login },
        '#withScript':: d.fn(help='"Path to the script from the application root directory."', args=[d.arg(name='script', type=d.T.string)]),
        withScript(script): { script: script },
        '#withSecurityLevel':: d.fn(help='"Security (HTTPS) enforcement for this URL. Possible values: [\\"SECURE_DEFAULT\\", \\"SECURE_NEVER\\", \\"SECURE_OPTIONAL\\", \\"SECURE_ALWAYS\\"]"', args=[d.arg(name='securityLevel', type=d.T.string)]),
        withSecurityLevel(securityLevel): { securityLevel: securityLevel },
        '#withUrl':: d.fn(help='"URL to serve the endpoint at."', args=[d.arg(name='url', type=d.T.string)]),
        withUrl(url): { url: url },
      },
      '#automaticScaling':: d.obj(help='"Automatic scaling is based on request rate, response latencies, and other application metrics."'),
      automaticScaling: {
        '#cpuUtilization':: d.obj(help='"Target scaling by CPU usage."'),
        cpuUtilization: {
          '#withAggregationWindowLength':: d.fn(help='"Period of time over which CPU utilization is calculated."', args=[d.arg(name='aggregationWindowLength', type=d.T.string)]),
          withAggregationWindowLength(aggregationWindowLength): { aggregationWindowLength: aggregationWindowLength },
          '#withTargetUtilization':: d.fn(help='"Target CPU utilization ratio to maintain when scaling. Must be between 0 and 1."', args=[d.arg(name='targetUtilization', type=d.T.number)]),
          withTargetUtilization(targetUtilization): { targetUtilization: targetUtilization },
        },
        '#diskUtilization':: d.obj(help='"Target scaling by disk usage."'),
        diskUtilization: {
          '#withTargetReadBytesPerSecond':: d.fn(help='"Target bytes read per second."', args=[d.arg(name='targetReadBytesPerSecond', type=d.T.integer)]),
          withTargetReadBytesPerSecond(targetReadBytesPerSecond): { targetReadBytesPerSecond: targetReadBytesPerSecond },
          '#withTargetReadOpsPerSecond':: d.fn(help='"Target ops read per seconds."', args=[d.arg(name='targetReadOpsPerSecond', type=d.T.integer)]),
          withTargetReadOpsPerSecond(targetReadOpsPerSecond): { targetReadOpsPerSecond: targetReadOpsPerSecond },
          '#withTargetWriteBytesPerSecond':: d.fn(help='"Target bytes written per second."', args=[d.arg(name='targetWriteBytesPerSecond', type=d.T.integer)]),
          withTargetWriteBytesPerSecond(targetWriteBytesPerSecond): { targetWriteBytesPerSecond: targetWriteBytesPerSecond },
          '#withTargetWriteOpsPerSecond':: d.fn(help='"Target ops written per second."', args=[d.arg(name='targetWriteOpsPerSecond', type=d.T.integer)]),
          withTargetWriteOpsPerSecond(targetWriteOpsPerSecond): { targetWriteOpsPerSecond: targetWriteOpsPerSecond },
        },
        '#networkUtilization':: d.obj(help='"Target scaling by network usage."'),
        networkUtilization: {
          '#withTargetReceivedBytesPerSecond':: d.fn(help='"Target bytes received per second."', args=[d.arg(name='targetReceivedBytesPerSecond', type=d.T.integer)]),
          withTargetReceivedBytesPerSecond(targetReceivedBytesPerSecond): { targetReceivedBytesPerSecond: targetReceivedBytesPerSecond },
          '#withTargetReceivedPacketsPerSecond':: d.fn(help='"Target packets received per second."', args=[d.arg(name='targetReceivedPacketsPerSecond', type=d.T.integer)]),
          withTargetReceivedPacketsPerSecond(targetReceivedPacketsPerSecond): { targetReceivedPacketsPerSecond: targetReceivedPacketsPerSecond },
          '#withTargetSentBytesPerSecond':: d.fn(help='"Target bytes sent per second."', args=[d.arg(name='targetSentBytesPerSecond', type=d.T.integer)]),
          withTargetSentBytesPerSecond(targetSentBytesPerSecond): { targetSentBytesPerSecond: targetSentBytesPerSecond },
          '#withTargetSentPacketsPerSecond':: d.fn(help='"Target packets sent per second."', args=[d.arg(name='targetSentPacketsPerSecond', type=d.T.integer)]),
          withTargetSentPacketsPerSecond(targetSentPacketsPerSecond): { targetSentPacketsPerSecond: targetSentPacketsPerSecond },
        },
        '#requestUtilization':: d.obj(help='"Target scaling by request utilization."'),
        requestUtilization: {
          '#withTargetConcurrentRequests':: d.fn(help='"Target number of concurrent requests."', args=[d.arg(name='targetConcurrentRequests', type=d.T.number)]),
          withTargetConcurrentRequests(targetConcurrentRequests): { targetConcurrentRequests: targetConcurrentRequests },
          '#withTargetRequestCountPerSecond':: d.fn(help='"Target requests per second."', args=[d.arg(name='targetRequestCountPerSecond', type=d.T.string)]),
          withTargetRequestCountPerSecond(targetRequestCountPerSecond): { targetRequestCountPerSecond: targetRequestCountPerSecond },
        },
        '#withCoolDownPeriod':: d.fn(help='"The time period that the Autoscaler should wait before it starts collecting information from a new instance. This prevents the autoscaler from collecting information when the instance is initializing, during which the collected usage would not be reliable. Default: 120s"', args=[d.arg(name='coolDownPeriod', type=d.T.string)]),
        withCoolDownPeriod(coolDownPeriod): { coolDownPeriod: coolDownPeriod },
        '#withCpuUtilization':: d.fn(help='"Target scaling by CPU usage."', args=[d.arg(name='cpuUtilization', type=d.T.array)]),
        withCpuUtilization(cpuUtilization): { cpuUtilization: if std.isArray(v=cpuUtilization) then cpuUtilization else [cpuUtilization] },
        '#withCpuUtilizationMixin':: d.fn(help='"Target scaling by CPU usage."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='cpuUtilization', type=d.T.array)]),
        withCpuUtilizationMixin(cpuUtilization): { cpuUtilization+: if std.isArray(v=cpuUtilization) then cpuUtilization else [cpuUtilization] },
        '#withDiskUtilization':: d.fn(help='"Target scaling by disk usage."', args=[d.arg(name='diskUtilization', type=d.T.array)]),
        withDiskUtilization(diskUtilization): { diskUtilization: if std.isArray(v=diskUtilization) then diskUtilization else [diskUtilization] },
        '#withDiskUtilizationMixin':: d.fn(help='"Target scaling by disk usage."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='diskUtilization', type=d.T.array)]),
        withDiskUtilizationMixin(diskUtilization): { diskUtilization+: if std.isArray(v=diskUtilization) then diskUtilization else [diskUtilization] },
        '#withMaxConcurrentRequests':: d.fn(help='"Number of concurrent requests an automatic scaling instance can accept before the scheduler spawns a new instance. \\n Defaults to a runtime-specific value."', args=[d.arg(name='maxConcurrentRequests', type=d.T.integer)]),
        withMaxConcurrentRequests(maxConcurrentRequests): { maxConcurrentRequests: maxConcurrentRequests },
        '#withMaxIdleInstances':: d.fn(help='"Maximum number of idle instances that should be maintained for this version."', args=[d.arg(name='maxIdleInstances', type=d.T.integer)]),
        withMaxIdleInstances(maxIdleInstances): { maxIdleInstances: maxIdleInstances },
        '#withMaxPendingLatency':: d.fn(help='"Maximum amount of time that a request should wait in the pending queue before starting a new instance to handle it."', args=[d.arg(name='maxPendingLatency', type=d.T.string)]),
        withMaxPendingLatency(maxPendingLatency): { maxPendingLatency: maxPendingLatency },
        '#withMaxTotalInstances':: d.fn(help='"Maximum number of instances that should be started to handle requests for this version. Default: 20"', args=[d.arg(name='maxTotalInstances', type=d.T.integer)]),
        withMaxTotalInstances(maxTotalInstances): { maxTotalInstances: maxTotalInstances },
        '#withMinIdleInstances':: d.fn(help='"Minimum number of idle instances that should be maintained for this version. Only applicable for the default version of a service."', args=[d.arg(name='minIdleInstances', type=d.T.integer)]),
        withMinIdleInstances(minIdleInstances): { minIdleInstances: minIdleInstances },
        '#withMinPendingLatency':: d.fn(help='"Minimum amount of time a request should wait in the pending queue before starting a new instance to handle it."', args=[d.arg(name='minPendingLatency', type=d.T.string)]),
        withMinPendingLatency(minPendingLatency): { minPendingLatency: minPendingLatency },
        '#withMinTotalInstances':: d.fn(help='"Minimum number of running instances that should be maintained for this version. Default: 2"', args=[d.arg(name='minTotalInstances', type=d.T.integer)]),
        withMinTotalInstances(minTotalInstances): { minTotalInstances: minTotalInstances },
        '#withNetworkUtilization':: d.fn(help='"Target scaling by network usage."', args=[d.arg(name='networkUtilization', type=d.T.array)]),
        withNetworkUtilization(networkUtilization): { networkUtilization: if std.isArray(v=networkUtilization) then networkUtilization else [networkUtilization] },
        '#withNetworkUtilizationMixin':: d.fn(help='"Target scaling by network usage."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='networkUtilization', type=d.T.array)]),
        withNetworkUtilizationMixin(networkUtilization): { networkUtilization+: if std.isArray(v=networkUtilization) then networkUtilization else [networkUtilization] },
        '#withRequestUtilization':: d.fn(help='"Target scaling by request utilization."', args=[d.arg(name='requestUtilization', type=d.T.array)]),
        withRequestUtilization(requestUtilization): { requestUtilization: if std.isArray(v=requestUtilization) then requestUtilization else [requestUtilization] },
        '#withRequestUtilizationMixin':: d.fn(help='"Target scaling by request utilization."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='requestUtilization', type=d.T.array)]),
        withRequestUtilizationMixin(requestUtilization): { requestUtilization+: if std.isArray(v=requestUtilization) then requestUtilization else [requestUtilization] },
      },
      '#deployment':: d.obj(help='"Code and application artifacts that make up this version."'),
      deployment: {
        '#cloudBuildOptions':: d.obj(help='"Options for the build operations performed as a part of the version deployment. Only applicable when creating a version using source code directly."'),
        cloudBuildOptions: {
          '#withAppYamlPath':: d.fn(help='"Path to the yaml file used in deployment, used to determine runtime configuration details."', args=[d.arg(name='appYamlPath', type=d.T.string)]),
          withAppYamlPath(appYamlPath): { appYamlPath: appYamlPath },
          '#withCloudBuildTimeout':: d.fn(help="\"The Cloud Build timeout used as part of any dependent builds performed by version creation. Defaults to 10 minutes. \\n A duration in seconds with up to nine fractional digits, terminated by 's'. Example: \\\"3.5s\\\".\"", args=[d.arg(name='cloudBuildTimeout', type=d.T.string)]),
          withCloudBuildTimeout(cloudBuildTimeout): { cloudBuildTimeout: cloudBuildTimeout },
        },
        '#container':: d.obj(help='"The Docker image for the container that runs the version."'),
        container: {
          '#withImage':: d.fn(help='"URI to the hosted container image in Google Container Registry. The URI must be fully qualified and include a tag or digest. Examples: \\"gcr.io/my-project/image:tag\\" or \\"gcr.io/my-project/image@digest\\', args=[d.arg(name='image', type=d.T.string)]),
          withImage(image): { image: image },
        },
        '#files':: d.obj(help='"Manifest of the files stored in Google Cloud Storage that are included as part of this version. All files must be readable using the credentials supplied with this call."'),
        files: {
          '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withSha1Sum':: d.fn(help='"SHA1 checksum of the file"', args=[d.arg(name='sha1Sum', type=d.T.string)]),
          withSha1Sum(sha1Sum): { sha1Sum: sha1Sum },
          '#withSourceUrl':: d.fn(help='"Source URL"', args=[d.arg(name='sourceUrl', type=d.T.string)]),
          withSourceUrl(sourceUrl): { sourceUrl: sourceUrl },
        },
        '#withCloudBuildOptions':: d.fn(help='"Options for the build operations performed as a part of the version deployment. Only applicable when creating a version using source code directly."', args=[d.arg(name='cloudBuildOptions', type=d.T.array)]),
        withCloudBuildOptions(cloudBuildOptions): { cloudBuildOptions: if std.isArray(v=cloudBuildOptions) then cloudBuildOptions else [cloudBuildOptions] },
        '#withCloudBuildOptionsMixin':: d.fn(help='"Options for the build operations performed as a part of the version deployment. Only applicable when creating a version using source code directly."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='cloudBuildOptions', type=d.T.array)]),
        withCloudBuildOptionsMixin(cloudBuildOptions): { cloudBuildOptions+: if std.isArray(v=cloudBuildOptions) then cloudBuildOptions else [cloudBuildOptions] },
        '#withContainer':: d.fn(help='"The Docker image for the container that runs the version."', args=[d.arg(name='container', type=d.T.array)]),
        withContainer(container): { container: if std.isArray(v=container) then container else [container] },
        '#withContainerMixin':: d.fn(help='"The Docker image for the container that runs the version."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='container', type=d.T.array)]),
        withContainerMixin(container): { container+: if std.isArray(v=container) then container else [container] },
        '#withFiles':: d.fn(help='"Manifest of the files stored in Google Cloud Storage that are included as part of this version. All files must be readable using the credentials supplied with this call."', args=[d.arg(name='files', type=d.T.array)]),
        withFiles(files): { files: if std.isArray(v=files) then files else [files] },
        '#withFilesMixin':: d.fn(help='"Manifest of the files stored in Google Cloud Storage that are included as part of this version. All files must be readable using the credentials supplied with this call."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='files', type=d.T.array)]),
        withFilesMixin(files): { files+: if std.isArray(v=files) then files else [files] },
        '#withZip':: d.fn(help='"Zip File"', args=[d.arg(name='zip', type=d.T.array)]),
        withZip(zip): { zip: if std.isArray(v=zip) then zip else [zip] },
        '#withZipMixin':: d.fn(help='"Zip File"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='zip', type=d.T.array)]),
        withZipMixin(zip): { zip+: if std.isArray(v=zip) then zip else [zip] },
        '#zip':: d.obj(help='"Zip File"'),
        zip: {
          '#withFilesCount':: d.fn(help='"files count"', args=[d.arg(name='filesCount', type=d.T.integer)]),
          withFilesCount(filesCount): { filesCount: filesCount },
          '#withSourceUrl':: d.fn(help='"Source URL"', args=[d.arg(name='sourceUrl', type=d.T.string)]),
          withSourceUrl(sourceUrl): { sourceUrl: sourceUrl },
        },
      },
      '#endpointsApiService':: d.obj(help='"Code and application artifacts that make up this version."'),
      endpointsApiService: {
        '#withConfigId':: d.fn(help='"Endpoints service configuration ID as specified by the Service Management API. For example \\"2016-09-19r1\\". \\n By default, the rollout strategy for Endpoints is \\"FIXED\\". This means that Endpoints starts up with a particular configuration ID. When a new configuration is rolled out, Endpoints must be given the new configuration ID. The configId field is used to give the configuration ID and is required in this case. \\n Endpoints also has a rollout strategy called \\"MANAGED\\". When using this, Endpoints fetches the latest configuration and does not need the configuration ID. In this case, configId must be omitted."', args=[d.arg(name='configId', type=d.T.string)]),
        withConfigId(configId): { configId: configId },
        '#withDisableTraceSampling':: d.fn(help='"Enable or disable trace sampling. By default, this is set to false for enabled."', args=[d.arg(name='disableTraceSampling', type=d.T.boolean)]),
        withDisableTraceSampling(disableTraceSampling): { disableTraceSampling: disableTraceSampling },
        '#withName':: d.fn(help='"Endpoints service name which is the name of the \\"service\\" resource in the Service Management API. For example \\"myapi.endpoints.myproject.cloud.goog\\', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withRolloutStrategy':: d.fn(help='"Endpoints rollout strategy. If FIXED, configId must be specified. If MANAGED, configId must be omitted. Default value: \\"FIXED\\" Possible values: [\\"FIXED\\", \\"MANAGED\\"]"', args=[d.arg(name='rolloutStrategy', type=d.T.string)]),
        withRolloutStrategy(rolloutStrategy): { rolloutStrategy: rolloutStrategy },
      },
      '#entrypoint':: d.obj(help='"The entrypoint for the application."'),
      entrypoint: {
        '#withShell':: d.fn(help='"The format should be a shell command that can be fed to bash -c."', args=[d.arg(name='shell', type=d.T.string)]),
        withShell(shell): { shell: shell },
      },
      '#handlers':: d.obj(help='"An ordered list of URL-matching patterns that should be applied to incoming requests. The first matching URL handles the request and other request handlers are not attempted."'),
      handlers: {
        '#script':: d.obj(help='"Executes a script to handle the requests that match this URL pattern. Only the auto value is supported for Node.js in the App Engine standard environment, for example \\"script:\\" \\"auto\\"."'),
        script: {
          '#withScriptPath':: d.fn(help='"Path to the script from the application root directory."', args=[d.arg(name='scriptPath', type=d.T.string)]),
          withScriptPath(scriptPath): { scriptPath: scriptPath },
        },
        '#staticFiles':: d.obj(help='"Files served directly to the user for a given URL, such as images, CSS stylesheets, or JavaScript source files. Static file handlers describe which files in the application directory are static files, and which URLs serve them."'),
        staticFiles: {
          '#withApplicationReadable':: d.fn(help='"Whether files should also be uploaded as code data. By default, files declared in static file handlers are uploaded as static data and are only served to end users; they cannot be read by the application. If enabled, uploads are charged against both your code and static data storage resource quotas."', args=[d.arg(name='applicationReadable', type=d.T.boolean)]),
          withApplicationReadable(applicationReadable): { applicationReadable: applicationReadable },
          '#withExpiration':: d.fn(help="\"Time a static file served by this handler should be cached by web proxies and browsers. A duration in seconds with up to nine fractional digits, terminated by 's'. Example \\\"3.5s\\\". Default is '0s'\"", args=[d.arg(name='expiration', type=d.T.string)]),
          withExpiration(expiration): { expiration: expiration },
          '#withHttpHeaders':: d.fn(help='"HTTP headers to use for all responses from these URLs. An object containing a list of \\"key:value\\" value pairs.\\"."', args=[d.arg(name='httpHeaders', type=d.T.object)]),
          withHttpHeaders(httpHeaders): { httpHeaders: httpHeaders },
          '#withHttpHeadersMixin':: d.fn(help='"HTTP headers to use for all responses from these URLs. An object containing a list of \\"key:value\\" value pairs.\\"."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='httpHeaders', type=d.T.object)]),
          withHttpHeadersMixin(httpHeaders): { httpHeaders+: httpHeaders },
          '#withMimeType':: d.fn(help="\"MIME type used to serve all files served by this handler. Defaults to file-specific MIME types, which are derived from each file's filename extension.\"", args=[d.arg(name='mimeType', type=d.T.string)]),
          withMimeType(mimeType): { mimeType: mimeType },
          '#withPath':: d.fn(help='"Path to the static files matched by the URL pattern, from the application root directory. The path can refer to text matched in groupings in the URL pattern."', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { path: path },
          '#withRequireMatchingFile':: d.fn(help='"Whether this handler should match the request if the file referenced by the handler does not exist."', args=[d.arg(name='requireMatchingFile', type=d.T.boolean)]),
          withRequireMatchingFile(requireMatchingFile): { requireMatchingFile: requireMatchingFile },
          '#withUploadPathRegex':: d.fn(help='"Regular expression that matches the file paths for all files that should be referenced by this handler."', args=[d.arg(name='uploadPathRegex', type=d.T.string)]),
          withUploadPathRegex(uploadPathRegex): { uploadPathRegex: uploadPathRegex },
        },
        '#withAuthFailAction':: d.fn(help='"Actions to take when the user is not logged in. Possible values: [\\"AUTH_FAIL_ACTION_REDIRECT\\", \\"AUTH_FAIL_ACTION_UNAUTHORIZED\\"]"', args=[d.arg(name='authFailAction', type=d.T.string)]),
        withAuthFailAction(authFailAction): { authFailAction: authFailAction },
        '#withLogin':: d.fn(help='"Methods to restrict access to a URL based on login status. Possible values: [\\"LOGIN_OPTIONAL\\", \\"LOGIN_ADMIN\\", \\"LOGIN_REQUIRED\\"]"', args=[d.arg(name='login', type=d.T.string)]),
        withLogin(login): { login: login },
        '#withRedirectHttpResponseCode':: d.fn(help='"30x code to use when performing redirects for the secure field. Possible values: [\\"REDIRECT_HTTP_RESPONSE_CODE_301\\", \\"REDIRECT_HTTP_RESPONSE_CODE_302\\", \\"REDIRECT_HTTP_RESPONSE_CODE_303\\", \\"REDIRECT_HTTP_RESPONSE_CODE_307\\"]"', args=[d.arg(name='redirectHttpResponseCode', type=d.T.string)]),
        withRedirectHttpResponseCode(redirectHttpResponseCode): { redirectHttpResponseCode: redirectHttpResponseCode },
        '#withScript':: d.fn(help='"Executes a script to handle the requests that match this URL pattern. Only the auto value is supported for Node.js in the App Engine standard environment, for example \\"script:\\" \\"auto\\"."', args=[d.arg(name='script', type=d.T.array)]),
        withScript(script): { script: if std.isArray(v=script) then script else [script] },
        '#withScriptMixin':: d.fn(help='"Executes a script to handle the requests that match this URL pattern. Only the auto value is supported for Node.js in the App Engine standard environment, for example \\"script:\\" \\"auto\\"."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='script', type=d.T.array)]),
        withScriptMixin(script): { script+: if std.isArray(v=script) then script else [script] },
        '#withSecurityLevel':: d.fn(help='"Security (HTTPS) enforcement for this URL. Possible values: [\\"SECURE_DEFAULT\\", \\"SECURE_NEVER\\", \\"SECURE_OPTIONAL\\", \\"SECURE_ALWAYS\\"]"', args=[d.arg(name='securityLevel', type=d.T.string)]),
        withSecurityLevel(securityLevel): { securityLevel: securityLevel },
        '#withStaticFiles':: d.fn(help='"Files served directly to the user for a given URL, such as images, CSS stylesheets, or JavaScript source files. Static file handlers describe which files in the application directory are static files, and which URLs serve them."', args=[d.arg(name='staticFiles', type=d.T.array)]),
        withStaticFiles(staticFiles): { staticFiles: if std.isArray(v=staticFiles) then staticFiles else [staticFiles] },
        '#withStaticFilesMixin':: d.fn(help='"Files served directly to the user for a given URL, such as images, CSS stylesheets, or JavaScript source files. Static file handlers describe which files in the application directory are static files, and which URLs serve them."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='staticFiles', type=d.T.array)]),
        withStaticFilesMixin(staticFiles): { staticFiles+: if std.isArray(v=staticFiles) then staticFiles else [staticFiles] },
        '#withUrlRegex':: d.fn(help='"URL prefix. Uses regular expression syntax, which means regexp special characters must be escaped, but should not contain groupings. All URLs that begin with this prefix are handled by this handler, using the portion of the URL after the prefix as part of the file path."', args=[d.arg(name='urlRegex', type=d.T.string)]),
        withUrlRegex(urlRegex): { urlRegex: urlRegex },
      },
      '#livenessCheck':: d.obj(help='"Health checking configuration for VM instances. Unhealthy instances are killed and replaced with new instances."'),
      livenessCheck: {
        '#withCheckInterval':: d.fn(help='"Interval between health checks."', args=[d.arg(name='checkInterval', type=d.T.string)]),
        withCheckInterval(checkInterval): { checkInterval: checkInterval },
        '#withFailureThreshold':: d.fn(help='"Number of consecutive failed checks required before considering the VM unhealthy. Default: 4."', args=[d.arg(name='failureThreshold', type=d.T.number)]),
        withFailureThreshold(failureThreshold): { failureThreshold: failureThreshold },
        '#withHost':: d.fn(help='"Host header to send when performing a HTTP Readiness check. Example: \\"myapp.appspot.com\\', args=[d.arg(name='host', type=d.T.string)]),
        withHost(host): { host: host },
        '#withInitialDelay':: d.fn(help='"The initial delay before starting to execute the checks. Default: \\"300s\\', args=[d.arg(name='initialDelay', type=d.T.string)]),
        withInitialDelay(initialDelay): { initialDelay: initialDelay },
        '#withPath':: d.fn(help='"The request path."', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { path: path },
        '#withSuccessThreshold':: d.fn(help='"Number of consecutive successful checks required before considering the VM healthy. Default: 2."', args=[d.arg(name='successThreshold', type=d.T.number)]),
        withSuccessThreshold(successThreshold): { successThreshold: successThreshold },
        '#withTimeout':: d.fn(help='"Time before the check is considered failed. Default: \\"4s\\', args=[d.arg(name='timeout', type=d.T.string)]),
        withTimeout(timeout): { timeout: timeout },
      },
      '#manualScaling':: d.obj(help='"A service with manual scaling runs continuously, allowing you to perform complex initialization and rely on the state of its memory over time."'),
      manualScaling: {
        '#withInstances':: d.fn(help="\"Number of instances to assign to the service at the start. \\n **Note:** When managing the number of instances at runtime through the App Engine Admin API or the (now deprecated) Python 2 Modules API set_num_instances() you must use 'lifecycle.ignore_changes = [\\\"manual_scaling\\\"[0].instances]' to prevent drift detection.\"", args=[d.arg(name='instances', type=d.T.integer)]),
        withInstances(instances): { instances: instances },
      },
      '#network':: d.obj(help='"Extra network settings"'),
      network: {
        '#withForwardedPorts':: d.fn(help='"List of ports, or port pairs, to forward from the virtual machine to the application container."', args=[d.arg(name='forwardedPorts', type=d.T.array)]),
        withForwardedPorts(forwardedPorts): { forwardedPorts: if std.isArray(v=forwardedPorts) then forwardedPorts else [forwardedPorts] },
        '#withForwardedPortsMixin':: d.fn(help='"List of ports, or port pairs, to forward from the virtual machine to the application container."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='forwardedPorts', type=d.T.array)]),
        withForwardedPortsMixin(forwardedPorts): { forwardedPorts+: if std.isArray(v=forwardedPorts) then forwardedPorts else [forwardedPorts] },
        '#withInstanceTag':: d.fn(help='"Tag to apply to the instance during creation."', args=[d.arg(name='instanceTag', type=d.T.string)]),
        withInstanceTag(instanceTag): { instanceTag: instanceTag },
        '#withName':: d.fn(help='"Google Compute Engine network where the virtual machines are created. Specify the short name, not the resource path."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withSessionAffinity':: d.fn(help='"Enable session affinity."', args=[d.arg(name='sessionAffinity', type=d.T.boolean)]),
        withSessionAffinity(sessionAffinity): { sessionAffinity: sessionAffinity },
        '#withSubnetwork':: d.fn(help='"Google Cloud Platform sub-network where the virtual machines are created. Specify the short name, not the resource path. \\n If the network that the instance is being created in is a Legacy network, then the IP address is allocated from the IPv4Range. If the network that the instance is being created in is an auto Subnet Mode Network, then only network name should be specified (not the subnetworkName) and the IP address is created from the IPCidrRange of the subnetwork that exists in that zone for that network. If the network that the instance is being created in is a custom Subnet Mode Network, then the subnetworkName must be specified and the IP address is created from the IPCidrRange of the subnetwork. If specified, the subnetwork must exist in the same region as the App Engine flexible environment application."', args=[d.arg(name='subnetwork', type=d.T.string)]),
        withSubnetwork(subnetwork): { subnetwork: subnetwork },
      },
      '#readinessCheck':: d.obj(help='"Configures readiness health checking for instances. Unhealthy instances are not put into the backend traffic rotation."'),
      readinessCheck: {
        '#withAppStartTimeout':: d.fn(help='"A maximum time limit on application initialization, measured from moment the application successfully replies to a healthcheck until it is ready to serve traffic. Default: \\"300s\\', args=[d.arg(name='appStartTimeout', type=d.T.string)]),
        withAppStartTimeout(appStartTimeout): { appStartTimeout: appStartTimeout },
        '#withCheckInterval':: d.fn(help='"Interval between health checks.  Default: \\"5s\\"."', args=[d.arg(name='checkInterval', type=d.T.string)]),
        withCheckInterval(checkInterval): { checkInterval: checkInterval },
        '#withFailureThreshold':: d.fn(help='"Number of consecutive failed checks required before removing traffic. Default: 2."', args=[d.arg(name='failureThreshold', type=d.T.number)]),
        withFailureThreshold(failureThreshold): { failureThreshold: failureThreshold },
        '#withHost':: d.fn(help='"Host header to send when performing a HTTP Readiness check. Example: \\"myapp.appspot.com\\', args=[d.arg(name='host', type=d.T.string)]),
        withHost(host): { host: host },
        '#withPath':: d.fn(help='"The request path."', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { path: path },
        '#withSuccessThreshold':: d.fn(help='"Number of consecutive successful checks required before receiving traffic. Default: 2."', args=[d.arg(name='successThreshold', type=d.T.number)]),
        withSuccessThreshold(successThreshold): { successThreshold: successThreshold },
        '#withTimeout':: d.fn(help='"Time before the check is considered failed. Default: \\"4s\\', args=[d.arg(name='timeout', type=d.T.string)]),
        withTimeout(timeout): { timeout: timeout },
      },
      '#resources':: d.obj(help='"Machine resources for a version."'),
      resources: {
        '#volumes':: d.obj(help='"List of ports, or port pairs, to forward from the virtual machine to the application container."'),
        volumes: {
          '#withName':: d.fn(help='"Unique name for the volume."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withSizeGb':: d.fn(help='"Volume size in gigabytes."', args=[d.arg(name='sizeGb', type=d.T.integer)]),
          withSizeGb(sizeGb): { sizeGb: sizeGb },
          '#withVolumeType':: d.fn(help="\"Underlying volume type, e.g. 'tmpfs'.\"", args=[d.arg(name='volumeType', type=d.T.string)]),
          withVolumeType(volumeType): { volumeType: volumeType },
        },
        '#withCpu':: d.fn(help='"Number of CPU cores needed."', args=[d.arg(name='cpu', type=d.T.integer)]),
        withCpu(cpu): { cpu: cpu },
        '#withDiskGb':: d.fn(help='"Disk size (GB) needed."', args=[d.arg(name='diskGb', type=d.T.integer)]),
        withDiskGb(diskGb): { diskGb: diskGb },
        '#withMemoryGb':: d.fn(help='"Memory (GB) needed."', args=[d.arg(name='memoryGb', type=d.T.number)]),
        withMemoryGb(memoryGb): { memoryGb: memoryGb },
        '#withVolumes':: d.fn(help='"List of ports, or port pairs, to forward from the virtual machine to the application container."', args=[d.arg(name='volumes', type=d.T.array)]),
        withVolumes(volumes): { volumes: if std.isArray(v=volumes) then volumes else [volumes] },
        '#withVolumesMixin':: d.fn(help='"List of ports, or port pairs, to forward from the virtual machine to the application container."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='volumes', type=d.T.array)]),
        withVolumesMixin(volumes): { volumes+: if std.isArray(v=volumes) then volumes else [volumes] },
      },
      '#vpcAccessConnector':: d.obj(help='"Enables VPC connectivity for standard apps."'),
      vpcAccessConnector: {
        '#withName':: d.fn(help='"Full Serverless VPC Access Connector name e.g. /projects/my-project/locations/us-central1/connectors/c1."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#withApiConfig':: d.fn(help='"Serving configuration for Google Cloud Endpoints."', args=[d.arg(name='apiConfig', type=d.T.array)]),
      withApiConfig(apiConfig): { spec+: { forProvider+: { apiConfig: if std.isArray(v=apiConfig) then apiConfig else [apiConfig] } } },
      '#withApiConfigMixin':: d.fn(help='"Serving configuration for Google Cloud Endpoints."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='apiConfig', type=d.T.array)]),
      withApiConfigMixin(apiConfig): { spec+: { forProvider+: { apiConfig+: if std.isArray(v=apiConfig) then apiConfig else [apiConfig] } } },
      '#withAutomaticScaling':: d.fn(help='"Automatic scaling is based on request rate, response latencies, and other application metrics."', args=[d.arg(name='automaticScaling', type=d.T.array)]),
      withAutomaticScaling(automaticScaling): { spec+: { forProvider+: { automaticScaling: if std.isArray(v=automaticScaling) then automaticScaling else [automaticScaling] } } },
      '#withAutomaticScalingMixin':: d.fn(help='"Automatic scaling is based on request rate, response latencies, and other application metrics."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='automaticScaling', type=d.T.array)]),
      withAutomaticScalingMixin(automaticScaling): { spec+: { forProvider+: { automaticScaling+: if std.isArray(v=automaticScaling) then automaticScaling else [automaticScaling] } } },
      '#withBetaSettings':: d.fn(help='"Metadata settings that are supplied to this version to enable beta runtime features."', args=[d.arg(name='betaSettings', type=d.T.object)]),
      withBetaSettings(betaSettings): { spec+: { forProvider+: { betaSettings: betaSettings } } },
      '#withBetaSettingsMixin':: d.fn(help='"Metadata settings that are supplied to this version to enable beta runtime features."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='betaSettings', type=d.T.object)]),
      withBetaSettingsMixin(betaSettings): { spec+: { forProvider+: { betaSettings+: betaSettings } } },
      '#withDefaultExpiration':: d.fn(help='"Duration that static files should be cached by web proxies and browsers. Only applicable if the corresponding StaticFilesHandler does not specify its own expiration time."', args=[d.arg(name='defaultExpiration', type=d.T.string)]),
      withDefaultExpiration(defaultExpiration): { spec+: { forProvider+: { defaultExpiration: defaultExpiration } } },
      '#withDeleteServiceOnDestroy':: d.fn(help='', args=[d.arg(name='deleteServiceOnDestroy', type=d.T.boolean)]),
      withDeleteServiceOnDestroy(deleteServiceOnDestroy): { spec+: { forProvider+: { deleteServiceOnDestroy: deleteServiceOnDestroy } } },
      '#withDeployment':: d.fn(help='"Code and application artifacts that make up this version."', args=[d.arg(name='deployment', type=d.T.array)]),
      withDeployment(deployment): { spec+: { forProvider+: { deployment: if std.isArray(v=deployment) then deployment else [deployment] } } },
      '#withDeploymentMixin':: d.fn(help='"Code and application artifacts that make up this version."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='deployment', type=d.T.array)]),
      withDeploymentMixin(deployment): { spec+: { forProvider+: { deployment+: if std.isArray(v=deployment) then deployment else [deployment] } } },
      '#withEndpointsApiService':: d.fn(help='"Code and application artifacts that make up this version."', args=[d.arg(name='endpointsApiService', type=d.T.array)]),
      withEndpointsApiService(endpointsApiService): { spec+: { forProvider+: { endpointsApiService: if std.isArray(v=endpointsApiService) then endpointsApiService else [endpointsApiService] } } },
      '#withEndpointsApiServiceMixin':: d.fn(help='"Code and application artifacts that make up this version."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='endpointsApiService', type=d.T.array)]),
      withEndpointsApiServiceMixin(endpointsApiService): { spec+: { forProvider+: { endpointsApiService+: if std.isArray(v=endpointsApiService) then endpointsApiService else [endpointsApiService] } } },
      '#withEntrypoint':: d.fn(help='"The entrypoint for the application."', args=[d.arg(name='entrypoint', type=d.T.array)]),
      withEntrypoint(entrypoint): { spec+: { forProvider+: { entrypoint: if std.isArray(v=entrypoint) then entrypoint else [entrypoint] } } },
      '#withEntrypointMixin':: d.fn(help='"The entrypoint for the application."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='entrypoint', type=d.T.array)]),
      withEntrypointMixin(entrypoint): { spec+: { forProvider+: { entrypoint+: if std.isArray(v=entrypoint) then entrypoint else [entrypoint] } } },
      '#withEnvVariables':: d.fn(help='"Environment variables available to the application.  As these are not returned in the API request, Terraform will not detect any changes made outside of the Terraform config."', args=[d.arg(name='envVariables', type=d.T.object)]),
      withEnvVariables(envVariables): { spec+: { forProvider+: { envVariables: envVariables } } },
      '#withEnvVariablesMixin':: d.fn(help='"Environment variables available to the application.  As these are not returned in the API request, Terraform will not detect any changes made outside of the Terraform config."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='envVariables', type=d.T.object)]),
      withEnvVariablesMixin(envVariables): { spec+: { forProvider+: { envVariables+: envVariables } } },
      '#withHandlers':: d.fn(help='"An ordered list of URL-matching patterns that should be applied to incoming requests. The first matching URL handles the request and other request handlers are not attempted."', args=[d.arg(name='handlers', type=d.T.array)]),
      withHandlers(handlers): { spec+: { forProvider+: { handlers: if std.isArray(v=handlers) then handlers else [handlers] } } },
      '#withHandlersMixin':: d.fn(help='"An ordered list of URL-matching patterns that should be applied to incoming requests. The first matching URL handles the request and other request handlers are not attempted."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='handlers', type=d.T.array)]),
      withHandlersMixin(handlers): { spec+: { forProvider+: { handlers+: if std.isArray(v=handlers) then handlers else [handlers] } } },
      '#withInboundServices':: d.fn(help='"A list of the types of messages that this application is able to receive. Possible values: [\\"INBOUND_SERVICE_MAIL\\", \\"INBOUND_SERVICE_MAIL_BOUNCE\\", \\"INBOUND_SERVICE_XMPP_ERROR\\", \\"INBOUND_SERVICE_XMPP_MESSAGE\\", \\"INBOUND_SERVICE_XMPP_SUBSCRIBE\\", \\"INBOUND_SERVICE_XMPP_PRESENCE\\", \\"INBOUND_SERVICE_CHANNEL_PRESENCE\\", \\"INBOUND_SERVICE_WARMUP\\"]"', args=[d.arg(name='inboundServices', type=d.T.array)]),
      withInboundServices(inboundServices): { spec+: { forProvider+: { inboundServices: if std.isArray(v=inboundServices) then inboundServices else [inboundServices] } } },
      '#withInboundServicesMixin':: d.fn(help='"A list of the types of messages that this application is able to receive. Possible values: [\\"INBOUND_SERVICE_MAIL\\", \\"INBOUND_SERVICE_MAIL_BOUNCE\\", \\"INBOUND_SERVICE_XMPP_ERROR\\", \\"INBOUND_SERVICE_XMPP_MESSAGE\\", \\"INBOUND_SERVICE_XMPP_SUBSCRIBE\\", \\"INBOUND_SERVICE_XMPP_PRESENCE\\", \\"INBOUND_SERVICE_CHANNEL_PRESENCE\\", \\"INBOUND_SERVICE_WARMUP\\"]"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='inboundServices', type=d.T.array)]),
      withInboundServicesMixin(inboundServices): { spec+: { forProvider+: { inboundServices+: if std.isArray(v=inboundServices) then inboundServices else [inboundServices] } } },
      '#withInstanceClass':: d.fn(help='"Instance class that is used to run this version. Valid values are AutomaticScaling: F1, F2, F4, F4_1G ManualScaling: B1, B2, B4, B8, B4_1G Defaults to F1 for AutomaticScaling and B1 for ManualScaling."', args=[d.arg(name='instanceClass', type=d.T.string)]),
      withInstanceClass(instanceClass): { spec+: { forProvider+: { instanceClass: instanceClass } } },
      '#withLivenessCheck':: d.fn(help='"Health checking configuration for VM instances. Unhealthy instances are killed and replaced with new instances."', args=[d.arg(name='livenessCheck', type=d.T.array)]),
      withLivenessCheck(livenessCheck): { spec+: { forProvider+: { livenessCheck: if std.isArray(v=livenessCheck) then livenessCheck else [livenessCheck] } } },
      '#withLivenessCheckMixin':: d.fn(help='"Health checking configuration for VM instances. Unhealthy instances are killed and replaced with new instances."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='livenessCheck', type=d.T.array)]),
      withLivenessCheckMixin(livenessCheck): { spec+: { forProvider+: { livenessCheck+: if std.isArray(v=livenessCheck) then livenessCheck else [livenessCheck] } } },
      '#withManualScaling':: d.fn(help='"A service with manual scaling runs continuously, allowing you to perform complex initialization and rely on the state of its memory over time."', args=[d.arg(name='manualScaling', type=d.T.array)]),
      withManualScaling(manualScaling): { spec+: { forProvider+: { manualScaling: if std.isArray(v=manualScaling) then manualScaling else [manualScaling] } } },
      '#withManualScalingMixin':: d.fn(help='"A service with manual scaling runs continuously, allowing you to perform complex initialization and rely on the state of its memory over time."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='manualScaling', type=d.T.array)]),
      withManualScalingMixin(manualScaling): { spec+: { forProvider+: { manualScaling+: if std.isArray(v=manualScaling) then manualScaling else [manualScaling] } } },
      '#withNetwork':: d.fn(help='"Extra network settings"', args=[d.arg(name='network', type=d.T.array)]),
      withNetwork(network): { spec+: { forProvider+: { network: if std.isArray(v=network) then network else [network] } } },
      '#withNetworkMixin':: d.fn(help='"Extra network settings"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='network', type=d.T.array)]),
      withNetworkMixin(network): { spec+: { forProvider+: { network+: if std.isArray(v=network) then network else [network] } } },
      '#withNobuildFilesRegex':: d.fn(help='"Files that match this pattern will not be built into this version. Only applicable for Go runtimes."', args=[d.arg(name='nobuildFilesRegex', type=d.T.string)]),
      withNobuildFilesRegex(nobuildFilesRegex): { spec+: { forProvider+: { nobuildFilesRegex: nobuildFilesRegex } } },
      '#withNoopOnDestroy':: d.fn(help='', args=[d.arg(name='noopOnDestroy', type=d.T.boolean)]),
      withNoopOnDestroy(noopOnDestroy): { spec+: { forProvider+: { noopOnDestroy: noopOnDestroy } } },
      '#withProject':: d.fn(help='', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withReadinessCheck':: d.fn(help='"Configures readiness health checking for instances. Unhealthy instances are not put into the backend traffic rotation."', args=[d.arg(name='readinessCheck', type=d.T.array)]),
      withReadinessCheck(readinessCheck): { spec+: { forProvider+: { readinessCheck: if std.isArray(v=readinessCheck) then readinessCheck else [readinessCheck] } } },
      '#withReadinessCheckMixin':: d.fn(help='"Configures readiness health checking for instances. Unhealthy instances are not put into the backend traffic rotation."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='readinessCheck', type=d.T.array)]),
      withReadinessCheckMixin(readinessCheck): { spec+: { forProvider+: { readinessCheck+: if std.isArray(v=readinessCheck) then readinessCheck else [readinessCheck] } } },
      '#withResources':: d.fn(help='"Machine resources for a version."', args=[d.arg(name='resources', type=d.T.array)]),
      withResources(resources): { spec+: { forProvider+: { resources: if std.isArray(v=resources) then resources else [resources] } } },
      '#withResourcesMixin':: d.fn(help='"Machine resources for a version."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='resources', type=d.T.array)]),
      withResourcesMixin(resources): { spec+: { forProvider+: { resources+: if std.isArray(v=resources) then resources else [resources] } } },
      '#withRuntime':: d.fn(help='"Desired runtime. Example python27."', args=[d.arg(name='runtime', type=d.T.string)]),
      withRuntime(runtime): { spec+: { forProvider+: { runtime: runtime } } },
      '#withRuntimeApiVersion':: d.fn(help='"The version of the API in the given runtime environment. Please see the app.yaml reference for valid values at https://cloud.google.com/appengine/docs/standard//config/appref"', args=[d.arg(name='runtimeApiVersion', type=d.T.string)]),
      withRuntimeApiVersion(runtimeApiVersion): { spec+: { forProvider+: { runtimeApiVersion: runtimeApiVersion } } },
      '#withRuntimeChannel':: d.fn(help='"The channel of the runtime to use. Only available for some runtimes."', args=[d.arg(name='runtimeChannel', type=d.T.string)]),
      withRuntimeChannel(runtimeChannel): { spec+: { forProvider+: { runtimeChannel: runtimeChannel } } },
      '#withRuntimeMainExecutablePath':: d.fn(help="\"The path or name of the app's main executable.\"", args=[d.arg(name='runtimeMainExecutablePath', type=d.T.string)]),
      withRuntimeMainExecutablePath(runtimeMainExecutablePath): { spec+: { forProvider+: { runtimeMainExecutablePath: runtimeMainExecutablePath } } },
      '#withService':: d.fn(help='"AppEngine service resource. Can contain numbers, letters, and hyphens."', args=[d.arg(name='service', type=d.T.string)]),
      withService(service): { spec+: { forProvider+: { service: service } } },
      '#withServingStatus':: d.fn(help='"Current serving status of this version. Only the versions with a SERVING status create instances and can be billed. Default value: \\"SERVING\\" Possible values: [\\"SERVING\\", \\"STOPPED\\"]"', args=[d.arg(name='servingStatus', type=d.T.string)]),
      withServingStatus(servingStatus): { spec+: { forProvider+: { servingStatus: servingStatus } } },
      '#withVersionId':: d.fn(help="\"Relative name of the version within the service. For example, 'v1'. Version names can contain only lowercase letters, numbers, or hyphens. Reserved names,\\\"default\\\", \\\"latest\\\", and any name with the prefix \\\"ah-\\\".\"", args=[d.arg(name='versionId', type=d.T.string)]),
      withVersionId(versionId): { spec+: { forProvider+: { versionId: versionId } } },
      '#withVpcAccessConnector':: d.fn(help='"Enables VPC connectivity for standard apps."', args=[d.arg(name='vpcAccessConnector', type=d.T.array)]),
      withVpcAccessConnector(vpcAccessConnector): { spec+: { forProvider+: { vpcAccessConnector: if std.isArray(v=vpcAccessConnector) then vpcAccessConnector else [vpcAccessConnector] } } },
      '#withVpcAccessConnectorMixin':: d.fn(help='"Enables VPC connectivity for standard apps."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='vpcAccessConnector', type=d.T.array)]),
      withVpcAccessConnectorMixin(vpcAccessConnector): { spec+: { forProvider+: { vpcAccessConnector+: if std.isArray(v=vpcAccessConnector) then vpcAccessConnector else [vpcAccessConnector] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
