{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='kafkaCluster', url='', help='"KafkaCluster is the Schema for the KafkaClusters API. Manages a HDInsight Kafka Cluster."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of KafkaCluster', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'hdinsight.azure.upbound.io/v1beta1',
    kind: 'KafkaCluster',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"KafkaClusterSpec defines the desired state of KafkaCluster"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#componentVersion':: d.obj(help='"A component_version block as defined below."'),
      componentVersion: {
        '#withKafka':: d.fn(help='"The version of Kafka which should be used for this HDInsight Kafka Cluster. Changing this forces a new resource to be created."', args=[d.arg(name='kafka', type=d.T.string)]),
        withKafka(kafka): { kafka: kafka },
      },
      '#computeIsolation':: d.obj(help='"A compute_isolation block as defined below."'),
      computeIsolation: {
        '#withComputeIsolationEnabled':: d.fn(help='"This field indicates whether enable compute isolation or not. Possible values are true or false."', args=[d.arg(name='computeIsolationEnabled', type=d.T.boolean)]),
        withComputeIsolationEnabled(computeIsolationEnabled): { computeIsolationEnabled: computeIsolationEnabled },
        '#withHostSku':: d.fn(help='"The name of the host SKU."', args=[d.arg(name='hostSku', type=d.T.string)]),
        withHostSku(hostSku): { hostSku: hostSku },
      },
      '#diskEncryption':: d.obj(help='"One or more disk_encryption block as defined below."'),
      diskEncryption: {
        '#withEncryptionAlgorithm':: d.fn(help='"This is an algorithm identifier for encryption. Possible values are RSA1_5, RSA-OAEP, RSA-OAEP-256."', args=[d.arg(name='encryptionAlgorithm', type=d.T.string)]),
        withEncryptionAlgorithm(encryptionAlgorithm): { encryptionAlgorithm: encryptionAlgorithm },
        '#withEncryptionAtHostEnabled':: d.fn(help='"This is indicator to show whether resource disk encryption is enabled."', args=[d.arg(name='encryptionAtHostEnabled', type=d.T.boolean)]),
        withEncryptionAtHostEnabled(encryptionAtHostEnabled): { encryptionAtHostEnabled: encryptionAtHostEnabled },
        '#withKeyVaultKeyId':: d.fn(help='"The ID of the key vault key."', args=[d.arg(name='keyVaultKeyId', type=d.T.string)]),
        withKeyVaultKeyId(keyVaultKeyId): { keyVaultKeyId: keyVaultKeyId },
        '#withKeyVaultManagedIdentityId':: d.fn(help='"This is the resource ID of Managed Identity used to access the key vault."', args=[d.arg(name='keyVaultManagedIdentityId', type=d.T.string)]),
        withKeyVaultManagedIdentityId(keyVaultManagedIdentityId): { keyVaultManagedIdentityId: keyVaultManagedIdentityId },
      },
      '#extension':: d.obj(help='"An extension block as defined below."'),
      extension: {
        '#primaryKeySecretRef':: d.obj(help='"The workspace key of the log analytics extension."'),
        primaryKeySecretRef: {
          '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { primaryKeySecretRef+: { key: key } },
          '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { primaryKeySecretRef+: { name: name } },
          '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { primaryKeySecretRef+: { namespace: namespace } },
        },
        '#withLogAnalyticsWorkspaceId':: d.fn(help='"The workspace ID of the log analytics extension."', args=[d.arg(name='logAnalyticsWorkspaceId', type=d.T.string)]),
        withLogAnalyticsWorkspaceId(logAnalyticsWorkspaceId): { logAnalyticsWorkspaceId: logAnalyticsWorkspaceId },
      },
      '#gateway':: d.obj(help='"A gateway block as defined below."'),
      gateway: {
        '#passwordSecretRef':: d.obj(help='"The password used for the Ambari Portal."'),
        passwordSecretRef: {
          '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { passwordSecretRef+: { key: key } },
          '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { passwordSecretRef+: { name: name } },
          '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
        },
        '#withUsername':: d.fn(help='"The username used for the Ambari Portal. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
        withUsername(username): { username: username },
      },
      '#metastores':: d.obj(help='"A metastores block as defined below."'),
      metastores: {
        '#ambari':: d.obj(help='"An ambari block as defined below."'),
        ambari: {
          '#passwordSecretRef':: d.obj(help='"The Password associated with the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#withDatabaseName':: d.fn(help="\"The external Oozie metastore's existing SQL database. Changing this forces a new resource to be created.\"", args=[d.arg(name='databaseName', type=d.T.string)]),
          withDatabaseName(databaseName): { databaseName: databaseName },
          '#withServer':: d.fn(help='"The fully-qualified domain name (FQDN) of the SQL server to use for the external Oozie metastore. Changing this forces a new resource to be created."', args=[d.arg(name='server', type=d.T.string)]),
          withServer(server): { server: server },
          '#withUsername':: d.fn(help='"The Username of the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
        },
        '#hive':: d.obj(help='"A hive block as defined below."'),
        hive: {
          '#passwordSecretRef':: d.obj(help='"The Password associated with the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#withDatabaseName':: d.fn(help="\"The external Oozie metastore's existing SQL database. Changing this forces a new resource to be created.\"", args=[d.arg(name='databaseName', type=d.T.string)]),
          withDatabaseName(databaseName): { databaseName: databaseName },
          '#withServer':: d.fn(help='"The fully-qualified domain name (FQDN) of the SQL server to use for the external Oozie metastore. Changing this forces a new resource to be created."', args=[d.arg(name='server', type=d.T.string)]),
          withServer(server): { server: server },
          '#withUsername':: d.fn(help='"The Username of the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
        },
        '#oozie':: d.obj(help='"An oozie block as defined below."'),
        oozie: {
          '#passwordSecretRef':: d.obj(help='"The Password associated with the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#withDatabaseName':: d.fn(help="\"The external Oozie metastore's existing SQL database. Changing this forces a new resource to be created.\"", args=[d.arg(name='databaseName', type=d.T.string)]),
          withDatabaseName(databaseName): { databaseName: databaseName },
          '#withServer':: d.fn(help='"The fully-qualified domain name (FQDN) of the SQL server to use for the external Oozie metastore. Changing this forces a new resource to be created."', args=[d.arg(name='server', type=d.T.string)]),
          withServer(server): { server: server },
          '#withUsername':: d.fn(help='"The Username of the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
        },
        '#withAmbari':: d.fn(help='"An ambari block as defined below."', args=[d.arg(name='ambari', type=d.T.array)]),
        withAmbari(ambari): { ambari: if std.isArray(v=ambari) then ambari else [ambari] },
        '#withAmbariMixin':: d.fn(help='"An ambari block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ambari', type=d.T.array)]),
        withAmbariMixin(ambari): { ambari+: if std.isArray(v=ambari) then ambari else [ambari] },
        '#withHive':: d.fn(help='"A hive block as defined below."', args=[d.arg(name='hive', type=d.T.array)]),
        withHive(hive): { hive: if std.isArray(v=hive) then hive else [hive] },
        '#withHiveMixin':: d.fn(help='"A hive block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='hive', type=d.T.array)]),
        withHiveMixin(hive): { hive+: if std.isArray(v=hive) then hive else [hive] },
        '#withOozie':: d.fn(help='"An oozie block as defined below."', args=[d.arg(name='oozie', type=d.T.array)]),
        withOozie(oozie): { oozie: if std.isArray(v=oozie) then oozie else [oozie] },
        '#withOozieMixin':: d.fn(help='"An oozie block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='oozie', type=d.T.array)]),
        withOozieMixin(oozie): { oozie+: if std.isArray(v=oozie) then oozie else [oozie] },
      },
      '#monitor':: d.obj(help='"A monitor block as defined below."'),
      monitor: {
        '#primaryKeySecretRef':: d.obj(help='"The Operations Management Suite (OMS) workspace key."'),
        primaryKeySecretRef: {
          '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { primaryKeySecretRef+: { key: key } },
          '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { primaryKeySecretRef+: { name: name } },
          '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { primaryKeySecretRef+: { namespace: namespace } },
        },
        '#withLogAnalyticsWorkspaceId':: d.fn(help='"The Operations Management Suite (OMS) workspace ID."', args=[d.arg(name='logAnalyticsWorkspaceId', type=d.T.string)]),
        withLogAnalyticsWorkspaceId(logAnalyticsWorkspaceId): { logAnalyticsWorkspaceId: logAnalyticsWorkspaceId },
      },
      '#network':: d.obj(help='"A network block as defined below."'),
      network: {
        '#withConnectionDirection':: d.fn(help='"The direction of the resource provider connection. Possible values include Inbound or Outbound. Defaults to Inbound. Changing this forces a new resource to be created."', args=[d.arg(name='connectionDirection', type=d.T.string)]),
        withConnectionDirection(connectionDirection): { connectionDirection: connectionDirection },
        '#withPrivateLinkEnabled':: d.fn(help='"Is the private link enabled? Possible values include True or False. Defaults to False. Changing this forces a new resource to be created."', args=[d.arg(name='privateLinkEnabled', type=d.T.boolean)]),
        withPrivateLinkEnabled(privateLinkEnabled): { privateLinkEnabled: privateLinkEnabled },
      },
      '#resourceGroupNameRef':: d.obj(help='"Reference to a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { resourceGroupNameRef+: { name: name } } } },
      },
      '#resourceGroupNameSelector':: d.obj(help='"Selector for a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#restProxy':: d.obj(help='"A rest_proxy block as defined below."'),
      restProxy: {
        '#withSecurityGroupId':: d.fn(help='"The Azure Active Directory Security Group ID. Changing this forces a new resource to be created."', args=[d.arg(name='securityGroupId', type=d.T.string)]),
        withSecurityGroupId(securityGroupId): { securityGroupId: securityGroupId },
        '#withSecurityGroupName':: d.fn(help='"The Azure Active Directory Security Group name. Changing this forces a new resource to be created."', args=[d.arg(name='securityGroupName', type=d.T.string)]),
        withSecurityGroupName(securityGroupName): { securityGroupName: securityGroupName },
      },
      '#roles':: d.obj(help='"A roles block as defined below."'),
      roles: {
        '#headNode':: d.obj(help='"A head_node block as defined above."'),
        headNode: {
          '#passwordSecretRef':: d.obj(help='"The Password associated with the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#scriptActions':: d.obj(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."'),
          scriptActions: {
            '#withName':: d.fn(help='"The name of the script action."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withParameters':: d.fn(help='"The parameters for the script provided."', args=[d.arg(name='parameters', type=d.T.string)]),
            withParameters(parameters): { parameters: parameters },
            '#withUri':: d.fn(help='"The URI to the script."', args=[d.arg(name='uri', type=d.T.string)]),
            withUri(uri): { uri: uri },
          },
          '#subnetIdRef':: d.obj(help='"Reference to a Subnet in network to populate subnetId."'),
          subnetIdRef: {
            '#policy':: d.obj(help='"Policies for referencing."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdRef+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdRef+: { policy+: { resolve: resolve } } },
            },
            '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { subnetIdRef+: { name: name } },
          },
          '#subnetIdSelector':: d.obj(help='"Selector for a Subnet in network to populate subnetId."'),
          subnetIdSelector: {
            '#policy':: d.obj(help='"Policies for selection."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdSelector+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdSelector+: { policy+: { resolve: resolve } } },
            },
            '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
            withMatchControllerRef(matchControllerRef): { subnetIdSelector+: { matchControllerRef: matchControllerRef } },
            '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabels(matchLabels): { subnetIdSelector+: { matchLabels: matchLabels } },
            '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabelsMixin(matchLabels): { subnetIdSelector+: { matchLabels+: matchLabels } },
          },
          '#withScriptActions':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActions(scriptActions): { scriptActions: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withScriptActionsMixin':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActionsMixin(scriptActions): { scriptActions+: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withSshKeys':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeys(sshKeys): { sshKeys: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSshKeysMixin':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeysMixin(sshKeys): { sshKeys+: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSubnetId':: d.fn(help='"The ID of the Subnet within the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='subnetId', type=d.T.string)]),
          withSubnetId(subnetId): { subnetId: subnetId },
          '#withUsername':: d.fn(help='"The Username of the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
          '#withVirtualNetworkId':: d.fn(help='"The ID of the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='virtualNetworkId', type=d.T.string)]),
          withVirtualNetworkId(virtualNetworkId): { virtualNetworkId: virtualNetworkId },
          '#withVmSize':: d.fn(help='"The Size of the Virtual Machine which should be used as the Zookeeper Nodes. Possible values are ExtraSmall, Small, Medium, Large, ExtraLarge, A5, A6, A7, A8, A9, A10, A11, Standard_A1_V2, Standard_A2_V2, Standard_A2m_V2, Standard_A3, Standard_A4_V2, Standard_A4m_V2, Standard_A8_V2, Standard_A8m_V2, Standard_D1, Standard_D2, Standard_D3, Standard_D4, Standard_D11, Standard_D12, Standard_D13, Standard_D14, Standard_D1_V2, Standard_D2_V2, Standard_D3_V2, Standard_D4_V2, Standard_D5_V2, Standard_D11_V2, Standard_D12_V2, Standard_D13_V2, Standard_D14_V2, Standard_DS1_V2, Standard_DS2_V2, Standard_DS3_V2, Standard_DS4_V2, Standard_DS5_V2, Standard_DS11_V2, Standard_DS12_V2, Standard_DS13_V2, Standard_DS14_V2, Standard_E2_V3, Standard_E4_V3, Standard_E8_V3, Standard_E16_V3, Standard_E20_V3, Standard_E32_V3, Standard_E64_V3, Standard_E64i_V3, Standard_E2s_V3, Standard_E4s_V3, Standard_E8s_V3, Standard_E16s_V3, Standard_E20s_V3, Standard_E32s_V3, Standard_E64s_V3, Standard_E64is_V3, Standard_D2a_V4, Standard_D4a_V4, Standard_D8a_V4, Standard_D16a_V4, Standard_D32a_V4, Standard_D48a_V4, Standard_D64a_V4, Standard_D96a_V4, Standard_E2a_V4, Standard_E4a_V4, Standard_E8a_V4, Standard_E16a_V4, Standard_E20a_V4, Standard_E32a_V4, Standard_E48a_V4, Standard_E64a_V4, Standard_E96a_V4, Standard_G1, Standard_G2, Standard_G3, Standard_G4, Standard_G5, Standard_F2s_V2, Standard_F4s_V2, Standard_F8s_V2, Standard_F16s_V2, Standard_F32s_V2, Standard_F64s_V2, Standard_F72s_V2, Standard_GS1, Standard_GS2, Standard_GS3, Standard_GS4, Standard_GS5 and Standard_NC24. Changing this forces a new resource to be created."', args=[d.arg(name='vmSize', type=d.T.string)]),
          withVmSize(vmSize): { vmSize: vmSize },
        },
        '#kafkaManagementNode':: d.obj(help='"A kafka_management_node block as defined below."'),
        kafkaManagementNode: {
          '#passwordSecretRef':: d.obj(help='"The Password associated with the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#scriptActions':: d.obj(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."'),
          scriptActions: {
            '#withName':: d.fn(help='"The name of the script action."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withParameters':: d.fn(help='"The parameters for the script provided."', args=[d.arg(name='parameters', type=d.T.string)]),
            withParameters(parameters): { parameters: parameters },
            '#withUri':: d.fn(help='"The URI to the script."', args=[d.arg(name='uri', type=d.T.string)]),
            withUri(uri): { uri: uri },
          },
          '#subnetIdRef':: d.obj(help='"Reference to a Subnet in network to populate subnetId."'),
          subnetIdRef: {
            '#policy':: d.obj(help='"Policies for referencing."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdRef+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdRef+: { policy+: { resolve: resolve } } },
            },
            '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { subnetIdRef+: { name: name } },
          },
          '#subnetIdSelector':: d.obj(help='"Selector for a Subnet in network to populate subnetId."'),
          subnetIdSelector: {
            '#policy':: d.obj(help='"Policies for selection."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdSelector+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdSelector+: { policy+: { resolve: resolve } } },
            },
            '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
            withMatchControllerRef(matchControllerRef): { subnetIdSelector+: { matchControllerRef: matchControllerRef } },
            '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabels(matchLabels): { subnetIdSelector+: { matchLabels: matchLabels } },
            '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabelsMixin(matchLabels): { subnetIdSelector+: { matchLabels+: matchLabels } },
          },
          '#withScriptActions':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActions(scriptActions): { scriptActions: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withScriptActionsMixin':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActionsMixin(scriptActions): { scriptActions+: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withSshKeys':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeys(sshKeys): { sshKeys: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSshKeysMixin':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeysMixin(sshKeys): { sshKeys+: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSubnetId':: d.fn(help='"The ID of the Subnet within the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='subnetId', type=d.T.string)]),
          withSubnetId(subnetId): { subnetId: subnetId },
          '#withUsername':: d.fn(help='"The Username of the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
          '#withVirtualNetworkId':: d.fn(help='"The ID of the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='virtualNetworkId', type=d.T.string)]),
          withVirtualNetworkId(virtualNetworkId): { virtualNetworkId: virtualNetworkId },
          '#withVmSize':: d.fn(help='"The Size of the Virtual Machine which should be used as the Zookeeper Nodes. Possible values are ExtraSmall, Small, Medium, Large, ExtraLarge, A5, A6, A7, A8, A9, A10, A11, Standard_A1_V2, Standard_A2_V2, Standard_A2m_V2, Standard_A3, Standard_A4_V2, Standard_A4m_V2, Standard_A8_V2, Standard_A8m_V2, Standard_D1, Standard_D2, Standard_D3, Standard_D4, Standard_D11, Standard_D12, Standard_D13, Standard_D14, Standard_D1_V2, Standard_D2_V2, Standard_D3_V2, Standard_D4_V2, Standard_D5_V2, Standard_D11_V2, Standard_D12_V2, Standard_D13_V2, Standard_D14_V2, Standard_DS1_V2, Standard_DS2_V2, Standard_DS3_V2, Standard_DS4_V2, Standard_DS5_V2, Standard_DS11_V2, Standard_DS12_V2, Standard_DS13_V2, Standard_DS14_V2, Standard_E2_V3, Standard_E4_V3, Standard_E8_V3, Standard_E16_V3, Standard_E20_V3, Standard_E32_V3, Standard_E64_V3, Standard_E64i_V3, Standard_E2s_V3, Standard_E4s_V3, Standard_E8s_V3, Standard_E16s_V3, Standard_E20s_V3, Standard_E32s_V3, Standard_E64s_V3, Standard_E64is_V3, Standard_D2a_V4, Standard_D4a_V4, Standard_D8a_V4, Standard_D16a_V4, Standard_D32a_V4, Standard_D48a_V4, Standard_D64a_V4, Standard_D96a_V4, Standard_E2a_V4, Standard_E4a_V4, Standard_E8a_V4, Standard_E16a_V4, Standard_E20a_V4, Standard_E32a_V4, Standard_E48a_V4, Standard_E64a_V4, Standard_E96a_V4, Standard_G1, Standard_G2, Standard_G3, Standard_G4, Standard_G5, Standard_F2s_V2, Standard_F4s_V2, Standard_F8s_V2, Standard_F16s_V2, Standard_F32s_V2, Standard_F64s_V2, Standard_F72s_V2, Standard_GS1, Standard_GS2, Standard_GS3, Standard_GS4, Standard_GS5 and Standard_NC24. Changing this forces a new resource to be created."', args=[d.arg(name='vmSize', type=d.T.string)]),
          withVmSize(vmSize): { vmSize: vmSize },
        },
        '#withHeadNode':: d.fn(help='"A head_node block as defined above."', args=[d.arg(name='headNode', type=d.T.array)]),
        withHeadNode(headNode): { headNode: if std.isArray(v=headNode) then headNode else [headNode] },
        '#withHeadNodeMixin':: d.fn(help='"A head_node block as defined above."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headNode', type=d.T.array)]),
        withHeadNodeMixin(headNode): { headNode+: if std.isArray(v=headNode) then headNode else [headNode] },
        '#withKafkaManagementNode':: d.fn(help='"A kafka_management_node block as defined below."', args=[d.arg(name='kafkaManagementNode', type=d.T.array)]),
        withKafkaManagementNode(kafkaManagementNode): { kafkaManagementNode: if std.isArray(v=kafkaManagementNode) then kafkaManagementNode else [kafkaManagementNode] },
        '#withKafkaManagementNodeMixin':: d.fn(help='"A kafka_management_node block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='kafkaManagementNode', type=d.T.array)]),
        withKafkaManagementNodeMixin(kafkaManagementNode): { kafkaManagementNode+: if std.isArray(v=kafkaManagementNode) then kafkaManagementNode else [kafkaManagementNode] },
        '#withWorkerNode':: d.fn(help='"A worker_node block as defined below."', args=[d.arg(name='workerNode', type=d.T.array)]),
        withWorkerNode(workerNode): { workerNode: if std.isArray(v=workerNode) then workerNode else [workerNode] },
        '#withWorkerNodeMixin':: d.fn(help='"A worker_node block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='workerNode', type=d.T.array)]),
        withWorkerNodeMixin(workerNode): { workerNode+: if std.isArray(v=workerNode) then workerNode else [workerNode] },
        '#withZookeeperNode':: d.fn(help='"A zookeeper_node block as defined below."', args=[d.arg(name='zookeeperNode', type=d.T.array)]),
        withZookeeperNode(zookeeperNode): { zookeeperNode: if std.isArray(v=zookeeperNode) then zookeeperNode else [zookeeperNode] },
        '#withZookeeperNodeMixin':: d.fn(help='"A zookeeper_node block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='zookeeperNode', type=d.T.array)]),
        withZookeeperNodeMixin(zookeeperNode): { zookeeperNode+: if std.isArray(v=zookeeperNode) then zookeeperNode else [zookeeperNode] },
        '#workerNode':: d.obj(help='"A worker_node block as defined below."'),
        workerNode: {
          '#passwordSecretRef':: d.obj(help='"The Password associated with the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#scriptActions':: d.obj(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."'),
          scriptActions: {
            '#withName':: d.fn(help='"The name of the script action."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withParameters':: d.fn(help='"The parameters for the script provided."', args=[d.arg(name='parameters', type=d.T.string)]),
            withParameters(parameters): { parameters: parameters },
            '#withUri':: d.fn(help='"The URI to the script."', args=[d.arg(name='uri', type=d.T.string)]),
            withUri(uri): { uri: uri },
          },
          '#subnetIdRef':: d.obj(help='"Reference to a Subnet in network to populate subnetId."'),
          subnetIdRef: {
            '#policy':: d.obj(help='"Policies for referencing."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdRef+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdRef+: { policy+: { resolve: resolve } } },
            },
            '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { subnetIdRef+: { name: name } },
          },
          '#subnetIdSelector':: d.obj(help='"Selector for a Subnet in network to populate subnetId."'),
          subnetIdSelector: {
            '#policy':: d.obj(help='"Policies for selection."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdSelector+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdSelector+: { policy+: { resolve: resolve } } },
            },
            '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
            withMatchControllerRef(matchControllerRef): { subnetIdSelector+: { matchControllerRef: matchControllerRef } },
            '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabels(matchLabels): { subnetIdSelector+: { matchLabels: matchLabels } },
            '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabelsMixin(matchLabels): { subnetIdSelector+: { matchLabels+: matchLabels } },
          },
          '#withNumberOfDisksPerNode':: d.fn(help='"The number of Data Disks which should be assigned to each Worker Node, which can be between 1 and 8. Changing this forces a new resource to be created."', args=[d.arg(name='numberOfDisksPerNode', type=d.T.number)]),
          withNumberOfDisksPerNode(numberOfDisksPerNode): { numberOfDisksPerNode: numberOfDisksPerNode },
          '#withScriptActions':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActions(scriptActions): { scriptActions: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withScriptActionsMixin':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActionsMixin(scriptActions): { scriptActions+: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withSshKeys':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeys(sshKeys): { sshKeys: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSshKeysMixin':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeysMixin(sshKeys): { sshKeys+: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSubnetId':: d.fn(help='"The ID of the Subnet within the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='subnetId', type=d.T.string)]),
          withSubnetId(subnetId): { subnetId: subnetId },
          '#withTargetInstanceCount':: d.fn(help='"The number of instances which should be run for the Worker Nodes."', args=[d.arg(name='targetInstanceCount', type=d.T.number)]),
          withTargetInstanceCount(targetInstanceCount): { targetInstanceCount: targetInstanceCount },
          '#withUsername':: d.fn(help='"The Username of the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
          '#withVirtualNetworkId':: d.fn(help='"The ID of the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='virtualNetworkId', type=d.T.string)]),
          withVirtualNetworkId(virtualNetworkId): { virtualNetworkId: virtualNetworkId },
          '#withVmSize':: d.fn(help='"The Size of the Virtual Machine which should be used as the Zookeeper Nodes. Possible values are ExtraSmall, Small, Medium, Large, ExtraLarge, A5, A6, A7, A8, A9, A10, A11, Standard_A1_V2, Standard_A2_V2, Standard_A2m_V2, Standard_A3, Standard_A4_V2, Standard_A4m_V2, Standard_A8_V2, Standard_A8m_V2, Standard_D1, Standard_D2, Standard_D3, Standard_D4, Standard_D11, Standard_D12, Standard_D13, Standard_D14, Standard_D1_V2, Standard_D2_V2, Standard_D3_V2, Standard_D4_V2, Standard_D5_V2, Standard_D11_V2, Standard_D12_V2, Standard_D13_V2, Standard_D14_V2, Standard_DS1_V2, Standard_DS2_V2, Standard_DS3_V2, Standard_DS4_V2, Standard_DS5_V2, Standard_DS11_V2, Standard_DS12_V2, Standard_DS13_V2, Standard_DS14_V2, Standard_E2_V3, Standard_E4_V3, Standard_E8_V3, Standard_E16_V3, Standard_E20_V3, Standard_E32_V3, Standard_E64_V3, Standard_E64i_V3, Standard_E2s_V3, Standard_E4s_V3, Standard_E8s_V3, Standard_E16s_V3, Standard_E20s_V3, Standard_E32s_V3, Standard_E64s_V3, Standard_E64is_V3, Standard_D2a_V4, Standard_D4a_V4, Standard_D8a_V4, Standard_D16a_V4, Standard_D32a_V4, Standard_D48a_V4, Standard_D64a_V4, Standard_D96a_V4, Standard_E2a_V4, Standard_E4a_V4, Standard_E8a_V4, Standard_E16a_V4, Standard_E20a_V4, Standard_E32a_V4, Standard_E48a_V4, Standard_E64a_V4, Standard_E96a_V4, Standard_G1, Standard_G2, Standard_G3, Standard_G4, Standard_G5, Standard_F2s_V2, Standard_F4s_V2, Standard_F8s_V2, Standard_F16s_V2, Standard_F32s_V2, Standard_F64s_V2, Standard_F72s_V2, Standard_GS1, Standard_GS2, Standard_GS3, Standard_GS4, Standard_GS5 and Standard_NC24. Changing this forces a new resource to be created."', args=[d.arg(name='vmSize', type=d.T.string)]),
          withVmSize(vmSize): { vmSize: vmSize },
        },
        '#zookeeperNode':: d.obj(help='"A zookeeper_node block as defined below."'),
        zookeeperNode: {
          '#passwordSecretRef':: d.obj(help='"The Password associated with the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."'),
          passwordSecretRef: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { passwordSecretRef+: { key: key } },
            '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { passwordSecretRef+: { name: name } },
            '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { passwordSecretRef+: { namespace: namespace } },
          },
          '#scriptActions':: d.obj(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."'),
          scriptActions: {
            '#withName':: d.fn(help='"The name of the script action."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withParameters':: d.fn(help='"The parameters for the script provided."', args=[d.arg(name='parameters', type=d.T.string)]),
            withParameters(parameters): { parameters: parameters },
            '#withUri':: d.fn(help='"The URI to the script."', args=[d.arg(name='uri', type=d.T.string)]),
            withUri(uri): { uri: uri },
          },
          '#subnetIdRef':: d.obj(help='"Reference to a Subnet in network to populate subnetId."'),
          subnetIdRef: {
            '#policy':: d.obj(help='"Policies for referencing."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdRef+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdRef+: { policy+: { resolve: resolve } } },
            },
            '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { subnetIdRef+: { name: name } },
          },
          '#subnetIdSelector':: d.obj(help='"Selector for a Subnet in network to populate subnetId."'),
          subnetIdSelector: {
            '#policy':: d.obj(help='"Policies for selection."'),
            policy: {
              '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
              withResolution(resolution): { subnetIdSelector+: { policy+: { resolution: resolution } } },
              '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
              withResolve(resolve): { subnetIdSelector+: { policy+: { resolve: resolve } } },
            },
            '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
            withMatchControllerRef(matchControllerRef): { subnetIdSelector+: { matchControllerRef: matchControllerRef } },
            '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabels(matchLabels): { subnetIdSelector+: { matchLabels: matchLabels } },
            '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
            withMatchLabelsMixin(matchLabels): { subnetIdSelector+: { matchLabels+: matchLabels } },
          },
          '#withScriptActions':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActions(scriptActions): { scriptActions: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withScriptActionsMixin':: d.fn(help='"The script action which will run on the cluster. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scriptActions', type=d.T.array)]),
          withScriptActionsMixin(scriptActions): { scriptActions+: if std.isArray(v=scriptActions) then scriptActions else [scriptActions] },
          '#withSshKeys':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeys(sshKeys): { sshKeys: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSshKeysMixin':: d.fn(help='"A list of SSH Keys which should be used for the local administrator on the Zookeeper Nodes. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sshKeys', type=d.T.array)]),
          withSshKeysMixin(sshKeys): { sshKeys+: if std.isArray(v=sshKeys) then sshKeys else [sshKeys] },
          '#withSubnetId':: d.fn(help='"The ID of the Subnet within the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='subnetId', type=d.T.string)]),
          withSubnetId(subnetId): { subnetId: subnetId },
          '#withUsername':: d.fn(help='"The Username of the local administrator for the Zookeeper Nodes. Changing this forces a new resource to be created."', args=[d.arg(name='username', type=d.T.string)]),
          withUsername(username): { username: username },
          '#withVirtualNetworkId':: d.fn(help='"The ID of the Virtual Network where the Zookeeper Nodes should be provisioned within. Changing this forces a new resource to be created."', args=[d.arg(name='virtualNetworkId', type=d.T.string)]),
          withVirtualNetworkId(virtualNetworkId): { virtualNetworkId: virtualNetworkId },
          '#withVmSize':: d.fn(help='"The Size of the Virtual Machine which should be used as the Zookeeper Nodes. Possible values are ExtraSmall, Small, Medium, Large, ExtraLarge, A5, A6, A7, A8, A9, A10, A11, Standard_A1_V2, Standard_A2_V2, Standard_A2m_V2, Standard_A3, Standard_A4_V2, Standard_A4m_V2, Standard_A8_V2, Standard_A8m_V2, Standard_D1, Standard_D2, Standard_D3, Standard_D4, Standard_D11, Standard_D12, Standard_D13, Standard_D14, Standard_D1_V2, Standard_D2_V2, Standard_D3_V2, Standard_D4_V2, Standard_D5_V2, Standard_D11_V2, Standard_D12_V2, Standard_D13_V2, Standard_D14_V2, Standard_DS1_V2, Standard_DS2_V2, Standard_DS3_V2, Standard_DS4_V2, Standard_DS5_V2, Standard_DS11_V2, Standard_DS12_V2, Standard_DS13_V2, Standard_DS14_V2, Standard_E2_V3, Standard_E4_V3, Standard_E8_V3, Standard_E16_V3, Standard_E20_V3, Standard_E32_V3, Standard_E64_V3, Standard_E64i_V3, Standard_E2s_V3, Standard_E4s_V3, Standard_E8s_V3, Standard_E16s_V3, Standard_E20s_V3, Standard_E32s_V3, Standard_E64s_V3, Standard_E64is_V3, Standard_D2a_V4, Standard_D4a_V4, Standard_D8a_V4, Standard_D16a_V4, Standard_D32a_V4, Standard_D48a_V4, Standard_D64a_V4, Standard_D96a_V4, Standard_E2a_V4, Standard_E4a_V4, Standard_E8a_V4, Standard_E16a_V4, Standard_E20a_V4, Standard_E32a_V4, Standard_E48a_V4, Standard_E64a_V4, Standard_E96a_V4, Standard_G1, Standard_G2, Standard_G3, Standard_G4, Standard_G5, Standard_F2s_V2, Standard_F4s_V2, Standard_F8s_V2, Standard_F16s_V2, Standard_F32s_V2, Standard_F64s_V2, Standard_F72s_V2, Standard_GS1, Standard_GS2, Standard_GS3, Standard_GS4, Standard_GS5 and Standard_NC24. Changing this forces a new resource to be created."', args=[d.arg(name='vmSize', type=d.T.string)]),
          withVmSize(vmSize): { vmSize: vmSize },
        },
      },
      '#securityProfile':: d.obj(help='"A security_profile block as defined below. Changing this forces a new resource to be created."'),
      securityProfile: {
        '#domainUserPasswordSecretRef':: d.obj(help='"The user password of the Azure Active Directory Domain. Changing this forces a new resource to be created."'),
        domainUserPasswordSecretRef: {
          '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { domainUserPasswordSecretRef+: { key: key } },
          '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { domainUserPasswordSecretRef+: { name: name } },
          '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { domainUserPasswordSecretRef+: { namespace: namespace } },
        },
        '#withAaddsResourceId':: d.fn(help='"The resource ID of the Azure Active Directory Domain Service. Changing this forces a new resource to be created."', args=[d.arg(name='aaddsResourceId', type=d.T.string)]),
        withAaddsResourceId(aaddsResourceId): { aaddsResourceId: aaddsResourceId },
        '#withClusterUsersGroupDns':: d.fn(help='"A list of the distinguished names for the cluster user groups. Changing this forces a new resource to be created."', args=[d.arg(name='clusterUsersGroupDns', type=d.T.array)]),
        withClusterUsersGroupDns(clusterUsersGroupDns): { clusterUsersGroupDns: if std.isArray(v=clusterUsersGroupDns) then clusterUsersGroupDns else [clusterUsersGroupDns] },
        '#withClusterUsersGroupDnsMixin':: d.fn(help='"A list of the distinguished names for the cluster user groups. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='clusterUsersGroupDns', type=d.T.array)]),
        withClusterUsersGroupDnsMixin(clusterUsersGroupDns): { clusterUsersGroupDns+: if std.isArray(v=clusterUsersGroupDns) then clusterUsersGroupDns else [clusterUsersGroupDns] },
        '#withDomainName':: d.fn(help='"The name of the Azure Active Directory Domain. Changing this forces a new resource to be created."', args=[d.arg(name='domainName', type=d.T.string)]),
        withDomainName(domainName): { domainName: domainName },
        '#withDomainUsername':: d.fn(help='"The username of the Azure Active Directory Domain. Changing this forces a new resource to be created."', args=[d.arg(name='domainUsername', type=d.T.string)]),
        withDomainUsername(domainUsername): { domainUsername: domainUsername },
        '#withLdapsUrls':: d.fn(help='"A list of the LDAPS URLs to communicate with the Azure Active Directory. Changing this forces a new resource to be created."', args=[d.arg(name='ldapsUrls', type=d.T.array)]),
        withLdapsUrls(ldapsUrls): { ldapsUrls: if std.isArray(v=ldapsUrls) then ldapsUrls else [ldapsUrls] },
        '#withLdapsUrlsMixin':: d.fn(help='"A list of the LDAPS URLs to communicate with the Azure Active Directory. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ldapsUrls', type=d.T.array)]),
        withLdapsUrlsMixin(ldapsUrls): { ldapsUrls+: if std.isArray(v=ldapsUrls) then ldapsUrls else [ldapsUrls] },
        '#withMsiResourceId':: d.fn(help='"The User Assigned Identity for the HDInsight Cluster. Changing this forces a new resource to be created."', args=[d.arg(name='msiResourceId', type=d.T.string)]),
        withMsiResourceId(msiResourceId): { msiResourceId: msiResourceId },
      },
      '#storageAccount':: d.obj(help='"One or more storage_account block as defined below."'),
      storageAccount: {
        '#storageAccountKeySecretRef':: d.obj(help='"The Access Key which should be used to connect to the Storage Account. Changing this forces a new resource to be created."'),
        storageAccountKeySecretRef: {
          '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { storageAccountKeySecretRef+: { key: key } },
          '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { storageAccountKeySecretRef+: { name: name } },
          '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { storageAccountKeySecretRef+: { namespace: namespace } },
        },
        '#storageContainerIdRef':: d.obj(help='"Reference to a Container in storage to populate storageContainerId."'),
        storageContainerIdRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { storageContainerIdRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { storageContainerIdRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { storageContainerIdRef+: { name: name } },
        },
        '#storageContainerIdSelector':: d.obj(help='"Selector for a Container in storage to populate storageContainerId."'),
        storageContainerIdSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { storageContainerIdSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { storageContainerIdSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { storageContainerIdSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { storageContainerIdSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { storageContainerIdSelector+: { matchLabels+: matchLabels } },
        },
        '#withIsDefault':: d.fn(help='"Is this the Default Storage Account for the HDInsight Hadoop Cluster? Changing this forces a new resource to be created."', args=[d.arg(name='isDefault', type=d.T.boolean)]),
        withIsDefault(isDefault): { isDefault: isDefault },
        '#withStorageContainerId':: d.fn(help='"The ID of the Storage Container. Changing this forces a new resource to be created."', args=[d.arg(name='storageContainerId', type=d.T.string)]),
        withStorageContainerId(storageContainerId): { storageContainerId: storageContainerId },
        '#withStorageResourceId':: d.fn(help='"The ID of the Storage Account. Changing this forces a new resource to be created."', args=[d.arg(name='storageResourceId', type=d.T.string)]),
        withStorageResourceId(storageResourceId): { storageResourceId: storageResourceId },
      },
      '#storageAccountGen2':: d.obj(help='"A storage_account_gen2 block as defined below."'),
      storageAccountGen2: {
        '#withFilesystemId':: d.fn(help='"The ID of the Gen2 Filesystem. Changing this forces a new resource to be created."', args=[d.arg(name='filesystemId', type=d.T.string)]),
        withFilesystemId(filesystemId): { filesystemId: filesystemId },
        '#withIsDefault':: d.fn(help='"Is this the Default Storage Account for the HDInsight Hadoop Cluster? Changing this forces a new resource to be created."', args=[d.arg(name='isDefault', type=d.T.boolean)]),
        withIsDefault(isDefault): { isDefault: isDefault },
        '#withManagedIdentityResourceId':: d.fn(help='"The ID of Managed Identity to use for accessing the Gen2 filesystem. Changing this forces a new resource to be created."', args=[d.arg(name='managedIdentityResourceId', type=d.T.string)]),
        withManagedIdentityResourceId(managedIdentityResourceId): { managedIdentityResourceId: managedIdentityResourceId },
        '#withStorageResourceId':: d.fn(help='"The ID of the Storage Account. Changing this forces a new resource to be created."', args=[d.arg(name='storageResourceId', type=d.T.string)]),
        withStorageResourceId(storageResourceId): { storageResourceId: storageResourceId },
      },
      '#withClusterVersion':: d.fn(help='"Specifies the Version of HDInsights which should be used for this Cluster. Changing this forces a new resource to be created."', args=[d.arg(name='clusterVersion', type=d.T.string)]),
      withClusterVersion(clusterVersion): { spec+: { forProvider+: { clusterVersion: clusterVersion } } },
      '#withComponentVersion':: d.fn(help='"A component_version block as defined below."', args=[d.arg(name='componentVersion', type=d.T.array)]),
      withComponentVersion(componentVersion): { spec+: { forProvider+: { componentVersion: if std.isArray(v=componentVersion) then componentVersion else [componentVersion] } } },
      '#withComponentVersionMixin':: d.fn(help='"A component_version block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='componentVersion', type=d.T.array)]),
      withComponentVersionMixin(componentVersion): { spec+: { forProvider+: { componentVersion+: if std.isArray(v=componentVersion) then componentVersion else [componentVersion] } } },
      '#withComputeIsolation':: d.fn(help='"A compute_isolation block as defined below."', args=[d.arg(name='computeIsolation', type=d.T.array)]),
      withComputeIsolation(computeIsolation): { spec+: { forProvider+: { computeIsolation: if std.isArray(v=computeIsolation) then computeIsolation else [computeIsolation] } } },
      '#withComputeIsolationMixin':: d.fn(help='"A compute_isolation block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='computeIsolation', type=d.T.array)]),
      withComputeIsolationMixin(computeIsolation): { spec+: { forProvider+: { computeIsolation+: if std.isArray(v=computeIsolation) then computeIsolation else [computeIsolation] } } },
      '#withDiskEncryption':: d.fn(help='"One or more disk_encryption block as defined below."', args=[d.arg(name='diskEncryption', type=d.T.array)]),
      withDiskEncryption(diskEncryption): { spec+: { forProvider+: { diskEncryption: if std.isArray(v=diskEncryption) then diskEncryption else [diskEncryption] } } },
      '#withDiskEncryptionMixin':: d.fn(help='"One or more disk_encryption block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='diskEncryption', type=d.T.array)]),
      withDiskEncryptionMixin(diskEncryption): { spec+: { forProvider+: { diskEncryption+: if std.isArray(v=diskEncryption) then diskEncryption else [diskEncryption] } } },
      '#withEncryptionInTransitEnabled':: d.fn(help='"Whether encryption in transit is enabled for this HDInsight Kafka Cluster. Changing this forces a new resource to be created."', args=[d.arg(name='encryptionInTransitEnabled', type=d.T.boolean)]),
      withEncryptionInTransitEnabled(encryptionInTransitEnabled): { spec+: { forProvider+: { encryptionInTransitEnabled: encryptionInTransitEnabled } } },
      '#withExtension':: d.fn(help='"An extension block as defined below."', args=[d.arg(name='extension', type=d.T.array)]),
      withExtension(extension): { spec+: { forProvider+: { extension: if std.isArray(v=extension) then extension else [extension] } } },
      '#withExtensionMixin':: d.fn(help='"An extension block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='extension', type=d.T.array)]),
      withExtensionMixin(extension): { spec+: { forProvider+: { extension+: if std.isArray(v=extension) then extension else [extension] } } },
      '#withGateway':: d.fn(help='"A gateway block as defined below."', args=[d.arg(name='gateway', type=d.T.array)]),
      withGateway(gateway): { spec+: { forProvider+: { gateway: if std.isArray(v=gateway) then gateway else [gateway] } } },
      '#withGatewayMixin':: d.fn(help='"A gateway block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='gateway', type=d.T.array)]),
      withGatewayMixin(gateway): { spec+: { forProvider+: { gateway+: if std.isArray(v=gateway) then gateway else [gateway] } } },
      '#withLocation':: d.fn(help='"Specifies the Azure Region which this HDInsight Kafka Cluster should exist. Changing this forces a new resource to be created."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { forProvider+: { location: location } } },
      '#withMetastores':: d.fn(help='"A metastores block as defined below."', args=[d.arg(name='metastores', type=d.T.array)]),
      withMetastores(metastores): { spec+: { forProvider+: { metastores: if std.isArray(v=metastores) then metastores else [metastores] } } },
      '#withMetastoresMixin':: d.fn(help='"A metastores block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metastores', type=d.T.array)]),
      withMetastoresMixin(metastores): { spec+: { forProvider+: { metastores+: if std.isArray(v=metastores) then metastores else [metastores] } } },
      '#withMonitor':: d.fn(help='"A monitor block as defined below."', args=[d.arg(name='monitor', type=d.T.array)]),
      withMonitor(monitor): { spec+: { forProvider+: { monitor: if std.isArray(v=monitor) then monitor else [monitor] } } },
      '#withMonitorMixin':: d.fn(help='"A monitor block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='monitor', type=d.T.array)]),
      withMonitorMixin(monitor): { spec+: { forProvider+: { monitor+: if std.isArray(v=monitor) then monitor else [monitor] } } },
      '#withNetwork':: d.fn(help='"A network block as defined below."', args=[d.arg(name='network', type=d.T.array)]),
      withNetwork(network): { spec+: { forProvider+: { network: if std.isArray(v=network) then network else [network] } } },
      '#withNetworkMixin':: d.fn(help='"A network block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='network', type=d.T.array)]),
      withNetworkMixin(network): { spec+: { forProvider+: { network+: if std.isArray(v=network) then network else [network] } } },
      '#withResourceGroupName':: d.fn(help='"Specifies the name of the Resource Group in which this HDInsight Kafka Cluster should exist. Changing this forces a new resource to be created."', args=[d.arg(name='resourceGroupName', type=d.T.string)]),
      withResourceGroupName(resourceGroupName): { spec+: { forProvider+: { resourceGroupName: resourceGroupName } } },
      '#withRestProxy':: d.fn(help='"A rest_proxy block as defined below."', args=[d.arg(name='restProxy', type=d.T.array)]),
      withRestProxy(restProxy): { spec+: { forProvider+: { restProxy: if std.isArray(v=restProxy) then restProxy else [restProxy] } } },
      '#withRestProxyMixin':: d.fn(help='"A rest_proxy block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='restProxy', type=d.T.array)]),
      withRestProxyMixin(restProxy): { spec+: { forProvider+: { restProxy+: if std.isArray(v=restProxy) then restProxy else [restProxy] } } },
      '#withRoles':: d.fn(help='"A roles block as defined below."', args=[d.arg(name='roles', type=d.T.array)]),
      withRoles(roles): { spec+: { forProvider+: { roles: if std.isArray(v=roles) then roles else [roles] } } },
      '#withRolesMixin':: d.fn(help='"A roles block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='roles', type=d.T.array)]),
      withRolesMixin(roles): { spec+: { forProvider+: { roles+: if std.isArray(v=roles) then roles else [roles] } } },
      '#withSecurityProfile':: d.fn(help='"A security_profile block as defined below. Changing this forces a new resource to be created."', args=[d.arg(name='securityProfile', type=d.T.array)]),
      withSecurityProfile(securityProfile): { spec+: { forProvider+: { securityProfile: if std.isArray(v=securityProfile) then securityProfile else [securityProfile] } } },
      '#withSecurityProfileMixin':: d.fn(help='"A security_profile block as defined below. Changing this forces a new resource to be created."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='securityProfile', type=d.T.array)]),
      withSecurityProfileMixin(securityProfile): { spec+: { forProvider+: { securityProfile+: if std.isArray(v=securityProfile) then securityProfile else [securityProfile] } } },
      '#withStorageAccount':: d.fn(help='"One or more storage_account block as defined below."', args=[d.arg(name='storageAccount', type=d.T.array)]),
      withStorageAccount(storageAccount): { spec+: { forProvider+: { storageAccount: if std.isArray(v=storageAccount) then storageAccount else [storageAccount] } } },
      '#withStorageAccountGen2':: d.fn(help='"A storage_account_gen2 block as defined below."', args=[d.arg(name='storageAccountGen2', type=d.T.array)]),
      withStorageAccountGen2(storageAccountGen2): { spec+: { forProvider+: { storageAccountGen2: if std.isArray(v=storageAccountGen2) then storageAccountGen2 else [storageAccountGen2] } } },
      '#withStorageAccountGen2Mixin':: d.fn(help='"A storage_account_gen2 block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='storageAccountGen2', type=d.T.array)]),
      withStorageAccountGen2Mixin(storageAccountGen2): { spec+: { forProvider+: { storageAccountGen2+: if std.isArray(v=storageAccountGen2) then storageAccountGen2 else [storageAccountGen2] } } },
      '#withStorageAccountMixin':: d.fn(help='"One or more storage_account block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='storageAccount', type=d.T.array)]),
      withStorageAccountMixin(storageAccount): { spec+: { forProvider+: { storageAccount+: if std.isArray(v=storageAccount) then storageAccount else [storageAccount] } } },
      '#withTags':: d.fn(help='"A map of Tags which should be assigned to this HDInsight Kafka Cluster."', args=[d.arg(name='tags', type=d.T.object)]),
      withTags(tags): { spec+: { forProvider+: { tags: tags } } },
      '#withTagsMixin':: d.fn(help='"A map of Tags which should be assigned to this HDInsight Kafka Cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
      withTagsMixin(tags): { spec+: { forProvider+: { tags+: tags } } },
      '#withTier':: d.fn(help='"Specifies the Tier which should be used for this HDInsight Kafka Cluster. Possible values are Standard or Premium. Changing this forces a new resource to be created."', args=[d.arg(name='tier', type=d.T.string)]),
      withTier(tier): { spec+: { forProvider+: { tier: tier } } },
      '#withTlsMinVersion':: d.fn(help='"The minimal supported TLS version. Possible values are 1.0, 1.1 or 1.2. Changing this forces a new resource to be created."', args=[d.arg(name='tlsMinVersion', type=d.T.string)]),
      withTlsMinVersion(tlsMinVersion): { spec+: { forProvider+: { tlsMinVersion: tlsMinVersion } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
