{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='nodeGroup', url='', help='"NodeGroup is the Schema for the NodeGroups API. Manages an EKS Node Group"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of NodeGroup', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'eks.aws.upbound.io/v1beta1',
    kind: 'NodeGroup',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"NodeGroupSpec defines the desired state of NodeGroup"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#clusterNameRef':: d.obj(help='"Reference to a Cluster to populate clusterName."'),
      clusterNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { clusterNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { clusterNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { clusterNameRef+: { name: name } } } },
      },
      '#clusterNameSelector':: d.obj(help='"Selector for a Cluster to populate clusterName."'),
      clusterNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { clusterNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { clusterNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { clusterNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { clusterNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { clusterNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#launchTemplate':: d.obj(help='"Configuration block with Launch Template settings. Detailed below."'),
      launchTemplate: {
        '#withId':: d.fn(help='"Identifier of the EC2 Launch Template. Conflicts with name."', args=[d.arg(name='id', type=d.T.string)]),
        withId(id): { id: id },
        '#withName':: d.fn(help='"Name of the EC2 Launch Template. Conflicts with id."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withVersion':: d.fn(help='"EC2 Launch Template version number. While the API accepts values like $Default and $Latest, the API will convert the value to the associated version number (e.g., 1). Using the default_version or latest_version attribute of the aws_launch_template resource or data source is recommended for this argument."', args=[d.arg(name='version', type=d.T.string)]),
        withVersion(version): { version: version },
      },
      '#nodeRoleArnRef':: d.obj(help='"Reference to a Role in iam to populate nodeRoleArn."'),
      nodeRoleArnRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { nodeRoleArnRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { nodeRoleArnRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { nodeRoleArnRef+: { name: name } } } },
      },
      '#nodeRoleArnSelector':: d.obj(help='"Selector for a Role in iam to populate nodeRoleArn."'),
      nodeRoleArnSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { nodeRoleArnSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { nodeRoleArnSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { nodeRoleArnSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { nodeRoleArnSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { nodeRoleArnSelector+: { matchLabels+: matchLabels } } } },
      },
      '#remoteAccess':: d.obj(help='"Configuration block with remote access settings. Detailed below."'),
      remoteAccess: {
        '#sourceSecurityGroupIdRefs':: d.obj(help='"References to SecurityGroup in ec2 to populate sourceSecurityGroupIds."'),
        sourceSecurityGroupIdRefs: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { policy+: { resolution: resolution } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { policy+: { resolve: resolve } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
        },
        '#sourceSecurityGroupIdSelector':: d.obj(help='"Selector for a list of SecurityGroup in ec2 to populate sourceSecurityGroupIds."'),
        sourceSecurityGroupIdSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { sourceSecurityGroupIdSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { sourceSecurityGroupIdSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { sourceSecurityGroupIdSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { sourceSecurityGroupIdSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { sourceSecurityGroupIdSelector+: { matchLabels+: matchLabels } },
        },
        '#withEc2SshKey':: d.fn(help='"EC2 Key Pair name that provides access for remote communication with the worker nodes in the EKS Node Group. If you specify this configuration, but do not specify source_security_group_ids when you create an EKS Node Group, either port 3389 for Windows, or port 22 for all other operating systems is opened on the worker nodes to the Internet (0.0.0.0/0). For Windows nodes, this will allow you to use RDP, for all others this allows you to SSH into the worker nodes."', args=[d.arg(name='ec2SshKey', type=d.T.string)]),
        withEc2SshKey(ec2SshKey): { ec2SshKey: ec2SshKey },
        '#withSourceSecurityGroupIdRefs':: d.fn(help='"References to SecurityGroup in ec2 to populate sourceSecurityGroupIds."', args=[d.arg(name='sourceSecurityGroupIdRefs', type=d.T.array)]),
        withSourceSecurityGroupIdRefs(sourceSecurityGroupIdRefs): { sourceSecurityGroupIdRefs: if std.isArray(v=sourceSecurityGroupIdRefs) then sourceSecurityGroupIdRefs else [sourceSecurityGroupIdRefs] },
        '#withSourceSecurityGroupIdRefsMixin':: d.fn(help='"References to SecurityGroup in ec2 to populate sourceSecurityGroupIds."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sourceSecurityGroupIdRefs', type=d.T.array)]),
        withSourceSecurityGroupIdRefsMixin(sourceSecurityGroupIdRefs): { sourceSecurityGroupIdRefs+: if std.isArray(v=sourceSecurityGroupIdRefs) then sourceSecurityGroupIdRefs else [sourceSecurityGroupIdRefs] },
        '#withSourceSecurityGroupIds':: d.fn(help='"Set of EC2 Security Group IDs to allow SSH access (port 22) from on the worker nodes. If you specify ec2_ssh_key, but do not specify this configuration when you create an EKS Node Group, port 22 on the worker nodes is opened to the Internet (0.0.0.0/0)."', args=[d.arg(name='sourceSecurityGroupIds', type=d.T.array)]),
        withSourceSecurityGroupIds(sourceSecurityGroupIds): { sourceSecurityGroupIds: if std.isArray(v=sourceSecurityGroupIds) then sourceSecurityGroupIds else [sourceSecurityGroupIds] },
        '#withSourceSecurityGroupIdsMixin':: d.fn(help='"Set of EC2 Security Group IDs to allow SSH access (port 22) from on the worker nodes. If you specify ec2_ssh_key, but do not specify this configuration when you create an EKS Node Group, port 22 on the worker nodes is opened to the Internet (0.0.0.0/0)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sourceSecurityGroupIds', type=d.T.array)]),
        withSourceSecurityGroupIdsMixin(sourceSecurityGroupIds): { sourceSecurityGroupIds+: if std.isArray(v=sourceSecurityGroupIds) then sourceSecurityGroupIds else [sourceSecurityGroupIds] },
      },
      '#scalingConfig':: d.obj(help='"Configuration block with scaling settings. Detailed below."'),
      scalingConfig: {
        '#withDesiredSize':: d.fn(help='"Desired number of worker nodes."', args=[d.arg(name='desiredSize', type=d.T.number)]),
        withDesiredSize(desiredSize): { desiredSize: desiredSize },
        '#withMaxSize':: d.fn(help='"Maximum number of worker nodes."', args=[d.arg(name='maxSize', type=d.T.number)]),
        withMaxSize(maxSize): { maxSize: maxSize },
        '#withMinSize':: d.fn(help='"Minimum number of worker nodes."', args=[d.arg(name='minSize', type=d.T.number)]),
        withMinSize(minSize): { minSize: minSize },
      },
      '#subnetIdRefs':: d.obj(help='"References to Subnet in ec2 to populate subnetIds."'),
      subnetIdRefs: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { policy+: { resolution: resolution } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { policy+: { resolve: resolve } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#subnetIdSelector':: d.obj(help='"Selector for a list of Subnet in ec2 to populate subnetIds."'),
      subnetIdSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { subnetIdSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { subnetIdSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { subnetIdSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { subnetIdSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { subnetIdSelector+: { matchLabels+: matchLabels } } } },
      },
      '#taint':: d.obj(help='"The Kubernetes taints to be applied to the nodes in the node group. Maximum of 50 taints per node group. Detailed below."'),
      taint: {
        '#withEffect':: d.fn(help='"The effect of the taint. Valid values: NO_SCHEDULE, NO_EXECUTE, PREFER_NO_SCHEDULE."', args=[d.arg(name='effect', type=d.T.string)]),
        withEffect(effect): { effect: effect },
        '#withKey':: d.fn(help='"The key of the taint. Maximum length of 63."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withValue':: d.fn(help='"The value of the taint. Maximum length of 63."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { value: value },
      },
      '#updateConfig':: d.obj(help=''),
      updateConfig: {
        '#withMaxUnavailable':: d.fn(help='"Desired max number of unavailable worker nodes during node group update."', args=[d.arg(name='maxUnavailable', type=d.T.number)]),
        withMaxUnavailable(maxUnavailable): { maxUnavailable: maxUnavailable },
        '#withMaxUnavailablePercentage':: d.fn(help='"Desired max percentage of unavailable worker nodes during node group update."', args=[d.arg(name='maxUnavailablePercentage', type=d.T.number)]),
        withMaxUnavailablePercentage(maxUnavailablePercentage): { maxUnavailablePercentage: maxUnavailablePercentage },
      },
      '#versionRef':: d.obj(help='"Reference to a Cluster in eks to populate version."'),
      versionRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { versionRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { versionRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { versionRef+: { name: name } } } },
      },
      '#versionSelector':: d.obj(help='"Selector for a Cluster in eks to populate version."'),
      versionSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { versionSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { versionSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { versionSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { versionSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { versionSelector+: { matchLabels+: matchLabels } } } },
      },
      '#withAmiType':: d.fn(help='"Type of Amazon Machine Image (AMI) associated with the EKS Node Group. See the AWS documentation for valid values."', args=[d.arg(name='amiType', type=d.T.string)]),
      withAmiType(amiType): { spec+: { forProvider+: { amiType: amiType } } },
      '#withCapacityType':: d.fn(help='"Type of capacity associated with the EKS Node Group. Valid values: ON_DEMAND, SPOT."', args=[d.arg(name='capacityType', type=d.T.string)]),
      withCapacityType(capacityType): { spec+: { forProvider+: { capacityType: capacityType } } },
      '#withClusterName':: d.fn(help='"100 characters in length. Must begin with an alphanumeric character, and must only contain alphanumeric characters, dashes and underscores (^[0-9A-Za-z][A-Za-z0-9\\\\-_]+$)."', args=[d.arg(name='clusterName', type=d.T.string)]),
      withClusterName(clusterName): { spec+: { forProvider+: { clusterName: clusterName } } },
      '#withDiskSize':: d.fn(help='"Disk size in GiB for worker nodes. Defaults to 50 for Windows, 20 all other node groups."', args=[d.arg(name='diskSize', type=d.T.number)]),
      withDiskSize(diskSize): { spec+: { forProvider+: { diskSize: diskSize } } },
      '#withForceUpdateVersion':: d.fn(help='"Force version update if existing pods are unable to be drained due to a pod disruption budget issue."', args=[d.arg(name='forceUpdateVersion', type=d.T.boolean)]),
      withForceUpdateVersion(forceUpdateVersion): { spec+: { forProvider+: { forceUpdateVersion: forceUpdateVersion } } },
      '#withInstanceTypes':: d.fn(help='"List of instance types associated with the EKS Node Group. Defaults to [\\"t3.medium\\"]."', args=[d.arg(name='instanceTypes', type=d.T.array)]),
      withInstanceTypes(instanceTypes): { spec+: { forProvider+: { instanceTypes: if std.isArray(v=instanceTypes) then instanceTypes else [instanceTypes] } } },
      '#withInstanceTypesMixin':: d.fn(help='"List of instance types associated with the EKS Node Group. Defaults to [\\"t3.medium\\"]."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='instanceTypes', type=d.T.array)]),
      withInstanceTypesMixin(instanceTypes): { spec+: { forProvider+: { instanceTypes+: if std.isArray(v=instanceTypes) then instanceTypes else [instanceTypes] } } },
      '#withLabels':: d.fn(help='"Key-value map of Kubernetes labels. Only labels that are applied with the EKS API are managed by this argument. Other Kubernetes labels applied to the EKS Node Group will not be managed."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { forProvider+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"Key-value map of Kubernetes labels. Only labels that are applied with the EKS API are managed by this argument. Other Kubernetes labels applied to the EKS Node Group will not be managed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { forProvider+: { labels+: labels } } },
      '#withLaunchTemplate':: d.fn(help='"Configuration block with Launch Template settings. Detailed below."', args=[d.arg(name='launchTemplate', type=d.T.array)]),
      withLaunchTemplate(launchTemplate): { spec+: { forProvider+: { launchTemplate: if std.isArray(v=launchTemplate) then launchTemplate else [launchTemplate] } } },
      '#withLaunchTemplateMixin':: d.fn(help='"Configuration block with Launch Template settings. Detailed below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='launchTemplate', type=d.T.array)]),
      withLaunchTemplateMixin(launchTemplate): { spec+: { forProvider+: { launchTemplate+: if std.isArray(v=launchTemplate) then launchTemplate else [launchTemplate] } } },
      '#withNodeRoleArn':: d.fn(help='"–  Amazon Resource Name (ARN) of the IAM Role that provides permissions for the EKS Node Group."', args=[d.arg(name='nodeRoleArn', type=d.T.string)]),
      withNodeRoleArn(nodeRoleArn): { spec+: { forProvider+: { nodeRoleArn: nodeRoleArn } } },
      '#withRegion':: d.fn(help="\"Region is the region you'd like your resource to be created in.\"", args=[d.arg(name='region', type=d.T.string)]),
      withRegion(region): { spec+: { forProvider+: { region: region } } },
      '#withReleaseVersion':: d.fn(help='"–  AMI version of the EKS Node Group. Defaults to latest version for Kubernetes version."', args=[d.arg(name='releaseVersion', type=d.T.string)]),
      withReleaseVersion(releaseVersion): { spec+: { forProvider+: { releaseVersion: releaseVersion } } },
      '#withRemoteAccess':: d.fn(help='"Configuration block with remote access settings. Detailed below."', args=[d.arg(name='remoteAccess', type=d.T.array)]),
      withRemoteAccess(remoteAccess): { spec+: { forProvider+: { remoteAccess: if std.isArray(v=remoteAccess) then remoteAccess else [remoteAccess] } } },
      '#withRemoteAccessMixin':: d.fn(help='"Configuration block with remote access settings. Detailed below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remoteAccess', type=d.T.array)]),
      withRemoteAccessMixin(remoteAccess): { spec+: { forProvider+: { remoteAccess+: if std.isArray(v=remoteAccess) then remoteAccess else [remoteAccess] } } },
      '#withScalingConfig':: d.fn(help='"Configuration block with scaling settings. Detailed below."', args=[d.arg(name='scalingConfig', type=d.T.array)]),
      withScalingConfig(scalingConfig): { spec+: { forProvider+: { scalingConfig: if std.isArray(v=scalingConfig) then scalingConfig else [scalingConfig] } } },
      '#withScalingConfigMixin':: d.fn(help='"Configuration block with scaling settings. Detailed below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scalingConfig', type=d.T.array)]),
      withScalingConfigMixin(scalingConfig): { spec+: { forProvider+: { scalingConfig+: if std.isArray(v=scalingConfig) then scalingConfig else [scalingConfig] } } },
      '#withSubnetIdRefs':: d.fn(help='"References to Subnet in ec2 to populate subnetIds."', args=[d.arg(name='subnetIdRefs', type=d.T.array)]),
      withSubnetIdRefs(subnetIdRefs): { spec+: { forProvider+: { subnetIdRefs: if std.isArray(v=subnetIdRefs) then subnetIdRefs else [subnetIdRefs] } } },
      '#withSubnetIdRefsMixin':: d.fn(help='"References to Subnet in ec2 to populate subnetIds."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='subnetIdRefs', type=d.T.array)]),
      withSubnetIdRefsMixin(subnetIdRefs): { spec+: { forProvider+: { subnetIdRefs+: if std.isArray(v=subnetIdRefs) then subnetIdRefs else [subnetIdRefs] } } },
      '#withSubnetIds':: d.fn(help='"–  Identifiers of EC2 Subnets to associate with the EKS Node Group. These subnets must have the following resource tag: kubernetes.io/cluster/CLUSTER_NAME (where CLUSTER_NAME is replaced with the name of the EKS Cluster)."', args=[d.arg(name='subnetIds', type=d.T.array)]),
      withSubnetIds(subnetIds): { spec+: { forProvider+: { subnetIds: if std.isArray(v=subnetIds) then subnetIds else [subnetIds] } } },
      '#withSubnetIdsMixin':: d.fn(help='"–  Identifiers of EC2 Subnets to associate with the EKS Node Group. These subnets must have the following resource tag: kubernetes.io/cluster/CLUSTER_NAME (where CLUSTER_NAME is replaced with the name of the EKS Cluster)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='subnetIds', type=d.T.array)]),
      withSubnetIdsMixin(subnetIds): { spec+: { forProvider+: { subnetIds+: if std.isArray(v=subnetIds) then subnetIds else [subnetIds] } } },
      '#withTags':: d.fn(help='"Key-value map of resource tags."', args=[d.arg(name='tags', type=d.T.object)]),
      withTags(tags): { spec+: { forProvider+: { tags: tags } } },
      '#withTagsMixin':: d.fn(help='"Key-value map of resource tags."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
      withTagsMixin(tags): { spec+: { forProvider+: { tags+: tags } } },
      '#withTaint':: d.fn(help='"The Kubernetes taints to be applied to the nodes in the node group. Maximum of 50 taints per node group. Detailed below."', args=[d.arg(name='taint', type=d.T.array)]),
      withTaint(taint): { spec+: { forProvider+: { taint: if std.isArray(v=taint) then taint else [taint] } } },
      '#withTaintMixin':: d.fn(help='"The Kubernetes taints to be applied to the nodes in the node group. Maximum of 50 taints per node group. Detailed below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='taint', type=d.T.array)]),
      withTaintMixin(taint): { spec+: { forProvider+: { taint+: if std.isArray(v=taint) then taint else [taint] } } },
      '#withUpdateConfig':: d.fn(help='', args=[d.arg(name='updateConfig', type=d.T.array)]),
      withUpdateConfig(updateConfig): { spec+: { forProvider+: { updateConfig: if std.isArray(v=updateConfig) then updateConfig else [updateConfig] } } },
      '#withUpdateConfigMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='updateConfig', type=d.T.array)]),
      withUpdateConfigMixin(updateConfig): { spec+: { forProvider+: { updateConfig+: if std.isArray(v=updateConfig) then updateConfig else [updateConfig] } } },
      '#withVersion':: d.fn(help='"–  Kubernetes version. Defaults to EKS Cluster Kubernetes version."', args=[d.arg(name='version', type=d.T.string)]),
      withVersion(version): { spec+: { forProvider+: { version: version } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
