{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='monitorScheduledQueryRulesAlertV2', url='', help='"MonitorScheduledQueryRulesAlertV2 is the Schema for the MonitorScheduledQueryRulesAlertV2s API. Manages an AlertingAction Scheduled Query Rules Version 2 resource within Azure Monitor"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of MonitorScheduledQueryRulesAlertV2', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'insights.azure.upbound.io/v1beta2',
    kind: 'MonitorScheduledQueryRulesAlertV2',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"MonitorScheduledQueryRulesAlertV2Spec defines the desired state of MonitorScheduledQueryRulesAlertV2"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#action':: d.obj(help='"An action block as defined below."'),
      action: {
        '#withActionGroups':: d.fn(help='"List of Action Group resource IDs to invoke when the alert fires."', args=[d.arg(name='actionGroups', type=d.T.array)]),
        withActionGroups(actionGroups): { spec+: { forProvider+: { action+: { actionGroups: if std.isArray(v=actionGroups) then actionGroups else [actionGroups] } } } },
        '#withActionGroupsMixin':: d.fn(help='"List of Action Group resource IDs to invoke when the alert fires."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='actionGroups', type=d.T.array)]),
        withActionGroupsMixin(actionGroups): { spec+: { forProvider+: { action+: { actionGroups+: if std.isArray(v=actionGroups) then actionGroups else [actionGroups] } } } },
        '#withCustomProperties':: d.fn(help='"Specifies the properties of an alert payload."', args=[d.arg(name='customProperties', type=d.T.object)]),
        withCustomProperties(customProperties): { spec+: { forProvider+: { action+: { customProperties: customProperties } } } },
        '#withCustomPropertiesMixin':: d.fn(help='"Specifies the properties of an alert payload."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='customProperties', type=d.T.object)]),
        withCustomPropertiesMixin(customProperties): { spec+: { forProvider+: { action+: { customProperties+: customProperties } } } },
      },
      '#criteria':: d.obj(help='"A criteria block as defined below."'),
      criteria: {
        '#dimension':: d.obj(help='"A dimension block as defined below."'),
        dimension: {
          '#withName':: d.fn(help='"Specifies the name which should be used for this Monitor Scheduled Query Rule. Changing this forces a new resource to be created."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withOperator':: d.fn(help='"Operator for dimension values. Possible values are Exclude,and Include."', args=[d.arg(name='operator', type=d.T.string)]),
          withOperator(operator): { operator: operator },
          '#withValues':: d.fn(help='"List of dimension values. Use a wildcard * to collect all."', args=[d.arg(name='values', type=d.T.array)]),
          withValues(values): { values: if std.isArray(v=values) then values else [values] },
          '#withValuesMixin':: d.fn(help='"List of dimension values. Use a wildcard * to collect all."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
          withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
        },
        '#failingPeriods':: d.obj(help='"A failing_periods block as defined below."'),
        failingPeriods: {
          '#withMinimumFailingPeriodsToTriggerAlert':: d.fn(help='"Specifies the number of violations to trigger an alert. Should be smaller or equal to number_of_evaluation_periods. Possible value is integer between 1 and 6."', args=[d.arg(name='minimumFailingPeriodsToTriggerAlert', type=d.T.number)]),
          withMinimumFailingPeriodsToTriggerAlert(minimumFailingPeriodsToTriggerAlert): { failingPeriods+: { minimumFailingPeriodsToTriggerAlert: minimumFailingPeriodsToTriggerAlert } },
          '#withNumberOfEvaluationPeriods':: d.fn(help='"Specifies the number of aggregated look-back points. The look-back time window is calculated based on the aggregation granularity window_duration and the selected number of aggregated points. Possible value is integer between 1 and 6."', args=[d.arg(name='numberOfEvaluationPeriods', type=d.T.number)]),
          withNumberOfEvaluationPeriods(numberOfEvaluationPeriods): { failingPeriods+: { numberOfEvaluationPeriods: numberOfEvaluationPeriods } },
        },
        '#withDimension':: d.fn(help='"A dimension block as defined below."', args=[d.arg(name='dimension', type=d.T.array)]),
        withDimension(dimension): { dimension: if std.isArray(v=dimension) then dimension else [dimension] },
        '#withDimensionMixin':: d.fn(help='"A dimension block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dimension', type=d.T.array)]),
        withDimensionMixin(dimension): { dimension+: if std.isArray(v=dimension) then dimension else [dimension] },
        '#withMetricMeasureColumn':: d.fn(help='"Specifies the column containing the metric measure number."', args=[d.arg(name='metricMeasureColumn', type=d.T.string)]),
        withMetricMeasureColumn(metricMeasureColumn): { metricMeasureColumn: metricMeasureColumn },
        '#withOperator':: d.fn(help='"Specifies the criteria operator. Possible values are Equal, GreaterThan, GreaterThanOrEqual, LessThan,and LessThanOrEqual."', args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withQuery':: d.fn(help='"The query to run on logs. The results returned by this query are used to populate the alert."', args=[d.arg(name='query', type=d.T.string)]),
        withQuery(query): { query: query },
        '#withResourceIdColumn':: d.fn(help='"Specifies the column containing the resource ID. The content of the column must be an uri formatted as resource ID."', args=[d.arg(name='resourceIdColumn', type=d.T.string)]),
        withResourceIdColumn(resourceIdColumn): { resourceIdColumn: resourceIdColumn },
        '#withThreshold':: d.fn(help='"Specifies the criteria threshold value that activates the alert."', args=[d.arg(name='threshold', type=d.T.number)]),
        withThreshold(threshold): { threshold: threshold },
        '#withTimeAggregationMethod':: d.fn(help='"The type of aggregation to apply to the data points in aggregation granularity. Possible values are Average, Count, Maximum, Minimum,and Total."', args=[d.arg(name='timeAggregationMethod', type=d.T.string)]),
        withTimeAggregationMethod(timeAggregationMethod): { timeAggregationMethod: timeAggregationMethod },
      },
      '#resourceGroupNameRef':: d.obj(help='"Reference to a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { resourceGroupNameRef+: { name: name } } } },
      },
      '#resourceGroupNameSelector':: d.obj(help='"Selector for a ResourceGroup in azure to populate resourceGroupName."'),
      resourceGroupNameSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { resourceGroupNameSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { resourceGroupNameSelector+: { matchLabels+: matchLabels } } } },
      },
      '#scopesRefs':: d.obj(help='"References to ApplicationInsights in insights to populate scopes."'),
      scopesRefs: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { policy+: { resolution: resolution } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { policy+: { resolve: resolve } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#scopesSelector':: d.obj(help='"Selector for a list of ApplicationInsights in insights to populate scopes."'),
      scopesSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { scopesSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { scopesSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { scopesSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { scopesSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { scopesSelector+: { matchLabels+: matchLabels } } } },
      },
      '#withAutoMitigationEnabled':: d.fn(help='"Specifies the flag that indicates whether the alert should be automatically resolved or not. Value should be true or false. The default is false."', args=[d.arg(name='autoMitigationEnabled', type=d.T.boolean)]),
      withAutoMitigationEnabled(autoMitigationEnabled): { spec+: { forProvider+: { autoMitigationEnabled: autoMitigationEnabled } } },
      '#withCriteria':: d.fn(help='"A criteria block as defined below."', args=[d.arg(name='criteria', type=d.T.array)]),
      withCriteria(criteria): { spec+: { forProvider+: { criteria: if std.isArray(v=criteria) then criteria else [criteria] } } },
      '#withCriteriaMixin':: d.fn(help='"A criteria block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='criteria', type=d.T.array)]),
      withCriteriaMixin(criteria): { spec+: { forProvider+: { criteria+: if std.isArray(v=criteria) then criteria else [criteria] } } },
      '#withDescription':: d.fn(help='"Specifies the description of the scheduled query rule."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withDisplayName':: d.fn(help='"Specifies the display name of the alert rule."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { forProvider+: { displayName: displayName } } },
      '#withEnabled':: d.fn(help='"Specifies the flag which indicates whether this scheduled query rule is enabled. Value should be true or false. Defaults to true."', args=[d.arg(name='enabled', type=d.T.boolean)]),
      withEnabled(enabled): { spec+: { forProvider+: { enabled: enabled } } },
      '#withEvaluationFrequency':: d.fn(help='"How often the scheduled query rule is evaluated, represented in ISO 8601 duration format. Possible values are PT1M, PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D."', args=[d.arg(name='evaluationFrequency', type=d.T.string)]),
      withEvaluationFrequency(evaluationFrequency): { spec+: { forProvider+: { evaluationFrequency: evaluationFrequency } } },
      '#withLocation':: d.fn(help='"Specifies the Azure Region where the Monitor Scheduled Query Rule should exist. Changing this forces a new resource to be created."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { forProvider+: { location: location } } },
      '#withMuteActionsAfterAlertDuration':: d.fn(help='"Mute actions for the chosen period of time in ISO 8601 duration format after the alert is fired. Possible values are PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D and P2D."', args=[d.arg(name='muteActionsAfterAlertDuration', type=d.T.string)]),
      withMuteActionsAfterAlertDuration(muteActionsAfterAlertDuration): { spec+: { forProvider+: { muteActionsAfterAlertDuration: muteActionsAfterAlertDuration } } },
      '#withQueryTimeRangeOverride':: d.fn(help='"Set this if the alert evaluation period is different from the query time range. If not specified, the value is window_duration*number_of_evaluation_periods. Possible values are PT5M, PT10M, PT15M, PT20M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D and P2D."', args=[d.arg(name='queryTimeRangeOverride', type=d.T.string)]),
      withQueryTimeRangeOverride(queryTimeRangeOverride): { spec+: { forProvider+: { queryTimeRangeOverride: queryTimeRangeOverride } } },
      '#withResourceGroupName':: d.fn(help='"Specifies the name of the Resource Group where the Monitor Scheduled Query Rule should exist. Changing this forces a new resource to be created."', args=[d.arg(name='resourceGroupName', type=d.T.string)]),
      withResourceGroupName(resourceGroupName): { spec+: { forProvider+: { resourceGroupName: resourceGroupName } } },
      '#withScopes':: d.fn(help='"Specifies the list of resource IDs that this scheduled query rule is scoped to. Changing this forces a new resource to be created. Currently, the API supports exactly 1 resource ID in the scopes list."', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopes(scopes): { spec+: { forProvider+: { scopes: if std.isArray(v=scopes) then scopes else [scopes] } } },
      '#withScopesMixin':: d.fn(help='"Specifies the list of resource IDs that this scheduled query rule is scoped to. Changing this forces a new resource to be created. Currently, the API supports exactly 1 resource ID in the scopes list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopesMixin(scopes): { spec+: { forProvider+: { scopes+: if std.isArray(v=scopes) then scopes else [scopes] } } },
      '#withScopesRefs':: d.fn(help='"References to ApplicationInsights in insights to populate scopes."', args=[d.arg(name='scopesRefs', type=d.T.array)]),
      withScopesRefs(scopesRefs): { spec+: { forProvider+: { scopesRefs: if std.isArray(v=scopesRefs) then scopesRefs else [scopesRefs] } } },
      '#withScopesRefsMixin':: d.fn(help='"References to ApplicationInsights in insights to populate scopes."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scopesRefs', type=d.T.array)]),
      withScopesRefsMixin(scopesRefs): { spec+: { forProvider+: { scopesRefs+: if std.isArray(v=scopesRefs) then scopesRefs else [scopesRefs] } } },
      '#withSeverity':: d.fn(help='"Severity of the alert. Should be an integer between 0 and 4. Value of 0 is severest."', args=[d.arg(name='severity', type=d.T.number)]),
      withSeverity(severity): { spec+: { forProvider+: { severity: severity } } },
      '#withSkipQueryValidation':: d.fn(help='"Specifies the flag which indicates whether the provided query should be validated or not. The default is false."', args=[d.arg(name='skipQueryValidation', type=d.T.boolean)]),
      withSkipQueryValidation(skipQueryValidation): { spec+: { forProvider+: { skipQueryValidation: skipQueryValidation } } },
      '#withTags':: d.fn(help='"A mapping of tags which should be assigned to the Monitor Scheduled Query Rule."', args=[d.arg(name='tags', type=d.T.object)]),
      withTags(tags): { spec+: { forProvider+: { tags: tags } } },
      '#withTagsMixin':: d.fn(help='"A mapping of tags which should be assigned to the Monitor Scheduled Query Rule."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
      withTagsMixin(tags): { spec+: { forProvider+: { tags+: tags } } },
      '#withTargetResourceTypes':: d.fn(help='"List of resource type of the target resource(s) on which the alert is created/updated. For example if the scope is a resource group and targetResourceTypes is Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource group which meet the alert criteria."', args=[d.arg(name='targetResourceTypes', type=d.T.array)]),
      withTargetResourceTypes(targetResourceTypes): { spec+: { forProvider+: { targetResourceTypes: if std.isArray(v=targetResourceTypes) then targetResourceTypes else [targetResourceTypes] } } },
      '#withTargetResourceTypesMixin':: d.fn(help='"List of resource type of the target resource(s) on which the alert is created/updated. For example if the scope is a resource group and targetResourceTypes is Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource group which meet the alert criteria."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetResourceTypes', type=d.T.array)]),
      withTargetResourceTypesMixin(targetResourceTypes): { spec+: { forProvider+: { targetResourceTypes+: if std.isArray(v=targetResourceTypes) then targetResourceTypes else [targetResourceTypes] } } },
      '#withWindowDuration':: d.fn(help='"Specifies the period of time in ISO 8601 duration format on which the Scheduled Query Rule will be executed (bin size). If evaluation_frequency is PT1M, possible values are PT1M, PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, and PT6H. Otherwise, possible values are PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D, and P2D."', args=[d.arg(name='windowDuration', type=d.T.string)]),
      withWindowDuration(windowDuration): { spec+: { forProvider+: { windowDuration: windowDuration } } },
      '#withWorkspaceAlertsStorageEnabled':: d.fn(help='"Specifies the flag which indicates whether this scheduled query rule check if storage is configured. Value should be true or false. The default is false."', args=[d.arg(name='workspaceAlertsStorageEnabled', type=d.T.boolean)]),
      withWorkspaceAlertsStorageEnabled(workspaceAlertsStorageEnabled): { spec+: { forProvider+: { workspaceAlertsStorageEnabled: workspaceAlertsStorageEnabled } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#action':: d.obj(help='"An action block as defined below."'),
      action: {
        '#withActionGroups':: d.fn(help='"List of Action Group resource IDs to invoke when the alert fires."', args=[d.arg(name='actionGroups', type=d.T.array)]),
        withActionGroups(actionGroups): { spec+: { initProvider+: { action+: { actionGroups: if std.isArray(v=actionGroups) then actionGroups else [actionGroups] } } } },
        '#withActionGroupsMixin':: d.fn(help='"List of Action Group resource IDs to invoke when the alert fires."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='actionGroups', type=d.T.array)]),
        withActionGroupsMixin(actionGroups): { spec+: { initProvider+: { action+: { actionGroups+: if std.isArray(v=actionGroups) then actionGroups else [actionGroups] } } } },
        '#withCustomProperties':: d.fn(help='"Specifies the properties of an alert payload."', args=[d.arg(name='customProperties', type=d.T.object)]),
        withCustomProperties(customProperties): { spec+: { initProvider+: { action+: { customProperties: customProperties } } } },
        '#withCustomPropertiesMixin':: d.fn(help='"Specifies the properties of an alert payload."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='customProperties', type=d.T.object)]),
        withCustomPropertiesMixin(customProperties): { spec+: { initProvider+: { action+: { customProperties+: customProperties } } } },
      },
      '#criteria':: d.obj(help='"A criteria block as defined below."'),
      criteria: {
        '#dimension':: d.obj(help='"A dimension block as defined below."'),
        dimension: {
          '#withName':: d.fn(help='"Specifies the name which should be used for this Monitor Scheduled Query Rule. Changing this forces a new resource to be created."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withOperator':: d.fn(help='"Operator for dimension values. Possible values are Exclude,and Include."', args=[d.arg(name='operator', type=d.T.string)]),
          withOperator(operator): { operator: operator },
          '#withValues':: d.fn(help='"List of dimension values. Use a wildcard * to collect all."', args=[d.arg(name='values', type=d.T.array)]),
          withValues(values): { values: if std.isArray(v=values) then values else [values] },
          '#withValuesMixin':: d.fn(help='"List of dimension values. Use a wildcard * to collect all."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
          withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
        },
        '#failingPeriods':: d.obj(help='"A failing_periods block as defined below."'),
        failingPeriods: {
          '#withMinimumFailingPeriodsToTriggerAlert':: d.fn(help='"Specifies the number of violations to trigger an alert. Should be smaller or equal to number_of_evaluation_periods. Possible value is integer between 1 and 6."', args=[d.arg(name='minimumFailingPeriodsToTriggerAlert', type=d.T.number)]),
          withMinimumFailingPeriodsToTriggerAlert(minimumFailingPeriodsToTriggerAlert): { failingPeriods+: { minimumFailingPeriodsToTriggerAlert: minimumFailingPeriodsToTriggerAlert } },
          '#withNumberOfEvaluationPeriods':: d.fn(help='"Specifies the number of aggregated look-back points. The look-back time window is calculated based on the aggregation granularity window_duration and the selected number of aggregated points. Possible value is integer between 1 and 6."', args=[d.arg(name='numberOfEvaluationPeriods', type=d.T.number)]),
          withNumberOfEvaluationPeriods(numberOfEvaluationPeriods): { failingPeriods+: { numberOfEvaluationPeriods: numberOfEvaluationPeriods } },
        },
        '#withDimension':: d.fn(help='"A dimension block as defined below."', args=[d.arg(name='dimension', type=d.T.array)]),
        withDimension(dimension): { dimension: if std.isArray(v=dimension) then dimension else [dimension] },
        '#withDimensionMixin':: d.fn(help='"A dimension block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dimension', type=d.T.array)]),
        withDimensionMixin(dimension): { dimension+: if std.isArray(v=dimension) then dimension else [dimension] },
        '#withMetricMeasureColumn':: d.fn(help='"Specifies the column containing the metric measure number."', args=[d.arg(name='metricMeasureColumn', type=d.T.string)]),
        withMetricMeasureColumn(metricMeasureColumn): { metricMeasureColumn: metricMeasureColumn },
        '#withOperator':: d.fn(help='"Specifies the criteria operator. Possible values are Equal, GreaterThan, GreaterThanOrEqual, LessThan,and LessThanOrEqual."', args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withQuery':: d.fn(help='"The query to run on logs. The results returned by this query are used to populate the alert."', args=[d.arg(name='query', type=d.T.string)]),
        withQuery(query): { query: query },
        '#withResourceIdColumn':: d.fn(help='"Specifies the column containing the resource ID. The content of the column must be an uri formatted as resource ID."', args=[d.arg(name='resourceIdColumn', type=d.T.string)]),
        withResourceIdColumn(resourceIdColumn): { resourceIdColumn: resourceIdColumn },
        '#withThreshold':: d.fn(help='"Specifies the criteria threshold value that activates the alert."', args=[d.arg(name='threshold', type=d.T.number)]),
        withThreshold(threshold): { threshold: threshold },
        '#withTimeAggregationMethod':: d.fn(help='"The type of aggregation to apply to the data points in aggregation granularity. Possible values are Average, Count, Maximum, Minimum,and Total."', args=[d.arg(name='timeAggregationMethod', type=d.T.string)]),
        withTimeAggregationMethod(timeAggregationMethod): { timeAggregationMethod: timeAggregationMethod },
      },
      '#scopesRefs':: d.obj(help='"References to ApplicationInsights in insights to populate scopes."'),
      scopesRefs: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { policy+: { resolution: resolution } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { policy+: { resolve: resolve } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#scopesSelector':: d.obj(help='"Selector for a list of ApplicationInsights in insights to populate scopes."'),
      scopesSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { scopesSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { scopesSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { scopesSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { scopesSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { scopesSelector+: { matchLabels+: matchLabels } } } },
      },
      '#withAutoMitigationEnabled':: d.fn(help='"Specifies the flag that indicates whether the alert should be automatically resolved or not. Value should be true or false. The default is false."', args=[d.arg(name='autoMitigationEnabled', type=d.T.boolean)]),
      withAutoMitigationEnabled(autoMitigationEnabled): { spec+: { initProvider+: { autoMitigationEnabled: autoMitigationEnabled } } },
      '#withCriteria':: d.fn(help='"A criteria block as defined below."', args=[d.arg(name='criteria', type=d.T.array)]),
      withCriteria(criteria): { spec+: { initProvider+: { criteria: if std.isArray(v=criteria) then criteria else [criteria] } } },
      '#withCriteriaMixin':: d.fn(help='"A criteria block as defined below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='criteria', type=d.T.array)]),
      withCriteriaMixin(criteria): { spec+: { initProvider+: { criteria+: if std.isArray(v=criteria) then criteria else [criteria] } } },
      '#withDescription':: d.fn(help='"Specifies the description of the scheduled query rule."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { initProvider+: { description: description } } },
      '#withDisplayName':: d.fn(help='"Specifies the display name of the alert rule."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { initProvider+: { displayName: displayName } } },
      '#withEnabled':: d.fn(help='"Specifies the flag which indicates whether this scheduled query rule is enabled. Value should be true or false. Defaults to true."', args=[d.arg(name='enabled', type=d.T.boolean)]),
      withEnabled(enabled): { spec+: { initProvider+: { enabled: enabled } } },
      '#withEvaluationFrequency':: d.fn(help='"How often the scheduled query rule is evaluated, represented in ISO 8601 duration format. Possible values are PT1M, PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D."', args=[d.arg(name='evaluationFrequency', type=d.T.string)]),
      withEvaluationFrequency(evaluationFrequency): { spec+: { initProvider+: { evaluationFrequency: evaluationFrequency } } },
      '#withLocation':: d.fn(help='"Specifies the Azure Region where the Monitor Scheduled Query Rule should exist. Changing this forces a new resource to be created."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { initProvider+: { location: location } } },
      '#withMuteActionsAfterAlertDuration':: d.fn(help='"Mute actions for the chosen period of time in ISO 8601 duration format after the alert is fired. Possible values are PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D and P2D."', args=[d.arg(name='muteActionsAfterAlertDuration', type=d.T.string)]),
      withMuteActionsAfterAlertDuration(muteActionsAfterAlertDuration): { spec+: { initProvider+: { muteActionsAfterAlertDuration: muteActionsAfterAlertDuration } } },
      '#withQueryTimeRangeOverride':: d.fn(help='"Set this if the alert evaluation period is different from the query time range. If not specified, the value is window_duration*number_of_evaluation_periods. Possible values are PT5M, PT10M, PT15M, PT20M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D and P2D."', args=[d.arg(name='queryTimeRangeOverride', type=d.T.string)]),
      withQueryTimeRangeOverride(queryTimeRangeOverride): { spec+: { initProvider+: { queryTimeRangeOverride: queryTimeRangeOverride } } },
      '#withScopes':: d.fn(help='"Specifies the list of resource IDs that this scheduled query rule is scoped to. Changing this forces a new resource to be created. Currently, the API supports exactly 1 resource ID in the scopes list."', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopes(scopes): { spec+: { initProvider+: { scopes: if std.isArray(v=scopes) then scopes else [scopes] } } },
      '#withScopesMixin':: d.fn(help='"Specifies the list of resource IDs that this scheduled query rule is scoped to. Changing this forces a new resource to be created. Currently, the API supports exactly 1 resource ID in the scopes list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopesMixin(scopes): { spec+: { initProvider+: { scopes+: if std.isArray(v=scopes) then scopes else [scopes] } } },
      '#withScopesRefs':: d.fn(help='"References to ApplicationInsights in insights to populate scopes."', args=[d.arg(name='scopesRefs', type=d.T.array)]),
      withScopesRefs(scopesRefs): { spec+: { initProvider+: { scopesRefs: if std.isArray(v=scopesRefs) then scopesRefs else [scopesRefs] } } },
      '#withScopesRefsMixin':: d.fn(help='"References to ApplicationInsights in insights to populate scopes."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scopesRefs', type=d.T.array)]),
      withScopesRefsMixin(scopesRefs): { spec+: { initProvider+: { scopesRefs+: if std.isArray(v=scopesRefs) then scopesRefs else [scopesRefs] } } },
      '#withSeverity':: d.fn(help='"Severity of the alert. Should be an integer between 0 and 4. Value of 0 is severest."', args=[d.arg(name='severity', type=d.T.number)]),
      withSeverity(severity): { spec+: { initProvider+: { severity: severity } } },
      '#withSkipQueryValidation':: d.fn(help='"Specifies the flag which indicates whether the provided query should be validated or not. The default is false."', args=[d.arg(name='skipQueryValidation', type=d.T.boolean)]),
      withSkipQueryValidation(skipQueryValidation): { spec+: { initProvider+: { skipQueryValidation: skipQueryValidation } } },
      '#withTags':: d.fn(help='"A mapping of tags which should be assigned to the Monitor Scheduled Query Rule."', args=[d.arg(name='tags', type=d.T.object)]),
      withTags(tags): { spec+: { initProvider+: { tags: tags } } },
      '#withTagsMixin':: d.fn(help='"A mapping of tags which should be assigned to the Monitor Scheduled Query Rule."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.object)]),
      withTagsMixin(tags): { spec+: { initProvider+: { tags+: tags } } },
      '#withTargetResourceTypes':: d.fn(help='"List of resource type of the target resource(s) on which the alert is created/updated. For example if the scope is a resource group and targetResourceTypes is Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource group which meet the alert criteria."', args=[d.arg(name='targetResourceTypes', type=d.T.array)]),
      withTargetResourceTypes(targetResourceTypes): { spec+: { initProvider+: { targetResourceTypes: if std.isArray(v=targetResourceTypes) then targetResourceTypes else [targetResourceTypes] } } },
      '#withTargetResourceTypesMixin':: d.fn(help='"List of resource type of the target resource(s) on which the alert is created/updated. For example if the scope is a resource group and targetResourceTypes is Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource group which meet the alert criteria."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetResourceTypes', type=d.T.array)]),
      withTargetResourceTypesMixin(targetResourceTypes): { spec+: { initProvider+: { targetResourceTypes+: if std.isArray(v=targetResourceTypes) then targetResourceTypes else [targetResourceTypes] } } },
      '#withWindowDuration':: d.fn(help='"Specifies the period of time in ISO 8601 duration format on which the Scheduled Query Rule will be executed (bin size). If evaluation_frequency is PT1M, possible values are PT1M, PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, and PT6H. Otherwise, possible values are PT5M, PT10M, PT15M, PT30M, PT45M, PT1H, PT2H, PT3H, PT4H, PT5H, PT6H, P1D, and P2D."', args=[d.arg(name='windowDuration', type=d.T.string)]),
      withWindowDuration(windowDuration): { spec+: { initProvider+: { windowDuration: windowDuration } } },
      '#withWorkspaceAlertsStorageEnabled':: d.fn(help='"Specifies the flag which indicates whether this scheduled query rule check if storage is configured. Value should be true or false. The default is false."', args=[d.arg(name='workspaceAlertsStorageEnabled', type=d.T.boolean)]),
      withWorkspaceAlertsStorageEnabled(workspaceAlertsStorageEnabled): { spec+: { initProvider+: { workspaceAlertsStorageEnabled: workspaceAlertsStorageEnabled } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which\\ncontains a name, metadata and a reference to secret store config to\\nwhich any connection details for this managed resource should be written.\\nConnection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used\\nfor this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.annotations\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret.\\n- For Kubernetes secrets, this will be used as \\"metadata.labels\\".\\n- It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret.\\n- Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource.\\nThis field is planned to be replaced in a future release in favor of\\nPublishConnectionDetailsTo. Currently, both could be set independently\\nand connection details would be published to both without affecting\\neach other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
