{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='connectivityTest', url='', help='"ConnectivityTest is the Schema for the ConnectivityTests API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ConnectivityTest', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'networkmanagement.gcp.jet.crossplane.io/v1alpha1',
    kind: 'ConnectivityTest',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"ConnectivityTestSpec defines the desired state of ConnectivityTest"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#destination':: d.obj(help="\"Required. Destination specification of the Connectivity Test. \\n You can use a combination of destination IP address, Compute Engine VM instance, or VPC network to uniquely identify the destination location. \\n Even if the destination IP address is not unique, the source IP location is unique. Usually, the analysis can infer the destination endpoint from route information. \\n If the destination you specify is a VM instance and the instance has multiple network interfaces, then you must also specify either a destination IP address or VPC network to identify the destination interface. \\n A reachability analysis proceeds even if the destination location is ambiguous. However, the result can include endpoints that you don't intend to test.\""),
      destination: {
        '#withInstance':: d.fn(help='"A Compute Engine instance URI."', args=[d.arg(name='instance', type=d.T.string)]),
        withInstance(instance): { instance: instance },
        '#withIpAddress':: d.fn(help="\"The IP address of the endpoint, which can be an external or internal IP. An IPv6 address is only allowed when the test's destination is a global load balancer VIP.\"", args=[d.arg(name='ipAddress', type=d.T.string)]),
        withIpAddress(ipAddress): { ipAddress: ipAddress },
        '#withNetwork':: d.fn(help='"A Compute Engine network URI."', args=[d.arg(name='network', type=d.T.string)]),
        withNetwork(network): { network: network },
        '#withPort':: d.fn(help='"The IP protocol port of the endpoint. Only applicable when protocol is TCP or UDP."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { port: port },
        '#withProjectId':: d.fn(help='"Project ID where the endpoint is located. The Project ID can be derived from the URI if you provide a VM instance or network URI. The following are two cases where you must provide the project ID: 1. Only the IP address is specified, and the IP address is within a GCP project. 2. When you are using Shared VPC and the IP address that you provide is from the service project. In this case, the network that the IP address resides in is defined in the host project."', args=[d.arg(name='projectId', type=d.T.string)]),
        withProjectId(projectId): { projectId: projectId },
      },
      '#source':: d.obj(help="\"Required. Source specification of the Connectivity Test. \\n You can use a combination of source IP address, virtual machine (VM) instance, or Compute Engine network to uniquely identify the source location. \\n Examples: If the source IP address is an internal IP address within a Google Cloud Virtual Private Cloud (VPC) network, then you must also specify the VPC network. Otherwise, specify the VM instance, which already contains its internal IP address and VPC network information. \\n If the source of the test is within an on-premises network, then you must provide the destination VPC network. \\n If the source endpoint is a Compute Engine VM instance with multiple network interfaces, the instance itself is not sufficient to identify the endpoint. So, you must also specify the source IP address or VPC network. \\n A reachability analysis proceeds even if the source location is ambiguous. However, the test result may include endpoints that you don't intend to test.\""),
      source: {
        '#withInstance':: d.fn(help='"A Compute Engine instance URI."', args=[d.arg(name='instance', type=d.T.string)]),
        withInstance(instance): { instance: instance },
        '#withIpAddress':: d.fn(help="\"The IP address of the endpoint, which can be an external or internal IP. An IPv6 address is only allowed when the test's destination is a global load balancer VIP.\"", args=[d.arg(name='ipAddress', type=d.T.string)]),
        withIpAddress(ipAddress): { ipAddress: ipAddress },
        '#withNetwork':: d.fn(help='"A Compute Engine network URI."', args=[d.arg(name='network', type=d.T.string)]),
        withNetwork(network): { network: network },
        '#withNetworkType':: d.fn(help='"Type of the network where the endpoint is located. Possible values: [\\"GCP_NETWORK\\", \\"NON_GCP_NETWORK\\"]"', args=[d.arg(name='networkType', type=d.T.string)]),
        withNetworkType(networkType): { networkType: networkType },
        '#withPort':: d.fn(help='"The IP protocol port of the endpoint. Only applicable when protocol is TCP or UDP."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { port: port },
        '#withProjectId':: d.fn(help='"Project ID where the endpoint is located. The Project ID can be derived from the URI if you provide a VM instance or network URI. The following are two cases where you must provide the project ID: \\n 1. Only the IP address is specified, and the IP address is within a GCP project. 2. When you are using Shared VPC and the IP address that you provide is from the service project. In this case, the network that the IP address resides in is defined in the host project."', args=[d.arg(name='projectId', type=d.T.string)]),
        withProjectId(projectId): { projectId: projectId },
      },
      '#withDescription':: d.fn(help='"The user-supplied description of the Connectivity Test. Maximum of 512 characters."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { spec+: { forProvider+: { description: description } } },
      '#withDestination':: d.fn(help="\"Required. Destination specification of the Connectivity Test. \\n You can use a combination of destination IP address, Compute Engine VM instance, or VPC network to uniquely identify the destination location. \\n Even if the destination IP address is not unique, the source IP location is unique. Usually, the analysis can infer the destination endpoint from route information. \\n If the destination you specify is a VM instance and the instance has multiple network interfaces, then you must also specify either a destination IP address or VPC network to identify the destination interface. \\n A reachability analysis proceeds even if the destination location is ambiguous. However, the result can include endpoints that you don't intend to test.\"", args=[d.arg(name='destination', type=d.T.array)]),
      withDestination(destination): { spec+: { forProvider+: { destination: if std.isArray(v=destination) then destination else [destination] } } },
      '#withDestinationMixin':: d.fn(help="\"Required. Destination specification of the Connectivity Test. \\n You can use a combination of destination IP address, Compute Engine VM instance, or VPC network to uniquely identify the destination location. \\n Even if the destination IP address is not unique, the source IP location is unique. Usually, the analysis can infer the destination endpoint from route information. \\n If the destination you specify is a VM instance and the instance has multiple network interfaces, then you must also specify either a destination IP address or VPC network to identify the destination interface. \\n A reachability analysis proceeds even if the destination location is ambiguous. However, the result can include endpoints that you don't intend to test.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='destination', type=d.T.array)]),
      withDestinationMixin(destination): { spec+: { forProvider+: { destination+: if std.isArray(v=destination) then destination else [destination] } } },
      '#withLabels':: d.fn(help='"Resource labels to represent user-provided metadata."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { forProvider+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"Resource labels to represent user-provided metadata."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { forProvider+: { labels+: labels } } },
      '#withName':: d.fn(help='"Unique name for the connectivity test."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { forProvider+: { name: name } } },
      '#withProject':: d.fn(help='', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withProtocol':: d.fn(help='"IP Protocol of the test. When not provided, \\"TCP\\" is assumed."', args=[d.arg(name='protocol', type=d.T.string)]),
      withProtocol(protocol): { spec+: { forProvider+: { protocol: protocol } } },
      '#withRelatedProjects':: d.fn(help='"Other projects that may be relevant for reachability analysis. This is applicable to scenarios where a test can cross project boundaries."', args=[d.arg(name='relatedProjects', type=d.T.array)]),
      withRelatedProjects(relatedProjects): { spec+: { forProvider+: { relatedProjects: if std.isArray(v=relatedProjects) then relatedProjects else [relatedProjects] } } },
      '#withRelatedProjectsMixin':: d.fn(help='"Other projects that may be relevant for reachability analysis. This is applicable to scenarios where a test can cross project boundaries."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='relatedProjects', type=d.T.array)]),
      withRelatedProjectsMixin(relatedProjects): { spec+: { forProvider+: { relatedProjects+: if std.isArray(v=relatedProjects) then relatedProjects else [relatedProjects] } } },
      '#withSource':: d.fn(help="\"Required. Source specification of the Connectivity Test. \\n You can use a combination of source IP address, virtual machine (VM) instance, or Compute Engine network to uniquely identify the source location. \\n Examples: If the source IP address is an internal IP address within a Google Cloud Virtual Private Cloud (VPC) network, then you must also specify the VPC network. Otherwise, specify the VM instance, which already contains its internal IP address and VPC network information. \\n If the source of the test is within an on-premises network, then you must provide the destination VPC network. \\n If the source endpoint is a Compute Engine VM instance with multiple network interfaces, the instance itself is not sufficient to identify the endpoint. So, you must also specify the source IP address or VPC network. \\n A reachability analysis proceeds even if the source location is ambiguous. However, the test result may include endpoints that you don't intend to test.\"", args=[d.arg(name='source', type=d.T.array)]),
      withSource(source): { spec+: { forProvider+: { source: if std.isArray(v=source) then source else [source] } } },
      '#withSourceMixin':: d.fn(help="\"Required. Source specification of the Connectivity Test. \\n You can use a combination of source IP address, virtual machine (VM) instance, or Compute Engine network to uniquely identify the source location. \\n Examples: If the source IP address is an internal IP address within a Google Cloud Virtual Private Cloud (VPC) network, then you must also specify the VPC network. Otherwise, specify the VM instance, which already contains its internal IP address and VPC network information. \\n If the source of the test is within an on-premises network, then you must provide the destination VPC network. \\n If the source endpoint is a Compute Engine VM instance with multiple network interfaces, the instance itself is not sufficient to identify the endpoint. So, you must also specify the source IP address or VPC network. \\n A reachability analysis proceeds even if the source location is ambiguous. However, the test result may include endpoints that you don't intend to test.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='source', type=d.T.array)]),
      withSourceMixin(source): { spec+: { forProvider+: { source+: if std.isArray(v=source) then source else [source] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
