{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='cluster', url='', help='"Cluster is the Schema for the Clusters API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Cluster', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'dataproc.gcp.jet.crossplane.io/v1alpha1',
    kind: 'Cluster',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"ClusterSpec defines the desired state of Cluster"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#clusterConfig':: d.obj(help='"Allows you to configure various aspects of the cluster."'),
      clusterConfig: {
        '#autoscalingConfig':: d.obj(help='"The autoscaling policy config associated with the cluster."'),
        autoscalingConfig: {
          '#withPolicyUri':: d.fn(help='"The autoscaling policy used by the cluster."', args=[d.arg(name='policyUri', type=d.T.string)]),
          withPolicyUri(policyUri): { policyUri: policyUri },
        },
        '#encryptionConfig':: d.obj(help='"The Customer managed encryption keys settings for the cluster."'),
        encryptionConfig: {
          '#withKmsKeyName':: d.fn(help='"The Cloud KMS key name to use for PD disk encryption for all instances in the cluster."', args=[d.arg(name='kmsKeyName', type=d.T.string)]),
          withKmsKeyName(kmsKeyName): { kmsKeyName: kmsKeyName },
        },
        '#gceClusterConfig':: d.obj(help='"Common config settings for resources of Google Compute Engine cluster instances, applicable to all instances in the cluster."'),
        gceClusterConfig: {
          '#shieldedInstanceConfig':: d.obj(help='"Shielded Instance Config for clusters using Compute Engine Shielded VMs."'),
          shieldedInstanceConfig: {
            '#withEnableIntegrityMonitoring':: d.fn(help='"Defines whether instances have integrity monitoring enabled."', args=[d.arg(name='enableIntegrityMonitoring', type=d.T.boolean)]),
            withEnableIntegrityMonitoring(enableIntegrityMonitoring): { enableIntegrityMonitoring: enableIntegrityMonitoring },
            '#withEnableSecureBoot':: d.fn(help='"Defines whether instances have Secure Boot enabled."', args=[d.arg(name='enableSecureBoot', type=d.T.boolean)]),
            withEnableSecureBoot(enableSecureBoot): { enableSecureBoot: enableSecureBoot },
            '#withEnableVtpm':: d.fn(help='"Defines whether instances have the vTPM enabled."', args=[d.arg(name='enableVtpm', type=d.T.boolean)]),
            withEnableVtpm(enableVtpm): { enableVtpm: enableVtpm },
          },
          '#withInternalIpOnly':: d.fn(help='"By default, clusters are not restricted to internal IP addresses, and will have ephemeral external IP addresses assigned to each instance. If set to true, all instances in the cluster will only have internal IP addresses. Note: Private Google Access (also known as privateIpGoogleAccess) must be enabled on the subnetwork that the cluster will be launched in."', args=[d.arg(name='internalIpOnly', type=d.T.boolean)]),
          withInternalIpOnly(internalIpOnly): { internalIpOnly: internalIpOnly },
          '#withMetadata':: d.fn(help='"A map of the Compute Engine metadata entries to add to all instances"', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadata(metadata): { metadata: metadata },
          '#withMetadataMixin':: d.fn(help='"A map of the Compute Engine metadata entries to add to all instances"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
          withMetadataMixin(metadata): { metadata+: metadata },
          '#withNetwork':: d.fn(help='"The name or self_link of the Google Compute Engine network to the cluster will be part of. Conflicts with subnetwork. If neither is specified, this defaults to the \\"default\\" network."', args=[d.arg(name='network', type=d.T.string)]),
          withNetwork(network): { network: network },
          '#withServiceAccount':: d.fn(help='"The service account to be used by the Node VMs. If not specified, the \\"default\\" service account is used."', args=[d.arg(name='serviceAccount', type=d.T.string)]),
          withServiceAccount(serviceAccount): { serviceAccount: serviceAccount },
          '#withServiceAccountScopes':: d.fn(help='"The set of Google API scopes to be made available on all of the node VMs under the service_account specified. These can be either FQDNs, or scope aliases."', args=[d.arg(name='serviceAccountScopes', type=d.T.array)]),
          withServiceAccountScopes(serviceAccountScopes): { serviceAccountScopes: if std.isArray(v=serviceAccountScopes) then serviceAccountScopes else [serviceAccountScopes] },
          '#withServiceAccountScopesMixin':: d.fn(help='"The set of Google API scopes to be made available on all of the node VMs under the service_account specified. These can be either FQDNs, or scope aliases."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='serviceAccountScopes', type=d.T.array)]),
          withServiceAccountScopesMixin(serviceAccountScopes): { serviceAccountScopes+: if std.isArray(v=serviceAccountScopes) then serviceAccountScopes else [serviceAccountScopes] },
          '#withShieldedInstanceConfig':: d.fn(help='"Shielded Instance Config for clusters using Compute Engine Shielded VMs."', args=[d.arg(name='shieldedInstanceConfig', type=d.T.array)]),
          withShieldedInstanceConfig(shieldedInstanceConfig): { shieldedInstanceConfig: if std.isArray(v=shieldedInstanceConfig) then shieldedInstanceConfig else [shieldedInstanceConfig] },
          '#withShieldedInstanceConfigMixin':: d.fn(help='"Shielded Instance Config for clusters using Compute Engine Shielded VMs."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='shieldedInstanceConfig', type=d.T.array)]),
          withShieldedInstanceConfigMixin(shieldedInstanceConfig): { shieldedInstanceConfig+: if std.isArray(v=shieldedInstanceConfig) then shieldedInstanceConfig else [shieldedInstanceConfig] },
          '#withSubnetwork':: d.fn(help='"The name or self_link of the Google Compute Engine subnetwork the cluster will be part of. Conflicts with network."', args=[d.arg(name='subnetwork', type=d.T.string)]),
          withSubnetwork(subnetwork): { subnetwork: subnetwork },
          '#withTags':: d.fn(help='"The list of instance tags applied to instances in the cluster. Tags are used to identify valid sources or targets for network firewalls."', args=[d.arg(name='tags', type=d.T.array)]),
          withTags(tags): { tags: if std.isArray(v=tags) then tags else [tags] },
          '#withTagsMixin':: d.fn(help='"The list of instance tags applied to instances in the cluster. Tags are used to identify valid sources or targets for network firewalls."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.array)]),
          withTagsMixin(tags): { tags+: if std.isArray(v=tags) then tags else [tags] },
          '#withZone':: d.fn(help="\"The GCP zone where your data is stored and used (i.e. where the master and the worker nodes will be created in). If region is set to 'global' (default) then zone is mandatory, otherwise GCP is able to make use of Auto Zone Placement to determine this automatically for you. Note: This setting additionally determines and restricts which computing resources are available for use with other configs such as cluster_config.master_config.machine_type and cluster_config.worker_config.machine_type.\"", args=[d.arg(name='zone', type=d.T.string)]),
          withZone(zone): { zone: zone },
        },
        '#initializationAction':: d.obj(help='"Commands to execute on each node after config is completed. You can specify multiple versions of these."'),
        initializationAction: {
          '#withScript':: d.fn(help='"The script to be executed during initialization of the cluster. The script must be a GCS file with a gs:// prefix."', args=[d.arg(name='script', type=d.T.string)]),
          withScript(script): { script: script },
          '#withTimeoutSec':: d.fn(help='"The maximum duration (in seconds) which script is allowed to take to execute its action. GCP will default to a predetermined computed value if not set (currently 300)."', args=[d.arg(name='timeoutSec', type=d.T.integer)]),
          withTimeoutSec(timeoutSec): { timeoutSec: timeoutSec },
        },
        '#masterConfig':: d.obj(help='"The Google Compute Engine config settings for the master/worker instances in a cluster."'),
        masterConfig: {
          '#accelerators':: d.obj(help='"The Compute Engine accelerator (GPU) configuration for these instances. Can be specified multiple times."'),
          accelerators: {
            '#withAcceleratorCount':: d.fn(help='"The number of the accelerator cards of this type exposed to this instance. Often restricted to one of 1, 2, 4, or 8."', args=[d.arg(name='acceleratorCount', type=d.T.integer)]),
            withAcceleratorCount(acceleratorCount): { acceleratorCount: acceleratorCount },
            '#withAcceleratorType':: d.fn(help='"The short name of the accelerator type to expose to this instance. For example, nvidia-tesla-k80."', args=[d.arg(name='acceleratorType', type=d.T.string)]),
            withAcceleratorType(acceleratorType): { acceleratorType: acceleratorType },
          },
          '#diskConfig':: d.obj(help='"Disk Config"'),
          diskConfig: {
            '#withBootDiskSizeGb':: d.fn(help='"Size of the primary disk attached to each node, specified in GB. The primary disk contains the boot volume and system libraries, and the smallest allowed disk size is 10GB. GCP will default to a predetermined computed value if not set (currently 500GB). Note: If SSDs are not attached, it also contains the HDFS data blocks and Hadoop working directories."', args=[d.arg(name='bootDiskSizeGb', type=d.T.integer)]),
            withBootDiskSizeGb(bootDiskSizeGb): { bootDiskSizeGb: bootDiskSizeGb },
            '#withBootDiskType':: d.fn(help='"The disk type of the primary disk attached to each node. One of \\"pd-ssd\\" or \\"pd-standard\\". Defaults to \\"pd-standard\\"."', args=[d.arg(name='bootDiskType', type=d.T.string)]),
            withBootDiskType(bootDiskType): { bootDiskType: bootDiskType },
            '#withNumLocalSsds':: d.fn(help='"The amount of local SSD disks that will be attached to each master cluster node. Defaults to 0."', args=[d.arg(name='numLocalSsds', type=d.T.integer)]),
            withNumLocalSsds(numLocalSsds): { numLocalSsds: numLocalSsds },
          },
          '#withAccelerators':: d.fn(help='"The Compute Engine accelerator (GPU) configuration for these instances. Can be specified multiple times."', args=[d.arg(name='accelerators', type=d.T.array)]),
          withAccelerators(accelerators): { accelerators: if std.isArray(v=accelerators) then accelerators else [accelerators] },
          '#withAcceleratorsMixin':: d.fn(help='"The Compute Engine accelerator (GPU) configuration for these instances. Can be specified multiple times."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='accelerators', type=d.T.array)]),
          withAcceleratorsMixin(accelerators): { accelerators+: if std.isArray(v=accelerators) then accelerators else [accelerators] },
          '#withDiskConfig':: d.fn(help='"Disk Config"', args=[d.arg(name='diskConfig', type=d.T.array)]),
          withDiskConfig(diskConfig): { diskConfig: if std.isArray(v=diskConfig) then diskConfig else [diskConfig] },
          '#withDiskConfigMixin':: d.fn(help='"Disk Config"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='diskConfig', type=d.T.array)]),
          withDiskConfigMixin(diskConfig): { diskConfig+: if std.isArray(v=diskConfig) then diskConfig else [diskConfig] },
          '#withImageUri':: d.fn(help='"The URI for the image to use for this master/worker"', args=[d.arg(name='imageUri', type=d.T.string)]),
          withImageUri(imageUri): { imageUri: imageUri },
          '#withMachineType':: d.fn(help='"The name of a Google Compute Engine machine type to create for the master/worker"', args=[d.arg(name='machineType', type=d.T.string)]),
          withMachineType(machineType): { machineType: machineType },
          '#withMinCpuPlatform':: d.fn(help='"The name of a minimum generation of CPU family for the master/worker. If not specified, GCP will default to a predetermined computed value for each zone."', args=[d.arg(name='minCpuPlatform', type=d.T.string)]),
          withMinCpuPlatform(minCpuPlatform): { minCpuPlatform: minCpuPlatform },
          '#withNumInstances':: d.fn(help='"Specifies the number of master/worker nodes to create. If not specified, GCP will default to a predetermined computed value."', args=[d.arg(name='numInstances', type=d.T.integer)]),
          withNumInstances(numInstances): { numInstances: numInstances },
        },
        '#preemptibleWorkerConfig':: d.obj(help='"The Google Compute Engine config settings for the additional (aka preemptible) instances in a cluster."'),
        preemptibleWorkerConfig: {
          '#diskConfig':: d.obj(help='"Disk Config"'),
          diskConfig: {
            '#withBootDiskSizeGb':: d.fn(help='"Size of the primary disk attached to each preemptible worker node, specified in GB. The smallest allowed disk size is 10GB. GCP will default to a predetermined computed value if not set (currently 500GB). Note: If SSDs are not attached, it also contains the HDFS data blocks and Hadoop working directories."', args=[d.arg(name='bootDiskSizeGb', type=d.T.integer)]),
            withBootDiskSizeGb(bootDiskSizeGb): { bootDiskSizeGb: bootDiskSizeGb },
            '#withBootDiskType':: d.fn(help='"The disk type of the primary disk attached to each preemptible worker node. One of \\"pd-ssd\\" or \\"pd-standard\\". Defaults to \\"pd-standard\\"."', args=[d.arg(name='bootDiskType', type=d.T.string)]),
            withBootDiskType(bootDiskType): { bootDiskType: bootDiskType },
            '#withNumLocalSsds':: d.fn(help='"The amount of local SSD disks that will be attached to each preemptible worker node. Defaults to 0."', args=[d.arg(name='numLocalSsds', type=d.T.integer)]),
            withNumLocalSsds(numLocalSsds): { numLocalSsds: numLocalSsds },
          },
          '#withDiskConfig':: d.fn(help='"Disk Config"', args=[d.arg(name='diskConfig', type=d.T.array)]),
          withDiskConfig(diskConfig): { diskConfig: if std.isArray(v=diskConfig) then diskConfig else [diskConfig] },
          '#withDiskConfigMixin':: d.fn(help='"Disk Config"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='diskConfig', type=d.T.array)]),
          withDiskConfigMixin(diskConfig): { diskConfig+: if std.isArray(v=diskConfig) then diskConfig else [diskConfig] },
          '#withNumInstances':: d.fn(help='"Specifies the number of preemptible nodes to create. Defaults to 0."', args=[d.arg(name='numInstances', type=d.T.integer)]),
          withNumInstances(numInstances): { numInstances: numInstances },
        },
        '#securityConfig':: d.obj(help='"Security related configuration."'),
        securityConfig: {
          '#kerberosConfig':: d.obj(help='"Kerberos related configuration"'),
          kerberosConfig: {
            '#withCrossRealmTrustAdminServer':: d.fn(help='"The admin server (IP or hostname) for the remote trusted realm in a cross realm trust relationship."', args=[d.arg(name='crossRealmTrustAdminServer', type=d.T.string)]),
            withCrossRealmTrustAdminServer(crossRealmTrustAdminServer): { crossRealmTrustAdminServer: crossRealmTrustAdminServer },
            '#withCrossRealmTrustKdc':: d.fn(help='"The KDC (IP or hostname) for the remote trusted realm in a cross realm trust relationship."', args=[d.arg(name='crossRealmTrustKdc', type=d.T.string)]),
            withCrossRealmTrustKdc(crossRealmTrustKdc): { crossRealmTrustKdc: crossRealmTrustKdc },
            '#withCrossRealmTrustRealm':: d.fn(help='"The remote realm the Dataproc on-cluster KDC will trust, should the user enable cross realm trust."', args=[d.arg(name='crossRealmTrustRealm', type=d.T.string)]),
            withCrossRealmTrustRealm(crossRealmTrustRealm): { crossRealmTrustRealm: crossRealmTrustRealm },
            '#withCrossRealmTrustSharedPasswordUri':: d.fn(help='"The Cloud Storage URI of a KMS encrypted file containing the shared password between the on-cluster Kerberos realm and the remote trusted realm, in a cross realm trust relationship."', args=[d.arg(name='crossRealmTrustSharedPasswordUri', type=d.T.string)]),
            withCrossRealmTrustSharedPasswordUri(crossRealmTrustSharedPasswordUri): { crossRealmTrustSharedPasswordUri: crossRealmTrustSharedPasswordUri },
            '#withEnableKerberos':: d.fn(help='"Flag to indicate whether to Kerberize the cluster."', args=[d.arg(name='enableKerberos', type=d.T.boolean)]),
            withEnableKerberos(enableKerberos): { enableKerberos: enableKerberos },
            '#withKdcDbKeyUri':: d.fn(help='"The Cloud Storage URI of a KMS encrypted file containing the master key of the KDC database."', args=[d.arg(name='kdcDbKeyUri', type=d.T.string)]),
            withKdcDbKeyUri(kdcDbKeyUri): { kdcDbKeyUri: kdcDbKeyUri },
            '#withKeyPasswordUri':: d.fn(help='"The Cloud Storage URI of a KMS encrypted file containing the password to the user provided key. For the self-signed certificate, this password is generated by Dataproc."', args=[d.arg(name='keyPasswordUri', type=d.T.string)]),
            withKeyPasswordUri(keyPasswordUri): { keyPasswordUri: keyPasswordUri },
            '#withKeystorePasswordUri':: d.fn(help='"The Cloud Storage URI of a KMS encrypted file containing the password to the user provided keystore. For the self-signed certificate, this password is generated by Dataproc"', args=[d.arg(name='keystorePasswordUri', type=d.T.string)]),
            withKeystorePasswordUri(keystorePasswordUri): { keystorePasswordUri: keystorePasswordUri },
            '#withKeystoreUri':: d.fn(help='"The Cloud Storage URI of the keystore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate."', args=[d.arg(name='keystoreUri', type=d.T.string)]),
            withKeystoreUri(keystoreUri): { keystoreUri: keystoreUri },
            '#withKmsKeyUri':: d.fn(help='"The uri of the KMS key used to encrypt various sensitive files."', args=[d.arg(name='kmsKeyUri', type=d.T.string)]),
            withKmsKeyUri(kmsKeyUri): { kmsKeyUri: kmsKeyUri },
            '#withRealm':: d.fn(help='"The name of the on-cluster Kerberos realm. If not specified, the uppercased domain of hostnames will be the realm."', args=[d.arg(name='realm', type=d.T.string)]),
            withRealm(realm): { realm: realm },
            '#withRootPrincipalPasswordUri':: d.fn(help='"The cloud Storage URI of a KMS encrypted file containing the root principal password."', args=[d.arg(name='rootPrincipalPasswordUri', type=d.T.string)]),
            withRootPrincipalPasswordUri(rootPrincipalPasswordUri): { rootPrincipalPasswordUri: rootPrincipalPasswordUri },
            '#withTgtLifetimeHours':: d.fn(help='"The lifetime of the ticket granting ticket, in hours."', args=[d.arg(name='tgtLifetimeHours', type=d.T.integer)]),
            withTgtLifetimeHours(tgtLifetimeHours): { tgtLifetimeHours: tgtLifetimeHours },
            '#withTruststorePasswordUri':: d.fn(help='"The Cloud Storage URI of a KMS encrypted file containing the password to the user provided truststore. For the self-signed certificate, this password is generated by Dataproc."', args=[d.arg(name='truststorePasswordUri', type=d.T.string)]),
            withTruststorePasswordUri(truststorePasswordUri): { truststorePasswordUri: truststorePasswordUri },
            '#withTruststoreUri':: d.fn(help='"The Cloud Storage URI of the truststore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate."', args=[d.arg(name='truststoreUri', type=d.T.string)]),
            withTruststoreUri(truststoreUri): { truststoreUri: truststoreUri },
          },
          '#withKerberosConfig':: d.fn(help='"Kerberos related configuration"', args=[d.arg(name='kerberosConfig', type=d.T.array)]),
          withKerberosConfig(kerberosConfig): { kerberosConfig: if std.isArray(v=kerberosConfig) then kerberosConfig else [kerberosConfig] },
          '#withKerberosConfigMixin':: d.fn(help='"Kerberos related configuration"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='kerberosConfig', type=d.T.array)]),
          withKerberosConfigMixin(kerberosConfig): { kerberosConfig+: if std.isArray(v=kerberosConfig) then kerberosConfig else [kerberosConfig] },
        },
        '#softwareConfig':: d.obj(help='"The config settings for software inside the cluster."'),
        softwareConfig: {
          '#withImageVersion':: d.fn(help='"The Cloud Dataproc image version to use for the cluster - this controls the sets of software versions installed onto the nodes when you create clusters. If not specified, defaults to the latest version."', args=[d.arg(name='imageVersion', type=d.T.string)]),
          withImageVersion(imageVersion): { imageVersion: imageVersion },
          '#withOptionalComponents':: d.fn(help='"The set of optional components to activate on the cluster."', args=[d.arg(name='optionalComponents', type=d.T.array)]),
          withOptionalComponents(optionalComponents): { optionalComponents: if std.isArray(v=optionalComponents) then optionalComponents else [optionalComponents] },
          '#withOptionalComponentsMixin':: d.fn(help='"The set of optional components to activate on the cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='optionalComponents', type=d.T.array)]),
          withOptionalComponentsMixin(optionalComponents): { optionalComponents+: if std.isArray(v=optionalComponents) then optionalComponents else [optionalComponents] },
          '#withOverrideProperties':: d.fn(help='"A list of override and additional properties (key/value pairs) used to modify various aspects of the common configuration files used when creating a cluster."', args=[d.arg(name='overrideProperties', type=d.T.object)]),
          withOverrideProperties(overrideProperties): { overrideProperties: overrideProperties },
          '#withOverridePropertiesMixin':: d.fn(help='"A list of override and additional properties (key/value pairs) used to modify various aspects of the common configuration files used when creating a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='overrideProperties', type=d.T.object)]),
          withOverridePropertiesMixin(overrideProperties): { overrideProperties+: overrideProperties },
        },
        '#withAutoscalingConfig':: d.fn(help='"The autoscaling policy config associated with the cluster."', args=[d.arg(name='autoscalingConfig', type=d.T.array)]),
        withAutoscalingConfig(autoscalingConfig): { autoscalingConfig: if std.isArray(v=autoscalingConfig) then autoscalingConfig else [autoscalingConfig] },
        '#withAutoscalingConfigMixin':: d.fn(help='"The autoscaling policy config associated with the cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='autoscalingConfig', type=d.T.array)]),
        withAutoscalingConfigMixin(autoscalingConfig): { autoscalingConfig+: if std.isArray(v=autoscalingConfig) then autoscalingConfig else [autoscalingConfig] },
        '#withEncryptionConfig':: d.fn(help='"The Customer managed encryption keys settings for the cluster."', args=[d.arg(name='encryptionConfig', type=d.T.array)]),
        withEncryptionConfig(encryptionConfig): { encryptionConfig: if std.isArray(v=encryptionConfig) then encryptionConfig else [encryptionConfig] },
        '#withEncryptionConfigMixin':: d.fn(help='"The Customer managed encryption keys settings for the cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='encryptionConfig', type=d.T.array)]),
        withEncryptionConfigMixin(encryptionConfig): { encryptionConfig+: if std.isArray(v=encryptionConfig) then encryptionConfig else [encryptionConfig] },
        '#withGceClusterConfig':: d.fn(help='"Common config settings for resources of Google Compute Engine cluster instances, applicable to all instances in the cluster."', args=[d.arg(name='gceClusterConfig', type=d.T.array)]),
        withGceClusterConfig(gceClusterConfig): { gceClusterConfig: if std.isArray(v=gceClusterConfig) then gceClusterConfig else [gceClusterConfig] },
        '#withGceClusterConfigMixin':: d.fn(help='"Common config settings for resources of Google Compute Engine cluster instances, applicable to all instances in the cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='gceClusterConfig', type=d.T.array)]),
        withGceClusterConfigMixin(gceClusterConfig): { gceClusterConfig+: if std.isArray(v=gceClusterConfig) then gceClusterConfig else [gceClusterConfig] },
        '#withInitializationAction':: d.fn(help='"Commands to execute on each node after config is completed. You can specify multiple versions of these."', args=[d.arg(name='initializationAction', type=d.T.array)]),
        withInitializationAction(initializationAction): { initializationAction: if std.isArray(v=initializationAction) then initializationAction else [initializationAction] },
        '#withInitializationActionMixin':: d.fn(help='"Commands to execute on each node after config is completed. You can specify multiple versions of these."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='initializationAction', type=d.T.array)]),
        withInitializationActionMixin(initializationAction): { initializationAction+: if std.isArray(v=initializationAction) then initializationAction else [initializationAction] },
        '#withMasterConfig':: d.fn(help='"The Google Compute Engine config settings for the master/worker instances in a cluster."', args=[d.arg(name='masterConfig', type=d.T.array)]),
        withMasterConfig(masterConfig): { masterConfig: if std.isArray(v=masterConfig) then masterConfig else [masterConfig] },
        '#withMasterConfigMixin':: d.fn(help='"The Google Compute Engine config settings for the master/worker instances in a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='masterConfig', type=d.T.array)]),
        withMasterConfigMixin(masterConfig): { masterConfig+: if std.isArray(v=masterConfig) then masterConfig else [masterConfig] },
        '#withPreemptibleWorkerConfig':: d.fn(help='"The Google Compute Engine config settings for the additional (aka preemptible) instances in a cluster."', args=[d.arg(name='preemptibleWorkerConfig', type=d.T.array)]),
        withPreemptibleWorkerConfig(preemptibleWorkerConfig): { preemptibleWorkerConfig: if std.isArray(v=preemptibleWorkerConfig) then preemptibleWorkerConfig else [preemptibleWorkerConfig] },
        '#withPreemptibleWorkerConfigMixin':: d.fn(help='"The Google Compute Engine config settings for the additional (aka preemptible) instances in a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='preemptibleWorkerConfig', type=d.T.array)]),
        withPreemptibleWorkerConfigMixin(preemptibleWorkerConfig): { preemptibleWorkerConfig+: if std.isArray(v=preemptibleWorkerConfig) then preemptibleWorkerConfig else [preemptibleWorkerConfig] },
        '#withSecurityConfig':: d.fn(help='"Security related configuration."', args=[d.arg(name='securityConfig', type=d.T.array)]),
        withSecurityConfig(securityConfig): { securityConfig: if std.isArray(v=securityConfig) then securityConfig else [securityConfig] },
        '#withSecurityConfigMixin':: d.fn(help='"Security related configuration."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='securityConfig', type=d.T.array)]),
        withSecurityConfigMixin(securityConfig): { securityConfig+: if std.isArray(v=securityConfig) then securityConfig else [securityConfig] },
        '#withSoftwareConfig':: d.fn(help='"The config settings for software inside the cluster."', args=[d.arg(name='softwareConfig', type=d.T.array)]),
        withSoftwareConfig(softwareConfig): { softwareConfig: if std.isArray(v=softwareConfig) then softwareConfig else [softwareConfig] },
        '#withSoftwareConfigMixin':: d.fn(help='"The config settings for software inside the cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='softwareConfig', type=d.T.array)]),
        withSoftwareConfigMixin(softwareConfig): { softwareConfig+: if std.isArray(v=softwareConfig) then softwareConfig else [softwareConfig] },
        '#withStagingBucket':: d.fn(help="\"The Cloud Storage staging bucket used to stage files, such as Hadoop jars, between client machines and the cluster. Note: If you don't explicitly specify a staging_bucket then GCP will auto create / assign one for you. However, you are not guaranteed an auto generated bucket which is solely dedicated to your cluster; it may be shared with other clusters in the same region/zone also choosing to use the auto generation option.\"", args=[d.arg(name='stagingBucket', type=d.T.string)]),
        withStagingBucket(stagingBucket): { stagingBucket: stagingBucket },
        '#withTempBucket':: d.fn(help="\"The Cloud Storage temp bucket used to store ephemeral cluster and jobs data, such as Spark and MapReduce history files. Note: If you don't explicitly specify a temp_bucket then GCP will auto create / assign one for you.\"", args=[d.arg(name='tempBucket', type=d.T.string)]),
        withTempBucket(tempBucket): { tempBucket: tempBucket },
        '#withWorkerConfig':: d.fn(help='"The Google Compute Engine config settings for the master/worker instances in a cluster."', args=[d.arg(name='workerConfig', type=d.T.array)]),
        withWorkerConfig(workerConfig): { workerConfig: if std.isArray(v=workerConfig) then workerConfig else [workerConfig] },
        '#withWorkerConfigMixin':: d.fn(help='"The Google Compute Engine config settings for the master/worker instances in a cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='workerConfig', type=d.T.array)]),
        withWorkerConfigMixin(workerConfig): { workerConfig+: if std.isArray(v=workerConfig) then workerConfig else [workerConfig] },
        '#workerConfig':: d.obj(help='"The Google Compute Engine config settings for the master/worker instances in a cluster."'),
        workerConfig: {
          '#accelerators':: d.obj(help='"The Compute Engine accelerator (GPU) configuration for these instances. Can be specified multiple times."'),
          accelerators: {
            '#withAcceleratorCount':: d.fn(help='"The number of the accelerator cards of this type exposed to this instance. Often restricted to one of 1, 2, 4, or 8."', args=[d.arg(name='acceleratorCount', type=d.T.integer)]),
            withAcceleratorCount(acceleratorCount): { acceleratorCount: acceleratorCount },
            '#withAcceleratorType':: d.fn(help='"The short name of the accelerator type to expose to this instance. For example, nvidia-tesla-k80."', args=[d.arg(name='acceleratorType', type=d.T.string)]),
            withAcceleratorType(acceleratorType): { acceleratorType: acceleratorType },
          },
          '#diskConfig':: d.obj(help='"Disk Config"'),
          diskConfig: {
            '#withBootDiskSizeGb':: d.fn(help='"Size of the primary disk attached to each node, specified in GB. The primary disk contains the boot volume and system libraries, and the smallest allowed disk size is 10GB. GCP will default to a predetermined computed value if not set (currently 500GB). Note: If SSDs are not attached, it also contains the HDFS data blocks and Hadoop working directories."', args=[d.arg(name='bootDiskSizeGb', type=d.T.integer)]),
            withBootDiskSizeGb(bootDiskSizeGb): { bootDiskSizeGb: bootDiskSizeGb },
            '#withBootDiskType':: d.fn(help='"The disk type of the primary disk attached to each node. One of \\"pd-ssd\\" or \\"pd-standard\\". Defaults to \\"pd-standard\\"."', args=[d.arg(name='bootDiskType', type=d.T.string)]),
            withBootDiskType(bootDiskType): { bootDiskType: bootDiskType },
            '#withNumLocalSsds':: d.fn(help='"The amount of local SSD disks that will be attached to each master cluster node. Defaults to 0."', args=[d.arg(name='numLocalSsds', type=d.T.integer)]),
            withNumLocalSsds(numLocalSsds): { numLocalSsds: numLocalSsds },
          },
          '#withAccelerators':: d.fn(help='"The Compute Engine accelerator (GPU) configuration for these instances. Can be specified multiple times."', args=[d.arg(name='accelerators', type=d.T.array)]),
          withAccelerators(accelerators): { accelerators: if std.isArray(v=accelerators) then accelerators else [accelerators] },
          '#withAcceleratorsMixin':: d.fn(help='"The Compute Engine accelerator (GPU) configuration for these instances. Can be specified multiple times."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='accelerators', type=d.T.array)]),
          withAcceleratorsMixin(accelerators): { accelerators+: if std.isArray(v=accelerators) then accelerators else [accelerators] },
          '#withDiskConfig':: d.fn(help='"Disk Config"', args=[d.arg(name='diskConfig', type=d.T.array)]),
          withDiskConfig(diskConfig): { diskConfig: if std.isArray(v=diskConfig) then diskConfig else [diskConfig] },
          '#withDiskConfigMixin':: d.fn(help='"Disk Config"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='diskConfig', type=d.T.array)]),
          withDiskConfigMixin(diskConfig): { diskConfig+: if std.isArray(v=diskConfig) then diskConfig else [diskConfig] },
          '#withImageUri':: d.fn(help='"The URI for the image to use for this master/worker"', args=[d.arg(name='imageUri', type=d.T.string)]),
          withImageUri(imageUri): { imageUri: imageUri },
          '#withMachineType':: d.fn(help='"The name of a Google Compute Engine machine type to create for the master/worker"', args=[d.arg(name='machineType', type=d.T.string)]),
          withMachineType(machineType): { machineType: machineType },
          '#withMinCpuPlatform':: d.fn(help='"The name of a minimum generation of CPU family for the master/worker. If not specified, GCP will default to a predetermined computed value for each zone."', args=[d.arg(name='minCpuPlatform', type=d.T.string)]),
          withMinCpuPlatform(minCpuPlatform): { minCpuPlatform: minCpuPlatform },
          '#withNumInstances':: d.fn(help='"Specifies the number of master/worker nodes to create. If not specified, GCP will default to a predetermined computed value."', args=[d.arg(name='numInstances', type=d.T.integer)]),
          withNumInstances(numInstances): { numInstances: numInstances },
        },
      },
      '#withClusterConfig':: d.fn(help='"Allows you to configure various aspects of the cluster."', args=[d.arg(name='clusterConfig', type=d.T.array)]),
      withClusterConfig(clusterConfig): { spec+: { forProvider+: { clusterConfig: if std.isArray(v=clusterConfig) then clusterConfig else [clusterConfig] } } },
      '#withClusterConfigMixin':: d.fn(help='"Allows you to configure various aspects of the cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='clusterConfig', type=d.T.array)]),
      withClusterConfigMixin(clusterConfig): { spec+: { forProvider+: { clusterConfig+: if std.isArray(v=clusterConfig) then clusterConfig else [clusterConfig] } } },
      '#withGracefulDecommissionTimeout':: d.fn(help='"The timeout duration which allows graceful decomissioning when you change the number of worker nodes directly through a terraform apply"', args=[d.arg(name='gracefulDecommissionTimeout', type=d.T.string)]),
      withGracefulDecommissionTimeout(gracefulDecommissionTimeout): { spec+: { forProvider+: { gracefulDecommissionTimeout: gracefulDecommissionTimeout } } },
      '#withLabels':: d.fn(help='"The list of labels (key/value pairs) to be applied to instances in the cluster. GCP generates some itself including goog-dataproc-cluster-name which is the name of the cluster."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { forProvider+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"The list of labels (key/value pairs) to be applied to instances in the cluster. GCP generates some itself including goog-dataproc-cluster-name which is the name of the cluster."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { forProvider+: { labels+: labels } } },
      '#withName':: d.fn(help='"The name of the cluster, unique within the project and zone."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { forProvider+: { name: name } } },
      '#withProject':: d.fn(help='"The ID of the project in which the cluster will exist. If it is not provided, the provider project is used."', args=[d.arg(name='project', type=d.T.string)]),
      withProject(project): { spec+: { forProvider+: { project: project } } },
      '#withRegion':: d.fn(help='"The region in which the cluster and associated nodes will be created in. Defaults to global."', args=[d.arg(name='region', type=d.T.string)]),
      withRegion(region): { spec+: { forProvider+: { region: region } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
