{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='page', url='', help='"Page is the Schema for the Pages API. A Dialogflow CX conversation (session) can be described and visualized as a state machine."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Page', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'dialogflowcx.gcp.upbound.io/v1beta1',
    kind: 'Page',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"PageSpec defines the desired state of Page"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#entryFulfillment':: d.obj(help='"The fulfillment to call when the session is entering the page. Structure is documented below."'),
      entryFulfillment: {
        '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
        messages: {
          '#text':: d.obj(help='"A collection of text responses."'),
          text: {
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text: if std.isArray(v=text) then text else [text] },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
          },
          '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
          withText(text): { text: if std.isArray(v=text) then text else [text] },
          '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
          withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
        },
        '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
        withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
        '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
        withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
        '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
        withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
        '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
        withTag(tag): { tag: tag },
        '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
        withWebhook(webhook): { webhook: webhook },
      },
      '#eventHandlers':: d.obj(help='"Handlers associated with the page to handle events such as webhook errors, no match or no input. Structure is documented below."'),
      eventHandlers: {
        '#triggerFulfillment':: d.obj(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."'),
        triggerFulfillment: {
          '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
          messages: {
            '#text':: d.obj(help='"A collection of text responses."'),
            text: {
              '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
              withText(text): { text: if std.isArray(v=text) then text else [text] },
              '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
              withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
            },
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text: if std.isArray(v=text) then text else [text] },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
          },
          '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
          withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
          '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
          withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
          '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
          withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
          '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
          withTag(tag): { tag: tag },
          '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
          withWebhook(webhook): { webhook: webhook },
        },
        '#withEvent':: d.fn(help='"The name of the event to handle."', args=[d.arg(name='event', type=d.T.string)]),
        withEvent(event): { event: event },
        '#withTargetFlow':: d.fn(help='"The target flow to transition to. Format: projects//locations//agents//flows/."', args=[d.arg(name='targetFlow', type=d.T.string)]),
        withTargetFlow(targetFlow): { targetFlow: targetFlow },
        '#withTargetPage':: d.fn(help='"The target page to transition to. Format: projects//locations//agents//flows//pages/."', args=[d.arg(name='targetPage', type=d.T.string)]),
        withTargetPage(targetPage): { targetPage: targetPage },
        '#withTriggerFulfillment':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillment(triggerFulfillment): { triggerFulfillment: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
        '#withTriggerFulfillmentMixin':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillmentMixin(triggerFulfillment): { triggerFulfillment+: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
      },
      '#form':: d.obj(help='"The form associated with the page, used for collecting parameters relevant to the page. Structure is documented below."'),
      form: {
        '#parameters':: d.obj(help='"Parameters to collect from the user. Structure is documented below."'),
        parameters: {
          '#fillBehavior':: d.obj(help='"Defines fill behavior for the parameter. Structure is documented below."'),
          fillBehavior: {
            '#initialPromptFulfillment':: d.obj(help='"The fulfillment to provide the initial prompt that the agent can present to the user in order to fill the parameter. Structure is documented below."'),
            initialPromptFulfillment: {
              '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
              messages: {
                '#text':: d.obj(help='"A collection of text responses."'),
                text: {
                  '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
                  withText(text): { text: if std.isArray(v=text) then text else [text] },
                  '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
                  withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
                },
                '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
                withText(text): { text: if std.isArray(v=text) then text else [text] },
                '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
                withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
              },
              '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
              withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
              '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
              withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
              '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
              withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
              '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
              withTag(tag): { tag: tag },
              '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
              withWebhook(webhook): { webhook: webhook },
            },
            '#withInitialPromptFulfillment':: d.fn(help='"The fulfillment to provide the initial prompt that the agent can present to the user in order to fill the parameter. Structure is documented below."', args=[d.arg(name='initialPromptFulfillment', type=d.T.array)]),
            withInitialPromptFulfillment(initialPromptFulfillment): { initialPromptFulfillment: if std.isArray(v=initialPromptFulfillment) then initialPromptFulfillment else [initialPromptFulfillment] },
            '#withInitialPromptFulfillmentMixin':: d.fn(help='"The fulfillment to provide the initial prompt that the agent can present to the user in order to fill the parameter. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='initialPromptFulfillment', type=d.T.array)]),
            withInitialPromptFulfillmentMixin(initialPromptFulfillment): { initialPromptFulfillment+: if std.isArray(v=initialPromptFulfillment) then initialPromptFulfillment else [initialPromptFulfillment] },
          },
          '#withDisplayName':: d.fn(help='"The human-readable name of the parameter, unique within the form."', args=[d.arg(name='displayName', type=d.T.string)]),
          withDisplayName(displayName): { displayName: displayName },
          '#withEntityType':: d.fn(help='"The entity type of the parameter. Format: projects/-/locations/-/agents/-/entityTypes/ for system entity types (for example, projects/-/locations/-/agents/-/entityTypes/sys.date), or projects//locations//agents//entityTypes/ for developer entity types."', args=[d.arg(name='entityType', type=d.T.string)]),
          withEntityType(entityType): { entityType: entityType },
          '#withFillBehavior':: d.fn(help='"Defines fill behavior for the parameter. Structure is documented below."', args=[d.arg(name='fillBehavior', type=d.T.array)]),
          withFillBehavior(fillBehavior): { fillBehavior: if std.isArray(v=fillBehavior) then fillBehavior else [fillBehavior] },
          '#withFillBehaviorMixin':: d.fn(help='"Defines fill behavior for the parameter. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='fillBehavior', type=d.T.array)]),
          withFillBehaviorMixin(fillBehavior): { fillBehavior+: if std.isArray(v=fillBehavior) then fillBehavior else [fillBehavior] },
          '#withIsList':: d.fn(help='"Indicates whether the parameter represents a list of values."', args=[d.arg(name='isList', type=d.T.boolean)]),
          withIsList(isList): { isList: isList },
          '#withRedact':: d.fn(help='"Indicates whether the parameter content should be redacted in log. If redaction is enabled, the parameter content will be replaced by parameter name during logging. Note: the parameter content is subject to redaction if either parameter level redaction or entity type level redaction is enabled."', args=[d.arg(name='redact', type=d.T.boolean)]),
          withRedact(redact): { redact: redact },
          '#withRequired':: d.fn(help='"Indicates whether the parameter is required. Optional parameters will not trigger prompts; however, they are filled if the user specifies them. Required parameters must be filled before form filling concludes."', args=[d.arg(name='required', type=d.T.boolean)]),
          withRequired(required): { required: required },
        },
        '#withParameters':: d.fn(help='"Parameters to collect from the user. Structure is documented below."', args=[d.arg(name='parameters', type=d.T.array)]),
        withParameters(parameters): { parameters: if std.isArray(v=parameters) then parameters else [parameters] },
        '#withParametersMixin':: d.fn(help='"Parameters to collect from the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='parameters', type=d.T.array)]),
        withParametersMixin(parameters): { parameters+: if std.isArray(v=parameters) then parameters else [parameters] },
      },
      '#parentRef':: d.obj(help='"Reference to a Agent in dialogflowcx to populate parent."'),
      parentRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { parentRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { parentRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { parentRef+: { name: name } } } },
      },
      '#parentSelector':: d.obj(help='"Selector for a Agent in dialogflowcx to populate parent."'),
      parentSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { parentSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { parentSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { parentSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { parentSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { parentSelector+: { matchLabels+: matchLabels } } } },
      },
      '#transitionRoutes':: d.obj(help='"A list of transitions for the transition rules of this page. They route the conversation to another page in the same flow, or another flow. When we are in a certain page, the TransitionRoutes are evalauted in the following order: TransitionRoutes defined in the page with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in flow with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in the page with only condition specified. TransitionRoutes defined in the transition route groups with only condition specified. Structure is documented below."'),
      transitionRoutes: {
        '#targetPageRef':: d.obj(help='"Reference to a Page in dialogflowcx to populate targetPage."'),
        targetPageRef: {
          '#policy':: d.obj(help='"Policies for referencing."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { targetPageRef+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { targetPageRef+: { policy+: { resolve: resolve } } },
          },
          '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { targetPageRef+: { name: name } },
        },
        '#targetPageSelector':: d.obj(help='"Selector for a Page in dialogflowcx to populate targetPage."'),
        targetPageSelector: {
          '#policy':: d.obj(help='"Policies for selection."'),
          policy: {
            '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
            withResolution(resolution): { targetPageSelector+: { policy+: { resolution: resolution } } },
            '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
            withResolve(resolve): { targetPageSelector+: { policy+: { resolve: resolve } } },
          },
          '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference as the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
          withMatchControllerRef(matchControllerRef): { targetPageSelector+: { matchControllerRef: matchControllerRef } },
          '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { targetPageSelector+: { matchLabels: matchLabels } },
          '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { targetPageSelector+: { matchLabels+: matchLabels } },
        },
        '#triggerFulfillment':: d.obj(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."'),
        triggerFulfillment: {
          '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
          messages: {
            '#text':: d.obj(help='"A collection of text responses."'),
            text: {
              '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
              withText(text): { text: if std.isArray(v=text) then text else [text] },
              '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
              withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
            },
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text: if std.isArray(v=text) then text else [text] },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
          },
          '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
          withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
          '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
          withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
          '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
          withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
          '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
          withTag(tag): { tag: tag },
          '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
          withWebhook(webhook): { webhook: webhook },
        },
        '#withCondition':: d.fn(help='"The condition to evaluate against form parameters or session parameters. At least one of intent or condition must be specified. When both intent and condition are specified, the transition can only happen when both are fulfilled."', args=[d.arg(name='condition', type=d.T.string)]),
        withCondition(condition): { condition: condition },
        '#withIntent':: d.fn(help='"The unique identifier of an Intent. Format: projects//locations//agents//intents/. Indicates that the transition can only happen when the given intent is matched. At least one of intent or condition must be specified. When both intent and condition are specified, the transition can only happen when both are fulfilled."', args=[d.arg(name='intent', type=d.T.string)]),
        withIntent(intent): { intent: intent },
        '#withTargetFlow':: d.fn(help='"The target flow to transition to. Format: projects//locations//agents//flows/."', args=[d.arg(name='targetFlow', type=d.T.string)]),
        withTargetFlow(targetFlow): { targetFlow: targetFlow },
        '#withTargetPage':: d.fn(help='"The target page to transition to. Format: projects//locations//agents//flows//pages/."', args=[d.arg(name='targetPage', type=d.T.string)]),
        withTargetPage(targetPage): { targetPage: targetPage },
        '#withTriggerFulfillment':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillment(triggerFulfillment): { triggerFulfillment: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
        '#withTriggerFulfillmentMixin':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillmentMixin(triggerFulfillment): { triggerFulfillment+: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
      },
      '#withDisplayName':: d.fn(help='"The human-readable name of the page, unique within the agent."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { forProvider+: { displayName: displayName } } },
      '#withEntryFulfillment':: d.fn(help='"The fulfillment to call when the session is entering the page. Structure is documented below."', args=[d.arg(name='entryFulfillment', type=d.T.array)]),
      withEntryFulfillment(entryFulfillment): { spec+: { forProvider+: { entryFulfillment: if std.isArray(v=entryFulfillment) then entryFulfillment else [entryFulfillment] } } },
      '#withEntryFulfillmentMixin':: d.fn(help='"The fulfillment to call when the session is entering the page. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='entryFulfillment', type=d.T.array)]),
      withEntryFulfillmentMixin(entryFulfillment): { spec+: { forProvider+: { entryFulfillment+: if std.isArray(v=entryFulfillment) then entryFulfillment else [entryFulfillment] } } },
      '#withEventHandlers':: d.fn(help='"Handlers associated with the page to handle events such as webhook errors, no match or no input. Structure is documented below."', args=[d.arg(name='eventHandlers', type=d.T.array)]),
      withEventHandlers(eventHandlers): { spec+: { forProvider+: { eventHandlers: if std.isArray(v=eventHandlers) then eventHandlers else [eventHandlers] } } },
      '#withEventHandlersMixin':: d.fn(help='"Handlers associated with the page to handle events such as webhook errors, no match or no input. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='eventHandlers', type=d.T.array)]),
      withEventHandlersMixin(eventHandlers): { spec+: { forProvider+: { eventHandlers+: if std.isArray(v=eventHandlers) then eventHandlers else [eventHandlers] } } },
      '#withForm':: d.fn(help='"The form associated with the page, used for collecting parameters relevant to the page. Structure is documented below."', args=[d.arg(name='form', type=d.T.array)]),
      withForm(form): { spec+: { forProvider+: { form: if std.isArray(v=form) then form else [form] } } },
      '#withFormMixin':: d.fn(help='"The form associated with the page, used for collecting parameters relevant to the page. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='form', type=d.T.array)]),
      withFormMixin(form): { spec+: { forProvider+: { form+: if std.isArray(v=form) then form else [form] } } },
      '#withLanguageCode':: d.fn(help="\"The language of the following fields in page: Page.entry_fulfillment.messages Page.entry_fulfillment.conditional_cases Page.event_handlers.trigger_fulfillment.messages Page.event_handlers.trigger_fulfillment.conditional_cases Page.form.parameters.fill_behavior.initial_prompt_fulfillment.messages Page.form.parameters.fill_behavior.initial_prompt_fulfillment.conditional_cases Page.form.parameters.fill_behavior.reprompt_event_handlers.messages Page.form.parameters.fill_behavior.reprompt_event_handlers.conditional_cases Page.transition_routes.trigger_fulfillment.messages Page.transition_routes.trigger_fulfillment.conditional_cases If not specified, the agent's default language is used. Many languages are supported. Note: languages must be enabled in the agent before they can be used.\"", args=[d.arg(name='languageCode', type=d.T.string)]),
      withLanguageCode(languageCode): { spec+: { forProvider+: { languageCode: languageCode } } },
      '#withParent':: d.fn(help='"The flow to create a page for. Format: projects//locations//agents//flows/."', args=[d.arg(name='parent', type=d.T.string)]),
      withParent(parent): { spec+: { forProvider+: { parent: parent } } },
      '#withTransitionRouteGroups':: d.fn(help="\"Ordered list of TransitionRouteGroups associated with the page. Transition route groups must be unique within a page. If multiple transition routes within a page scope refer to the same intent, then the precedence order is: page's transition route -\u003e page's transition route group -\u003e flow's transition routes. If multiple transition route groups within a page contain the same intent, then the first group in the ordered list takes precedence. Format:projects//locations//agents//flows//transitionRouteGroups/.\"", args=[d.arg(name='transitionRouteGroups', type=d.T.array)]),
      withTransitionRouteGroups(transitionRouteGroups): { spec+: { forProvider+: { transitionRouteGroups: if std.isArray(v=transitionRouteGroups) then transitionRouteGroups else [transitionRouteGroups] } } },
      '#withTransitionRouteGroupsMixin':: d.fn(help="\"Ordered list of TransitionRouteGroups associated with the page. Transition route groups must be unique within a page. If multiple transition routes within a page scope refer to the same intent, then the precedence order is: page's transition route -\u003e page's transition route group -\u003e flow's transition routes. If multiple transition route groups within a page contain the same intent, then the first group in the ordered list takes precedence. Format:projects//locations//agents//flows//transitionRouteGroups/.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='transitionRouteGroups', type=d.T.array)]),
      withTransitionRouteGroupsMixin(transitionRouteGroups): { spec+: { forProvider+: { transitionRouteGroups+: if std.isArray(v=transitionRouteGroups) then transitionRouteGroups else [transitionRouteGroups] } } },
      '#withTransitionRoutes':: d.fn(help='"A list of transitions for the transition rules of this page. They route the conversation to another page in the same flow, or another flow. When we are in a certain page, the TransitionRoutes are evalauted in the following order: TransitionRoutes defined in the page with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in flow with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in the page with only condition specified. TransitionRoutes defined in the transition route groups with only condition specified. Structure is documented below."', args=[d.arg(name='transitionRoutes', type=d.T.array)]),
      withTransitionRoutes(transitionRoutes): { spec+: { forProvider+: { transitionRoutes: if std.isArray(v=transitionRoutes) then transitionRoutes else [transitionRoutes] } } },
      '#withTransitionRoutesMixin':: d.fn(help='"A list of transitions for the transition rules of this page. They route the conversation to another page in the same flow, or another flow. When we are in a certain page, the TransitionRoutes are evalauted in the following order: TransitionRoutes defined in the page with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in flow with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in the page with only condition specified. TransitionRoutes defined in the transition route groups with only condition specified. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='transitionRoutes', type=d.T.array)]),
      withTransitionRoutesMixin(transitionRoutes): { spec+: { forProvider+: { transitionRoutes+: if std.isArray(v=transitionRoutes) then transitionRoutes else [transitionRoutes] } } },
    },
    '#initProvider':: d.obj(help='"THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice. InitProvider holds the same fields as ForProvider, with the exception of Identifier and other resource reference fields. The fields that are in InitProvider are merged into ForProvider when the resource is created. The same fields are also added to the terraform ignore_changes hook, to avoid updating them after creation. This is useful for fields that are required on creation, but we do not desire to update them after creation, for example because of an external controller is managing them, like an autoscaler."'),
    initProvider: {
      '#entryFulfillment':: d.obj(help='"The fulfillment to call when the session is entering the page. Structure is documented below."'),
      entryFulfillment: {
        '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
        messages: {
          '#text':: d.obj(help='"A collection of text responses."'),
          text: {
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text: if std.isArray(v=text) then text else [text] },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
          },
          '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
          withText(text): { text: if std.isArray(v=text) then text else [text] },
          '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
          withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
        },
        '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
        withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
        '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
        withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
        '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
        withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
        '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
        withTag(tag): { tag: tag },
        '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
        withWebhook(webhook): { webhook: webhook },
      },
      '#eventHandlers':: d.obj(help='"Handlers associated with the page to handle events such as webhook errors, no match or no input. Structure is documented below."'),
      eventHandlers: {
        '#triggerFulfillment':: d.obj(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."'),
        triggerFulfillment: {
          '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
          messages: {
            '#text':: d.obj(help='"A collection of text responses."'),
            text: {
              '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
              withText(text): { text: if std.isArray(v=text) then text else [text] },
              '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
              withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
            },
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text: if std.isArray(v=text) then text else [text] },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
          },
          '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
          withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
          '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
          withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
          '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
          withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
          '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
          withTag(tag): { tag: tag },
          '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
          withWebhook(webhook): { webhook: webhook },
        },
        '#withEvent':: d.fn(help='"The name of the event to handle."', args=[d.arg(name='event', type=d.T.string)]),
        withEvent(event): { event: event },
        '#withTargetFlow':: d.fn(help='"The target flow to transition to. Format: projects//locations//agents//flows/."', args=[d.arg(name='targetFlow', type=d.T.string)]),
        withTargetFlow(targetFlow): { targetFlow: targetFlow },
        '#withTargetPage':: d.fn(help='"The target page to transition to. Format: projects//locations//agents//flows//pages/."', args=[d.arg(name='targetPage', type=d.T.string)]),
        withTargetPage(targetPage): { targetPage: targetPage },
        '#withTriggerFulfillment':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillment(triggerFulfillment): { triggerFulfillment: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
        '#withTriggerFulfillmentMixin':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillmentMixin(triggerFulfillment): { triggerFulfillment+: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
      },
      '#form':: d.obj(help='"The form associated with the page, used for collecting parameters relevant to the page. Structure is documented below."'),
      form: {
        '#parameters':: d.obj(help='"Parameters to collect from the user. Structure is documented below."'),
        parameters: {
          '#fillBehavior':: d.obj(help='"Defines fill behavior for the parameter. Structure is documented below."'),
          fillBehavior: {
            '#initialPromptFulfillment':: d.obj(help='"The fulfillment to provide the initial prompt that the agent can present to the user in order to fill the parameter. Structure is documented below."'),
            initialPromptFulfillment: {
              '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
              messages: {
                '#text':: d.obj(help='"A collection of text responses."'),
                text: {
                  '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
                  withText(text): { text: if std.isArray(v=text) then text else [text] },
                  '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
                  withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
                },
                '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
                withText(text): { text: if std.isArray(v=text) then text else [text] },
                '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
                withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
              },
              '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
              withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
              '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
              withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
              '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
              withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
              '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
              withTag(tag): { tag: tag },
              '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
              withWebhook(webhook): { webhook: webhook },
            },
            '#withInitialPromptFulfillment':: d.fn(help='"The fulfillment to provide the initial prompt that the agent can present to the user in order to fill the parameter. Structure is documented below."', args=[d.arg(name='initialPromptFulfillment', type=d.T.array)]),
            withInitialPromptFulfillment(initialPromptFulfillment): { initialPromptFulfillment: if std.isArray(v=initialPromptFulfillment) then initialPromptFulfillment else [initialPromptFulfillment] },
            '#withInitialPromptFulfillmentMixin':: d.fn(help='"The fulfillment to provide the initial prompt that the agent can present to the user in order to fill the parameter. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='initialPromptFulfillment', type=d.T.array)]),
            withInitialPromptFulfillmentMixin(initialPromptFulfillment): { initialPromptFulfillment+: if std.isArray(v=initialPromptFulfillment) then initialPromptFulfillment else [initialPromptFulfillment] },
          },
          '#withDisplayName':: d.fn(help='"The human-readable name of the parameter, unique within the form."', args=[d.arg(name='displayName', type=d.T.string)]),
          withDisplayName(displayName): { displayName: displayName },
          '#withEntityType':: d.fn(help='"The entity type of the parameter. Format: projects/-/locations/-/agents/-/entityTypes/ for system entity types (for example, projects/-/locations/-/agents/-/entityTypes/sys.date), or projects//locations//agents//entityTypes/ for developer entity types."', args=[d.arg(name='entityType', type=d.T.string)]),
          withEntityType(entityType): { entityType: entityType },
          '#withFillBehavior':: d.fn(help='"Defines fill behavior for the parameter. Structure is documented below."', args=[d.arg(name='fillBehavior', type=d.T.array)]),
          withFillBehavior(fillBehavior): { fillBehavior: if std.isArray(v=fillBehavior) then fillBehavior else [fillBehavior] },
          '#withFillBehaviorMixin':: d.fn(help='"Defines fill behavior for the parameter. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='fillBehavior', type=d.T.array)]),
          withFillBehaviorMixin(fillBehavior): { fillBehavior+: if std.isArray(v=fillBehavior) then fillBehavior else [fillBehavior] },
          '#withIsList':: d.fn(help='"Indicates whether the parameter represents a list of values."', args=[d.arg(name='isList', type=d.T.boolean)]),
          withIsList(isList): { isList: isList },
          '#withRedact':: d.fn(help='"Indicates whether the parameter content should be redacted in log. If redaction is enabled, the parameter content will be replaced by parameter name during logging. Note: the parameter content is subject to redaction if either parameter level redaction or entity type level redaction is enabled."', args=[d.arg(name='redact', type=d.T.boolean)]),
          withRedact(redact): { redact: redact },
          '#withRequired':: d.fn(help='"Indicates whether the parameter is required. Optional parameters will not trigger prompts; however, they are filled if the user specifies them. Required parameters must be filled before form filling concludes."', args=[d.arg(name='required', type=d.T.boolean)]),
          withRequired(required): { required: required },
        },
        '#withParameters':: d.fn(help='"Parameters to collect from the user. Structure is documented below."', args=[d.arg(name='parameters', type=d.T.array)]),
        withParameters(parameters): { parameters: if std.isArray(v=parameters) then parameters else [parameters] },
        '#withParametersMixin':: d.fn(help='"Parameters to collect from the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='parameters', type=d.T.array)]),
        withParametersMixin(parameters): { parameters+: if std.isArray(v=parameters) then parameters else [parameters] },
      },
      '#transitionRoutes':: d.obj(help='"A list of transitions for the transition rules of this page. They route the conversation to another page in the same flow, or another flow. When we are in a certain page, the TransitionRoutes are evalauted in the following order: TransitionRoutes defined in the page with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in flow with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in the page with only condition specified. TransitionRoutes defined in the transition route groups with only condition specified. Structure is documented below."'),
      transitionRoutes: {
        '#triggerFulfillment':: d.obj(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."'),
        triggerFulfillment: {
          '#messages':: d.obj(help='"The list of rich message responses to present to the user. Structure is documented below."'),
          messages: {
            '#text':: d.obj(help='"A collection of text responses."'),
            text: {
              '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
              withText(text): { text: if std.isArray(v=text) then text else [text] },
              '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
              withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
            },
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text: if std.isArray(v=text) then text else [text] },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: if std.isArray(v=text) then text else [text] },
          },
          '#withMessages':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."', args=[d.arg(name='messages', type=d.T.array)]),
          withMessages(messages): { messages: if std.isArray(v=messages) then messages else [messages] },
          '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
          withMessagesMixin(messages): { messages+: if std.isArray(v=messages) then messages else [messages] },
          '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
          withReturnPartialResponses(returnPartialResponses): { returnPartialResponses: returnPartialResponses },
          '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
          withTag(tag): { tag: tag },
          '#withWebhook':: d.fn(help='"The webhook to call. Format: projects//locations//agents//webhooks/."', args=[d.arg(name='webhook', type=d.T.string)]),
          withWebhook(webhook): { webhook: webhook },
        },
        '#withCondition':: d.fn(help='"The condition to evaluate against form parameters or session parameters. At least one of intent or condition must be specified. When both intent and condition are specified, the transition can only happen when both are fulfilled."', args=[d.arg(name='condition', type=d.T.string)]),
        withCondition(condition): { condition: condition },
        '#withIntent':: d.fn(help='"The unique identifier of an Intent. Format: projects//locations//agents//intents/. Indicates that the transition can only happen when the given intent is matched. At least one of intent or condition must be specified. When both intent and condition are specified, the transition can only happen when both are fulfilled."', args=[d.arg(name='intent', type=d.T.string)]),
        withIntent(intent): { intent: intent },
        '#withTargetFlow':: d.fn(help='"The target flow to transition to. Format: projects//locations//agents//flows/."', args=[d.arg(name='targetFlow', type=d.T.string)]),
        withTargetFlow(targetFlow): { targetFlow: targetFlow },
        '#withTriggerFulfillment':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillment(triggerFulfillment): { triggerFulfillment: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
        '#withTriggerFulfillmentMixin':: d.fn(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='triggerFulfillment', type=d.T.array)]),
        withTriggerFulfillmentMixin(triggerFulfillment): { triggerFulfillment+: if std.isArray(v=triggerFulfillment) then triggerFulfillment else [triggerFulfillment] },
      },
      '#withDisplayName':: d.fn(help='"The human-readable name of the page, unique within the agent."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { initProvider+: { displayName: displayName } } },
      '#withEntryFulfillment':: d.fn(help='"The fulfillment to call when the session is entering the page. Structure is documented below."', args=[d.arg(name='entryFulfillment', type=d.T.array)]),
      withEntryFulfillment(entryFulfillment): { spec+: { initProvider+: { entryFulfillment: if std.isArray(v=entryFulfillment) then entryFulfillment else [entryFulfillment] } } },
      '#withEntryFulfillmentMixin':: d.fn(help='"The fulfillment to call when the session is entering the page. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='entryFulfillment', type=d.T.array)]),
      withEntryFulfillmentMixin(entryFulfillment): { spec+: { initProvider+: { entryFulfillment+: if std.isArray(v=entryFulfillment) then entryFulfillment else [entryFulfillment] } } },
      '#withEventHandlers':: d.fn(help='"Handlers associated with the page to handle events such as webhook errors, no match or no input. Structure is documented below."', args=[d.arg(name='eventHandlers', type=d.T.array)]),
      withEventHandlers(eventHandlers): { spec+: { initProvider+: { eventHandlers: if std.isArray(v=eventHandlers) then eventHandlers else [eventHandlers] } } },
      '#withEventHandlersMixin':: d.fn(help='"Handlers associated with the page to handle events such as webhook errors, no match or no input. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='eventHandlers', type=d.T.array)]),
      withEventHandlersMixin(eventHandlers): { spec+: { initProvider+: { eventHandlers+: if std.isArray(v=eventHandlers) then eventHandlers else [eventHandlers] } } },
      '#withForm':: d.fn(help='"The form associated with the page, used for collecting parameters relevant to the page. Structure is documented below."', args=[d.arg(name='form', type=d.T.array)]),
      withForm(form): { spec+: { initProvider+: { form: if std.isArray(v=form) then form else [form] } } },
      '#withFormMixin':: d.fn(help='"The form associated with the page, used for collecting parameters relevant to the page. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='form', type=d.T.array)]),
      withFormMixin(form): { spec+: { initProvider+: { form+: if std.isArray(v=form) then form else [form] } } },
      '#withLanguageCode':: d.fn(help="\"The language of the following fields in page: Page.entry_fulfillment.messages Page.entry_fulfillment.conditional_cases Page.event_handlers.trigger_fulfillment.messages Page.event_handlers.trigger_fulfillment.conditional_cases Page.form.parameters.fill_behavior.initial_prompt_fulfillment.messages Page.form.parameters.fill_behavior.initial_prompt_fulfillment.conditional_cases Page.form.parameters.fill_behavior.reprompt_event_handlers.messages Page.form.parameters.fill_behavior.reprompt_event_handlers.conditional_cases Page.transition_routes.trigger_fulfillment.messages Page.transition_routes.trigger_fulfillment.conditional_cases If not specified, the agent's default language is used. Many languages are supported. Note: languages must be enabled in the agent before they can be used.\"", args=[d.arg(name='languageCode', type=d.T.string)]),
      withLanguageCode(languageCode): { spec+: { initProvider+: { languageCode: languageCode } } },
      '#withTransitionRouteGroups':: d.fn(help="\"Ordered list of TransitionRouteGroups associated with the page. Transition route groups must be unique within a page. If multiple transition routes within a page scope refer to the same intent, then the precedence order is: page's transition route -\u003e page's transition route group -\u003e flow's transition routes. If multiple transition route groups within a page contain the same intent, then the first group in the ordered list takes precedence. Format:projects//locations//agents//flows//transitionRouteGroups/.\"", args=[d.arg(name='transitionRouteGroups', type=d.T.array)]),
      withTransitionRouteGroups(transitionRouteGroups): { spec+: { initProvider+: { transitionRouteGroups: if std.isArray(v=transitionRouteGroups) then transitionRouteGroups else [transitionRouteGroups] } } },
      '#withTransitionRouteGroupsMixin':: d.fn(help="\"Ordered list of TransitionRouteGroups associated with the page. Transition route groups must be unique within a page. If multiple transition routes within a page scope refer to the same intent, then the precedence order is: page's transition route -\u003e page's transition route group -\u003e flow's transition routes. If multiple transition route groups within a page contain the same intent, then the first group in the ordered list takes precedence. Format:projects//locations//agents//flows//transitionRouteGroups/.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='transitionRouteGroups', type=d.T.array)]),
      withTransitionRouteGroupsMixin(transitionRouteGroups): { spec+: { initProvider+: { transitionRouteGroups+: if std.isArray(v=transitionRouteGroups) then transitionRouteGroups else [transitionRouteGroups] } } },
      '#withTransitionRoutes':: d.fn(help='"A list of transitions for the transition rules of this page. They route the conversation to another page in the same flow, or another flow. When we are in a certain page, the TransitionRoutes are evalauted in the following order: TransitionRoutes defined in the page with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in flow with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in the page with only condition specified. TransitionRoutes defined in the transition route groups with only condition specified. Structure is documented below."', args=[d.arg(name='transitionRoutes', type=d.T.array)]),
      withTransitionRoutes(transitionRoutes): { spec+: { initProvider+: { transitionRoutes: if std.isArray(v=transitionRoutes) then transitionRoutes else [transitionRoutes] } } },
      '#withTransitionRoutesMixin':: d.fn(help='"A list of transitions for the transition rules of this page. They route the conversation to another page in the same flow, or another flow. When we are in a certain page, the TransitionRoutes are evalauted in the following order: TransitionRoutes defined in the page with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in flow with intent specified. TransitionRoutes defined in the transition route groups with intent specified. TransitionRoutes defined in the page with only condition specified. TransitionRoutes defined in the transition route groups with only condition specified. Structure is documented below."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='transitionRoutes', type=d.T.array)]),
      withTransitionRoutesMixin(transitionRoutes): { spec+: { initProvider+: { transitionRoutes+: if std.isArray(v=transitionRoutes) then transitionRoutes else [transitionRoutes] } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#providerRef':: d.obj(help='"ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`"'),
    providerRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerRef+: { name: name } } },
    },
    '#publishConnectionDetailsTo':: d.obj(help='"PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource."'),
    publishConnectionDetailsTo: {
      '#configRef':: d.obj(help='"SecretStoreConfigRef specifies which secret store config should be used for this ConnectionSecret."'),
      configRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required. The default is 'Required', which means the reconcile will fail if the reference cannot be resolved. 'Optional' means this reference will be a no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default is 'IfNotPresent', which will attempt to resolve the reference only when the corresponding field is not present. Use 'Always' to resolve the reference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { publishConnectionDetailsTo+: { configRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { publishConnectionDetailsTo+: { configRef+: { name: name } } } },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata for connection secret."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations are the annotations to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.annotations\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { publishConnectionDetailsTo+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Labels are the labels/tags to be added to connection secret. - For Kubernetes secrets, this will be used as \\"metadata.labels\\". - It is up to Secret Store implementation for others store types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { publishConnectionDetailsTo+: { metadata+: { labels+: labels } } } },
        '#withType':: d.fn(help='"Type is the SecretType for the connection secret. - Only valid for Kubernetes Secret Stores."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { publishConnectionDetailsTo+: { metadata+: { type: type } } } },
      },
      '#withName':: d.fn(help='"Name is the name of the connection secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { publishConnectionDetailsTo+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the external resource. This field is planned to be deprecated in favor of the ManagementPolicies field in a future release. Currently, both could be set independently and non-default values would be honored if the feature flag is enabled. See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice. ManagementPolicies specify the array of actions Crossplane is allowed to take on the managed and external resources. This field is planned to replace the DeletionPolicy field in a future release. Currently, both could be set independently and non-default values would be honored if the feature flag is enabled. If both are custom, the DeletionPolicy field will be ignored. See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223 and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored unless the relevant Crossplane feature flag is enabled, and may be changed or removed without notice. ManagementPolicies specify the array of actions Crossplane is allowed to take on the managed and external resources. This field is planned to replace the DeletionPolicy field in a future release. Currently, both could be set independently and non-default values would be honored if the feature flag is enabled. If both are custom, the DeletionPolicy field will be ignored. See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223 and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource. This field is planned to be replaced in a future release in favor of PublishConnectionDetailsTo. Currently, both could be set independently and connection details would be published to both without affecting each other."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
